### ISSUE TITLE
py_requirement support for python_version transitions

### ISSUE THREAD

**Issue by arrdem** [bazelbuild/rules_python#1010]
# 🚀 feature request

### Description

At present the `requirement` macro(s) generated when parsing pip requirements locks just compute absolute rule names. This makes it difficult-impossible to play games with what a `py_requirement` reference means.

Consider a repo with say py3.10 and py3.11 interpreters using the new transition-based `python_version` rules for `py_binary` and `py_test`. Since requirements locks vary between interpreters, such a configuration would need at least two `pip_parse` based repositories, one for each interpreter.

A `py_library(..., deps = [requirement("pyyaml")], ...)` is now ambiguous in this configuration. Likely, `requirement` is an aliased import of `requirement` from either the 3.10 or 3.11 repository, but both of these solutions would be wrong as they don't reflect the `python_version` transition. We don't want to reference say `@@pypi_py310_darwin_aarch64_pyyaml/:lib` when composing a 3.11 binary, we would want to resolve the semantically equivalent `@@pypi_py311_darwin_aarch64_pyyaml/:lib`.

### Describe the solution you'd like

It seems like support for a `python_version` aware `requirement` could be implemented by creating a `py_requirement` transition rule which is aware of the available pip repositories and, similar to how the repositories themselves are implemented, generating a workspace full of such shim rules with a `requirement` macro for convenience.

Such a transition rule could I think also support muxing across requirement files for platform and architecture using the same mechanism. So `requirement("pyyaml")` would reference say `@@pypi_transitions//:pyyaml` which would then choose between say `@@pypi_py310_darwin_aarch64_pyyaml//:lib` and `@@pypi_py311_darwin_aarch64_pyyaml//:lib` But honestly I'm not sold on this idea and would love feedback/alternative proposals from folks more familiar with the available Bazel mechanisms.

**Comment by rickeylev** [comment]
This is possible today, however, it requires using the `incompatible_generate_aliases=True`. I think this is required for the multi-version-aware toolchain and pip wrappers? (I'm not sure how else they could be functioning). Under the hood, an "alias" repo is generated, where e.g. `@mypip//foo:foo` is an alias that does e.g. `select({":py38": "mypip_38_foo", ...})`. (this is similar as proposed by OP).

I'm not sure if this was filed before or after the incompatible_generate_aliases feature was introduced, but in any case, this FR can be closed.
