### ISSUE TITLE
0.15.0 Sha256 Sum Changed

### ISSUE THREAD

**Issue by loganasherjones** [bazelbuild/rules_python#1031]
# 🐞 bug report

### Affected Rule

N/A

### Is this a regression?

N/A

### Description

Recently, the `0.15.0` version of `rules_python` seems to have a different `sha256sum`. According to the [release page for 0.15.0](https://github.com/bazelbuild/rules_python/releases/tag/0.15.0) the `sha256` should be `fda23c37fbacf7579f94d5e8f342d3a831140e9471b770782e83846117dd6596` but I'm currently getting `99e0d77f6ca445134adb5ef3d321a065d3b55b47a834cca110c30bf519d919bb`.

## 🔬 Minimal Reproduction

Create a `WORKSPACE` using the instructions from the 0.15.0 release page:

```
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
http_archive(
    name = "bazel_skylib",
    sha256 = "74d544d96f4a5bb630d465ca8bbcfe231e3594e5aae57e1edbf17a6eb3ca2506",
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/bazel-skylib/releases/download/1.3.0/bazel-skylib-1.3.0.tar.gz",
        "https://github.com/bazelbuild/bazel-skylib/releases/download/1.3.0/bazel-skylib-1.3.0.tar.gz",
    ],
)
http_archive(
    name = "rules_python",
    sha256 = "fda23c37fbacf7579f94d5e8f342d3a831140e9471b770782e83846117dd6596",
    strip_prefix = "rules_python-0.15.0",
    url = "https://github.com/bazelbuild/rules_python/archive/refs/tags/0.15.0.tar.gz",
)
```

`main.py`

```python
print("Hello, World")
```

`BUILD`:

```
load("@rules_python//python:defs.bzl", "py_binary")

py_binary(
  name = "main",
  srcs = ["main.py"],
)
```

```
bazel run //:main
```

Will fail with a checksum issue.

## 🔥 Exception or Error

<pre><code>
ERROR: An error occurred during the fetch of repository 'rules_python':
   Traceback (most recent call last):
	File "/home/.cache/bazel/external/bazel_tools/tools/build_defs/repo/http.bzl", line 125, column 45, in _http_archive_impl
		download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://github.com/bazelbuild/rules_python/archive/refs/tags/0.15.0.tar.gz] to /home/.cache/bazel/external/rules_python/temp14311180362336136035/0.15.0.tar.gz: Checksum was 99e0d77f6ca445134adb5ef3d321a065d3b55b47a834cca110c30bf519d919bb but wanted fda23c37fbacf7579f94d5e8f342d3a831140e9471b770782e83846117dd6596

</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Confirmed on Ubuntu, Red Hat and Windows
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>

  </code>
</pre>

**Rules_python version:**

<pre>
  <code>
0.15.0
  </code>
</pre>

**Anything else relevant?**

**Comment by loganasherjones** [comment]
Hmm, this also appears to be affecting [rules_jvm 0.9.0](https://github.com/bazel-contrib/rules_jvm/releases/tag/v0.9.0) Did GitHub change something?

**Comment by CrazyKevinHu** [comment]
same for https://github.com/bazelbuild/rules_python/archive/refs/tags/0.7.0.tar.gz wrong hash

**Comment by loganasherjones** [comment]
Ok, I think this happened because we currently rely on the [source code .tar.gz](https://github.com/bazelbuild/rules_python/archive/refs/tags/0.17.3.tar.gz) files.

Unfortunately, this source code is generated automatically by GitHub on release. This means that GitHub can change the contents of it relatively easily. Here seems to be some supporting evidence:

* [libgit issue](https://github.com/libgit2/libgit2/issues/4343)
* [Github Community Discussion](https://github.com/orgs/community/discussions/23512#discussioncomment-3240660)
* [Stack exchange post](https://security.stackexchange.com/a/240209)

My guess is that GitHub changed something recently for how these source code `.tar.gz` files are downloaded. Seems like it's going to cause some massive headaches for bazel libraries that release this way.

I think the core problem is that the release does not include it's own `.tar.gz` file. Compare that with something like [skylib release](https://github.com/bazelbuild/bazel-skylib/releases) which upload their own version of the `.tar.gz` file.

**Comment by phlax** [comment]
fyi we are hitting similar issues in other project (Envoy) - so it seems like github have broken the tarball hashes (again)

**Comment by loganasherjones** [comment]
Yep looks like there is a [community discussion on it now](https://github.com/orgs/community/discussions/45830)

**Comment by loganasherjones** [comment]
I'm going to go ahead and close this as GitHub seems to have reverted the change. I think #1032 will solve problems like this in the future. For details on what happened see the community discussion linked above.
