### ISSUE TITLE
Extras not being found/importable

### ISSUE THREAD

**Issue by snapbug** [bazelbuild/rules_python#1036]
# 🐞 bug report

### Affected Rule

I'll say `py_binary`, because this is a runtime error, so will only manifest in executable targets. But might be further up/down the chain.

### Is this a regression?

I don't know.

### Description

Adding a lib with extras in requirements then trying to import those extras in a python file results in `ModuleNotFoundError`.

## 🔬 Minimal Reproduction

I created a repository here https://github.com/snapbug/bazel_python_extras

## 🔥 Exception or Error

When running the `python_binary` target:

<pre><code>Traceback (most recent call last):
  File "/private/var/tmp/_bazel_mcrane/13baa2ea46f1177a54f65afb9fe31f59/execroot/__main__/bazel-out/darwin-fastbuild/bin/foo.runfiles/__main__/foo.py", line 2, in <module>
    from ray import serve
ImportError: cannot import name 'serve' from 'ray' (/private/var/tmp/_bazel_mcrane/13baa2ea46f1177a54f65afb9fe31f59/execroot/__main__/bazel-out/darwin-fastbuild/bin/foo.runfiles/pip_ray_cpp/site-packages/ray/__init__.py)
</code></pre>

where this import comes from an extra, and works with native python shell. The minimal repro has another example with a different error message.

## 🌍  Your Environment

**Operating System:**

<pre><code>OSX 13.1</code></pre>

**Output of `bazel version`:**

<pre><code>bazel 6.0.0</code></pre>

**Rules_python version:**

<pre><code>17.3</code></pre>

**Anything else relevant?**

I took a look at the other issues mentioning "extras", but they all seem to relate to older version of `rules_python` that required speif

**Comment by linzhp** [comment]
Same here, using something like `requirement("ray[serve]")` doesn't help either

**Comment by linzhp** [comment]
Actually, it worked after running `bazel run //:py_deps.update`.

**Comment by snapbug** [comment]
🤔 it doesn't seem to work for me no matter how many times I `run //:py_deps.update`.

I ran it on a linux box I have access to 
```shell
> uname -a
Linux starling 5.15.0-47-generic #51-Ubuntu SMP Thu Aug 11 07:51:15 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

and got a `ModuleNotFoundError` deep in the internals of the import of `ray.serve`, which feels like that might be rays problem, but at least it shows that the error is somewhere on the osx side, given everything else is the same. So some "progress" I guess...

**Comment by linzhp** [comment]
Yeah, I got `ModuleNotFoundError: No module named 'colorama'` on both Linux and macOS. So it's not rules_python not supporting extras, but specific to ray not handling its deps on colorama properly.

**Comment by snapbug** [comment]
Yeah, I think it's odd that I get different behaviour on os/linux, but either way I generally agree, not a rules_python issue. 🙂
