### ISSUE TITLE
Unset transitions for `data` attributes in multi-Python setups 

### ISSUE THREAD

**Issue by chowder** [bazelbuild/rules_python#1042]
# 🚀 feature request

### Relevant Rules

This feature concerns the `_transition_py_binary` and `_transition_py_test` rules in 

https://github.com/bazelbuild/rules_python/blob/main/python/config_settings/transition.bzl

### Description

As an example, if I have a large `cc_binary` target that is used in the `data` attribute of two `py_binary` rules that go through different transitions, the `cc_binary` target will be compiled twice. 

Extending on the examples provided by `multi_python_versions`:

```starlark
cc_binary(
    name = "mytool",
    ....
)

py_binary_3_8(
    name = "version_3_8",
    srcs = ["version.py"],
    main = "version.py",
    data = [":mytool"],
)

py_binary_3_9(
    name = "version_3_9",
    srcs = ["version.py"],
    main = "version.py",
    data = [":mytool"],
)
```
`mytool` will end up being compiled twice, once when I compile `:version_3_8` and again for `:version_3_9`

### Describe the solution you'd like

An outgoing transition should be applied to `data` attributes for these transition rules, perhaps transitioning back to the default transition value, [similar to what `rules_go` does](https://github.com/bazelbuild/rules_go/blob/31d17212968b472032035a45353a1751f1c0f529/go/private/rules/transition.bzl#L350-L362) (although it should be much simpler in this scenario)

It's worth noting that this still won't de-duplicate the build graph by default, but with Bazel 6 there's the `--experimental_output_directory_naming_scheme` flag which enables this feature. (see: https://github.com/bazelbuild/bazel/commit/52d1d4ae9bfee7379093d46258fa3a56e4d69e61) 

### Describe alternatives you've considered

No alternatives have been considered, but happy to take suggestions!

**Comment by rickeylev** [comment]
Building the same binary twice is certainly problematic and does lead to quite a bit of bloat (we saw similar problems during the python 2/3 migration and with the host-exec migration).

Does dropping the transition on data prevent selecting different data dependencies based on Python version? I don't recall the ordering of select vs attribute transitions. e.g. given

```
py_38_binary(...
   data = select(py38: ["py38.txt"], py39: ["py39.txt"])
)
```

Then "py38.txt" to be selected; changing it to py_39_binary should result in py39.txt, etc.

This does make me worry about confusing behavior (similar to what host config caused), e.g. this:

```
py_38_binary(
  name = "py38bin",
  data = [":pybin"]
)
py_binary( # use currently active py version
  name = "pybin"
)
```

Dropping the python version means "pybin" has a somewhat surprising switch from 3.8 to whatever the flag's default is.
