### ISSUE TITLE
Cannot build testonly py_wheel

### ISSUE THREAD

**Issue by faximan** [bazelbuild/rules_python#1057]
# 🐞 bug report

### Affected Rule

 The issue is caused by the rule:  py_wheel

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 0.16.2

### Description

With the addition of `.dist` meta targets in https://github.com/bazelbuild/rules_python/pull/1019, I can no longer build `//...` when including a `py_wheel` tagged `testonly`.

## 🔬 Minimal Reproduction

```
load("@rules_python//python:packaging.bzl", "py_wheel")
py_wheel(
    name = "foo_test_wheel",
    testonly = 1,
    distribution = "foo_test",
    version = "0.0.1",
)
```

`bazel --bazelrc=/dev/null build //...`

## 🔥 Exception or Error

<pre><code>
ERROR: ~/python/BUILD:240:9: in py_wheel_dist rule //foo_test_wheel.dist: non-test target '//:foo_test_wheel.dist' depends on testonly target '//:foo_test_wheel' and doesn't have testonly attribute set
</code></pre>

## 🌍  Your Environment

**Operating System:**

Debian

**Output of `bazel version`:**

<pre>
  <code>
Build label: 5.4.0
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Dec 15 16:14:25 2022 (1671120865)
Build timestamp: 1671120865
Build timestamp as int: 1671120865
  </code>
</pre>

**Rules_python version:**

<pre>
  <code>
0.17.3
  </code>
</pre>

**Comment by rickeylev** [comment]
Sorry about that. Thanks for the report. This is an easy fix. PR #1064 sent
