### ISSUE TITLE
Unable to use python_interpreter_target when using bzlmod

### ISSUE THREAD

**Issue by siddharthab** [bazelbuild/rules_python#1058]
# 🐞 bug report

### Affected Rule

 The issue is caused by the rule: pip.parse (in bzlmod)

### Is this a regression?

 No

### Description

 pip.parse supports the `python_intepreter_target` attribute but getting its value from `@python//:defs.bzl` is not currently possible because the string value is not available as an extension. This attribute is also not used in the bzlmod example in the repo.

## 🔬 Minimal Reproduction

```
# MODULE.bazel

bazel_dep(name = "rules_python", version = "0.18.0")
python = use_extension("@rules_python//python:extensions.bzl", "python")
python.toolchain(
    name = "python",
    python_version = "3.10",
)
use_repo(python, "python")
use_repo(python, "python_toolchains")
register_toolchains(
    "@python_toolchains//:all",
)
pip = use_extension("@rules_python//python:extensions.bzl", "pip")
interpreter = use_extension("@python//:defs.bzl", "interpreter")
pip.parse(
    name = "pip",
    python_interpreter_target = interpreter,
    requirements_lock = "//alife:requirements.txt",
)
use_repo(pip, "pip")
```

## 🔥 Exception or Error

```
ERROR: Target parsing failed due to unexpected exception: in tag at <root>/MODULE.bazel:39:10, error converting value for attribute python_interpreter_target: expected value of type 'string' for python_interpreter_target, but got <unknown object com.google.devtools.build.lib.bazel.bzlmod.ModuleFileGlobals$ModuleExtensionProxy> (module_extension_proxy)
```

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Debian GNU/Linux rodete
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
Build label: 6.0.0
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Mon Dec 19 15:52:35 2022 (1671465155)
Build timestamp: 1671465155
Build timestamp as int: 1671465155
  </code>
</pre>

**Rules_python version:**

<pre>
  <code>
0.18.0
  </code>
</pre>

**Anything else relevant?**

**Comment by matts1** [comment]
+1 to this issue. Unfortunately, pip defaults to using the system interpreter. This means that I had it working on one system, but on another system, I got this error message (since the other system had python 3.6 installed):

```
$ bazel build //rules_cros/toolchains/python:all
INFO: Repository rules_python~override~pip~pip_pylint instantiated at:
  callstack not available
Repository rule whl_library defined at:
  /home/msta/.cache/bazel/_bazel_msta/e517ea39ecb43168812d1d21bda62f96/external/rules_python~override/python/pip_install/pip_repository.bzl:712:30: in <toplevel>
ERROR: An error occurred during the fetch of repository 'rules_python~override~pip~pip_pylint':
   Traceback (most recent call last):
        File "/home/msta/.cache/bazel/_bazel_msta/e517ea39ecb43168812d1d21bda62f96/external/rules_python~override/python/pip_install/pip_repository.bzl", line 688, column 13, in _whl_library_impl
                fail("whl_library %s failed: %s (%s)" % (rctx.attr.name, result.stdout, result.stderr))
Error in fail: whl_library rules_python~override~pip~pip_pylint failed:  (Traceback (most recent call last):
  File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/msta/.cache/bazel/_bazel_msta/e517ea39ecb43168812d1d21bda62f96/external/rules_python~override/python/pip_install/tools/wheel_installer/wheel_installer.py", line 32, in <module>
    from python.pip_install.tools.wheel_installer import namespace_pkgs, wheel
  File "/home/msta/.cache/bazel/_bazel_msta/e517ea39ecb43168812d1d21bda62f96/external/rules_python~override/python/pip_install/tools/wheel_installer/wheel.py", line 19, in <module>
    import installer
  File "/home/msta/.cache/bazel/_bazel_msta/e517ea39ecb43168812d1d21bda62f96/external/rules_python~override~internal_deps~pypi__installer/installer/__init__.py", line 6, in <module>
    from installer._core import install  # noqa
  File "/home/msta/.cache/bazel/_bazel_msta/e517ea39ecb43168812d1d21bda62f96/external/rules_python~override~internal_deps~pypi__installer/installer/_core.py", line 7, in <module>
    from installer.destinations import WheelDestination
  File "/home/msta/.cache/bazel/_bazel_msta/e517ea39ecb43168812d1d21bda62f96/external/rules_python~override~internal_deps~pypi__installer/installer/destinations.py", line 19, in <module>
    from installer.scripts import Script
  File "/home/msta/.cache/bazel/_bazel_msta/e517ea39ecb43168812d1d21bda62f96/external/rules_python~override~internal_deps~pypi__installer/installer/scripts.py", line 6, in <module>
    from importlib.resources import read_binary
ModuleNotFoundError: No module named 'importlib.resources'
)
```

**Comment by matts1** [comment]
That's to be expected, and WAI. Return values from use_extension aren't usable directly by functions (https://github.com/bazelbuild/bazel/issues/17048).

Here's how I do it in our repo. It's not great because it can only work on a single platform. Ideally I'd like to be able to write `use_repo(python, "@python3.10.8_host")`, which could be done via this mechanism https://github.com/bazelbuild/bazel/issues/17493, but for now the best approach would probably be for rules_python to always expose the _host suffix which is a duplicate of the interpreter defined for that specific platform.
```
# Python support
PY_VERSION = "3.10.8"
bazel_dep(name = "rules_python", version = "0.18.0")

python = use_extension("@rules_python//python:extensions.bzl", "python")
python.toolchain(
    name = "python%s" % PY_VERSION,
    python_version = PY_VERSION,
)

PY_INTERPRETER_REPO = "python%s_x86_64-unknown-linux-gnu" % PY_VERSION
use_repo(
    python,
    "python%s_toolchains" % PY_VERSION,
    PY_INTERPRETER_REPO,
)
register_toolchains("@python%s_toolchains//:all" % PY_VERSION)

pip = use_extension("@rules_python//python:extensions.bzl", "pip")
pip.parse(
    name = "pip",
    requirements_lock = "//rules_cros/toolchains/python:requirements_lock.txt",
    python_interpreter_target="@%s//:python" % PY_INTERPRETER_REPO
)
use_repo(pip, "pip")
```

**Comment by chrislovecnm** [comment]
I am having the same problem. There is another argument that is named `python_interpreter` and I am uncertain how to use that flag as well.

**Comment by chrislovecnm** [comment]
@matts1 Any ideas on how to get the toolchain to download the Python as we did before? It is not ...

**Comment by chrislovecnm** [comment]
> Any ideas on how to get the toolchain to download the Python as we did before? It is not ... at least with windows.

So I have figured out that `bzlmod` does not support downloading a hermetic toolchain in the `MODULES.bzl` file.  I am working on figuring out a solution.

**Comment by mvgijssel** [comment]
In https://github.com/mvgijssel/setup/pull/180/files I've hacked something together that works for now. It creates a module extension which symlinks the correct Python interpreter in place and references that file inside the `python_interpreter_target` attribute:

`extensions.bzl`
```bazel
load("@python3//:defs.bzl", "interpreter")

def _symlink_python_interpreter_impl(repository_ctx):
    repository_ctx.file('BUILD.bazel', content='''
package(default_visibility = ["//visibility:public"])
exports_files(["python"])
''')
    python_path = repository_ctx.path(Label(interpreter))
    repository_ctx.symlink(python_path, 'python')

_symlink_python_interpreter = repository_rule(
    implementation=_symlink_python_interpreter_impl,
    local=True,
)

def _python_interpreter(module_ctx):
    print(module_ctx)

    _symlink_python_interpreter(
        name = "python_interpreter",
    )

python_interpreter = module_extension(
    implementation = _python_interpreter,
)
```

`MODULE.bazel`
```bazel
# NOTE: custom extension so we can reference the hermetic python interpreter in the pip.parse rules
# Can be removed once https://github.com/bazelbuild/rules_python/issues/1058 is solved.
python_interpreter = use_extension(":extensions.bzl", "python_interpreter")
use_repo(python_interpreter, "python_interpreter")

# ...

pip.parse(
    name = "pytest",
    python_interpreter_target = "@python_interpreter//:python",
    requirements_lock = "@//tools/pytest:requirements.lock",
)

use_repo(pip, "pytest")
```

**Comment by chrislovecnm** [comment]
So @mvgijssel way you did this does not work on Windows.  Grumble.

**Comment by mvgijssel** [comment]
> @mvgijssel do you have any recommendations for us to add this to the extension in the rules?

Good question! The gist of the change is to use a generically named repo to symlink the platform specific interpreter. Not sure if this actually works with cross platform builds etc and apparently not with Windows 🙈. 

Maybe it’s possible to copy (instead of symlink) the interpreter and associated files into a generically named repo? Then at least it also works for windows.

Now I’m curious btw how folks solve this in rules_nodejs as that also provides a hermetic nodejs version 🤔.

**Comment by chrislovecnm** [comment]
@siddharthab can we close this? #1155 gives you this functionality now. When we release next you will will have it

**Comment by siddharthab** [comment]
Thanks for all the consideration and work. The solution looks good to me. Closing this issue.
