### ISSUE TITLE
Reimplement rules in Starlark in rules_python

### ISSUE THREAD

**Issue by rickeylev** [bazelbuild/rules_python#1069]
This is the general tracking issue for re-implementing the Bazel-bundled Python rules in Starlark in the rules_python repo.

The Bazel-side issue is https://github.com/bazelbuild/bazel/issues/15897

As of now (Feb 2023), the Bazel bundled rules (not providers or flags, though) have all been re-implemented in Starlark. They will used in Bazel 7. Hooks for low-level Bazel behaviors the Python rules need are exposed to the rules_python repo. So now this is mostly a matter of copying that code over here, cleaning it up, and flushing out any missing hooks.

TODO
* [x] Copy Bazel code over to rules_python
* [ ] Re-implement Bazel tests in rules_python
* [ ] Re-implement flags in Starlark
* [x] Setup a CI config that uses e.g. bazel=rolling to get access to pre-release bazel versions
* [x] Enable pystar by default

That's the high level gist, some lower level TODOs are:
* [x] Implement compatibility shim so rules_python and Bazel rules can interoperate to some degree
* [ ] Deprecate and remove Bazel-bundled flags
* [ ] Deprecate and remove Python-related parts in `@bazel_tools`

An optional bonus thing is to backport the low-level hooks to 5.x and/or 6.x. This makes them available sooner, so that we don't have to wait for Bazel 7. There isn't a _ton_ to backport (I intentionally made them to be amenable to this idea), but there's several small pieces. The two general pieces are exposing the flags as fragments and the `py_internal` object:
* `py_internal` object and it's backing pieces:
  * [PyBuiltins.java](https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/rules/python/PyBuiltins.java)
  * [BazelPyBuiltins.java](https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/bazel/rules/python/BazelPyBuiltins.java)
  * [`py_internal` name declaration in BazelRuleClassProvider.java](https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/bazel/rules/BazelRuleClassProvider.java#L468-L471)
  * [`py_internal` name override in exports.bzl](https://github.com/bazelbuild/bazel/blob/master/src/main/starlark/builtins_bzl/common/exports.bzl#L45)
  * [py_internal.bzl](https://github.com/bazelbuild/bazel/blob/master/src/main/starlark/builtins_bzl/common/python/py_internal.bzl)
* Configuration fields (Bazel builtin flags); Strictly speaking, only flags that don't have a fixed set of values (e.g arbitrary string or labels) need to be made available. Other flags can be "wrapped" in a regular Starlark-defined flag by just having an exhaustive listing of `config_settings`
  * [`--python_path` and `--python_top` from BazelPythonConfiguration](https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/bazel/rules/python/BazelPythonConfiguration.java#L148-L161); note, however, that `--python_top` is _supposed_ to be unused (superceded by toolchains) and `--python_path` is _probably_ unused (unclear; some comments indicate it might be used as part of windows support)
  * [`--build_python_zip` from PythonConfiguration.java](https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/rules/python/PythonConfiguration.java#L131-L144); note, however, it, too, can be replicated in Starlark by using platforms or the `py_internal.get_current_os_name()` helper.

**Comment by aignas** [comment]
@rickeylev I can consistently reproduce build failure when running:
```
USE_BAZEL_VERSION=last_green RULES_PYTHON_ENABLE_PYSTAR=1 bazelisk test //python/tests/toolchains:python_3_9_10_x86_64-unknown-linux-gnu_test
```

It seems to resolve the wrong version of the toolchain and I think this is something to have changed in the `bazel@HEAD`.

**Comment by aignas** [comment]
Doing a `bisect`:
```console
$ RULES_PYTHON_ENABLE_PYSTAR=1 bazelisk --bisect=2c9d68e05861ac3e71cb86de2b69bc52403411bf..HEAD test //python/tests/toolchains:python_3_9_10_x86_64-unknown-linux-gnu_test
```

yielded the following commits:
* https://github.com/bazelbuild/bazel/commit/75657569220178f11ec12f7ce33812e571c6c854 (passes)
* https://github.com/bazelbuild/bazel/commit/2b8219042c
* https://github.com/bazelbuild/bazel/commit/659d7b223ad5d180c6ca89eb7fa8420f3632edeb (404)

**Comment by aignas** [comment]
Create #1496 for the current CI issues.

**Comment by Ryang20718** [comment]
wondering if pyc support is on the roadmap? https://github.com/bazelbuild/bazel/issues/16245

**Comment by aignas** [comment]
Let's close this as complete as it is working well. Thank you @rickeylev!
