### ISSUE TITLE
Cannot depend on requirements that have files with '{}' in their names

### ISSUE THREAD

**Issue by whilp** [bazelbuild/rules_python#107]
rules_python version: 8b5d0683a7d878b28fffe464779c8a53659fc645
aws-sam-cli version: https://github.com/awslabs/aws-sam-cli/tree/v0.4.0

When building a target that depends on aws-sam-cli, we get the following failure:

> ERROR: /home/me/.cache/bazel/_bazel_root/ed98a75197af1b342217f8ed7660737f/external/pypi__aws_sam_cli_0_4_0/BUILD:6:1: @pypi__aws_sam_cli_0_4_0//:pkg: invalid label 'samcli/local/init/templates/cookiecutter-aws-sam-hello-python/{{cookiecutter.project_name}}/hello_world/__init__.py' in element 77 of attribute 'srcs' in 'py_library' rule: invalid target name 'samcli/local/init/templates/cookiecutter-aws-sam-hello-python/{{cookiecutter.project_name}}/hello_world/__init__.py': target names may not contain '{'
> ERROR: /home/me/.cache/bazel/_bazel_root/ed98a75197af1b342217f8ed7660737f/external/pypi__aws_sam_cli_0_4_0/BUILD:6:1: @pypi__aws_sam_cli_0_4_0//:pkg: invalid label 'samcli/local/init/templates/cookiecutter-aws-sam-hello-dotnet/{{cookiecutter.project_name}}/.gitignore' in element 14 of attribute 'data' in 'py_library' rule: invalid target name 'samcli/local/init/templates/cookiecutter-aws-sam-hello-dotnet/{{cookiecutter.project_name}}/.gitignore': target names may not contain '{'

It's admittedly odd to include '{}' in target names. I'm not sure what the right thing for rules_python to do here would be, but it does seem unfortunate if certain deps cannot be expressed because of the way their files are named.

**Comment by kornholi** [comment]
Does it work with Bazel 0.15? The naming requirements were relaxed in https://github.com/bazelbuild/bazel/commit/c4f2d80270f1ce947fcf7fb0a4e5f0afb3a7062d

**Comment by thundergolfer** [comment]
Can confirm the error is not present with: 

- Bazel `4.0.0`
- rules_python `0.2.0` using `pip_install`
- `aws-sam-cli==0.4.0` (same version as used in issue desc)
