### ISSUE TITLE
Tag new release version including wheel publishing

### ISSUE THREAD

**Issue by giokara-oqton** [bazelbuild/rules_python#1090]
# 🚀 feature request

### Relevant Rules

Python wheel publishing, already introduced by https://github.com/bazelbuild/rules_python/pull/1015.

### Describe the solution you'd like

We would like a new release tag of this repo including https://github.com/bazelbuild/rules_python/pull/1015. We already use this rule on a feature branch, but QA at our company does not allow use of rules that have not been released.

**Comment by rickeylev** [comment]
0.19.0 has been released: https://github.com/bazelbuild/rules_python/releases/tag/0.19.0
