### ISSUE TITLE
feat(wheel): support src-layout project

### ISSUE THREAD

**Issue by aarnphm** [bazelbuild/rules_python#1101]
# 🚀 feature request

### Relevant Rules

`py_wheel`

### Description

 A clear and concise description of the problem or missing capability...

Currently, `py_wheel` only supports projects with [ad-hoc layout](https://setuptools.pypa.io/en/latest/userguide/package_discovery.html#flat-layout). It would be nice if `py_wheel` can also support `src-layout`.

### Describe the solution you'd like

```starlark
load("@rules_python//python:packaging.bzl", "py_wheel")

py_wheel(
   name = "my_lib"
   layout= "src" | "adhoc" # can default to adhoc, which is current behaviour
   deps = [...]
```

### Describe alternatives you've considered

Previously, I was depending on a shell script to build the wheel and use bazel to manage it.

I implemented a custom rule for `py_wheel` to support this feature, but it would be nice if it is supported upstream.

**Comment by pstradomski** [comment]
Bazel doesn't really work well with src layout - you'd need "import src.foo" everywhere and //src in BUILD files.

With that in mind, py_wheel has strip_prefixes feature, so you can use that today to achieve your goals.

**Comment by aarnphm** [comment]
> With that in mind, py_wheel has strip_prefixes feature, so you can use that today to achieve your goals.

I'm aware of this options (it is `strip_path_prefixes`), but I'm thinking of probably a nicer way to officially support this, similar to setuptools.

Currently I have a rule for `py_package` that behaves similar to what `strip_path_prefixes`, that also support C extension. But I'm not sure what is the state or roadmap from rules_python to support C extension wheels.
