### ISSUE TITLE
Wheels Example using $(VERSION) make variable substitution

### ISSUE THREAD

**Issue by stonier** [bazelbuild/rules_python#1104]
# 🚀 feature request

### Example

Looking for an example on how to inject `$(VERSION)` as described in the code here:

https://github.com/bazelbuild/rules_python/blob/c504355672223144cefb2cbf3f69e2d38e7e2726/python/private/py_wheel.bzl#L97

### Description

The current examples only demonstrate injection of the pre-defined timestamp make variable:

https://github.com/bazelbuild/rules_python/blob/c504355672223144cefb2cbf3f69e2d38e7e2726/examples/wheel/BUILD.bazel#LL77C39-L77C39

### Describe the solution you'd like

Not at all sure if this is even possible with the current setup. I've attempted to define a target that returns a TemplateVariableInfo provider that defines $(VERSION) and then added it to the rules' toolchains argument, but that complains about the target not providing a ToolchainTypeInfo provider.

**Comment by aarnphm** [comment]
I think you can do the following
```starlark
py_wheel(
	...
    version = "{BUILD_EMBED_LABEL}",
	...
)
```

Then when you run `bazel build`:

```bash
bazel build --stamp --embed_label=<version> -- //:wheel
```
