### ISSUE TITLE
docs: pip cache location

### ISSUE THREAD

**Issue by sasha-wing** [bazelbuild/rules_python#1106]
# 🚀 feature request

### Relevant Rules
pip rules 
### Description

I can't find any documentation on where the cache for the pip rules is located.
Can you please add documentation for that?

I need it for CI optimizations

### Describe the solution you'd like

A documentation about the cache location

### Describe alternatives you've considered
I tried using the default pip cache location but Im not sure it is actually using it

**Comment by aignas** [comment]
As far as I am aware there are no such toggles yet.

Have you considered setting up https://bazel.build/remote/caching? This is what we use to not need to download the packages all the time.
