### ISSUE TITLE
how to use bazel with venv.

### ISSUE THREAD

**Issue by PraflyGod** [bazelbuild/rules_python#112]
Our online project always use python-env. Yes, every project just has a dir called venv, which contain python, pip, all the stuff needed. How I can work with bazel to get benefit.

**Comment by PraflyGod** [comment]
I found the solution.  Thanks.

**Comment by dsully** [comment]
@PraflyGod could you share the solution you found so that others who search can find this issue?

Thanks

**Comment by jvolkman** [comment]
For anyone interested, I've created a rule to build virtual envs using Bazel: https://github.com/cedarai/rules_pyvenv
