### ISSUE TITLE
compile_pip_requirements in package below workspace root level not working on Windows

### ISSUE THREAD

**Issue by e8y** [bazelbuild/rules_python#1129]
# 🐞 bug report

### Affected Rule

`compile_pip_requirements`

### Is this a regression?

Unsure

### Description

I'm trying to use `compile_pip_requirements` to create a requirements_lock.txt file from a requirements.in file. I don't have the requirements_lock.txt file yet, so I'm trying to use this rule to create it for the first time.

First, I had to comment out everything in my workspace / build files referring to the requirements_lock.txt input to avoid getting errors. This seems to be a usability quirk---I was hoping that running `bazel run //mypackage:requirements.update` would work without triggering the other rules that depend on requirements_lock.txt (i.e., from `bazel build`).

After cleaning that up, I then get the following error(s):

```
PS C:\work\workspace_root\mypackage> bazel run requirements.update
INFO: Analyzed target //mypackage:requirements.update (52 packages loaded, 1050 targets configured).
INFO: Found 1 target...
ERROR: C:/work/workspace_root\mypackage/BUILD:36:25: PythonZipper mypackage/requirements.update.zip failed: missing input file '//mypackage:requirements_lock.txt'
ERROR: C:/work/workspace_root\mypackage/BUILD:36:25: PythonZipper mypackage/requirements.update.zip failed: 1 input file(s) do not exist
Target //mypackage:requirements.update failed to build
Use --verbose_failures to see the command lines of failed build steps.
ERROR: C:/work/workspace_root\mypackage/BUILD:36:25 PythonZipper mypackage/requirements.update.zip failed: 1 input file(s) do not exist
```

#### `WORKSPACE`

```
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
http_archive(
    name = "rules_python",
    sha256 = "ffc7b877c95413c82bfd5482c017edcf759a6250d8b24e82f41f3c8b8d9e287e",
    strip_prefix = "rules_python-0.19.0",
    url = "https://github.com/bazelbuild/rules_python/releases/download/0.19.0/rules_python-0.19.0.tar.gz",
)
```

#### `mypackage/BUILD`

```
load("@rules_python//python:pip.bzl", "compile_pip_requirements")
compile_pip_requirements(
    name = "requirements",
    #extra_args = ["--allow-unsafe"],
    requirements_in = "//mypackage:requirements.in",  # also tried just "requirements.in"
    requirements_txt = "//mypackage:requirements_lock.txt",  # also tried just "requirements_lock.txt"
    visibility = ["//visibility:public"],
)
```

#### Command

```
> cd workspace_root
> bazel run //mypackage:requirements.update
```

Also tried the following, with the same result:

```
> cd mypackage
> bazel run requirements.update
```

I also tried just `touch`ing an empty `requirements_lock.txt` file but get the same result.

## 🔥 Exception or Error

<pre><code>

PS C:\work\workspace_root\mypackage> bazel run requirements.update
INFO: Analyzed target //mypackage:requirements.update (52 packages loaded, 1050 targets configured).
INFO: Found 1 target...
ERROR: C:/work/workspace_root\mypackage/BUILD:36:25: PythonZipper mypackage/requirements.update.zip failed: missing input file '//mypackage:requirements_lock.txt'
ERROR: C:/work/workspace_root\mypackage/BUILD:36:25: PythonZipper mypackage/requirements.update.zip failed: 1 input file(s) do not exist
Target //mypackage:requirements.update failed to build
Use --verbose_failures to see the command lines of failed build steps.
ERROR: C:/work/workspace_root\mypackage/BUILD:36:25 PythonZipper mypackage/requirements.update.zip failed: 1 input file(s) do not exist
</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Windows 10, 64-bit (Version 21H2, Build 19044.2604)
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
Bazelisk version: v1.16.0
Build label: 6.1.0
Build target: bazel-out/x64_windows-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Mon Mar 6 17:11:12 2023 (1678122672)
Build timestamp: 1678122672
Build timestamp as int: 1678122672
  </code>
</pre>

**Rules_python version:**

<pre>
  <code>
0.19.0
  </code>
</pre>

**Anything else relevant?**

**Comment by chrislovecnm** [comment]
So I just tried:

```console
cd rules_python\examples\build_file_generation
```
```console
bazelisk --output_user_root=C:/b run --show_progress_rate_limit=5 --curses=yes --color=yes --terminal_columns=143 --show_timestamps --verbose_failures --jobs=30 --announce_rc --experimental_repository_cache_hardlinks --disk_cache= requirements.update
```

It seems to work on using the main branch on Windows 10.  Can you create an example using the latest version of `rules_python` or main?
