### ISSUE TITLE
py_wheel_dist does not declare runfiles

### ISSUE THREAD

**Issue by alokpr** [bazelbuild/rules_python#1130]
# 🐞 bug report

### Affected Rule

py_wheel

### Is this a regression?

Not a regression. Publishing a wheel is a new feature in version 0.19 which is broken

### Description

`bazel run //path/to:my_wheel.publish` fails.

## 🔥 Exception or Error

<pre><code>

ERROR    InvalidDistribution: Cannot find file (or expand pattern): '//path/to:my_wheel_dist/*'

</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.6 LTS
Release:	18.04
Codename:	bionic
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
Build label: 5.4.0
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Dec 15 16:14:25 2022 (1671120865)
Build timestamp: 1671120865
Build timestamp as int: 1671120865
  </code>
</pre>

**Rules_python version:**

<pre>
  <code>
0.19.0
  </code>
</pre>

**Anything else relevant?**

Adding the dist directory to runfiles fixes the issue

**Comment by alokpr** [comment]
Attaching the patch file that fixes the issue. Happy to send a PR if needed.
```
diff --git a/python/packaging.bzl b/python/packaging.bzl
index fffd239..5ddb229 100644
--- a/python/packaging.bzl
+++ b/python/packaging.bzl
@@ -50,7 +50,7 @@ def _py_wheel_dist_impl(ctx):
         use_default_shell_env = True,
     )
     return [
-        DefaultInfo(files = depset([dir])),
+        DefaultInfo(files = depset([dir]), runfiles = ctx.runfiles([dir])),
     ]
 
 py_wheel_dist = rule(
```

**Comment by LouisLU9911** [comment]
I met the same problem. @alokpr 's workaround works, thanks!
