### ISSUE TITLE
Duplicate python libs

### ISSUE THREAD

**Issue by junyousician** [bazelbuild/rules_python#114]
When using the python rule for building, there are duplicate python libs symlinks for example:
 
`bazel-out/darwin-fastbuild/bin/<app>/app.runfiles/pypi__Jinja2_2_8`
and 
`bazel-out/darwin-fastbuild/bin/<app>/app.runfiles/__main__/external/pypi__Jinja2_2_8`

both of them are the symlinks of the lib exists on my local machine path `/private/var/tmp/.../external/pypi__Jinja2_2_8`

Since we package our app to zip file for deployment, libs will get copied twice to the zip file when zipping app.runfiles folder. Is this behavior normal or do we doing the bazel app packaging wrong?

**Comment by groodt** [comment]
This is a very old bug. Please provide a reproduction using a modern version of rules_python.

In terms of something specific to try, you could try using the built-in `--build_python_zip` functionality or the output group.

```
filegroup(
  name = "foo_zip",
  srcs=  ["//bar:foo"],
  output_group = "python_zip_file",
)
```
