### ISSUE TITLE
Gazelle plugin's modules_mapping rule still depends on WORKSPACE file when enable bzlmod

### ISSUE THREAD

**Issue by teabuff** [bazelbuild/rules_python#1153]
# 🐞 bug report

### Affected Rule

The issue is caused by the modules_mapping rule: https://github.com/bazelbuild/rules_python/blob/main/gazelle/modules_mapping/def.bzl#L41

### Is this a regression?

No

### Description

Following the newly added bzlmod document in #1149 to try the rules_python with bzlmod, however the current example [build_file_generation](https://github.com/bazelbuild/rules_python/tree/main/examples/build_file_generation) will complain the `@pip` repository could not be resolved when build the modules_map:

```
$ bazel build --enable_bzlmod //:modules_map
ERROR: rules_python/examples/build_file_generation/BUILD.bazel:25:16: no such package '@pip//flask': The repository '@pip' could not be resolved: Repository '@pip' is not defined and referenced by '//:modules_map'
```

After some test, I believe this is due to the modules_mapping somewhat always point to the `@pip` repository in the old WORKSPACE instead of the one defined in MODULE.bazel. This is annoying because you have to still write all the snippet in WORKSPACE file with bzlmod in order to use the gazelle plugin (//:gazelle_python_manifest.update).  Especially if you want to start a new bazel python project using bzlmod, you need write duplicate snippets for both MODULE.bazel and WORKSPACE file.

## 🔬 Minimal Reproduction

This can be easily reproduced by creating a WORKSPACE.bzlmod file in the [build_file_generation](https://github.com/bazelbuild/rules_python/tree/main/examples/build_file_generation) folder:

```
$ git clone https://github.com/bazelbuild/rules_python.git
$ cd rules_python/examples/build_file_generation
$ touch WORKSPACE.bzlmod
$ bazel build --enable_bzlmod //:modules_map
```

The empty WORKSPACE.bzlmod would clear all the effects of snippets defined in WORKSPACE. In bzlmod, we already finish all the setup in the MODULE.bazel file. Therefore, we don't need the WORKSPACE file.

## 🔥 Exception or Error

N/A

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
 Debian 6.1.12-1 (2023-02-15) x86_64 GNU/Linux
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
Bazelisk version: v1.12.2
Build label: 6.1.1
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed Mar 15 15:44:56 2023 (1678895096)
Build timestamp: 1678895096
Build timestamp as int: 1678895096
  </code>
</pre>

**Rules_python version:**

<pre>
  <code>
0.19.0
  </code>
</pre>

**Anything else relevant?**
N/A

**Comment by aignas** [comment]
This should have been fixed in #1146, could you verify that the fix works for you?

**Comment by chrislovecnm** [comment]
@aignas take a look at my new pr. It is not fixed

**Comment by aignas** [comment]
@chrislovecnm, your PR has a missing line that is causing the failure, so the issue in your PR and in this ticket is not the same.

**Comment by teabuff** [comment]
@aignas Thank you so much for the awesome work! I can confirm this is fixed even in my separate Workspace. And I am wondering if you can also modify the document a little bit regarding the snippet of a MODULE.bazel file: https://github.com/bazelbuild/rules_python/tree/main/gazelle#adding-gazelle-to-your-project

I feel we might need to archive_override the rules_python_gazelle_plugin bazel_dep as the following:

```
bazel_dep(name = "rules_python_gazelle_plugin", version = "0.20.0") <-- better to be version 0.20.x include your fix 
archive_override(
    module_name = "rules_python_gazelle_plugin",
    urls = ["https://github.com/bazelbuild/rules_python/releases/download/0.20.0/rules_python-0.20.0.tar.gz"],
    integrity = "sha256-pkTalptoJMyH+P57GBAaimxX2l2znKplZuxhCfN9IUE=",
    strip_prefix="rules_python-0.20.0/gazelle",
)
```

The build_file_generator example directly use the local_path_override to point to the current workspace. However, for using it in a completely separate Workspace, I am not sure if there is a better way than using archive_override to refer to a Module(rules_python_gazelle_plugin) defined within another Module(rules_python). If you know it, please do not hesitate to let me know. Thanks again for working on this.

**Comment by chrislovecnm** [comment]
@teabuff is this working for you now?  If so can you close the issue?

**Comment by teabuff** [comment]
Sure, thanks, close as this works!
