### ISSUE TITLE
Add `:deps` to `pip_import` and enable change detection of imported requirement files.

### ISSUE THREAD

**Issue by daicoden** [bazelbuild/rules_python#116]
given to files: `requirements.txt` and `test_requirments.txt`

where test_requirments looks like:

```
-r requirements.txt
pytest==3.2.1
```

It would be helpful if we could have a dependency field to explicitly list those files are linked, right now when you change requirements.txt the workspace does not update.

Even better would be if the pip install worked in a sandbox, so pip install would fail unless you specified all the relevant requirement files.

```
pip_import(
    name = "all_deps",
    requirements = "//foo/bar/:test_requirements.txt",
    deps = ["//foo/bar:requirements.txt"]
)
```

**Comment by thundergolfer** [comment]
From `python3 -m pip install --help`:

```
  -r, --requirement <file>    Install from the given requirements file. This option can be used multiple
                              times.
```

If I understand the `-r` behaviour correctly is just concatenating `.txt` file contents before running install. I think this can just be handled in a preprocessing step and the Bazel repo rules can remain supportive of only a single `requirements.txt` file as input.

**Comment by daicoden** [comment]
Note: it's not quite a concatenation, you have to read the file contents, strip out any of the -r lines, find the files relative imported files to the current file being parsed, but fair enough.
