### ISSUE TITLE
py_wheel does not propagate "visibility" attribute to the "publish" rule

### ISSUE THREAD

**Issue by alokpr** [bazelbuild/rules_python#1192]
# 🐞 bug report

### Affected Rule

py_wheel

### Is this a regression?

Not a regression. Publishing a wheel is a new feature in version 0.19 which is broken

### Description

The visibility attribute on py_wheel target is not propagated to the auto-generated "publish" target.

## 🔬 Minimal Reproduction

$ cat A/BUILD.bazel
```
py_wheel(
    name = "foo",
    distribution = "foo",
    visibility = ["//visibility:public"],
)
```

$ cat B/BUILD.bazel
```
load("@rules_multirun//:defs.bzl", "multirun")

multirun(
    name = "wheels.publish",
    commands = [
        "//A:foo.publish",
    ]
)
```

## 🔥 Exception or Error

<pre><code>
bazel run //B:wheels.publish
ERROR: B/BUILD.bazel: in multirun rule //:wheels.publish: target '//A.publish' is not visible from target '//:wheels.publish'. Check the visibility declaration of the former target if you think the dependency is legitimate
ERROR: B/BUILD.bazel: Analysis of target '//:wheels.publish' failed
ERROR: Analysis of target '//:wheels.publish' failed; build aborted:
</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Ubuntu 22.04
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
Build label: 5.4.0
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Dec 15 16:14:25 2022 (1671120865)
Build timestamp: 1671120865
Build timestamp as int: 1671120865
  </code>
</pre>

**Rules_python version:**

<pre>
  <code>
0.19
  </code>
</pre>

**Anything else relevant?**

**Comment by alokpr** [comment]
This simple patch fixes the issue:
```
diff --git a/python/packaging.bzl b/python/packaging.bzl
index fffd239..45d5c96 100644
--- a/python/packaging.bzl
+++ b/python/packaging.bzl
@@ -172,6 +172,7 @@ def py_wheel(name, twine = None, **kwargs):
             imports = ["."],
             main = twine_main,
             deps = [twine],
+            visibility = kwargs.get("visibility"),
         )

 py_wheel_rule = _py_wheel
```

**Comment by chrislovecnm** [comment]
@alokpr thanks for the patch.  I submitted a PR
