### ISSUE TITLE
Example of pip_parse_vendored under bzlmod

### ISSUE THREAD

**Issue by mrmeku** [bazelbuild/rules_python#1198]
# 🚀 feature request

### Description

The current example for vendoring in pip_parse uses a WORKSPACE file to load in a generated .bzl file. This is all well and good, but if someone wanted to fetch rules_python via bzl mod that no longer works. Its not immediately obvious how to make this work within a MODULE.bazel file, or if this can be done at all. 

### Describe the solution you'd like

Making a new example directory or migrating the existing example of pip_parse_vendored to bzlmod

**Comment by chrislovecnm** [comment]
Will https://github.com/bazelbuild/rules_python/pull/1155 provide enough of an example?  You don't have to have gazelle, but I think the example outlines the details.

**Comment by aignas** [comment]
Thanks for raising the issue @mrmeku. I am not sure what the goal of such example would be as using `bzlmod` should not fetch anything from the internet and the behaviour of the `pip.parse` extension should be the same as in the vendored `requirments.bzl` workflow. Could you add more details about what you are trying to solve which would need a vendoring capability within `bzlmod`?

**Comment by mrmeku** [comment]
Oh, that makes sense! I didn't realize that the behavoir using `pip.parse` was already meeting that requirement. I'll close this out
