### ISSUE TITLE
Xgboost compiles successfully but some interfaces cannot be called

### ISSUE THREAD

**Issue by 5201314wq** [bazelbuild/rules_python#122]
I have added xgboost in my bazel project with rules_python.
After I build my project, there be a xgboost directory in pypi__xgboost_0_80 of my project's runfiles.and in xgboost, i can find  rabit.py， But when I call xgb.train() in my code, I get an error as follows：
File "/**/bazel-bin/**/test.runfiles/pypi__xgboost_0_80/xgboost/training.py", line 52, in _train_internal
    assert(rabit.get_world_size() != 1 or version == 0)
AttributeError: 'module' object has no attribute 'get_world_size'

I have also tried other versions of xgboost and bazel 0.13.1 and 0.17.1, but it doesn't work.
when i use ‘pip install xgboost==0.80’, everything works fine.

**Comment by cmgreen210** [comment]
Were you able to solve this? I'm running into the same problem.

**Comment by cmgreen210** [comment]
@brandjon thank you for your very prompt reply! Indeed, the `rabit` file and directory are the issue. Luckily, I've have a way to patch pip packages and remove (or rename) the `rabit` directory (which I don't believe is necessary for the library to function). Thanks!

**Comment by scele** [comment]
I don't think #157 will solve this. I assume `pypi__xgboost_0_80` here was extracted from a wheel, the layout of the [source code repo](https://github.com/dmlc/xgboost) where the wheel was built is irrelevant. If you look at the wheel (download e.g. [here](https://files.pythonhosted.org/packages/54/21/8b2ec99862903a6d3aed62ce156d21d114b8666e669c46d9e54041df9496/xgboost-0.81-py2.py3-none-manylinux1_x86_64.whl)), it contains both `rabit.py` and `rabit` subdirectory (and no `python-package` subdir at all). So the question seems to be, how come pip-installing the module will resolve to `rabit.py`, but when used via bazel it will resolve to the `rabit` subdir?!

@brandjon if you agree, would you mind re-opening this issue?

**Comment by brandjon** [comment]
Right. Thanks for pointing that out.

**Comment by groodt** [comment]
I've ran into this issue too. After much head-scratching, it appears to be caused by the behaviour where empty `__init__.py` files are added into Python packages when the wheels are unpacked and spread.

You can disable this behaviour with: `--incompatible_default_to_explicit_init_py` which will eventually become the default from my understanding.

This only partially fixes the problem. For xgboost 0.90 you also need `purelib` support, which is missing from `rules_python`, but available in other rules. https://github.com/bazelbuild/rules_python/issues/92

**Comment by thundergolfer** [comment]
@5201314wq it's been a long long while, but if you try the `pip_install` repo rule with `xgboost==1.3.3` things should work for you 🙂.
