### ISSUE TITLE
Enable rules_python on Bazel with downstream projects pipeline

### ISSUE THREAD

**Issue by mhlopko** [bazelbuild/rules_python#123]
Hello,

since https://github.com/bazelbuild/rules_python/issues/98 is not making any progress (e.g. https://buildkite.com/bazel/rules-python-python/builds/125#2202858d-3d7f-47ad-84cb-e0ef30cbd7d4 is still red), I'm disabling rules_python on Bazel with downstream projects pipeline (https://buildkite.com/bazel/bazel-with-downstream-projects-bazel/builds/473#6a09dbe3-9923-4931-ac04-10d6f5cd60a5). Once rules_python are green again on https://buildkite.com/bazel/rules-python-python, please ping bazel-green-team@googlegroups.com to re-enable it.

Thanks!

**Comment by mhlopko** [comment]
Or better, create an issue on https://github.com/bazelbuild/continuous-integration, thanks!

**Comment by brandjon** [comment]
We're green. Created [continuous-integration #382](https://github.com/bazelbuild/continuous-integration/issues/382). Thanks!
