### ISSUE TITLE
unable to find pip extras

### ISSUE THREAD

**Issue by bbarnes52** [bazelbuild/rules_python#126]
BUILD
```
load("@preprocessing//:requirements.bzl", "requirement")

py_binary(
    name = "preprocessing",
    main = "preprocess.py",
    srcs = ["preprocess.py"],
    deps = [ 
        "//src/roboflow/pipeline/common:constants",
        requirement("apache-beam[gcp]"),
        requirement("protobuf"),
        requirement("tensorflow"),
    ]   
)
```

requirements.txt

```
apache-beam[gcp]==2.5.0
tensorflow==1.8
protobuf==3.6.1
```
ERROR: /src/workspace/src/roboflow/pipeline/preprocessing/BUILD:3:1: Traceback (most recent call last):
        File "/src/workspace/src/roboflow/pipeline/preprocessing/BUILD", line 3
                py_binary(name = "preprocessing", main = "pr...", <2 more arguments>)
        File "/src/workspace/src/roboflow/pipeline/preprocessing/BUILD", line 9, in py_binary
                requirement("apache-beam[gcp]")
        File "/tmp/build_output/a08c2e4811c846650b733c6fc815a920/external/preprocessing/requirements.bzl", line 498, in requirement
                fail(("Could not find pip-provided de...))
Could not find pip-provided dependency: 'apache-beam[gcp]'

**Comment by bbarnes52** [comment]
@mattmoor it looks like this was the subject of #12  is it possible the fix is not WAI?

**Comment by bbarnes52** [comment]
some context, hoping it helps this issue gets prioritized: I'm a GCP customer that wants to use both DataFlow and Cloud Build + Remote Build Execution. This issue actually blocks me from doing so, because I cannot specify apache_beam[gcp] as a dependency in my bazel builds, and so we are not spending as much money as we would like on DataFlow!

**Comment by pcn** [comment]
I'm going to speculate here, but is it possible that the problem here is that the extras support is based on there being a wheel built with the extras support included? If that's the case, then if the extras-containing-wheel doesn't exist in the cheeseshop or a private pypi, then the extras resolution code can't find it.

**Comment by pcn** [comment]
If I do this test:
```
|S|spacey@masonjar:~/dvcs/github/rules_python/examples/extras (master)$ git diff
diff --git a/examples/extras/BUILD b/examples/extras/BUILD
index 94880ce..ac21087 100644
--- a/examples/extras/BUILD
+++ b/examples/extras/BUILD
@@ -25,5 +25,6 @@ py_test(
         requirement("google-cloud-language"),
         # Make sure that we can resolve the "extra" dependency
         requirement("googleapis-common-protos[grpc]"),
+        requirement("urllib3[secure]")
     ],
 )
diff --git a/examples/extras/extras_test.py b/examples/extras/extras_test.py
index 3ad249d..e0c1591 100644
--- a/examples/extras/extras_test.py
+++ b/examples/extras/extras_test.py
@@ -14,7 +14,6 @@
 
 import unittest
 
-
 # The test is the build itself, which should not work if extras are missing.
 class ExtrasTest(unittest.TestCase):
   def test_nothing(self):
diff --git a/examples/extras/requirements.txt b/examples/extras/requirements.txt
index 743bbe7..a537b7e 100644
--- a/examples/extras/requirements.txt
+++ b/examples/extras/requirements.txt
@@ -1 +1,2 @@
 google-cloud-language==0.27.0
+urllib3[secure]==1.24.1
```

and run it, the tests fail:
```
|S|spacey@masonjar:~/dvcs/github/rules_python/examples/extras (master)$ bazel build extras_test
ERROR: /home/spacey/dvcs/github/rules_python/examples/extras/BUILD:21:1: Traceback (most recent call last):
	File "/home/spacey/dvcs/github/rules_python/examples/extras/BUILD", line 21
		py_test(name = "extras_test", srcs = ["ext..."], ...]")])
	File "/home/spacey/dvcs/github/rules_python/examples/extras/BUILD", line 28, in py_test
		requirement("urllib3[secure]")
	File "/home/spacey/.cache/bazel/_bazel_spacey/1ae7dfbb7c05ad803982282d8865e887/external/examples_extras/requirements.bzl", line 266, in requirement
		fail(("Could not find pip-provided de...))
Could not find pip-provided dependency: 'urllib3[secure]'
ERROR: Skipping 'extras_test': no such target '//examples/extras:extras_test': target 'extras_test' not declared in package 'examples/extras' defined by /home/spacey/dvcs/github/rules_python/examples/extras/BUILD
WARNING: Target pattern parsing failed.
ERROR: no such target '//examples/extras:extras_test': target 'extras_test' not declared in package 'examples/extras' defined by /home/spacey/dvcs/github/rules_python/examples/extras/BUILD
INFO: Elapsed time: 0.330s
INFO: 0 processes.
```

And indeed the extras aren't described in the generated .bzl file:
```
|S|spacey@masonjar:~/dvcs/github/rules_python/examples/extras (master)$ grep -A3 urllib3 /home/spacey/.cache/bazel/_bazel_spacey/1ae7dfbb7c05ad803982282d8865e887/external/examples_extras/requirements.bzl | head -7
  if "pypi__urllib3_1_24_1" not in native.existing_rules():
    whl_library(
        name = "pypi__urllib3_1_24_1",
        whl = "@examples_extras//:urllib3-1.24.1-py2.py3-none-any.whl",
        requirements = "@examples_extras//:requirements.bzl",
        extras = []
    )
```

The reason this is breaking is here:

https://github.com/bazelbuild/rules_python/blob/master/rules_python/whl.py#L57-L69

which calls https://github.com/bazelbuild/rules_python/blob/master/rules_python/whl.py#L109-L112

Note the comment:
```
 # TODO: handle fields other than just name
```

So if a particular package doesn't include a metadata.json, which isn't necessarily common, the `METADATA` file, which is pretty common, doesn't get used for anything than the `name` property.

If I test this: https://github.com/bazelbuild/rules_python/compare/master...pcn:features/more-compatible-metadata-reading

This makes it so that the output of piptool has the extras in it:
```
~/dvcs/github/rules_python/examples/extras$ ../../bazel-bin/rules_python/piptool --input requirements.txt --directory . --output test.bzl
~/dvcs/github/rules_python/examples/extras$ grep -C3 secure test.bzl | head
        name = "pypi__urllib3_1_24_1",
        whl = "@None//:urllib3-1.24.1-py2.py3-none-any.whl",
        requirements = "@None//:requirements.bzl",
        extras = ["secure","socks"]
    )

  if "pypi__idna_2_8" not in native.existing_rules():
--
    )
```
I'm pretty sure this isn't the preferred approach, but since this cause is known, it seems like this could lead to an acceptable fix.

**Comment by pcn** [comment]
Also, even though I can get piptool to work for me, the piptool.par that gets invoked when I try to run the tests breaks - I'm not clear as to why, I'm sure I'm missing something obvious.

**Comment by thundergolfer** [comment]
Very closely related to https://github.com/bazelbuild/rules_python/issues/185, which was just closed on account of new `pip_install` and `pip_parse` supporting `apache-beam[gcp]` dependency. Will close this too.
