### ISSUE TITLE
Use repo-relative labels instead of @rules_python-qualified labels

### ISSUE THREAD

**Issue by rickeylev** [bazelbuild/rules_python#1296]
Currently, the code base uses a mixture of `@rules_python//foo:bar` and `//foo:bar` labels. Having a mixture is innocuous, but introduces an unnecessary inconsistency in style.

Let's just normalize on using the `//` labels within our project instead of `@rules_python//`. It's shorter and makes it clear the references are intra-repo instead of inter-repo.

**Comment by alexeagle** [comment]
There is a case where the fully-qualified labels are needed though - when they are resolved from String -> Label in the user's context. It requires a bit of thought and care (or sufficient automated tests to catch this, which I think we probably have)

**Comment by rickeylev** [comment]
Good point. Let's make a habit of dropping a comment where we have to use the repo-qualified name for technical reasons.
