### ISSUE TITLE
Python repositories in Windows may include unnecessary files

### ISSUE THREAD

**Issue by lpulley** [bazelbuild/rules_python#1298]
The Python repository glob includes/excludes may not be sufficiently filtering unnecessary files on Windows.

> I’m guessing we need to add a pattern for windows as well. If you don’t work with windows can you please file an issue so we investigate it?

_Originally posted by @chrislovecnm in https://github.com/bazelbuild/rules_python/issues/1285#issuecomment-1623827497_

**Comment by aignas** [comment]
None of the maintainers are actively working on Windows and contributions on fixing this would be greatly welcome!
