### ISSUE TITLE
Target aliases don't work with annotations in pip_parse()

### ISSUE THREAD

**Issue by georgiyekkert** [bazelbuild/rules_python#1311]
### Affected Rule

pip_parse

### Is this a regression?

Didn't try this in other versions

### Description

if you pass both arguments `incompatible_generate_aliases` and `annotations` to pip_parse(), specified annotations will be ignored.

## 🔬 Minimal Reproduction

<pre>
  <code>
NUMPY_ANNOTATIONS = {
    "numpy": package_annotation(
        additive_build_content = """\
filegroup(
    name = "includes",
    srcs = glob(["site-packages/numpy/core/include/**/*.h"]),
)
cc_library(
    name = "numpy_headers",
    hdrs = [":includes"],
    strip_include_prefix="site-packages/numpy/core/include/",
)
""",
    ),
}

pip_parse(
    name = "pypi",
    annotations = NUMPY_ANNOTATIONS,
    incompatible_generate_aliases = True,
    python_interpreter_target = interpreter,
    requirements = "//:requirements_lock.txt",
)
  </code>
</pre>

## 🔥 Exception or Error

When you try to use the annotated `cc_library`, it will just fail, e.g.
`no such target '@pypi//numpy:numpy_headers': target 'numpy_headers' not declared in package 'numpy'`

Without `incompatible_generate_aliases` it works as intended.

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
gLinux
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
Build label: 6.1.0
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Mon Mar 6 17:09:47 2023 (1678122587)
Build timestamp: 1678122587
Build timestamp as int: 1678122587
  </code>
</pre>

**Rules_python version:**

<pre>
  <code>
0.23.1
  </code>
</pre>

**Comment by rickeylev** [comment]
Context: this is affecting tensorflow trying to set incompatible_generate_aliases=True to make the eventual bzlmod support easier.

**Comment by chrislovecnm** [comment]
Can you provide a minimal example?

**Comment by georgiyekkert** [comment]
See in my fork:
https://github.com/georgiyekkert/rules_python/commit/3f7c51403ac0c26111d71e928096b9af9e068757

`bazel test :pip_parse_correct_alias_annotations_test` will pass

`bazel test :pip_parse_empty_alias_annotations_test` will fail with `no such target '@pip_parsed//requests:test': target 'test' not declared in package 'requests'`.

`pip_parsed_requests` gets annotated
`pip_parsed//requests` doesn't get annotated.

**Comment by aignas** [comment]
These are my thoughts on how we could make it work, but I am not sure if it's kosher, given our desire to refactor the API of how users can change the `BUILD.bazel` files produced by `whl_library`.

We could make it work by:
* Parsing the `additive_build_content` and search for `^    name = "\(\S+\)"` and then create aliases for those in the `render_pkg_aliases`. This could potentially work even if we had a single patch and the regex we would need to use is would be something along the lines of `^+      name = "\(\S+\)"`, but this usage of regex does not smell good here.
* Asking the user to provide a list of extra aliases they wish to provide in the `hub repo`. This results in duplicated code, but we would know for sure what targets we should expose in the `hub` repo, so I think it is probably a better solution to this problem.
