### ISSUE TITLE
bzlmod pip instructions out of date

### ISSUE THREAD

**Issue by jsharpe** [bazelbuild/rules_python#1318]
# 🐞 bug report

### Affected Rule
n/a

### Is this a regression?
n/a

### Description

The instructions here use the old bzlmod extension API: https://github.com/bazelbuild/rules_python#using-pip-with-bzlmod

**Comment by chrislovecnm** [comment]
https://github.com/bazelbuild/rules_python/pull/1282 Addresses this

**Comment by chrislovecnm** [comment]
@jsharpe we good now?

**Comment by jsharpe** [comment]
Yes looks good to me
