### ISSUE TITLE
target '//python/cc:current_py_cc_headers' failed in Bazel CI

### ISSUE THREAD

**Issue by sgowroji** [bazelbuild/rules_python#1324]
Also seeing below errors for  https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3155#01893d8e-ea2e-4a6a-9b42-623bdab05f5f CI .

Logs :  
```
ERROR: /var/lib/buildkite-agent/builds/bk-docker-28rd/bazel-downstream-projects/rules_python/python/cc/BUILD.bazel:14:22: in current_py_cc_headers rule //python/cc:current_py_cc_headers: non-test target '//python/cc:current_py_cc_headers' depends on testonly target '//tests/cc:fake_py_cc_toolchain_impl' and doesn't have testonly attribute set
(02:22:54) ERROR: /var/lib/buildkite-agent/builds/bk-docker-28rd/bazel-downstream-projects/rules_python/python/cc/BUILD.bazel:14:22: Analysis of target '//python/cc:current_py_cc_headers' failed
```

Steps :
```
git clone -v https://github.com/bazelbuild/rules_python.git
git reset b8f16458c1d785a24921e569cc6174e8e3f6b45e --hard
export USE_BAZEL_VERSION=7845acae9769a72dc507dc2f57c4e032ebf429d3
bazel build ... @rules_python//examples/wheel/...
```
Culprit : https://github.com/bazelbuild/bazel/commit/18aeb52a59e65efcbeac7041faf60d81f9d434cb

_Originally posted by @sgowroji in https://github.com/bazelbuild/rules_python/issues/1299#issuecomment-1628505662_

**Comment by rickeylev** [comment]
This looks like a simple fix -- just remove testonly=True on the fake toolchain implementation. It's only be set because it's only used by tests, so it's NBD to remove it. PR #1327 sent out
