### ISSUE TITLE
py_proto_library overriding "google" module

### ISSUE THREAD

**Issue by yechuan51** [bazelbuild/rules_python#1338]
# 🐞 bug report

### Affected Rule

 The issue is caused by the rule: 

py_proto_library

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

Unable to verify.

### Description

 A clear and concise description of the problem...

I realized an issue yesterday that many of the PIP dependencies cannot be used because of ModuleNotFoundError. I investigated a bit and found out that they are all "google.xxx" modules. 

My investigation has led me here, I believe the implementation of py_proto_library might have caused all "import google.xxx" to be directed to a runfile path with just "google.protobuf". 

## 🔬 Minimal Reproduction

I created a PR on a forked version of this repo:
https://github.com/yechuan51/rules_python_overriding_module/pull/1

In additon, I have created a repo from scratch that reproduces this error:
https://github.com/yechuan51/proto_rule_overshadow

## 🔥 Exception or Error

<pre><code>

/home/ubuntu/.cache/bazel/_bazel_ubuntu/9b2305b6489efaf56c30b637b3658310/execroot/rules_python_pip_parse_example/bazel-out/k8-fastbuild/bin/main.runfiles/com_github_protocolbuffers_protobuf/python/google/__init__.py
['/home/ubuntu/.cache/bazel/_bazel_ubuntu/9b2305b6489efaf56c30b637b3658310/execroot/rules_python_pip_parse_example/bazel-out/k8-fastbuild/bin/main.runfiles/com_github_protocolbuffers_protobuf/python/google']
/home/ubuntu/.cache/bazel/_bazel_ubuntu/9b2305b6489efaf56c30b637b3658310/execroot/rules_python_pip_parse_example/bazel-out/k8-fastbuild/bin/main.runfiles/com_github_protocolbuffers_protobuf/python/google/protobuf/__init__.py
Traceback (most recent call last):
  File "/home/ubuntu/.cache/bazel/_bazel_ubuntu/9b2305b6489efaf56c30b637b3658310/execroot/rules_python_pip_parse_example/bazel-out/k8-fastbuild/bin/main.runfiles/rules_python_pip_parse_example/main.py", line 20, in <module>
    import google.auth
ModuleNotFoundError: No module named 'google.auth'

</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
  Ubuntu 22.04
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
   6.2.1
  </code>
</pre>

**Rules_python version:**

<pre>
  <code>
0.24.0
  </code>
</pre>

**Anything else relevant?**
I asked the same question on Stackoverflow:
https://stackoverflow.com/questions/76746080/bazel-python-proto-rules-overriding-google-module

**Comment by yechuan51** [comment]
Update:

After more time spent, I was lucky enough to find a version of the rules_python that doesn't have this issue. After much regression testing, I found the change that introduced this issue:
https://github.com/bazelbuild/rules_python/commit/6905e63ee9e63e210db7d1a2b65ebbae12d691d8

I'm also able to create a patch to verify the issue is isolated within python/private/proto/py_proto_library.bzl. 

@aignas @rickeylev can you please take a look and see if this change might have caused this unintended behaviour? Thank you!

**Comment by aignas** [comment]
As per [this slack thread](https://bazelbuild.slack.com/archives/CA306CEV6/p1694608910286409?thread_ts=1694363746.866729&cid=CA306CEV6) the solution would be to disable the deprecated (https://github.com/bazelbuild/bazel/issues/7386) feature to create `__init__.py` files by default by using https://bazel.build/reference/command-line-reference#flag--incompatible_default_to_explicit_init_py.

If this works please close the issue.
