### ISSUE TITLE
Multiple Python versions and differences in requirements lock files

### ISSUE THREAD

**Issue by chrislovecnm** [bazelbuild/rules_python#1342]
We require that a Python package exists in the requirements file for the Python version that is marked as default.  

https://github.com/bazelbuild/rules_python/blob/bb7004b1c8e79220ad0212dbc131e11a06aecf6c/python/pip.bzl#L263

This is because we are writing a select statement that uses the default Python version as the default condition.

https://github.com/bazelbuild/rules_python/blob/bb7004b1c8e79220ad0212dbc131e11a06aecf6c/python/pip.bzl#L308

Do we always need parity between the different requirement lock files?  Can we have cases where `requirements_lock_3_9.txt` and `requirements_lock_3_10.txt` files will differ? A Python package exists in one lock file but not another.

**Comment by groodt** [comment]
This seems illogical to me.

It's natural for requirements lock files between python versions to differ, so personally I think this feature doesn't make sense and it's bzlmod refactoring that is making it more clear by bringing some strictness to things.

I think a better solution for users who want a single set of input dependencies, but a python version-specific locked requirements at runtime, is to handle it in user-space `select` where the user selects over multiple differing `pip_parse` repositories.

**Comment by arrdem** [comment]
I'd disagree. It's somewhat typical to see that package versions need to be bumped to support a newer interpreter, and it's entirely possible that along with the bump come new transitives. Or some transitive is no longer needed (`toml` say). Not sure what's best here just noting that this is possible.

**Comment by groodt** [comment]
We're saying the same thing I think. We're saying that packages differ between python versions and that it's illogical to assume parity between python interpreter versions and the concept of a default fallback and repository alias cannot and does not make logical sense from a correctness point of view.

**Comment by arrdem** [comment]
Ah. Yes.
