### ISSUE TITLE
Unable to build Ray on Power (Error: key "3.9.16" not found in dictionary)

### ISSUE THREAD

**Issue by pawan-kalligudda** [bazelbuild/rules_python#1350]
ERROR: Traceback (most recent call last):
        File "/root/ray_build/ray/WORKSPACE", line 42, column 27, in <toplevel>
                python_register_toolchains(
        File "/root/.cache/bazel/_bazel_root/7f16b0bd7b2d7e213ac52cfc0f0101d7/ex                                                                             ternal/rules_python/python/repositories.bzl", line 269, column 31, in python_register_toolchains
                sha256 = tool_versions[python_version]["sha256"].get(platform, None)
Error: key "3.9.16" not found in dictionary
ERROR: error loading package '': Encountered error while reading extension file 'defs.bzl': no such package '@python3_9//': error loading package 'external': Could not load //external package

The code from https://github.com/bazelbuild/rules_python/blob/bb8c4859950ecea29e794e85df579558c9d893fd/python/repositories.bzl
file on line number 529 https://github.com/bazelbuild/rules_python/blob/bb8c4859950ecea29e794e85df579558c9d893fd/python/repositories.bzl#L529 does not pick the python version (in this case 3.9.16) as key when mentioned in python_register_toolchains function in ray/WORKSPACE https://github.com/ray-project/ray/blob/ray-2.6.1/WORKSPACE.

ray_version: 2.6.1
rules_version: 0.24.0

**Comment by chrislovecnm** [comment]
You say that you are using 0.24.0 but the WORKSPACE file you provided is using a version of rules Python that does not have PPC - 0.21.0.

https://github.com/ray-project/ray/blob/d68bf04883af2e430fc3a50fd544bb7c84aff2e9/WORKSPACE#L36C42-L36C42
