### ISSUE TITLE
Windows: `pywin32` doesn't work with the hermetic Python toolchain

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/rules_python#1356]
# 🐞 bug report

### Affected Rule

rules_python

### Is this a regression?

Probably not.

### Description

I'm trying to do `import win32api` on Windows, but got 
```
ModuleNotFoundError: No module named 'win32api'
```
even if I specify `pywin32==303` in the requirements.txt file.

## 🔬 Minimal Reproduction

Fetch the reproducible case at https://github.com/meteorcloudy/my_tests/tree/master/pywin32_test

then run
```
bazel run //:bin
```

## 🔥 Exception or Error

<pre><code>

$ bazel run //:bin
INFO: Invocation ID: 3c7000e6-65e3-4816-a2b5-551faa933a03
INFO: Reading 'startup' options from c:\users\pcloudy\.bazelrc: --output_user_root=C:/src/tmp
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=375
INFO: Options provided by the client:
  Inherited 'build' options: --python_path=C:/python3/python.exe
INFO: Reading rc options for 'run' from c:\users\pcloudy\.bazelrc:
  Inherited 'build' options: --curses=yes --color=yes --verbose_failures --announce_rc --disk_cache=C:/src/tmp/bazel_disk_cache
INFO: Analyzed target //:bin (40 packages loaded, 3463 targets configured).
INFO: Found 1 target...
Target //:bin up-to-date:
  bazel-bin/bin.exe
  bazel-bin/bin.zip
INFO: Elapsed time: 15.868s, Critical Path: 7.96s
INFO: 6 processes: 5 internal, 1 local.
INFO: Build completed successfully, 6 total actions
INFO: Running command line: bazel-bin/bin.exe
Traceback (most recent call last):
  File "C:\temp\2\Bazel.runfiles_s_pq9z9_\runfiles\__main__\bin.py", line 1, in <module>
    import win32api
ModuleNotFoundError: No module named 'win32api'
</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Windows
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
6.3.1
  </code>
</pre>

**Rules_python version:**

<pre>
  <code>
0.24.0
  </code>
</pre>

**Anything else relevant?**
If I do `import win32.win32api`, I get
```
ImportError: DLL load failed while importing win32api: The specified module could not be found.
```

**Comment by aignas** [comment]
Given that `pywin32` is on its way out, should we care about this here? What would be the use case for supporting this?

**Comment by meteorcloudy** [comment]
It's used in Bazel's python integration test: https://cs.opensource.google/bazel/bazel/+/master:src/test/py/bazel/launcher_test.py;l=673?q=%22win32api%22&ss=bazel

What is the alternative of `pywin32`? For us, we only need the `win32api.GetShortPathName` API.

**Comment by aignas** [comment]
I think I misspoke about pywin32 and we should probably investigate what is going on.

**Comment by aignas** [comment]
I think it could be related to https://github.com/indygreg/PyOxidizer/issues/442

**Comment by groodt** [comment]
@meteorcloudy 

If we are willing to try again, there is a random option from Stackoverflow that might help you avoid the dependency.
https://stackoverflow.com/a/23598461

I would try it myself if I had easy access to a Windows environment. 

The prebuilt indygreg interpreters struggle when they hit TKinter or WxPython, so if you can avoid those, then you will have an easier time.

**Comment by meteorcloudy** [comment]
@groodt Thanks, the launcher_test is the only blocker for enabling hermetic python toolchain on Windows, which basically means removing https://github.com/bazelbuild/bazel/blob/24ef85f2f7aa827eeb4595e93b0a0985409d84f4/.bazelrc#L28-L31. If you want to give it a try to test the approach, a PR is welcome!

**Comment by groodt** [comment]
@meteorcloudy Must be our lucky day... that actually worked! https://github.com/bazelbuild/bazel/pull/22799

Time to buy a lottery ticket!

**Comment by meteorcloudy** [comment]
Amazing, thanks a lot!

**Comment by albertocavalcante** [comment]
Is there any way I can make a lib that depends on `pywin32` works with Bazel using `rules_python` or the only option is to migrate off of it somehow?

If not, I wonder if https://github.com/aspect-build/rules_py maybe supports this? cc: @alexeagle
