### ISSUE TITLE
pip_install fails to correctly install pip wheel 

### ISSUE THREAD

**Issue by bedbad** [bazelbuild/rules_python#1366]
# 🐞 bug report
**The Package in question is google's pip wheel mediapipe**
### Affected Rule

 The issue is caused by the rule: 
pip_install (pip_parse)

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....
No, just doesn't work in newest versions either

### Description

 A clear and concise description of the problem...

## 🔬 Minimal Reproduction
4 files:
WORKSPACE
BUILD
main.py
requirement.txt

WORKSPACE
```
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
http_archive(
    name = "rules_python",
    sha256 = "56dc7569e5dd149e576941bdb67a57e19cd2a7a63cc352b62ac047732008d7e1",
    strip_prefix = "rules_python-0.10.0",
    url = "https://github.com/bazelbuild/rules_python/archive/refs/tags/0.10.0.tar.gz",
)

load("@rules_python//python:repositories.bzl", "python_register_toolchains")
python_register_toolchains(
    name = "python3_9",
    # Available versions are listed in @rules_python//python:versions.bzl.
    # We recommend using the same version your team is already standardized on.
    python_version = "3.9",
)
load("@python3_9//:defs.bzl","interpreter")

load("@rules_python//python:pip.bzl", "pip_install")

# Create a central repo that knows about the dependencies needed from
# requirements_lock.txt.
pip_install(
   name = "main_requirements",
   requirements = "//:requirements.txt",
   python_interpreter_target = interpreter,
)
```
BUILD
```
load("@rules_python//python:defs.bzl", "py_binary")
load("@main_requirements//:requirements.bzl", "requirement")

py_binary(
    name = "main",
    srcs = ["main.py"],
    deps = [requirement("numpy"),
          requirement("mediapipe"),
          requirement("opencv-python")],
)
```
main.py
```
main.py
import cv2
import numpy
import mediapipe

if __name__ == '__main__':
    print(cv2.__version__)
    print(numpy.__version__)
    print(mediapipe.__version__)

```
requirements.txt
```
requests
matplotlib==3.5.1
mediapipe==0.10.3
numpy==1.22.2
opencv-python==4.5.5.62
opencv-contrib-python==4.5.5.62
```
## 🔥 Exception or Error

<pre><code>

```
Traceback (most recent call last):
  File "/private/var/tmp/_bazel_Ilya/16e97d99692654a3f695f6730e2ec214/execroot/__main__/bazel-out/darwin_arm64-fastbuild/bin/gest.runfiles/__main__/gest.py", line 1, in <module>
    import mediapipe
  File "/private/var/tmp/_bazel_Ilya/16e97d99692654a3f695f6730e2ec214/execroot/__main__/bazel-out/darwin_arm64-fastbuild/bin/gest.runfiles/main_requirements/pypi__mediapipe/site-packages/mediapipe/__init__.py", line 15, in <module>
    from mediapipe.python import *
  File "/private/var/tmp/_bazel_Ilya/16e97d99692654a3f695f6730e2ec214/execroot/__main__/bazel-out/darwin_arm64-fastbuild/bin/gest.runfiles/main_requirements/pypi__mediapipe/site-packages/mediapipe/python/__init__.py", line 17, in <module>
    from mediapipe.python._framework_bindings import resource_util
ImportError: cannot import name 'resource_util' from 'mediapipe.python._framework_bindings' (/private/var/tmp/_bazel_Ilya/16e97d99692654a3f695f6730e2ec214/execroot/__main__/bazel-out/darwin_arm64-fastbuild/bin/gest.runfiles/main_requirements/pypi__mediapipe/site-packages/mediapipe/python/_framework_bindings/__init__.py)
```
</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
`Darwin ims-MacBook-Air.local 22.4.0 Darwin Kernel Version 22.4.0: Mon Mar  6 21:00:41 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T8103 arm64
`  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
```
Build label: 6.3.1
Build target: bazel-out/darwin_arm64-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Mon Jul 31 16:15:41 2023 (1690820141)
Build timestamp: 1690820141
Build timestamp as int: 1690820141
```
  </code>
</pre>

**Rules_python version:**

<pre>
  <code>
0.10
  </code>
</pre>

**Anything else relevant?**
https://github.com/google/mediapipe/issues/3805#issuecomment-1303735919

**Comment by aignas** [comment]
@bedbad, can you reproduce the error with the latest `rules_python` release please (0.24.0)? `rules_python 0.10.0` is really old.

**Comment by bedbad** [comment]
Yes, and version 0.24.0 fails much earlier:
`ERROR: /private/var/tmp/_bazel_user/16e97d99692654a3f695f6730e2ec214/external/main_requirements_mediapipe/BUILD.bazel:22:11: no such package '@main_requirements_sounddevice//': The repository '@main_requirements_sounddevice' could not be resolved: Repository '@main_requirements_sounddevice' is not defined and referenced by '@main_requirements_mediapipe//:pkg'`

even though "sounddevice" is added to main_requirements through requirements=requirements.txt and install_deps() is called.

Please try it yourself! It's minimal to reproduce.

**Comment by bedbad** [comment]
Can a member of python rules look at it and reproduce? This really is a roadblock for me

**Comment by aignas** [comment]
You have to supply a fully resolved `requirements.txt` to the `pip_parse` repository rule. Please see https://github.com/bazelbuild/rules_python#pip-rules

Let me know if that works for you.

**Comment by bedbad** [comment]
Thank you, will let you know
