### ISSUE TITLE
py_wheel support in bzlmod

### ISSUE THREAD

**Issue by rickeylev** [bazelbuild/rules_python#1369]
We don't currently have any tests verifying py_wheel works under bzlmod. I don't think any of us have tried it out ourselves, either.

It should just work. I don't recall it doing anything particularly special, but you never know.

So, at the least, manually verify it works and post the result here. Ideally, add some tests to verify it actually works.

**Comment by aignas** [comment]
FYI we have it working at `$dayjob` with:
```starlark
pip.parse(
    hub_name = "publish_deps",
    python_version = "3.10",
    requirements_darwin = "@rules_python//tools/publish:requirements_darwin.txt",
    requirements_lock = "@rules_python//tools/publish:requirements.txt",
    requirements_windows = "@rules_python//tools/publish:requirements_windows.txt",
)
use_repo(pip, "publish_deps_310_twine", #extras )
```

It would help if this entry was in `@rules_python//:MODULE.bazel` and it was used by default in `bzlmod`.

**Comment by chrislovecnm** [comment]
@aignas how can we add this as a test?

**Comment by rickeylev** [comment]
That users have to manually define twine is annoying, but is consistent with workspace. From https://rules-python.readthedocs.io/en/latest/api/packaging.html#py-wheel

> To publish the wheel to Pypi, the twine package is required. rules_python doesn’t provide twine itself, see https://github.com/bazelbuild/rules_python/issues/1016 However you can install it with pip_parse, just like we do in the WORKSPACE file in rules_python.

So it's OK to still require users add something to MODULE.bazel to make twine work. I'm just talking about bzlmod feature parity; a separate FR so that users don't have to do this themselves makes sense.

That said:

> use_repo(pip, "publish_deps_310_twine")

I'm not a fan of that, since it's (1) version specific, and (2) I think the "310" part is an internal detail leaking out. The workspace equiv is `@publish_deps_twince//:pkg` (which would be `@publish_deps//twine` now that generate_aliases is enabled by default.

Is that old code perhaps? I would think `@publish_deps//twine` should work under bzlmod?

**Comment by aignas** [comment]
The code that accepts the `twine` label expects to find a Python file in the same third-party repository, which is not present there when `bzlmod` like hub aliases are used. I created a draft PR that works around that.
