### ISSUE TITLE
Please help, rules_python 0.2.0 doesn't work as advertised

### ISSUE THREAD

**Issue by grepwood** [bazelbuild/rules_python#1380]
Hi. I'm using rules_python version `0.2.0`. Please don't ask me why, and please don't pass judgement. I'm struggling to upgrade from `0.0.1 with custom patches`. I've noticed that `pip_install()` and `requirement()` don't work as advertised in the readme.

Here's a piece of my workspace:
```
load("@rules_python//python:pip.bzl", "pip_install")
pip_install(
    name = "all_python_deps",
    requirements = "//worker:requirements.txt",
    python_interpreter = "python3",
# We keep wheels of all currently installed Python libraries in /usr/local/lib/wheels.
# Also, this greatly improves execution time of literally everything that touches the workspace.
    extra_pip_args = ['-w', '/usr/local/lib/wheels'],
# Rural life has its charms m8
    timeout = 9001
)
```

I can issue queries just fine. However the cookie crumbles when I try to build, let's say `bazel build //microservice/foobar`. Here is `microservice/foobar/BUILD.bazel`:
```
package(default_visibility = ["//visibility:public"])
load("@all_python_deps//:requirements.bzl", "requirement")
load("@package_bundle//file:packages.bzl", "packages")
load("@io_bazel_rules_docker//python3.bzl", "py3_image") # we're using version 0.15.0, please don't ask why, we are embarassed
load("@io_bazel_rules_docker//container:container.bzl", "container_image")

requirements = [
    "certifi",
    "charset-normalizer",
    "idna",
    "urllib3",
    "requests"
]

py3_image(
    name = "base_image",
    srcs = [
        "src/__init__.py",
        "src/meat.py",
        "src/potatoes.py"
    ],
    base = "@some_docker_image_with_python//image",
    main = "src/main.py",
    deps = [requirement(name) for name in requirements]
)
```
This fails with the following error:
```
(time) ERROR: /path/to/microservice/foobar/BUILD.bazel:15:10: no such package `@all_python_deps//pypi__requests`: BUILD file not found in directory `pypi__requests` of external repository @all_python_deps. Add a BUILD file to a directory to mark it as a package, and referenced by '//path/to/microservice/foobar:base_image'
```

This problem was introduced in rules_python `0.1.0`. I needed to upgrade from `0.0.3` because:
1. The setup I maintain is generally, criminally outdated and I'm working on this
2. We have created a monolithic requirements.txt file that supports all microservices and binaries we use in the project, to have a centralized version summary. This however, bloated the time of execution of `pip_import()` (when we had rules_python `0.0.1` through `0.0.3`) by a factor of 5.33, because in those ancient version of rules_python there is a hardcoded dependency on a particularly ancient version of pip and wheel, which ironically, makes it impossible to consume locally pre-built wheels. Only in version `0.1.0` I could finally consume all pre-built wheels.

All of this is working not as described by the contemporary readme: https://github.com/bazelbuild/rules_python/blob/6f37aa9966f53e063c41b7509a386d53a9f156c3/README.md

It says that if I do the newfangled `pip_install()` like I would normally `pip_import()` I should be able to call `requirement()`. However this is not the case. The readme does not address this issue.

How can I fix this?

**Comment by grepwood** [comment]
I've managed to make the build pass by removing
```
    extra_pip_args = ['-w', '/usr/local/lib/wheels'],
```
however, this produces suboptimal results. We are still downloading 10 or so dependencies and compiling them from source. I cannot use `~/.cache/pip/wheels` because the home directory is a k8s pvc, so whatever sits there on the Docker image, it will be hidden by the pvc mount.

How can I specify what directory `rules_python` should look for wheels from?

**Comment by chrislovecnm** [comment]
@grepwood I would put the wheels into source control or maybe test if a symlink would work

**Comment by grepwood** [comment]
Can close.
