### ISSUE TITLE
Add Python 3.8.17 & 3.8.18

### ISSUE THREAD

**Issue by kpark-hrp** [bazelbuild/rules_python#1396]
# 🚀 feature request

### Relevant Rules

`python/versions.bzl`

### Description

Can we add Python version `3.8.17` and `3.8.18` to the versions list?

**Comment by aignas** [comment]
`3.8.18` has not been released by https://github.com/indygreg/python-build-standalone/releases yet.

**Comment by kpark-hrp** [comment]
@aignas Python `3.8.18` is now released by https://github.com/indygreg/python-build-standalone/releases
