### ISSUE TITLE
requirements.update doesn't work on windows when requirements.in in a subpackage

### ISSUE THREAD

**Issue by carpenterjc** [bazelbuild/rules_python#1431]
### Affected Rule
The issue is caused by the rule: compile_pip_requirements

### Is this a regression?
Yes this regressed between: https://github.com/bazelbuild/rules_python/compare/0.18.0...0.19.0

### Description
If you have a rule in a sub package (so it contains a directory separator) then on windows you will get an issue where it cannot find file path for requirements.txt.

Note: the slashes are the wrong direction for windows. 

## 🔬 Minimal Reproduction

In 0.25.0 branch of rules_python
<pre><code>
cd .\examples\pip_parse\
REM This works
bazel run requirements.update

mkdir bad
copy .\BUILD.bazel bad
copy .\requirements.in bad
copy .\requirements_lock.txt bad

REM This fails with Error: Could not open file 'bad/requirements_lock.txt': No such file or directory
bazel run //bad:requirements.update

</code></pre>

## 🔥 Exception or Error

<pre><code>

INFO: Running command line: bazel-bin/tools/thirdparty/requirements.update.exe tools/thirdparty/requirements.in tools/thirdparty/requirements.txt None None None //tools/thirdparty:requirements.update --allow-unsafe --no-reuse-hashes
Updating tools/thirdparty/requirements.txt
Traceback (most recent call last):
  File "C:\Users\JAMESC~1\AppData\Local\Temp\Bazel.runfiles_gwh6jf4s\runfiles\rules_python\python\pip_install\tools\dependency_resolver\dependency_resolver.py", line 139, in <module>
    if not os.path.samefile(requirements_txt, requirements_txt_tree):
  File "C:\Users\JAMESC~1\AppData\Local\Temp\Bazel.runfiles_gwh6jf4s\runfiles\python3_10_x86_64-pc-windows-msvc\lib\genericpath.py", line 100, in samefile
    s1 = os.stat(f1)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'tools/thirdparty/requirements.txt'
</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
windows 
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
Build label: 6.2.0
Build target: bazel-out/x64_windows-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue May 9 18:34:17 2023 (1683657257)
Build timestamp: 1683657257
Build timestamp as int: 1683657257
  </code>
</pre>

**Rules_python version:**

<pre>
  <code>
0.25.0
  </code>
</pre>

**Anything else relevant?**
Same code works fine on macos and WSL.

**Comment by bhogan-bdai** [comment]
This is old, but leaving this here for future folks.

I also ran into this issue. When I enabled symlink support [doc](https://bazel.build/configure/windows#symlink), the step started working because it could find the output lock file.

.bazelrc
```
startup --windows_enable_symlinks
build --enable_runfiles
```
