### ISSUE TITLE
Gazelle with `python_generation_mode project` can generate duplicate py_test targets

### ISSUE THREAD

**Issue by RJPercival** [bazelbuild/rules_python#1442]
# 🐞 bug report

### Affected Rule

The issue is caused by the rule: `py_test`

### Is this a regression?

Unknown

### Description

When using `# gazelle:python_generation_mode project`, the Python Gazelle plugin still generates one `py_test` target per file, but puts them all in the `BUILD` file that has the `python_generation_mode` directive in it. This can result in duplicate target names if two test files have the same filename (but are in different subdirectories), as the subdirectory path is not incorporated into the target names.

When using `python_generation_mode project`, I would expect a single `py_test` target for all of the tests across all of the subdirectories, just as with `py_library`.

## 🔬 Minimal Reproduction

BUILD file:
```BUILD
# gazelle:python_generation_mode project

<usual gazelle targets here>
```

```sh
$ echo "# gazelle:python_generation_mode project" > BUILD.bazel
$ mkdir bar
$ touch bar/test_foo.py
$ mkdir baz
$ touch baz/test_foo.py
$ bazel run //:gazelle
gazelle: multiple rules found with label @test//:test_foo
```

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
macOS Sonoma
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
bazel 6.3.2
  </code>
</pre>

**Rules_python version:**

<pre>
  <code>
0.25.0
  </code>
</pre>

**Comment by kpark-hrp** [comment]
@rickeylev Not sure if this has to do anything. But since `0.27.0`, `# gazelle:python_generation_mode project` is generating an empty `py_test` despite `__test__.py` not existing.

For example,
```starlark
py_test(
    name = "populators_test",
    imports = ["../.."],
    main = "__test__.py",
)
```

There isn't even a `srcs` parameter, so it doesn't even work.

**Comment by aignas** [comment]
@kpark-hrp, could you please create a separate issue?

**Comment by kpark-hrp** [comment]
@aignas @rickeylev Created the bug issue here: https://github.com/bazelbuild/rules_python/issues/1690
