### ISSUE TITLE
How do I run tests on packages which have their own dependency?

### ISSUE THREAD

**Issue by abhi-jha** [bazelbuild/rules_python#1468]
I am trying to test a python package which depends on another package. This means the dependency needs to be built before I can test my main package. I have provided the dependent package as one of the py_pytest_test deps. But still the main package which imports objects from the dependent package complains with ModulNotFoundError .

Any body else faced this issue?

Is there a sample project where something like this is being dealt with.

**Comment by aignas** [comment]
`py_pytest_test` is not maintained by the `rules_python` team, that said, I would assume its usage should be similar to the `py_test` usage in the `examples` folder. Feel free to look at it and see if you can learn how to use it.
