### ISSUE TITLE
Missing dependencies when not using latest Python version

### ISSUE THREAD

**Issue by kilian-funk** [bazelbuild/rules_python#1472]
# 🐞 bug report

### Affected Rule

 The issue is caused by the function:
`python_register_toolchains` 

### Is this a regression?

 Yes. The root cause has existed for a long time but this got more problematic in version 0.25.0 with the introduction of platforms 
`ppc64le-unknown-linux-gnu` and `s390x-unknown-linux-gnu`.

### Description

When using a WORKSPACE file and not using the latest Python versions, then there are dangling repo references to the new above-mentioned platforms. This leads to errors when doing Bazel queries on reverse dependencies.

## 🔬 Minimal Reproduction

Create a Bazel workspace with this WORKSPACE file:
```
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
VERSION = "0.26.0"
http_archive(
    name = "rules_python",
    strip_prefix = "rules_python-{}".format(VERSION),
    url = "https://github.com/bazelbuild/rules_python/releases/download/{}/rules_python-{}.tar.gz".format(VERSION, VERSION),
)
load("@rules_python//python:repositories.bzl", "py_repositories")
py_repositories()
load("@rules_python//python:repositories.bzl", "python_register_toolchains")
python_register_toolchains(
    name = "python_3_8",
    python_version = "3.8",                                                                                                                                                   
)
```
then run the command
```
bazel query 'rdeps(@python_3_8//...,@python_3_8//:python3)'
```

## 🔥 Exception or Error

<pre><code>
ERROR: Evaluation of query "rdeps(@python_3_8//..., @python_3_8//:python3)" failed: preloading transitive closure failed: no such package '@python_3_8_ppc64le-unknown-linux-gnu//': The repository '@python_3_8_ppc64le-unknown-linux-gnu' could not be resolved: Repository '@python_3_8_ppc64le-unknown-linux-gnu' is not defined
</code></pre>

In a real-world workspace making a lot of use of Python, this error also shows on much more relevant and less obvious queries:
```
bazel cquery 'rdeps(//..., //<any_target_in_a_workspace_with_python_dependencies>)'
``` 

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Ubuntu Linux 20.04
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
bazel 6.3.2
  </code>
</pre>

**Rules_python version:**

<pre>
  <code>
0.26.0
  </code>
</pre>
The issue was introduced in 0.25.0 when adding two new platforms.

**Anything else relevant?**
The root cause of this seems to be the fact that loading a Python interpreter for some platforms and version combinations is skipped, but the aliases are always created.

**Comment by rickeylev** [comment]
I think the cause here is repositories.bzl#python_repository not being in sync with toolchains_repo.bzl#toolchains_alias. Essentially:

```
# python_repository
for entry in versions:
  if not entry.sha256: skip
  else: create repository <entry>

# toolchain_aliases
for entry in versions:
  select_expr.append(refer to repo <entry>)
```

We skip creating a repo if there's no sha because it indicates there's no download for it.

Fixing this should be fairly simple. Either add the same guard in toolchains_repo.bzl, or pass the list of created repos into the toolchains_repo call (it's a few lines below where they're created).

**Comment by kilian-funk** [comment]
Yes, I figured that out after creating the issue. I will prepare a PR for it.
