### ISSUE TITLE
Should 0.26.0 have been published to the central registry automatically?

### ISSUE THREAD

**Issue by mpereira** [bazelbuild/rules_python#1474]
Just checking if there's some automation that failed to do so. 0.26.0 was released a couple of days ago but it's still not available in the registry: https://registry.bazel.build/modules/rules_python

**Comment by tradergt** [comment]
Looked like they were sent but no one has approved/merged them: 
https://github.com/bazelbuild/bazel-central-registry/pull/982
https://github.com/bazelbuild/bazel-central-registry/pull/983

**Comment by aignas** [comment]
Thank you for the interest in 0.26.0 bzlmod package, these have been merged, so closing for now.

**Comment by mpereira** [comment]
@tradergt thanks for the context, I hadn't seen those PRs.

@aignas sweet!
