### ISSUE TITLE
pip_import should infer current workspace by default

### ISSUE THREAD

**Issue by michaelsafyan** [bazelbuild/rules_python#148]
I've strangely found that:

```
pip_import(
    name = "pip_deps",
    requirements = "//:requirements.txt",
)
```

... will work, while:

```
pip_import(
    name = "pip_deps",
    requirements = ":requirements.txt",
)
```

... results in an undecipherable error message that references a file with "/external/" in the path where it hadn't been there before. The file ":requirements.txt" and "//:requirements.txt" should be equally valid ways to refer to the same file at the top level of the current workspace. Please fix. Or, at the very least, please improve the error message that results in the erroneous case.

**Comment by thundergolfer** [comment]
This is a pain, and occurs on other repo rules in the Bazel ecosystem that don't infer the current WORKSPACE, but unfortunately I'll have to mark this as wontfix as `pip_install` is actively maintained now instead of `pip_import`, which is maintained only for legacy purposes.
