### ISSUE TITLE
Document how to use entry_point in a repo migrating to bzlmod

### ISSUE THREAD

**Issue by alexeagle** [bazelbuild/rules_python#1493]
Users who are mid-migration will have both a WORKSPACE.bazel file and a WORKSPACE.bzlmod file (the latter being used under `--enable_bzlmod`)

Rulesets especially have this problem since they want to document both usages. Most of my example/e2e folders are meant to test/demonstrate rules with both.

The recent change in 0.26.0

> (bzlmod) The entry_point macro is no longer supported and has been removed in favor of the py_console_script_binary macro for bzlmod users.

seems to suggest that a repo is either using bzlmod or not. Is there some BUILD file I can write that works both ways? It doesn't seem I can use a `select`

```
load("@rules_python//python/entry_points:py_console_script_binary.bzl", "py_console_script_binary")

py_console_script_binary(
    name = "black",
    pkg = select({
        "@aspect_bazel_lib//lib:flag_bzlmod": "@pip//black:pkg",
        "//conditions:default": "@pip_black//:pkg",
    })
)
```

I think users like this may be forced to stay on an older rules_python release?

**Comment by alexeagle** [comment]
I also tried this workaround:

```
load("@rules_python//python/entry_points:py_console_script_binary.bzl", "py_console_script_binary")
load("@pip//:requirements.bzl", "entry_point")

py_console_script_binary(
    name = "black_w_bzlmod",
    pkg = "@pip//black:pkg",
    script = "black",
)

alias(
    name = "black", 
    actual = select({
        "@aspect_bazel_lib//lib:bzlmod": ":black_w_bzlmod",
        "//conditions:default":  entry_point("black"),
    })
)
```

But the RHS of the default select branch still gets evaluated even though the result won't be used, so I get

```
Error in fail: Please replace this instance of entry_point with the following:

load("@rules_python//python/entry_points:py_console_script_binary.bzl", "py_console_script_binary")

py_console_script_binary(
    name = "black",
    pkg = "@%%@@rules_python~0.26.0~pip~pip//black:pkg",
    script = "black",
)
```

**Comment by aignas** [comment]
There is a flag called `incompatible_generate_aliases = True` that can be passed to `pip_parse` that would allow you to have the same code. This has been only documented in the `build_file_generation` non-bzlmod example. Should we flip the flag in the coming release?

**Comment by alexeagle** [comment]
ooh thanks @aignas! I'd suggest documenting that in the release notes along with the breaking change. Excited to get some stability here in 1.0 :)

**Comment by aignas** [comment]
With #1525 merged and the docs available in https://rules-python.readthedocs.io/en/latest/api/entry_points/py_console_script_binary.html I think we should be good. Please feel free to reopen if you disagree.
