### ISSUE TITLE
Flip feature flags for 0.27.0

### ISSUE THREAD

**Issue by aignas** [bazelbuild/rules_python#1498]
This is not necessarily to release 0.27.0 very soon, but to rather collect any extra info/feature flag toggles that we should do before the release is out.

The queued up changes are: https://github.com/bazelbuild/rules_python/compare/0.26.0...main

This is a list of flags that we may want to flip for this release and notify users that the previous will be removed in 0.28.0:
- [ ] `incompatible_generate_aliases` should default to `True` to make the third party repo structure very similar in `bzlmod` and non-bzlmod.
- [X] Start failing if users use `pip_install` instead of `pip_parse` we should introduce a message for the users to start using `pip_parse` instead. (See #1510)
- [x] Set default `py_wheel` related feature flags to True, see https://github.com/bazelbuild/rules_python/blob/main/python/private/py_wheel.bzl#L121 (#1331, #1513)

**Comment by rickeylev** [comment]
I'm +1 on introducing all 3 changes.
