### ISSUE TITLE
Temporary cert_path not cleaned in piptool.py

### ISSUE THREAD

**Issue by kaizers** [bazelbuild/rules_python#150]
The temporary cert_path used to extract cert from wheel is not cleaned after use. This causes /tmp to continue collecting a number of these when not properly sandboxed.

**Comment by thundergolfer** [comment]
@kaizers I have also recently discovered this. Thanks for doing the PR, linking it here: https://github.com/bazelbuild/rules_python/pull/169

Did you free re-signing the CLA? I've seen it be finicky.

**Comment by AustinSchuh** [comment]
I'm continuing on the work that Kaizer was doing.  The patch I sent out has the CLA signed and should be all ready pending review.

**Comment by AustinSchuh** [comment]
https://github.com/bazelbuild/rules_python/pull/169 closed, so I think we can close this one?
