### ISSUE TITLE
Error computing the main repository mapping: no such package '@pip_deps//

### ISSUE THREAD

**Issue by vymao** [bazelbuild/rules_python#1534]
# 🐞 bug report
### Description

 A clear and concise description of the problem...
I'm trying to build projects that seem to reference the usage of `pip_deps`. I'm not 100% sure if this is the right repo for this, but every time, it seems like I get the following error message: 

```
Unable to find package for @pip_deps//:requirements.bzl: The repository '@pip_deps' could not be resolved: Repository '@pip_deps' is not defined. and referenced by '//main:main'
ERROR: Analysis of target '//main:main' failed; build aborted: Analysis failed
INFO: Elapsed time: 0.134s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (1 packages loaded, 0 targets configured)
    currently loading: @pytorch// ... (2 packages)
    Fetching repository @rules_cuda; starting
    Fetching repository @pybind11_bazel; starting

```

Does `pip_deps` belong here? 

## 🔬 Minimal Reproduction

In the torch BUILD file: 
https://github.com/pytorch/pytorch/blob/v2.1.1-rc4/WORKSPACE#L214-L222

## 🌍  Your Environment

**Operating System:** Mac OS Ventura 13.6

**Output of `bazel version`:**

<pre>
  <code>
Bazelisk version: development
Build label: 6.4.0
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Oct 19 17:15:28 2023 (1697735728)
Build timestamp: 1697735728
Build timestamp as int: 1697735728
  </code>
</pre>

**Rules_python version:** 0.26.0

**Anything else relevant?**

**Comment by aignas** [comment]
It is hard to understand what kind of setup you have to help you. Could you paste a minimal example that reproduces the error in addition to the source of the error please?
