### ISSUE TITLE
Use rules_python python_bootstrap_template instead of bazel_tools's

### ISSUE THREAD

**Issue by rickeylev** [bazelbuild/rules_python#1556]
When a py_binary is built, the resulting executable is expanded from the template python_bootstrap_template.txt.

As of Bazel 7, `py_runtime` allows specifying this template. This allows us to customize program startup without changes in Bazel itself.

I copied the one in Bazel into rules_python, it lives here: https://github.com/bazelbuild/rules_python/blob/main/python/private/python_bootstrap_template.txt#L4

The basic todos are:
* [ ] Change toolchain generation code, the part that creates `py_runtime()`, and add a version check for Bazel 7. If its Bazel 7, set `bootstrap_template` to the rules python template.

The benefits of this are:
1. We can now have python version specific bootstrap templates. Or other platform-specific templates.
2. We can use some shell tricks to help solve #691. I'm not sure we can _entirely_ solve it, but we probably get close enough.

**Comment by groodt** [comment]
The will be huge! Can’t wait. So many things can be improved if the rules can manage the bootstrap.

**Comment by armandomontanez** [comment]
Is this issue resolved? While debugging some Python stuff, I found the bootstrap template from `rules_python` was being used.

**Comment by rickeylev** [comment]
Yeah, I think so. The py_runtime implementation was switch over to starlark, and it gets its bootstrap from rules_python, which is used by py_binary.

For Bazel 6, we have to keep the template compatible across all python versions. With Bazel 7 we could (but don't currently) create a bootstrap for each specific version.

But yes, for the most part, rules_python does control it directly now.

**Comment by arrdem** [comment]
🎉
