### ISSUE TITLE
Rules_python pip parse integration tests are failing with Bazel@HEAD

### ISSUE THREAD

**Issue by sgowroji** [bazelbuild/rules_python#1595]
rules_python (pip_parse integration tests ) : https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3508#018c3d0b-1c89-4aee-a83e-2a3fc0d4c12d

Platform :  Windows, MacOS, Ubuntu

Logs:
```
ERROR: /private/var/tmp/_bazel_buildkite/faab6577784d68c5821b7403d2b2c4ea/external/rules_python~override~pip~pypi_39_sphinxcontrib_serializinghtml/BUILD.bazel:44:6: in alias rule @@rules_python~override~pip~pypi_39_sphinxcontrib_serializinghtml//:pkg: cycle in dependency graph:
    //:main (ecdff594a22acbffc689da83aea527600ffd26ef57d9a96d887b7135b3c1742e)
    //:main (f1bf3cc88fc4bcfaec1f268c0af4264c676ac85c11a9ec091707ff065c401cd6)
    @@rules_python~override~pip~pypi//sphinxcontrib_serializinghtml:pkg (f1bf3cc88fc4bcfaec1f268c0af4264c676ac85c11a9ec091707ff065c401cd6)
.-> @@rules_python~override~pip~pypi_39_sphinxcontrib_serializinghtml//:pkg (f1bf3cc88fc4bcfaec1f268c0af4264c676ac85c11a9ec091707ff065c401cd6)
|   @@rules_python~override~pip~pypi_39_sphinxcontrib_serializinghtml//:_pkg (f1bf3cc88fc4bcfaec1f268c0af4264c676ac85c11a9ec091707ff065c401cd6)
|   @@rules_python~override~pip~pypi_39_sphinx//:pkg (f1bf3cc88fc4bcfaec1f268c0af4264c676ac85c11a9ec091707ff065c401cd6)
|   @@rules_python~override~pip~pypi_39_sphinx//:_pkg (f1bf3cc88fc4bcfaec1f268c0af4264c676ac85c11a9ec091707ff065c401cd6)
`-- @@rules_python~override~pip~pypi_39_sphinxcontrib_serializinghtml//:pkg (f1bf3cc88fc4bcfaec1f268c0af4264c676ac85c11a9ec091707ff065c401cd6)
(04:02:21) ERROR: Analysis of target '//:main' failed; build aborted
```
Steps:
```
git clone https://github.com/bazelbuild/rules_python.git
git reset bc5a0b029e8f115aa649b68240e25d33d175e91a --hard
export USE_BAZEL_VERSION=2eda429be6523390e75bf0fb55ece62defd08da0
examples/pip_parse
bazel build -- ...
```

CC Greenteam @meteorcloudy

**Comment by rickeylev** [comment]
I was able to repro this. Oddly, I didn't even need to use the latest bazel. Not sure why our CI would be green. In any case, fix looks pretty simple, just need to copy/paste the code that breaks that circular dependency.

**Comment by sgowroji** [comment]
Hi @rickeylev,  CI is  Still failing at [https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3519#018c569d-fdd9-4891-88cf-0c933cf84c9f.](https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3519#018c569d-fdd9-4891-88cf-0c933cf84c9f.) Can you please take a look. Thanks!

**Comment by meteorcloudy** [comment]
Looks like the last green commit wasn't updated due to the failure in https://buildkite.com/bazel/rules-python-python/builds/6460, I retriggered the failing build.

@sgowroji You can always double check if the downstream pipeline is testing the project with the latest commit:
![image](https://github.com/bazelbuild/rules_python/assets/4171702/91220e85-bebd-4787-b1b5-2ed03c9811f2)
![image](https://github.com/bazelbuild/rules_python/assets/4171702/3bccb356-5862-40fd-b7ea-37dce3ad2048)

**Comment by sgowroji** [comment]
Oh okay! Thanks for clarifying!

**Comment by meteorcloudy** [comment]
That said, @rickeylev please do check the test timeout in https://buildkite.com/bazel/rules-python-python/builds/6460#018c5883-bbbb-4a27-abed-377b639ec0ce
```
//:requirements_3_10_test                                               TIMEOUT in 3 out of 3 in 61.4s
```
