### ISSUE TITLE
Add `conftest.py` files with less boilerplate to `py_test` targets

### ISSUE THREAD

**Issue by michael-hoss** [bazelbuild/rules_python#1607]
# 🚀 feature request

### Relevant Rules

`py_test`

### Description

In [pytest](https://pytest.org) , all `conftest.py` files (see [conftest docs](https://docs.pytest.org/en/6.2.x/fixture.html?highlight=conftest#conftest-py-sharing-fixtures-across-multiple-files)) on the same directory level or above of a given test file are automatically imported. However, this only works in bazel's `py_test` rule if I create `py_library` targets for my `conftest.py` files and manually add them as deps to my `py_test` targets. Alternatively, I guess I could also add them as srcs.

This manual assurance of conftest imports in the `BUILD` files means a lot of boilerplate code to me. 

### Describe the solution you'd like

A boolean argument to the `py_test` rule named something like `use_conftest` defaulting to True would be perfect for me. I understand that this is not reasonable as long as pytest is not part of the standard library.

#### 1) Inherited `py_test` rule in my own `WORKSPACE`

Would have to look sth. like this 

In `pytest_test.bzl`:
```starlark
load("@rules_python//python:defs.bzl", "py_test")

def pytest_test(name, **kwargs):
    py_test(
        name = name,
        srcs = kwargs.get("srcs", []) + native.glob(["**/conftest.py"]),
        **kwargs
    )
```

In `WORKSPACE`
```starlark
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "rules_python",
    sha256 = "e85ae30de33625a63eca7fc40a94fea845e641888e52f32b6beea91e8b1b2793",
    strip_prefix = "rules_python-0.27.1",
    url = "https://github.com/bazelbuild/rules_python/releases/download/0.27.1/rules_python-0.27.1.tar.gz",
)

load("@rules_python//python:repositories.bzl", "py_repositories")
py_repositories()

load("@rules_python//python:defs.bzl", "py_test")
py_test()

load("//:pytest_test.bzl", "pytest_test")
```

However, this doesn't work yet. First error I get is "Error in py_test: py_test rule has no 'name' attribute".

Would really appreciate a quick help on how to inherit that rule. 

#### 2) Create one `py_library` target with all `conftest.py` files of the workspace

Like this, I would only have to add the same target to all tests as dep.

However
- this dep would still be boilerplate code in all `py_test` targets
- it could get large for a lot of `conftest.py` files in a large repo

**Comment by aignas** [comment]
The correct solution is 1. in the issue description, but you should not use the created macro in the workspace file, but it should be used in the build file instead.

Since this is not technically an issue in rules python, I'll close it.
