### ISSUE TITLE
Examples and documentation outdated (compile_pip_requirements)

### ISSUE THREAD

**Issue by caeus** [bazelbuild/rules_python#1660]
Most examples found in the repo do this (https://github.com/bazelbuild/rules_python/blob/4c2d7d9d6608795522322a9b2294b5053e41b979/examples/pip_parse/BUILD.bazel#L58)

Note how `"requirements.in"` is set in the `src` attribute. Well, it should go in the `requirements_in` attribute.

**Comment by shabanzd** [comment]
https://github.com/bazelbuild/rules_python/issues/1660 says that requirements_in is deprecated
