### ISSUE TITLE
Flask import breaks on OSX

### ISSUE THREAD

**Issue by mattmoor** [bazelbuild/rules_python#17]
You can see it in the Bazel CI job [here](https://github.com/bazelbuild/rules_k8s/pull/38)

**Comment by mattmoor** [comment]
It looks like this starts working once `pip` is installed on the system.

**Comment by mattmoor** [comment]
Ok, I think I understand the error now, but not sure how to fix.

Normal installation of the `wheel` package installs a Python command for `bdist_wheel`.  Wheel construction seems to rely on the capacity to shell out to:
```shell
/usr/bin/python -u -c "..." bdist_wheel -d ...
```

However, because we don't have `pip` or `wheel` installed on the system, this assumption is bad.

I'm not sure how this would work in a `virtualenv` for instance, but perhaps we could make the context of a `{par,py}_binary` look like a `virtualenv` to subprocesses and somehow communicate this kind of tool installation from the `whl_library` to the `py_binary` (through `py_library` hops)?

@duggelz I'd appreciate your thoughts on this (no rush).

**Comment by mattmoor** [comment]
@duggelz if you are around, I'd appreciate any thoughts you might have in this space.

**Comment by mattmoor** [comment]
Here's where this is configured in `setup.py`: https://github.com/pypa/wheel/blob/master/setup.py#L54

**Comment by mattmoor** [comment]
The `wheel`'s `.whl` has the following in `metadata.json`:
```json
    "extensions": {
        "python.commands": {
            "wrap_console": {
                "wheel": "wheel.tool:main"
            }
        },
        "python.details": {
            "contacts": [
                {
                    "email": "dholth@fastmail.fm",
                    "name": "Daniel Holth",
                    "role": "author"
                }
            ],
            "document_names": {
                "description": "DESCRIPTION.rst",
                "license": "LICENSE.txt"
            },
            "project_urls": {
                "Home": "https://bitbucket.org/pypa/wheel/"
            }
        },
        "python.exports": {
            "console_scripts": {
                "wheel": "wheel.tool:main"
            },
            "distutils.commands": {
                "bdist_wheel": "wheel.bdist_wheel:bdist_wheel"
            }
        }
    },
```

**Comment by mattmoor** [comment]
Watching [this](http://pyvideo.org/pycon-us-2011/pycon-2011--reverse-engineering-ian-bicking--39-s.html) crazy video on how `virtualenv` works... :)

**Comment by mattmoor** [comment]
I think this comes down to:
```python
from pkg_resources import iter_entry_points
for entry_point in iter_entry_points(group='distutils.commands', name=None):
    print(entry_point)
```

Which should show:
```
...
bdist_wheel = wheel.bdist_wheel:bdist_wheel
...
```

**Comment by mattmoor** [comment]
`pkg_resources` seems to load package information via a convoluted process around `sys.path_hooks` ([docs](https://docs.python.org/2/library/sys.html#sys.path_hooks)).

Exploring this in a Bazel context (`py_test`) I see that `sys.path_hooks` basically has a [single hook](https://docs.python.org/2/library/zipimport.html#zipimport.zipimporter): `zipimport.zipimporter`.

Interestingly `pkg_resources.resource_filename` works fine in `py_test`, but I know @duggelz has indicated `pkg_resources` doesn't like some of the games Bazel / Python plays.

**Comment by mattmoor** [comment]
Hmm, within the context of the `version_test.py`, if I add `wheel==0.30.0a0` to `requirements.txt` and if I add:
```python
    ws = pkg_resources.WorkingSet()
    for dist in ws:
      print str(dist)
```

... to the test, I get the right `Distribution`s of everything...

I'll try putting this into a PAR, and if all else fails having that PAR invoke a little python script.

**Comment by mattmoor** [comment]
Woof, so this is `py_binary` vs. `par_binary`.

If you clone the `par-kour` branch on my fork:
```shell
$ bazel run examples/par:list_resources
...
INFO: Running command line: bazel-bin/examples/par/list_resources
pip 9.0.1          <-- what I bundled
wheel 0.30.0a0     <--
...
$ bazel run examples/par:list_resources.par
...
INFO: Running command line: bazel-bin/examples/par/list_resources.par
...
pip 1.5.4          <-- system installed version
...
```

**Comment by mattmoor** [comment]
@duggelz Is this something we could maybe fix in our `PAR` file's entrypoint?

**Comment by mattmoor** [comment]
It looks like the logic in `py_binary`s entrypoint basically takes the set of things for which we had `importpath="."`, builds a new `PYTHONPATH` environment variable, and then execs the original `main` script.

**Comment by mattmoor** [comment]
FYI, this matches @duggelz investigation [here](https://github.com/google/subpar/issues/38)

**Comment by duggelz** [comment]
After various futile attempts, I think the only reasonable way to make this work is to have the .par file unpack itself at runtime.

**Comment by mattmoor** [comment]
@duggelz What's left, this seems to work for me in the `rules_python` OSX Bazel CI leg.

**Comment by mattmoor** [comment]
I haven't tried Flask, but I was hitting this on the `extras` PR, and no more.

**Comment by duggelz** [comment]
The only thing left is to add a good e2e test where we explicit create virtualenvs with various problems and run bazel inside them.  But we effectively already get that by running on different OS's :)

**Comment by thundergolfer** [comment]
Will close this, as the last comment was over 3 years ago and in the interim time the `pip_install` repo rule has been introduced which can allow users to import Flask on OSX.
