### ISSUE TITLE
Support Python 3.12.1 and 3.11.7

### ISSUE THREAD

**Issue by aignas** [bazelbuild/rules_python#1721]
Creating an issue which could be good for anyone looking to contribute to `rules_python`. The file that should be modified is `//python:versions.bzl`.

Adding https://github.com/indygreg/python-build-standalone/releases/tag/20240107

**Comment by trentontrees** [comment]
Added a PR to bring in the new versions of python: https://github.com/bazelbuild/rules_python/pull/1725

**Comment by jvolkman** [comment]
I think this is resolved by #1725?
