### ISSUE TITLE
TCL/TK and python3 tkinter simple application failed to start. 

### ISSUE THREAD

**Issue by tymons** [bazelbuild/rules_python#1722]
# 🐞 bug report

### Affected Rule

 The issue is caused by the rule:  py_binary

### Is this a regression?

 Yes, the previous version in which this bug was not present was: bazel 5.*

### Description

When I want to create simple application with tkinter, the application just exists without any logs and no window was created.

## 🔬 Minimal Reproduction

Having simple application `main.py`:

```python3
import tkinter

tkinter._test()
````
and BUILD file

```
load("@rules_python//python:defs.bzl", "py_binary")

py_binary(
    name = "main",
    srcs = ["main.py"],
)
```

## 🔥 Exception or Error

<pre><code>

(12:28:42) INFO: Current date is 2024-01-26
(12:28:42) INFO: Analyzed target //ml/apps/tk:main (0 packages loaded, 0 targets configured).
(12:28:42) INFO: Found 1 target...
Target //ml/apps/tk:main up-to-date:
  bazel-bin/ml/apps/tk/main
(12:28:42) INFO: Elapsed time: 0.065s, Critical Path: 0.00s
(12:28:42) INFO: 1 process: 1 internal.
(12:28:42) INFO: Build completed successfully, 1 total action
(12:28:42) INFO: Running command line: bazel-bin/ml/apps/tk/main
</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Linux machine 6.5.0-15-generic #15~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Jan 12 18:54:30 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
Bazelisk version: v1.19.0
Build label: 6.4.0
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Oct 19 17:07:43 2023 (1697735263)
Build timestamp: 1697735263
Build timestamp as int: 1697735263
  </code>
</pre>

**Rules_python version:**

<pre>
  <code>
bazel_dep(name = "rules_python", version = "0.26.0")
  </code>
</pre>

**Anything else relevant?**

If I am running same application without `bazel` it is working perfectly. I am assuming that we are missing some libs in the bazel-out.
This issue was not present in previous version of bazel (5.*).

**Comment by aignas** [comment]
#1778 may be related. With the previous bazel version you might have been using the auto-detecting python version toolchain.

Closing as duplicate.
