### ISSUE TITLE
python 3.12 coverage is not generating/collecting

### ISSUE THREAD

**Issue by trentontrees** [bazelbuild/rules_python#1726]
# 🐞 bug report

### Is this a regression?

works in 3.11

### Description

Building coverage using python 3.12 is not properly connecting through rules_python (best I can tell).

## 🔬 Minimal Reproduction

Repo: https://github.com/trentontrees/bazel-python-coverage
Branch: fails_3_12

bazel coverage --combined_report=lcov //apps/demo/...

## 🔥 Exception or Error

<pre><code>
INFO: Found 2 targets and 1 test target...
INFO: LCOV coverage report is located at /private/var/tmp/_bazel_trent/31f4e5efa0716cece0da5230e85c5024/execroot/__main__/bazel-out/_coverage/_coverage_report.dat
 and execpath is bazel-out/_coverage/_coverage_report.dat
INFO: From Coverage report generation:
Jan 28, 2024 5:14:10 PM com.google.devtools.coverageoutputgenerator.Main getTracefiles
INFO: Found 1 tracefiles.
Jan 28, 2024 5:14:10 PM com.google.devtools.coverageoutputgenerator.Main parseFilesSequentially
INFO: Parsing file bazel-out/darwin_arm64-fastbuild/testlogs/apps/demo/lib_test/coverage.dat
Jan 28, 2024 5:14:10 PM com.google.devtools.coverageoutputgenerator.Main getGcovInfoFiles
INFO: No gcov info file found.
Jan 28, 2024 5:14:10 PM com.google.devtools.coverageoutputgenerator.Main getGcovJsonInfoFiles
INFO: No gcov json file found.
Jan 28, 2024 5:14:10 PM com.google.devtools.coverageoutputgenerator.Main getProfdataFileOrNull
INFO: No .profdata file found.
Jan 28, 2024 5:14:10 PM com.google.devtools.coverageoutputgenerator.Main runWithArgs
WARNING: There was no coverage found.
</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
aarch64-apple-darwin
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
Bazelisk version: development
Build label: 6.4.0
Build target: bazel-out/darwin_arm64-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Oct 19 17:08:20 2023 (1697735300)
Build timestamp: 1697735300
Build timestamp as int: 1697735300
  </code>
</pre>

**Rules_python version:**

<pre>
  <code>
rules_python-0.29.0
  </code>
</pre>

**Anything else relevant?**
I can build coverage with python 3.12 tooling, just not automatically with rules_python.

**Comment by aignas** [comment]
Coverage wheels should be included for 3.12 python, it could be that the script generating the dependencies only includes it for versions up to 3.11. There is python/private/coverage_deps.bzl file that can be looked at to check this.

**Comment by trentontrees** [comment]
Thanks for the pointer.  Created a PR to fix this issue: https://github.com/bazelbuild/rules_python/pull/1727

**Comment by trentontrees** [comment]
Should be fixed in the future 0.30.0 release.
