### ISSUE TITLE
Add support for python-wheel data directory

### ISSUE THREAD

**Issue by BradHolmes** [bazelbuild/rules_python#1777]
# 🚀 feature request

### Relevant Rules

`//python:packaging.bzl - py_wheel`

### Description

The `py_wheel` rule should support the `.data` directory as specified in [PEP 427, The .data directory](https://peps.python.org/pep-0427/#the-data-directory).   This is _different_ than including data files in the source tree.  

### Describe the solution you'd like

It seems to me that changes are needed all the way down in `wheelmaker`, with arguments and logic that mirrors the support of the current flag 'extra_distinfo_file'.  This would be exposed in `py_wheel` as perhaps `data_files`, and a similar ability to rename the files.

### Describe alternatives you've considered

I haven't been able to think of any alternatives, but would be open to hear about them from others.

---

Finally, let me take a moment to say thank you for a wonderful project.  It is really easy to use and adopt, especially with bazelmod.  

If the solution I've described is on the right track, I can take the first pass at implementing and testing it.

**Comment by aignas** [comment]
Thanks for the ticket. I think the need for adding data files is real and I am wondering if there is a way to make this work in a different way, for example using rules_pkg to somehow create a file mapping (I think it provides the renaming feature you mentioned about) and then consume that from rules python without adding an extra dependency on rules_pkg within the rules_python itself.

I haven't looked at the code yet, so I don't know if it is possible and how difficult it would be, but the fact that we need to do changes all the way through to the wheelmaker and introduce a code similar to the extra dist info file handling makes me suspect that we may have some legacy baggage here.

**Comment by BradHolmes** [comment]
Thank you for the reply and support for this feature.

I agree, this is a fairly invasive change (though I believe backwards compatible).  Good thought on `rules_pkg`, but the problematic lines in `wheelmaker` are [here](https://github.com/bazelbuild/rules_python/blob/main/tools/wheelmaker.py#L240-L244), 

```
        self._distinfo_dir = (
            self._wheelname_fragment_distribution_name
            + "-"
            + self._version
            + ".dist-info/"
        )
```
I believe we need to put the usual files in that path, but _data_ files in `.... self._version + ".data/"`.  I'm not enough of a bazel expert to know how to use `rules_pkg` to achieve that.  Thus the straightforward suggestion to add a `self._data_dir` attribute.
