### ISSUE TITLE
Allow users to override system Python

### ISSUE THREAD

**Issue by beasleyr-vmw** [bazelbuild/rules_python#178]
rules_python's `pip_import` and `whl_library` repository rules call out to `python`. On CentOS 6, the system Python is ancient---Python 2.6.6---and it does not satisfy rules_python's need for dict comprehensions. I have newer Python distributions available, but no way to get `pip_import` to use them---prepending the alternate Python's location to my `PATH` doesn't work.

It'd be great if rules_python had some way to let me override its use of the system python.

**Comment by brandjon** [comment]
Dedupping this to #249.
