### ISSUE TITLE
Update affected standalone python releases

### ISSUE THREAD

**Issue by liningpan** [bazelbuild/rules_python#1785]
# 🐞 bug report

### Affected Rule

register toolchain

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description

Certain standalone python releases are accidentally linked with `libcrypt.so.1`. If the shared object is not available on the system, the python interpreter will not run.
- <https://github.com/indygreg/python-build-standalone/issues/197>
- <https://github.com/indygreg/python-build-standalone/commit/80cd87f3401ebe42618d98b23d62f6fc6f5d7f63>
 

## 🔥 Exception or Error

> `/.../bazel-out/k8-fastbuild/bin/requirements.update.runfiles/python_3_10_x86_64-unknown-linux-gnu/bin/python3: error while loading shared libraries: libcrypt.so.1: cannot open shared object file: No such file or directory`

</code></pre>

## 🌍  Your Environment

**Operating System:** `Arch Linux`

**Output of `bazel version`:**

```
Bazelisk version: v1.18.0
Aspect CLI version: 5.9.12
Build label: 6.5.0
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue Jan 23 16:44:21 2024 (1706028261)
Build timestamp: 1706028261
Build timestamp as int: 1706028261
```

**Rules_python version:** `0.31.0`

**Anything else relevant?**

**Comment by aignas** [comment]
This sounds like a reasonable request. I think the best solution would be to update the existing Python toolchain download URLs to use the toolchains from the python standalone build used in #1781.

Added the `help wanted` tag so that anyone feels free to submit a PR with a changelog entry if it is a pressing issue to them. I can review them.
