### ISSUE TITLE
Add option for making gazelle destructive

### ISSUE THREAD

**Issue by dougthor42** [bazelbuild/rules_python#1814]
# 🚀 feature request

### Relevant Rules

+ gazelle

### Description

Gazelle is ["non-destructive"](https://github.com/bazelbuild/rules_python/blob/e86252ffd6d1a1bf32ae99933acc5ab49b78ec1e/gazelle/README.md#usage)

> Gazelle is non-destructive. It will try to leave your edits to BUILD files alone, only making updates to py_* targets.

In general, this is a Really Good Thing :tm: . However, this can be somewhat annoying when making changes. For example, let's say you have a large project and run `gazelle` on it. Neat! All files generated. But then you decide that the default visibility needs to be changed to //foo/bar:baz. So you add your directive:

```
# gazelle:python_default_visibilty //foo/bar:baz
```

and run gazelle again.  ...   ....   nothing changed! Well dang, now I have to delete all BUILD files and run gazelle again.

### Describe the solution you'd like

I think a CLI arg or env var or something that allows gazelle to become destructive would be useful.

And ideal might be fine-grained destructiveness:

+ `--overwrite-visibility`: will only delete and re-add `visibility` attributes.
+ `--purge-existing-targets`: will purge all targets found in BUILD files and remake them.
+ ... what others might be nice?

### Describe alternatives you've considered

The current workaround is to `sed` all files and, for the specific visibility example above, update values there. However, that `sed` command gets tricky if the initial visibility was multi-line.

**Comment by aignas** [comment]
Buildozer can help here as well:
1. Remove all of the stuff that you need with buildozer.
2. Run gazelle.

I think this method would give you the fine granularity that you seek for.

TBH, I am not sure that this is a problem that rules_python gazelle should be solving. But I am happy to be convinced otherwise. :)

**Comment by dougthor42** [comment]
Ah, wonderful! I'd _heard_ of `buildozer` but never actually looked into what it could do... I'd say that yes `buildozer` satisfies my immediate need, at least.

```
buildozer 'remove visibility' '//...:*'
```

EZ-PZ.

As for whether this should be a problem that rules_python gazelle solves... I'm leaning towards not.

Aside from the original example, one other potential use case for destructiveness is to have CI run `gazelle --destructive` (or whatever) and fail with a diff if gazelle would make changes. But that can also be done with a buildozer command before running gazelle.

I'm happy with the solution, so I'll close this request. Thanks!
