### ISSUE TITLE
Gazelle considers both `test_*.py` and `*_test.py` files to be `py_test` targets.

### ISSUE THREAD

**Issue by dougthor42** [bazelbuild/rules_python#1816]
# 🐞 bug report

### Affected Rule

+ gazelle

### Is this a regression?

Nope! Just unexpected behavior.

### Description

A typical python project will use only **one of** `*_test.py` or `test_*.py` to name test files.

However, gazelle will make `py_test` targets for both types:

https://github.com/bazelbuild/rules_python/blob/e86252ffd6d1a1bf32ae99933acc5ab49b78ec1e/gazelle/python/generate.go#L116

https://github.com/bazelbuild/rules_python/blob/e86252ffd6d1a1bf32ae99933acc5ab49b78ec1e/gazelle/python/generate.go#L198

This can lead to unexpected behavior:

#### Example 1: unit test utilities

Assume that a project uses `*_test.py` for unit/integration tests. Using `pytest`, the config would be:

```toml
[tool.pytest.ini_options]
python_files = ["*_test.py"]
```

Also assume that there needs to be some utilities related to testing. A typical solution would be to make a `test_utils.py` file because that does not get collected by the pytest test runner.

`gazelle` will incorrectly (at least according to the user) make:

```starlark
py_test(
    name = "test_utils",
    srcs = ["test_utils.py"],
)
```

The user expects a `py_library` instead.

#### Example 2: Non-code tests, such as electrical or physical testing

Code that deals with electrical or physical testing (voltage, current, vibration, pressure, etc) is typically called `test_foo` or `foo_test`. For example, code that determines the breakdown voltage of a part might be called `test_breakdown_voltage.py`. Code might also need to create collections or suites of non-code tests, and would live in `test_suites.py`.

Again, according to the user, gazelle will incorrectly make `py_test` targets for such instead of `py_library` targets.

## 🔬 Minimal Reproduction

1. Make `test_foo.py`
2. Make `foo_test.py`
3. Run `gazelle`
4. See that both were generated as `py_test` targets.

## 🔥 Exception or Error

N/A

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux rodete
Release:        n/a
Codename:       rodete
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
$ bazel version
Starting local Bazel server and connecting to it...
Build label: 7.1.0
Build target: @@//src/main/java/com/google/devtools/build/lib/bazel:BazelServer
Build time: Mon Mar 11 17:55:31 2024 (1710179731)
Build timestamp: 1710179731
Build timestamp as int: 1710179731
  </code>
</pre>

**Rules_python version:**

<pre>
  <code>
0.31.0 @ bdb2aa2e5c0ca435918037aa3568c0b0c4c9c1ab
  </code>
</pre>

**Anything else relevant?**

Don't think so.

**Comment by dougthor42** [comment]
> Is `test_*.py` even a common convention in Python?

Yes, though it seems like it's going out of style in favor of `*_test.py` (but that might just be observation/recency bias).

+ `pytest` docs use `test_*.py` on the [Getting Started](https://docs.pytest.org/en/8.0.x/getting-started.html#assert-that-a-certain-exception-is-raised) page.
+ `unittest`'s test discovery still [uses `test*.py` by default](https://docs.python.org/3/library/unittest.html#cmdoption-unittest-discover-p) (though note the lack of underscore).
+ `nose2` [uses `test_*.py`](https://docs.nose2.io/en/latest/usage.html#naming-tests) by default but can be configured.

**Comment by aignas** [comment]
The suggested implementation sounds good to me. I think the default behaviour even had a few tests to ensure that people can create libraries with 'test' in the file. But that might have changed at some point.
