### ISSUE TITLE
Facing build issues on PPC64LE architecture

### ISSUE THREAD

**Issue by vinodk99** [bazelbuild/rules_python#1832]
# 🐞 bug report

### Affected Rule

 The issue is caused by the rule: 

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description

While building facing issues on ppc64le architecture for the version:0.31.0

## 🔥 Exception or Error

<pre><code>
 bazel build //...
Starting local Bazel server and connecting to it...
WARNING: For repository 'bazel_skylib', the root module requires module version bazel_skylib@1.3.0, but got bazel_skylib@1.4.2 in the resolved dependency graph.
WARNING: For repository 'platforms', the root module requires module version platforms@0.0.4, but got platforms@0.0.7 in the resolved dependency graph.
WARNING: /rules_python/docs/BUILD.bazel:31:6: target '//docs:bazel_repo_tools' is deprecated: Use @bazel_tools//tools:bzl_srcs instead; targets under //docs are internal.
WARNING: /rules_python/docs/BUILD.bazel:25:6: target '//docs:defs' is deprecated: Use //python:defs_bzl instead; targets under //docs are internal.
WARNING: /rules_python/docs/BUILD.bazel:37:12: target '//docs:pip_install_bzl' is deprecated: Use //python:pip_bzl or //python/pip_install:pip_repository_bzl instead; targets under //docs are internal.
WARNING: /rules_python/docs/BUILD.bazel:47:6: target '//docs:requirements_parser_bzl' is deprecated: Use //python/pip_install:pip_repository_bzl instead; Both the requirements parser and targets under //docs are internal
INFO: Repository rules_bazel_integration_test~0.20.0~bazel_binaries~bazel_binaries_bazelisk instantiated at:
  callstack not available
Repository rule bazelisk_binary defined at:
  /root/.cache/bazel/_bazel_root/a946ea50162806df64f75665b6e6ad3e/external/rules_bazel_integration_test~0.20.0/bazel_integration_test/private/bazel_binaries.bzl:95:34: in <toplevel>
ERROR: An error occurred during the fetch of repository 'rules_bazel_integration_test~0.20.0~bazel_binaries~bazel_binaries_bazelisk':
   Traceback (most recent call last):
        File "/root/.cache/bazel/_bazel_root/a946ea50162806df64f75665b6e6ad3e/external/rules_bazel_integration_test~0.20.0/bazel_integration_test/private/bazel_binaries.bzl", line 87, column 30, in _bazelisk_binary_impl
                _download_bazelisk_binary(repository_ctx, version)
        File "/root/.cache/bazel/_bazel_root/a946ea50162806df64f75665b6e6ad3e/external/rules_bazel_integration_test~0.20.0/bazel_integration_test/private/bazel_binaries.bzl", line 43, column 13, in _download_bazelisk_binary
                fail("Unrecognized os and arch. os: {}, arch: {}".format(
Error in fail: Unrecognized os and arch. os: linux, arch: ppc64le
ERROR: <builtin>: fetching bazelisk_binary rule //:rules_bazel_integration_test~0.20.0~bazel_binaries~bazel_binaries_bazelisk: Traceback (most recent call last):
        File "/root/.cache/bazel/_bazel_root/a946ea50162806df64f75665b6e6ad3e/external/rules_bazel_integration_test~0.20.0/bazel_integration_test/private/bazel_binaries.bzl", line 87, column 30, in _bazelisk_binary_impl
                _download_bazelisk_binary(repository_ctx, version)
        File "/root/.cache/bazel/_bazel_root/a946ea50162806df64f75665b6e6ad3e/external/rules_bazel_integration_test~0.20.0/bazel_integration_test/private/bazel_binaries.bzl", line 43, column 13, in _download_bazelisk_binary
                fail("Unrecognized os and arch. os: {}, arch: {}".format(
Error in fail: Unrecognized os and arch. os: linux, arch: ppc64le
INFO: Repository _main~internal_deps~pypi__click instantiated at:
  callstack not available
Repository rule http_archive defined at:
  /root/.cache/bazel/_bazel_root/a946ea50162806df64f75665b6e6ad3e/external/bazel_tools/tools/build_defs/repo/http.bzl:372:31: in <toplevel>
INFO: Repository rules_cc~0.0.9 instantiated at:
  callstack not available
Repository rule http_archive defined at:
  /root/.cache/bazel/_bazel_root/a946ea50162806df64f75665b6e6ad3e/external/bazel_tools/tools/build_defs/repo/http.bzl:372:31: in <toplevel>
INFO: Repository rules_pkg~0.7.0 instantiated at:
  callstack not available
Repository rule http_archive defined at:
  /root/.cache/bazel/_bazel_root/a946ea50162806df64f75665b6e6ad3e/external/bazel_tools/tools/build_defs/repo/http.bzl:372:31: in <toplevel>
INFO: Repository wheel_for_testing instantiated at:
  /rules_python/WORKSPACE:133:10: in <toplevel>
Repository rule http_file defined at:
  /root/.cache/bazel/_bazel_root/a946ea50162806df64f75665b6e6ad3e/external/bazel_tools/tools/build_defs/repo/http.bzl:466:28: in <toplevel>
ERROR: /root/.cache/bazel/_bazel_root/a946ea50162806df64f75665b6e6ad3e/external/rules_bazel_integration_test~0.20.0~bazel_binaries~build_bazel_bazel_6_4_0/BUILD:2:10: @rules_bazel_integration_test~0.20.0~bazel_binaries~build_bazel_bazel_6_4_0//:bazel_binary depends on @rules_bazel_integration_test~0.20.0~bazel_binaries~bazel_binaries_bazelisk//:bazelisk in repository @rules_bazel_integration_test~0.20.0~bazel_binaries~bazel_binaries_bazelisk which failed to fetch. no such package '@rules_bazel_integration_test~0.20.0~bazel_binaries~bazel_binaries_bazelisk//': Unrecognized os and arch. os: linux, arch: ppc64le
ERROR: Analysis of target '//tests/integration:compile_pip_requirements_test_bazel_6_4_0' failed; build aborted:
INFO: Elapsed time: 13.796s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (143 packages loaded, 673 targets configured)
    currently loading: @rules_java~6.3.0//toolchains ... (13 packages)
    Fetching repository @rules_go~0.41.0; starting
    Fetching repository @_main~internal_deps~pypi__pip; starting
    Fetching repository @_main~internal_deps~pypi__setuptools; starting
    Fetching repository @publish_deps_twine; Restarting.
    Fetching https://files.pythonhosted.org/.../numpy-1.25.2-cp311-cp311-manylinux_2_17_aarch64.manylinux2014_aarch64.whl
    Fetching /root/.cache/bazel/_bazel_root/a946ea50162806df64f75665b6e6ad3e/external/rules_go~0.41.0; Extracting rules_go-v0.41.0.zip
    Fetching ..._root/a946ea50162806df64f75665b6e6ad3e/external/_main~internal_deps~pypi__setuptools; Extracting setuptools-68.1.2-py3-none-any.whl.zip
    Fetching ...ot/a946ea50162806df64f75665b6e6ad3e/external/_main~internal_deps~pypi__pip; Extracting pip-23.2.1-py3-none-any.whl.zip ... (11 fetches)

</code></pre>

## 🌍  Your Environment

**Operating System:**

NAME="Red Hat Enterprise Linux"
VERSION="9.3 (Plow)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="9.3"
PLATFORM_ID="platform:el9"
PRETTY_NAME="Red Hat Enterprise Linux 9.3 (Plow)"

**Output of `bazel version`:**

Build label: 6.4.0- (@non-git)
Build target: bazel-out/ppc-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Fri Apr 5 03:41:57 2024 (1712288517)
Build timestamp: 1712288517
Build timestamp as int: 1712288517

**Rules_python version:**
0.31.0

**Anything else relevant?**

**Comment by aignas** [comment]
This is because the integration tests are downloading bazel from the internet and there is no bazel built for these platforms.

See https://github.com/bazelbuild/bazel/releases/tag/7.1.1

Feel free to raise an issue with the upstream if having rules python integration tests against this architecture is important to you.

I think the only sensible thing we can do for now is to enumerate the platforms that we have bazel binaries for and mark the targets as compatible with those platforms, but that would mean duplication of what bazel binaries are available that I am not sure makes sense to have in rules_python.
