### ISSUE TITLE
pandas doesn't work with rules_python

### ISSUE THREAD

**Issue by jpvelez** [bazelbuild/rules_python#187]
It looks like pandas doesn't work with rules_python.

Here is my `requirements.txt`:
```
pandas
```

But when I try to run any code that imports pandas:
```
bazel run //:main
DEBUG: Rule 'io_bazel_rules_python' indicated that a canonical reproducible form can be obtained by modifying arguments shallow_since = "1557171904 -0400"
INFO: Analysed target //:main (1 packages loaded, 2 targets configured).
INFO: Found 1 target...
Target //:main up-to-date:
  bazel-bin/main
INFO: Elapsed time: 8.351s, Critical Path: 0.01s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
INFO: Build completed successfully, 1 total action
Traceback (most recent call last):
  File "/private/var/tmp/_bazel_jpvelez/38a707cf9d0f20110a0d780b5b663df2/execroot/bazel_python_bug/bazel-out/darwin-fastbuild/bin/main.runfiles/bazel_python_bug/main.py", line 3, in <module>
    import pandas
  File "/private/var/tmp/_bazel_jpvelez/38a707cf9d0f20110a0d780b5b663df2/execroot/bazel_python_bug/bazel-out/darwin-fastbuild/bin/main.runfiles/pypi__pandas_0_24_2/pandas/__init__.py", line 19, in <module>
    "Missing required dependencies {0}".format(missing_dependencies))
ImportError: Missing required dependencies ['dateutil']
```

pandas requires `python-dateutil` to work, but pandas' `BUILD` file doesn't list it as a dependency:

```
package(default_visibility = ["//visibility:public"])

load("@pip//:requirements.bzl", "requirement")

py_library(
    name = "pkg",
    srcs = glob(["**/*.py"]),
    data = glob(["**/*"], exclude=["**/*.py", "**/* *", "BUILD", "WORKSPACE"]),
    # This makes this directory a top-level in the python import
    # search path for anything that depends on this.
    imports = ["."],
    deps = [],
) 
```

It doesn't list `numpy` or `pytz` either, the other two pandas dependencies: https://github.com/pandas-dev/pandas/blob/master/setup.py#L35

It appears that these requirements are not being resolved and downloaded by `pip_import`... even when you add `python-dateutil` to `requirements.txt`, it still doesn't fix the target.

The workaround is to add `python-dateutil` to requirements, and then `requirements('python-dateutil')` to the target deps.

To reproduce the error, clone [this repo](https://github.com/jpvelez/bazel-python-bug/tree/a46d2cce6b09d14516077824b0f5aecf499009b9) and type `bazel run //:main`.

**Comment by kai-kzh** [comment]
Seeing the same behavior in my code. Looks pip_import is not importing recursively.

**Comment by ValentinMouret** [comment]
Hello,

I ran into the same problem and it was solved by adding Pandas dependencies to the `requirements.txt`:

```
numpy
pandas
python-dateutil
pytz
```
And then importing them in the `BUILD` like so:
```py
py_library(
    name = "foo",
    srcs = ["foo.py"],
    deps = [
        requirement("pandas"),
        requirement("numpy"),
        requirement("python-dateutil"),
        requirement("pytz"),
    ],
)
```

You can also make it a variable to ease your life: 
```py
pandas_requirements = [requirement(x) for x in ("pandas", "numpy", "pytz", "python-dateutil")]
```

**Comment by dayfine** [comment]
I think you should use https://github.com/dillon-giacoppo/rules_python_external
See #263

**Comment by thundergolfer** [comment]
`pandas` now certainly works with the [`pip_install`](https://github.com/bazelbuild/rules_python/blob/5d6c0a2f154f4ebdc4e9d3fda7e5e33f61bef4da/README.md#importing-pip-dependencies) repository rule 👍 . I'm involved in multiple WORKSPACES that include that package.
