### ISSUE TITLE
py_library import path is wrong for certain pypi packages (like tensorflow)

### ISSUE THREAD

**Issue by WesleyYue** [bazelbuild/rules_python#189]
Inside where the py_library() is generated for each specified requirement, the import path is specified as "." (https://github.com/bazelbuild/rules_python/blob/master/rules_python/whl.py#L149). While this works for most packages, not all packages have the python module in the top level of the whl. For example, the tensorflow python module is inside tensorfow-<version_info>.whl/tensorfow-<version_info>.data/purelib/tensorflow. Because of this, `import tensorflow` will fail in a py_binary that has requirement("tensorflow"). What I believe rules_python/whl.py should be doing is to check whether the top-level folders have an \_\_init\_\_.py file inside of them, and if not, search the directory tree until it finds them.

**Comment by danieljanes** [comment]
Thanks for opening this issue @WesleyYue. This is a huge blocker for us as well and I believe there is related info in #71 (and https://github.com/apt-itude/rules_pip/issues/15).

**Comment by alexeagle** [comment]
rules_python 0.1.0 has been released which upstreams the rules_python_external repo. Please switch from `pip_import` to `pip_install` which doesn't have this issue.
