### ISSUE TITLE
numpy not properly built when using python3

### ISSUE THREAD

**Issue by rnburn** [bazelbuild/rules_python#190]
If I set up a pip requirement for numpy, I get this error when using python3

```
ImportError: pypi__numpy_1_16_3/numpy/core/_multiarray_umath.so: undefined symbol: _Py_ZeroStruct
```

My guess is that the extension module is not being built correctly (See these [comments](https://github.com/cocodataset/cocoapi/issues/90#issuecomment-360302008)).

Here are the details of my bazel setup

I added a python runtime for python3
```
# ci/BUILD
py_runtime(
    name = "python3",
    interpreter_path = "/usr/bin/python3",
)
```

And I force python3 to be used by adding the following to my .bazelrc
```
# .bazelrc
build --python_top=//ci:python3
run --python_top=//ci:python3
test --python_top=//ci:python3
```

Is there anything I can do to fix this?

**Comment by rnburn** [comment]
I was able to get numpy to work with python3 by using the fork in PR https://github.com/bazelbuild/rules_python/pull/85 with pip3_import.

I hope you guys will prioritize getting that merged in.

**Comment by thundergolfer** [comment]
This is closely related to a few other issues, which have the `pip_import` Python3 issue at their root. See: https://github.com/bazelbuild/rules_python/issues/220#issuecomment-518713498

I reckon this can be closed as a dupe.

**Comment by brandjon** [comment]
Dedupping to #249.
