### ISSUE TITLE
failing tests due to global 'test_arg' which is unsupported by 'unittest'

### ISSUE THREAD

**Issue by sha1n** [bazelbuild/rules_python#194]
I'm working in a mixed repo, where we have several languages built with Bazel. Our repository `.bazelrc` file contains some `--test_arg` flags for JVM testing purposes, which all work fine until I introduced some Python tests into the repo.
When I run my `unittest` based python tests, the testing framework does not recognize those and fails with the following error message:

`error: unrecognized arguments: --jvm_flags=XXX`

To work around that issue, I introduced code that filters out those arguments, which works as expected, but I was wondering if there is a cleaner way of doing that, hopefully at a higher level? 

```
if __name__ == '__main__':
    unittest.main(argv=list((arg for arg in sys.argv if not arg.startswith("--jvm"))))
```

Thanks!

**Comment by aaliddell** [comment]
Putting `test_arg` in bazelrc is not really recommended unless you can guarantee every rule understands or ignores the arguments. Here's two options:

1. Use the [`args` attr](https://docs.bazel.build/versions/master/be/common-definitions.html#test.args) to each test rule. To save repeating yourself, you could define the Java test flags in one file and then load them wherever needed.

2. Use the `test_arg` inline along with a query for all java test rules: `bazel test --test_arg=blah $(bazel query 'kind("java_test rule", //...)')` (not tested)

**Comment by sha1n** [comment]
Thanks @aaliddell!

Indeed sounds like a bad idea when working in an environment like ours.. I think I'll create a macro for JVM test targets, in which I will embed those args (maybe with an option to override them), and leave the `.bazelrc` clean of those.
