### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by mattmoor** [bazelbuild/rules_python#2]
We should get `rules_python` to a state where Bazel can enable:
```json
                {"node": "windows-x86_64"}
```

... in `.ci/rules_python.json`.

Some early scouting of this on top of my `pip_import` PR reveals that there are [at least some blocking issues](http://ci.bazel.io/blue/organizations/jenkins/PR%2Frules_python/detail/rules_python/26/pipeline/25) (I believe) unrelated to my changes.

**Comment by alexeagle** [comment]
Happy Birthday #2! 🍰

**Comment by kylecordes** [comment]
I would prefer this issue not be closed, but kept open pending eventual future well-tuned Windows support.
