### ISSUE TITLE
Rename canonical workspace to `@rules_python`

### ISSUE THREAD

**Issue by brandjon** [bazelbuild/rules_python#203]
The canonical workspace name -- i.e. the name appearing in the `workspace()` declaration, documentation, examples, and code -- is currently `@io_bazel_rules_python`. We should change this to `@rules_python` for consistency with `@rules_cc`, `@rules_java`, etc.

This reflects how this repository is (or ought to be) the canonical home for all things Python in Bazel, and is especially important in light of bazelbuild/bazel#8893. As part of that work, Bazel itself may begin to assume that the core Python rules (`py_binary`, etc.) are available under a `@rules_python` repo.

**Comment by brandjon** [comment]
For more rationale see [here](https://groups.google.com/d/msg/bazel-dev/6ThDzdTM-9w/VgwJLYE7CAAJ).

**Comment by johnynek** [comment]
I think this is unfortunate.

DNS based names, a-la java have been used elsewhere. I think continuing that is the only sure-fire collision avoidance.

Name collision avoidance is worth it IMO.

**Comment by brandjon** [comment]
Ideally it should be possible to remap the names of dependencies and transitive dependencies, so that name collisions can be handled. This works to some extent but is broken in rules_python's case because the generated pypi repos hard code the `@rules_python` identifier. In principle if we parameterize that identifier then users can get around name conflicts involving rules_python.
