### ISSUE TITLE
docutils release broke boto example

### ISSUE THREAD

**Issue by brandjon** [bazelbuild/rules_python#205]
I'm getting an error at workspace-evaluation time when trying to fetch the repos for the boto example. This breaks the workflow for building and testing `rules_python` since our examples are not in a separate subworkspace.

The error ends in

> KeyError: "There is no item named 'docutils-0.15.post1.dist-info/METADATA' in the archive"

According to PyPI release history, docutils-0.15 [was released yesterday](https://pypi.org/project/docutils/#history). This release [contains a file with the version suffix "post1"](https://pypi.org/project/docutils/0.15/#files), whereas other releases [do not have such a suffix](https://pypi.org/project/docutils/0.14/#files). I imagine this is messing with our parsing of the version.

I haven't seen a "post1" suffix before and it doesn't appear to be mentioned explicitly in the semantic versioning doc, so I'm not yet sure if it's our parsing or their release that's broken.

**Comment by brandjon** [comment]
According to [PEP 440](https://www.python.org/dev/peps/pep-0440/#public-version-identifiers), the `.post1` syntax is allowed in a version identifier, so it's our fault.

**Comment by brandjon** [comment]
Wait, if `.post1` is part of the version identifier, then according to [PEP 427](https://www.python.org/dev/peps/pep-0427/#file-contents) it should've also been included in the name of the wheel's dist-info dir, but the name is just `docutils-0.15.dist-info` . The docutils project appears to have published a broken wheel.

**Comment by overload1997** [comment]
I met the same problem when I run 'bazel build' today, how can I solve this?
![image](https://user-images.githubusercontent.com/39192877/61688398-806e8f00-ad57-11e9-80b2-862889daa337.png)

**Comment by brandjon** [comment]
Did you get this problem as a user of rules_python (loading it from your own workspace), or when trying to build/test a checkout of rules_python itself? I thought this issue would only affect development of rules_python since the failure occurred in an example repo declared in our WORKSPACE but not user workspaces.

But now I'm concerned that other people are transitively depending on docutils via other packages, and that this is a problem across the board.

**Comment by aaliddell** [comment]
Copy of details from slack:
- The docutils whl was generated by `bdist_wheel` version 0.29
- This version of `bdist_wheel` (and the latest version) correctly include the `post` suffix in both the whl filename and the dist-info name, as per the PEPs
- The docutils whl file is actually a whl file for version 0.15, which has been renamed with the `post1` suffix but not regenerated, leading to the external filename not matching the internal version data

So the docutils wheel is invalid

**Comment by brandjon** [comment]
Thanks to @aaliddell and @clintharrison for helping track it down.

For reference, docutils 0.15 originally had a [bug](https://sourceforge.net/p/docutils/bugs/365/), and the patch release was created by fixing and renaming the built wheel without regenerating it with the bumped version. Some users have already identified this as an issue for them, and it's likely to affect users who are installing via tooling besides pip.

Hopefully they'll release another version soon so this broken distribution will fade into obscurity, but in the meantime affected users should blacklist it in their requirements.txt (`docutils!=0.15.post1`).
