### ISSUE TITLE
[Question] Make a target that pulls in all python dependencies?

### ISSUE THREAD

**Issue by dougthor42** [bazelbuild/rules_python#2055]
It is possible to make a target that pulls in _all_ pip-installed python modules, perhaps as dependencies? If so, how?

Basically this:

```starlark
py_library(  # or genrule or anything else, really
    name = "all_the_things",
    src = "main.py",
    deps = ["@pypi//..."],
)
```

Obviously the above doesn't work because `deps` must be a single target, not a query, but I think it gets the point across.

### Context:

I've been asked:

> Do you think we could create a bazel rule to build quantum-python which slurps up all the 3rd party server deps and is essentially just using bazel to build a venv?
> ...
> The only thing trick I'm not sure how to accomplish yet is to tell Bazel we want all requirements instead of having to list them out 1 by 1

Translated: we want to use make an OCI image (`py_oci_image`) that has all of the python deps defined in `requirements.txt` already installed.

**Comment by rickeylev** [comment]
I think the thing you want is `load("@pypi//:requirements.bzl", "all_requirements")`. Or something like that, I forget the exact name. There's a list/map of all the things that were pulled in, which you can stick as the deps of a py_library to depend on everything.

> using bazel to build an a venv

An idea we've talked about, but nobody has got around to trying, is creating a `py_venv` rule. It takes a list of deps as input; as output, it produces a directory named "site-packages" with all the various dependencies "installed" into it. Want to try your hand at it?

How it would integrate into e.g. py_binary is an open question still, but that first building block has to be made before we can figure that part out.

**Comment by groodt** [comment]
To be clear, do you want the wheels or installed and unpacked python repl with all dependencies?

The packaging rules are all still considered "unstable", but there are a few approaches.

One common way is to use the "all_requirements" macro.

If you're using gazelle, as a user space BUILD file automater, it can do it for you.

Another way would be to consider using rules_venv or rules_py which have additional support for runtime venv.

Given that it sounds like you have a locked requirements.txt, you could also install that into your base image using docker as well.

Speaking from personal anecdotal experience, it’s a convenient way to go sometimes, but it doesn’t really scale that well. It gets slow. Your mileage may vary.

If it's for your engineers internal convenience or adhoc notebook style usage, what I've found to work wheel is to share the same internal artifact repository between your bazel build and your engineers, so they can pip install as usual until they're ready to add code into a repo BUILD.bazel

**Comment by arrdem** [comment]
Due to ah. Limitations. Of our current build, we have a rule that uses the `all_requirements` macro to implement what we call a `:venv` target in that it contains all the dependencies from the lockfile which defines our standard virtualenv. This allows tests which predate Bazel (and other things) to punt on having proper dependency statements for the moment.

```
load(
    "@pypi_311_main//:requirements.bzl",
    pypi_311_main_all_reqs = "all_requirements",
)

package(default_visibility = ["//visibility:public"])

# A synthetic Python library which exists only to put src/py on the importpath.
py_library(
    name = "py",
    imports = ["."],
)

# A synthetic Python library which allows users to take a dependency on the entire virtual env.
py_library(
    name = "venv",
    deps = [":py"] + pypi_311_main_all_reqs,
)
```

This probably looks different under bzlmod but we aren't there yet.

**Comment by groodt** [comment]
Closing. Solutions and guidance has been provided.

**Comment by dougthor42** [comment]
:+1: for closing. Sorry I didn't follow up on this! No one was poking me about it so I wasn't poking you fine folks about it...
