### ISSUE TITLE
Allow `pip_compile` to accept a set of constraint files

### ISSUE THREAD

**Issue by shs96c** [bazelbuild/rules_python#2098]
# 🚀 feature request

### Relevant Rules

`pip_compile` and `compile_pip_requirements`

### Description

When running a `pip-compile` on the command line, it's possible to specify a [constraints file](https://pip.pypa.io/en/stable/user_guide/#constraints-files). Using this file is useful when (eg) [`setuptools` finally removes the `test` command](https://github.com/pypa/setuptools/issues/4519), but something in your requirements still depends on it. Simply adding the version in the requirements file doesn't work.

### Describe the solution you'd like

The "simplest" thing would be for `compile_pip_requirements` to accept a `constraint` attribute which can be made available via a `PIP_CONSTRAINT` environment variable.

Since it's possible to add `-c` options to the `requirements.in` file, a more complete solution would be to allow `extra_data` to be passed to `pip_compile` ([since `data` is already defined](https://github.com/bazelbuild/rules_python/blob/main/python/private/pypi/pip_compile.bzl#L91)) and have those files be in a known location that can referred to in the `requirements.in` file.

### Describe alternatives you've considered

Moving to Poetry

**Comment by aignas** [comment]
@mattem provided a solution on [Bazel #python slack channel](https://bazelbuild.slack.com/archives/CA306CEV6/p1722246687557339):
> `compile_pip_requirements` accepts both env and data. This worked for me, testing in one of the examples:
> ```starlark
> compile_pip_requirements(
>     name = "requirements",
>     src = "requirements.in",
>     data = ["constraints.txt"],
>     env = {
>         "PIP_CONSTRAINT": "constraints.txt",
>     },
>     requirements_txt = "requirements_lock.txt",
>     requirements_windows = "requirements_windows.txt",
> )```
> 
>
> The constraints file contained the `setuptools < 72.0.0`

@shs96c also wrote there:
> The key thing that might trip people up is that the env-var should point to the path from the root of the repo rather than just the relative path to constraints file.

Given that the offending `setuptools` has been yanked and it is possible to pass the constraints, I am going to close this as won't do.
