### ISSUE TITLE
ciruclar dep with markdown-it-py[linkify, plugins]==3.0.0

### ISSUE THREAD

**Issue by froody** [bazelbuild/rules_python#2103]
# 🐞 bug report

### Affected Rule

 The issue is caused by the rule: 
`pip.parse`

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....
not sure

### Description

 A clear and concise description of the problem...
When `markdown-it-py[linkify, plugins]==3.0.0` and associated deps are in a requirements.txt and used by a target, bazel fails with the error below.

## 🔬 Minimal Reproduction

https://github.com/froody/rules_py_markdown_it
Clone and run `bazel run //:test`. I tested on linux-x86_64

Remove the extras `[linkify, plugins]`, i.e. `markdown-it-py==3.0.0` to make the test pass

## 🔥 Exception or Error

<pre><code>
ERROR: /home/tbirch/.cache/bazel/_bazel_tbirch/4ad4510fd6c3f2ce36db8631e3ab23d4/external/rules_python~~pip~pip_deps/markdown_it_py/BUILD.bazel:10:6: in alias rule @@rules_python~~pip~pip_deps//markdown_it_py:pkg: cycle in dependency graph:
    //:test (b357dd09923b37f48f631ab81341a90e6b4443fce0a2dddfde9d204ca537a54e)
    //:test (5c864536bb2c4dd7b84e076a6dab8f700df816ad8f8998bb302a45cc805cb966)
.-> @@rules_python~~pip~pip_deps//markdown_it_py:pkg (5c864536bb2c4dd7b84e076a6dab8f700df816ad8f8998bb302a45cc805cb966)
|   @@rules_python~~pip~pip_deps_312_markdown_it_py//:pkg (5c864536bb2c4dd7b84e076a6dab8f700df816ad8f8998bb302a45cc805cb966)
|   @@rules_python~~pip~pip_deps//mdit_py_plugins:pkg (5c864536bb2c4dd7b84e076a6dab8f700df816ad8f8998bb302a45cc805cb966)
|   @@rules_python~~pip~pip_deps_312_mdit_py_plugins//:pkg (5c864536bb2c4dd7b84e076a6dab8f700df816ad8f8998bb302a45cc805cb966)
`-- @@rules_python~~pip~pip_deps//markdown_it_py:pkg (5c864536bb2c4dd7b84e076a6dab8f700df816ad8f8998bb302a45cc805cb966)
ERROR: Analysis of target '//:test' failed; build aborted
INFO: Elapsed time: 0.137s, Critical Path: 0.00s
INFO: 1 process: 1 internal.
ERROR: Build did NOT complete successfully
ERROR: Build failed. Not running target
</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
ubuntu-22.04
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
Bazelisk version: development
Build label: 7.2.1
Build target: @@//src/main/java/com/google/devtools/build/lib/bazel:BazelServer
Build time: Tue Jun 25 15:53:05 2024 (1719330785)
Build timestamp: 1719330785
Build timestamp as int: 1719330785
  </code>
</pre>

**Rules_python version:**

<pre>
  <code>
0.34.0
  </code>
</pre>

**Anything else relevant?**

**Comment by aignas** [comment]
See https://rules-python.readthedocs.io/en/latest/pypi-dependencies.html#circular-dependencies
