### ISSUE TITLE
bootstrap_impl=script doesn't handle RUNFILES_MANIFEST_FILE

### ISSUE THREAD

**Issue by rickeylev** [bazelbuild/rules_python#2186]
# 🐞 bug report

### Affected Rule

py_binary with `--boostrap_impl=script`

### Is this a regression?

Yes, bootstrap=system_python doesn't have this problem

Originally reported by @scasagrande in #2177 

### Description

When bootstrap=script is used, it doesn't properly handle when `RUNFILES_MANIFEST_FILE` is used to find the runfiles directory.

Looking at the code, both code paths that look for `*.runfiles/MANIFEST` and `*.runfiles_manifest` might have the same problem.

The fix is to reappend `.runfiles` to the file name after stripping off the manifest location.

## 🔬 Minimal Reproduction

To repro, these flags must be set: `--enable_runfiles=false --build_runfiles_manifests=true --spawn_strategy=local`

It seems that the RUNFILES_MANIFEST_FILE envvar is only set for local executions when runfiles are disabled.

**Comment by scasagrande** [comment]
small correction: flag is `--build_runfile_manifests` (runfile, not runfiles)

**Comment by rickeylev** [comment]
The difficulty in reproducing this might related to a bazel bug: https://github.com/bazelbuild/bazel/issues/7994

Basically, RUNFILES_MANIFEST_FILE isn't set when it should be under sandboxed execution.

Testing this will be annoying. We can't modify `--enable_runfiles` using a transition (it doesn't error, just gets ignored), so have to set it on the command line. Otherwise, `tags=local` can force local running and a transition can affect `--build_runfile_manifests`

I'm thinking it'll just be easier to have the shell test modify the env vars and call the binary again.
