### ISSUE TITLE
pip import results in python3 incompatible libraries

### ISSUE THREAD

**Issue by sha1n** [bazelbuild/rules_python#220]
`pip_import` is using 'python' hardcoded, which in many cases (urllib2, psutil and several others) results in Python 2 libraries that are not compatible with Python 3. 

I replaced "python" with "python3" in the following line and everything works perfectly on my environment.
https://github.com/bazelbuild/rules_python/blob/4b84ad270387a7c439ebdccfd530e2339601ef27/python/pip.bzl#L27

Since this is blocking my team, I created a local copy of `pip.bzl` and patched it just for now. I'm not sure what is the appropriate way to approach this. If there is a way to get the PY/3 interpreter path from Bazel, a fair solution can be to add a `python_version` parameter to the import rule.

Seems like an essential feature for Python 3 support and I will be happy to contribute a PR if we can decide on a solution. WDYT?

**Comment by aaliddell** [comment]
There's a few open PRs about this issue, with varying solutions:
- https://github.com/bazelbuild/rules_python/pull/85
- https://github.com/bazelbuild/rules_python/pull/158
- https://github.com/bazelbuild/rules_python/pull/179

There's also [rules_pip](https://github.com/apt-itude/rules_pip), which offers a `python_interpreter` attribute to solve this on its `pip_repository ` rule. This is the solution I have had to use until there's support in rules_python, although rules_pip actually subjectively has a nicer interface for using the fetched packages.

**Comment by sha1n** [comment]
Thanks @aaliddell! I was unaware of rules_pip and will definitely take a look.
Seems like #42 and #119 are also related to the same core issue, but I haven't seen any progress on either of them for a very long time. 

I'll keep following.

**Comment by ali5h** [comment]
also check this https://github.com/ali5h/rules_pip_lock

**Comment by lshamis** [comment]
Python 2 will be officially past EOL come 2020: https://pythonclock.org/
This is an important issue to resolve before teams can start switching to Python 3.

**Comment by brandjon** [comment]
This should be resolved imminently. Dedupping this issue to #249.
