### ISSUE TITLE
release 0.35.0 has spammy output

### ISSUE THREAD

**Issue by ghorn** [bazelbuild/rules_python#2206]
In a recent release (I think 0.35.0), we get a lot more output when we `bazel build`. It spams the terminal. I'm not sure if this mainly affects bigger corporate repos with lots of dependencies, or if it also affects smaller projcts.

I see something like:

>  ```Fetching ...foobar; Running whl_library.ResolveRequirement(rules_python~~pip~foo_some_package, some_package=2.3.4     --hash=sha256:98471230984712039847102398471203984172043298      --hash=sha256:324293487239482374823749238472398472984 --hash=sha256:2319412730413749810297381209384712039. --hash=sha256:1343495834978534270953498753439084252730 ........```

Looks like the relevant code is 
* `mrctx.report_progress("Running {}".format(op))` in https://github.com/bazelbuild/rules_python/blob/main/python/private/repo_utils.bzl#L139
* and `op_tmpl = "whl_library.ResolveRequirement({name}, {requirement})"` in https://github.com/bazelbuild/rules_python/blob/fcd1d5e9993306891a41b100a80ea407eb3802bc/python/private/pypi/whl_library.bzl#L243

### desired behavior
Make the output much shorter, preferably fitting into one line.

**Comment by rickeylev** [comment]
Ah right. That `requirement` variable has not just the version, but all the hashes, too.

The intent here was to have it show what package and version it was resolving, not the entire set of hashes (that's a bit much)

**Comment by ghorn** [comment]
Glad it's not more complicated. Is the fix obvious to you?

**Comment by rickeylev** [comment]
I think just snip off the `requirement` value put into the log message at ` `, or some equivalent.

Something like:

```
op = op_tmpl.format(name = rctx.attr.name, requirement = rctx.attr.requirement.partition(' ')[0])
```

around L247

Happy to approve a PR

**Comment by mattnworb** [comment]
opened https://github.com/bazelbuild/rules_python/pull/2280 for this
