### ISSUE TITLE
py_test legacy_create_init should be False by default

### ISSUE THREAD

**Issue by shs96c** [bazelbuild/rules_python#221]
Having the [legacy_create_init](https://docs.bazel.build/versions/master/be/python.html#py_test.legacy_create_init) attribute default to `True` is deeply confusing. Enabling legacy behaviour by default is a quirky thing to do, given that this seems to be an artefact of how Google use blaze. I believe that setting the default value to `False` will follow the principle of least surprise for most users.

**Comment by brandjon** [comment]
Indeed, it's something we want to clean up by changing the default and then removing the flag entirely (under the principle that we should avoid global flags). Closing as dup of bazelbuild/bazel#7386.
