### ISSUE TITLE
python_interpreter_target is ignored for entrypoint binaries

### ISSUE THREAD

**Issue by brandonchinn178** [bazelbuild/rules_python#2233]
# 🐞 bug report

### Affected Rule

pip_parse()

### Is this a regression?

I'm not sure

### Description

If I use `python_register_multi_toolchains` to register multiple Python versions, then do
```
loads("@python/3.11:defs.bzl", py311_interpreter = "interpreter")

pip_parse(
    name = "foo_deps",
    ...
    python_interpreter_target = py311_interpreter,
)
```
If I then do `bazel run @foo_deps_somepkg//:rules_python_wheel_entry_point_somepkg`, it will run the entrypoint with the default python interpreter, not the one in `python_interpreter_target`.

Indeed, if I look at `external/foo_deps_somepkg/BUILD.bazel`, I see
```py
load("@rules_python//python:defs.bzl", "py_library", "py_binary")
```
which will load the default `py_binary()` rule, not the one corresponding to the interpreter. This seems to match the logic on HEAD: https://github.com/bazelbuild/rules_python/blob/ade0b2b134565b865b8725bea4dc7896535c4c1a/python/private/pypi/generate_whl_library_build_bazel.bzl#L293

## 🔥 Exception or Error

<pre><code>

</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>

  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>

  </code>
</pre>

**Rules_python version:**

<pre>
  <code>

  </code>
</pre>

**Anything else relevant?**

**Comment by aignas** [comment]
This is working as intended, please look at the `py_console_script_binary` on how to run with some particular interpreter.
