### ISSUE TITLE
Support producing uncompressed wheels for development

### ISSUE THREAD

**Issue by keith** [bazelbuild/rules_python#2240]
Currently `py_wheel` + `wheelmaker` uses [standard zip compression](https://github.com/bazelbuild/rules_python/blob/1d7fd51ceab8d09858eca85cce9a16b867b8a3e2/tools/wheelmaker.py#L107) when producing a wheel. When you're iterating on a wheel target, this can take a huge amount of time for large wheels with native binaries. In our case it takes ~3 minutes just to zip the dev wheel. It would be great if this compression knob was exposed somehow, in our case that time goes down to ~10 seconds if I just change this to `zipfile.ZIP_STORED`.

**Comment by rickeylev** [comment]
I'd approve a PR adding an arg to py_wheel that plumbs through to affect the compression level.

**Comment by keith** [comment]
Awesome! I can try to take a look at that next week

**Comment by keith** [comment]
https://github.com/bazelbuild/rules_python/pull/2260
