### ISSUE TITLE
genrule Tagged as manual or testonly=True Still Builds during build (not test) When Used in py_test

### ISSUE THREAD

**Issue by brianantony456** [bazelbuild/rules_python#2247]
# 🐞 bug report

### Description

When a genrule is tagged with `manual` or `testonly=True`, it's expected that the rule should not build unless explicitly invoked. However, when this rule is used in the data attribute of a py_test, it still builds during the build invocation.

i.e. `bazelisk build ...`

I would expect that it builds only when `bazelisk test ...` is run.

## 🔬 Minimal Reproduction
```python
load("@rules_python//python:defs.bzl", "py_test")

genrule(
    name = "manual-test-only-rule",
    srcs = [],
    outs = ["dummy"],
    cmd = "echo xxx > $@",
    testonly = True,
    tags = ["manual"]
)

py_test(
    name = "test-me",
    srcs = ["test-me.py"],
    testonly = True,
    data = [":manual_test_only_rule"],
)
```

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
        RHEL7
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
        7.3.1
  </code>
</pre>

**Rules_python version:**

<pre>
  <code>
       0.36
  </code>
</pre>

**Comment by aignas** [comment]
In this case `py_test` is not set to `manual`, hence it will be built. Pass `tags = ["manual"]` to `py_test` to see the behaviour you expect.

**Comment by lingithub1** [comment]
@aignas , you are right. However, you might have overlooked something: The main purpose of assing `tags = ["manual"]` to `py_test` or `sh_test` does what it is intended to do: It makes `bazelisk test //...` skip this test. This is _not_ @brianantony456 's intention.

Therefore, passing `manual` to the test rule is not a good solution.

I think the underlying question is: If you do a `bazel build` on a test rule, should Bazel really build all inputs of the test?
The alternative would be: delay all (build) operations until they are _necessary_, meaning: until `bazel test`.

**Comment by aignas** [comment]
I understand this tradeoff, however this limitation is not rules_python responsibility, this is how bazel itself works and we are not doing anything in rules_python that could affect the outcome of this as far as I am aware.

Feel free to raise a ticket on bazelbuild/bazel issue tracker for this use case.
