### ISSUE TITLE
Wheel examples fail to build when using fully qualified package path

### ISSUE THREAD

**Issue by brandjon** [bazelbuild/rules_python#225]
@fweikert discovered that we fail to build in the Bazel federation's CI because they specify our `//experimental/examples/...` targets as `@rules_python//experimental/examples/...`, and this messes up the `py_package` filtering logic. The failure repros locally with e.g.

    bazel build @rules_python//experimental/examples/wheel:minimal_with_py_package

**Comment by pstradomski** [comment]
I'll take a look next week.

**Comment by brandjon** [comment]
From what I can tell it seems like `_path_inside_wheel` should be using `short_path` and stripping out the `../<repo_name>` leading portion. That should make `py_package` filter based on matching the package path relative to whatever repo the file came from. Not sure if that's your intent for `py_package` but it sounds plausible.

Since the workaround for the federation is to disable these targets in their CI, I'll downgrade this to P2 pending your look next week.

**Comment by pstradomski** [comment]
That could work. We need to verify it also works for generated files, but we already have tests for that.
