### ISSUE TITLE
[Bazel CI] Error no native function or rules 'sh_test'


### ISSUE THREAD

**Issue by sgowroji** [bazelbuild/rules_python#2299]
CI: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/4198#01928938-25f1-42af-ad77-b740b840f290

 Platform: MacOS

 Logs: 
```
 ERROR: Traceback (most recent call last):
	File "/Users/buildkite/builds/bk-macos-pln3-pwxc/bazel-org-repo-root/rules_python/tests/integration/BUILD.bazel", line 90, column 30, in <toplevel>
		rules_python_integration_test(
	File "/Users/buildkite/builds/bk-macos-pln3-pwxc/bazel-org-repo-root/rules_python/tests/integration/integration_test.bzl", line 109, column 31, in rules_python_integration_test
		bazel_integration_test(
	File "/private/var/tmp/_bazel_buildkite/023fa58f497dd9f18a2fd23677a71d45/external/rules_bazel_integration_test+/bazel_integration_test/private/bazel_integration_test.bzl", line 164, column 11, in bazel_integration_test
		native.sh_test(
Error: no native function or rule 'sh_test'
Available attributes: action_listener, alias, available_xcodes, cc_binary, cc_import, cc_libc_top_alias, cc_library, cc_proto_library, cc_shared_library, cc_static_library, cc_test, cc_toolchain, cc_toolchain_alias, cc_toolchain_suite, config_feature_flag, config_setting, constraint_setting, constraint_value, environment, existing_rule, existing_rules, exports_files, extra_action, fdo_prefetch_hints, fdo_profile, filegroup, genquery, genrule, glob, java_binary, java_import, java_library, java_lite_proto_library, java_package_configuration, java_plugin, java_plugins_flag_alias, java_proto_library, java_runtime, java_test, java_toolchain, label_flag, label_setting, legacy_globals, memprof_profile, module_name, module_version, objc_import, objc_library, package, package_group, package_name, package_relative_label, platform, propeller_optimize, proto_lang_toolchain, proto_library, repo_name, repository_name, starlark_doc_extract, subpackages, test_suite, toolchain, toolchain_type, xcode_config, xcode_config_alias, xcode_version

``` 
 Culprit: 

 Steps:
  ``` 
 git clone https://github.com/bazelbuild/rules_python
git reset 0e604b06ae4c29c9d386677d3ac57ffe4012e3d7  --hard
export USE_BAZEL_VERSION=00fdb673ba8276e83f1c821a7f93aab7038377e2
bazel build ... @rules_python//examples/wheel/... 
 ``` 
 CC Greenteam @meteorcloudy

**Comment by aignas** [comment]
FYI, the tests are failing with
```
Error in expand_location: file '@@rules_shell//shell/private:sh_executable.bzl' cannot use private API
```

At least for older `bazel` versions. Could you please take a look?

**Comment by rickeylev** [comment]
If the plan is for it to require a minimum bazel version, then let us know so we can try and apply appropriate workarounds, if necessary (IMHO: this is a detail rules_shell should take care of).

Also, is there a tracking bug for the migration? It would just be handy to have if we need to refer to it or report bugs we find.

**Comment by meteorcloudy** [comment]
rules_shell 0.2.0 already automatically fallback to native rules if available, see https://github.com/bazelbuild/rules_shell/pull/10

I think the correct way is to load rules_shell everywhere like protobuf did: https://github.com/protocolbuffers/protobuf/commit/8ec13ede1f4e07ca88a71d02aca004e3c281700a

/cc @comius @fmeum

**Comment by sgowroji** [comment]
Rules\_python CI is still failing [https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/4208#01929dce-7b67-4627-896b-5289323e35b1](https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/4208#01929dce-7b67-4627-896b-5289323e35b1)  CC @rickeylev . Can you please take a look. Thanks!

**Comment by rickeylev** [comment]
That failure appears to be from a dependency: rules_bazel_integration_test (https://github.com/bazel-contrib/rules_bazel_integration_test)

> <snip>/external/rules_bazel_integration_test+/bazel_integration_test/private/bazel_integration_test.bzl

It'll require a fix in that project.
