### ISSUE TITLE
Generated binary file fails when asyncio imported

### ISSUE THREAD

**Issue by kgreenek** [bazelbuild/rules_python#23]
I created an example repository illustrating the issue:
https://github.com/kgreenek/bazel_asyncio

After building the :bazel_asyncio target, you would expect to run the command with:
```bash
./bazel-bin/bazel_asyncio
```

However, that command fails with the following traceback:
```bash
Traceback (most recent call last):
  File "/home/kevin/Projects/bazel_asyncio/bazel-bin/bazel_asyncio.runfiles/__main__/bazel_asyncio.py", line 1, in <module>
    import asyncio
  File "/home/kevin/Projects/bazel_asyncio/bazel-bin/bazel_asyncio.runfiles/pypi__asyncio_3_4_3/asyncio/__init__.py", line 9, in <module>
    from . import selectors
  File "/home/kevin/Projects/bazel_asyncio/bazel-bin/bazel_asyncio.runfiles/pypi__asyncio_3_4_3/asyncio/selectors.py", line 39
    "{!r}".format(fileobj)) from None
                               ^
SyntaxError: invalid syntax
```

It also fails if I explicitly use python3 to run that file:
```bash
python3 bazel-bin/bazel_asyncio
```

This seems to to be a good work-around. It works even without asyncio pip installed on my machine:
```bash
python3 bazel-bin/bazel_asyncio.runfiles/__main__/bazel_asyncio.py
```

**Comment by mattmoor** [comment]
@duggelz My naive thought is that this is a Bazel Core / `py_binary` bug, WDYT?

**Comment by kgreenek** [comment]
I got it to work by migrating to the new pip_import() bazel rules, so that may also have had something to do with it. With those rules, now bazel is aware of the pip dependencies, so it makes sure the paths are all set up properly.

Now I also make sure that I am using python3 with a virtualenv.

Closing this for now unless it comes back up.
