### ISSUE TITLE
py_binary works fine with toolchains and platforms but py3_image fails (OSX)

### ISSUE THREAD

**Issue by cdg720** [bazelbuild/rules_python#230]
Hi,

I have a simple py3_image that fails to run in [my repository](https://github.com/cdg720/bazel_examples/tree/master/py3_image).

For example,
```
bazel run -c opt //foo:hello_world_image \
  --extra_toolchains=//platform_defs:my_platform_python_toolchain \
  --platforms=//platform_defs:my_platform
```
fails on my mac with the following:
```
Use --sandbox_debug to see verbose messages from the sandbox
Traceback (most recent call last):
  File "bazel-out/host/bin/external/bazel_tools/tools/build_defs/hash/sha256", line 340, in <module>
    Main()
  File "bazel-out/host/bin/external/bazel_tools/tools/build_defs/hash/sha256", line 326, in Main
    ret_code = subprocess.call(args)
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 172, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory: '/usr/bin/python3'
Target //foo:hello_world_image failed to build
Use --verbose_failures to see the command lines of failed build steps.
```
One cannot have ```/usr/bin/python3``` on recent macs anymore and I have ```/usr/local/bin/python3``` installed.

However, py_binary runs fine:
```
bazel run -c opt //foo:hello_world_py \
  --extra_toolchains=//platform_defs:my_platform_python_toolchain \
  --platforms=//platform_defs:my_platform
```
prints "Hello World!" and other things.

Does anyone know what I need to do to get py3_image run?

I have asked about [this](https://github.com/bazelbuild/rules_docker/issues/1093) to [rules_docker](https://github.com/bazelbuild/rules_docker) and was told that I might be able to get help here.

**Comment by brandjon** [comment]
Given that this works for `py_binary`, I'm tempted to say that this is an issue with the `py3_image` rule and should be addressed within the rules_docker repo. But I see the failure occurs in a bazel_tools target built in the host config. So maybe it's an issue of toolchain resolution working differently in the host config?

Can you please run this build with `--toolchain_resolution_debug` to confirm what toolchain is being selected for both targets?

**Comment by katre** [comment]
The problem is probably the changed target platform: for the top-level (successful) build, it's `//platform_defs:my_platform`, but for the host mode build it's `@bazel_tools//platforms:host_platform`.

Since the default host doesn't have the extra constraints ":usr_weirdpath_python2" or ":usr_weirdpath_python3", the toolchain that uses those isn't selected.

**Comment by katre** [comment]
Since the `//platform_defs:my_platform` is intended to represent your local machine, use `--host_platform=//platform_defs:myplatform` in addition to `--platforms=//platform_def:my_platform`.

**Comment by brandjon** [comment]
BTW the `weirdpath` constraints were hypothetical examples, you don't need them in your code.

**Comment by cdg720** [comment]
Thank you all! In my case, I needed to pass extra_toolchains and host_platform but not platforms.

```
bazel run -c opt //foo:hello_world_image \
  --extra_toolchains=//platform_defs:my_platform_python_toolchain \
  --host_platform=//platform_defs:my_platform
```
works for me.

**Comment by mdvorsky** [comment]
This sounds similar to https://github.com/bazelbuild/rules_docker/issues/1105

**Comment by karlhepler** [comment]
@cdg720 

I cloned your repository and ran the following:

```
bazel run -c opt //foo:hello_world_image \
  --extra_toolchains=//platform_defs:my_platform_python_toolchain \
  --host_platform=//platform_defs:my_platform
```

It did not work for me. I feel like I'm doing something wrong - how do I get these `//platform_defs`? I'm trying to do something similar in my project and I was hoping your solution might work for me, but I can't seem to get your solution to work for me.

Here is the error output:

```
➜  py3_image git:(master) ✗ bazel run -c opt foo:hello_world_image --extra_toolchains=//platform_defs:my_platform_python_toolchain --host_platform=//platform_defs:my_platform
ERROR: While resolving toolchains for target @io_bazel_rules_docker//:fastbuild: com.google.devtools.build.lib.packages.BuildFileNotFoundException: no such package 'platform_defs': BUILD file not found in any of the following directories. Add a BUILD file to a directory to mark it as a package.
 - /Users/redacted/Desktop/bazel_examples/py3_image/platform_defs
ERROR: Analysis of target '//foo:hello_world_image' failed; build aborted: com.google.devtools.build.lib.packages.BuildFileNotFoundException: no such package 'platform_defs': BUILD file not found in any of the following directories. Add a BUILD file to a directory to mark it as a package.
 - /Users/redacted/Desktop/bazel_examples/py3_image/platform_defs
INFO: Elapsed time: 0.130s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)
```

**Comment by cdg720** [comment]
my repository is now using bazel 2.0 and it doesn't use toolchains and host_platform anymore. i needed them when i was using bazel 0.28.*
