### ISSUE TITLE
[Question] Fixing up Python import paths when using `py_library`

### ISSUE THREAD

**Issue by nicholasjng** [bazelbuild/rules_python#2346]
Apologies if this is a solved problem, I just couldn't get it to work on my end.

Suppose I want to vendor/bootstrap a PyPI dep without the usual pip_parse facility (just from the sdist, basically). Since that contains the Python files under another directory, usually named `src`, I lose the top package name when I use such a library:

```
# from nanobind's sdist, so the top-level package is "nanobind", which is what I want
py_library(
    name = "stubgen",
    srcs = ["src/stubgen.py"],
    imports = ["src"],
    deps = ["@pypi__typing_extensions//:lib"],
)
```

In a script of mine consuming this library, I have to write `from stubgen import ...`, whereas I'd like to be able to write `from nanobind.stubgen import ...` (which would be its usual import statement from a wheel install). Is there any way to fix up these paths that I'm missing?

**Comment by aignas** [comment]
We don't have any `imports` magic yet to solve something like this. We may support `sdists` better in the future later.
