### ISSUE TITLE
DEBUG logs show "create_whl_repos WARNING: falling back to pip"

### ISSUE THREAD

**Issue by dougthor42** [bazelbuild/rules_python#2354]
# 🐞 bug report

### Affected Rule

+ `create_whl_repos`

### Is this a regression?

Seems to be. It wasn't happening on 0.36.0 and did happen when updating to 0.37.1.

I'll spend some time trying to bisect the exact commit.

### Description

Some logs show "WARNING" in their text, but are logged at the DEBUG level.

```
DEBUG: /usr/local/google/home/dthor/.cache/bazel/_bazel_dthor/dbe74c4144b5c9a438d84a119652bef9/external/rules_python~/python/private/repo_utils.bzl:75:16: 
rules_python:pypi:create_whl_repos WARNING: falling back to pip for installing the right file for rupyle==20241025.9027810.4790800     --hash=sha256:...     --hash=sha256:...
```

![image](https://github.com/user-attachments/assets/ad571ecf-b085-4870-9016-268e7dbcd69e)

**EDIT:**
I forgot to add: the requested fix here is to elevate these logs to the WARNING level.

## 🔬 Minimal Reproduction

Reproduction probably needs some specific attributes of python packages and I'm not exactly sure what those attributes are.

I know I can reproduce on my own system though, so that's something.

For my own repro:

1. check out a commit that uses rules_python 0.36.0
2. run `bazel clean --expunge_async; bazel run --config=local //:gazelle_python_manifest.update`
3. See no DEBUG line
4. check out a commit that uses `rules_python` 0.37.1`
5. run `bazel clean --expunge_async; bazel run --config=local //:gazelle_python_manifest.update`
6. See DEBUG line

## 🔥 Exception or Error

N/A

## 🌍  Your Environment

**Operating System:**

gLinux

**Output of `bazel version`:**

```
$ bazel version
Bazelisk version: v1.20.0
Build label: 7.3.2
Build target: @@//src/main/java/com/google/devtools/build/lib/bazel:BazelServer
Build time: Tue Oct 1 17:46:05 2024 (1727804765)
Build timestamp: 1727804765
Build timestamp as int: 1727804765
```

**Rules_python version:**

```
0.37.1
```

**Anything else relevant?**

**Comment by dougthor42** [comment]
One thing that I forgot to mention is that we're also bumping python version to 3.13 **and** the issue doesn't show up for 3.12. So it's possible that the issue is specific to the combination of our wheels and py3.13.

The log line is

https://github.com/bazelbuild/rules_python/blob/462399013e6dc32ba2a8e38e0adce50a58d92361/python/private/pypi/extension.bzl#L335

which as you can see is already a WARNING level (aside: use `logger.warning` over `logger.warn`, as [`.warn` is deprecated](https://github.com/python/cpython/blob/e1190c054383cc139a40b081568ff76c73de05c8/Lib/logging/__init__.py#L1533-L1536)) so the issue appears to be something in the translation from python logging to bazel logging.


> I'll spend some time trying to bisect the exact commit.

Hmm... I am now unable to reliably reproduce it. Fun.

----

Well anyway, I've already spent more time that I should have on this and it's by no means a blocker of _anything_ so I'll have to come back to this later. And by "later" I most likely mean: "the next time it bugs me again, which might be never".

I'll leave this open in case someone knows a quick fix, but it's definitely a P2 or lower priority.

**Comment by rickeylev** [comment]
> the requested fix here is to elevate these logs to the WARNING level.

Unfortunately, there's no APi to emit the "WARNING: ..." (and purple/pink text) in starlark. The best we can do is the DEBUG message with the WARNING text later

**Comment by dougthor42** [comment]
SGTM!
