### ISSUE TITLE
uv tool sha256sum is incorrect for aarch64-apple-darwin

### ISSUE THREAD

**Issue by schultetwin** [bazelbuild/rules_python#2411]
# 🐞 bug report

### Affected Rule

 The issue is caused by the rule: `uv = use_extension("@rules_python//python/uv:extensions.bzl", "uv")`

### Is this a regression?

Yes, the previous version in which this bug was not present was: Yes. Bad hash introduced here: https://github.com/bazelbuild/rules_python/pull/2333/files#diff-1757fb851d4a183b61f34ea410721b38095ac28194ec1b6b233152155febb69c.

### Description

The `sha256sum` for `uv` or aarch64-apple-darwin is incorrect. It's coded as: `35786030f926e3d34d186edc0ea3989698e57755852af9ae4b39da5109abcbfa`. It should be: `bb2ff4348114ef220ca52e44d5086640c4a1a18f797a5f1ab6f8559fc37b1230`. See here for confirmation: https://github.com/astral-sh/uv/releases/download/0.4.25/uv-aarch64-apple-darwin.tar.gz.sha256.

## 🔬 Minimal Reproduction

Use `uv` on an aarch64 macbook

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Macbook Pro M1
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
Bazelisk version: 1.20.0
Build label: 7.3.2
Build target: @@//src/main/java/com/google/devtools/build/lib/bazel:BazelServer
Build time: Tue Oct 1 17:48:21 2024 (1727804901)
Build timestamp: 1727804901
Build timestamp as int: 1727804901
  </code>
</pre>

**Rules_python version:**

<pre>
  <code>
0.38.0
  </code>
</pre>

**Anything else relevant?**

See here to see if this has been fixed: https://github.com/bazelbuild/rules_python/blob/main/python/uv/private/versions.bzl#L73

**Comment by aignas** [comment]
Thank you for the report. If you would like this to be fixed before we have time to fix this ourselves, please submit a patch.
