### ISSUE TITLE
SSL: CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by deryck1031** [bazelbuild/rules_python#242]
The certification works with wget:
     wget --ca-certificate=./python-base64.cer https://pypi.python.org/simple/numpy/

but it failed when trying to get numpy package using rules_python (with same certification file):

 pip_import failed: Collecting numpy (from -r /home/user/work/third_party/requirements.txt (line 2))
  Could not fetch URL https://pypi.python.org/simple/numpy/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.python.org', port=443): Max retries exceeded with url: /simple/numpy/ (Caused by SSLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)'),)) - skipping
 (  Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)'),)': /simple/numpy/
  Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)'),)': /simple/numpy/
  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)'),)': /simple/numpy/
  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)'),)': /simple/numpy/
  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)'),)': /simple/numpy/

**Comment by deryck1031** [comment]
Below are in my WORKSPACE: 

 http_archive(
    name = "rules_python",
    strip_prefix = "rules_python-master",
    url = "https://github.com/bazelbuild/rules_python/archive/master.zip",
  )


load("@rules_python//python:repositories.bzl", "py_repositories")
py_repositories()

load("@rules_python//python:pip.bzl", "pip_import")
pip_import(
   name = "my_deps",
   requirements = "//third_party:requirements.txt",
)

load("@my_deps//third_party:requirements.bzl", "pip_install")

pip_install()

**Comment by brandjon** [comment]
I'm not able to reproduce, I can build a hello world package that imports numpy. Possibly a transient problem with pypi?

**Comment by deryck1031** [comment]
The error msg mentioned port 443, but my proxy port is 8080.  I have http proxy set, so shouldn't it use port 8080?

**Comment by deryck1031** [comment]
what certification file does it use?  Can I overwrite it?
