### ISSUE TITLE
Requesting info about packaging rules, eg. a roadmap

### ISSUE THREAD

**Issue by thundergolfer** [bazelbuild/rules_python#246]
👋 `rules_python` team,

### Description

In line with current `README`, I understand that 'core' rules are stable but that the packaging side of things is still ALPHA. 

As the packaging rules have key features missing (eg. wheel building determinism, complete transitive deps handling), people using `rules_python` have been building on top of them or building new packaging rules. Here's a couple examples of the latter:

* [`apt-itude/rules_pip`](https://github.com/apt-itude/rules_pip), which the author has said he's unlikely to continue developing
* [`tubular/rules_pygen`](https://github.com/tubular/rules_pygen), which is not super actively developed, but is still being developed. 

I'd say there a more of this kind that aren't open-source, at places like Dropbox and Spotify.

At my company we're trying to understand whether we should invest in developing own internal solution. We currently have something called `py-bazel-deps` which is taking inspiration from [`bazel-deps`](https://github.com/johnynek/bazel-deps), but if the Python equivalent of [`rules_jvm_external`](https://github.com/bazelbuild/rules_jvm_external) were to be announced soon* then our `py-bazel-deps` would be superseded like `bazel-deps` was superseded by `rules_jvm_external` and we might as well have waited.

Bazel's docs currently has roadmaps here, https://bazel.build/roadmap.html. If `rules_python` had its own roadmap that provided rough feature delivery timelines that would really help us assess the value of investment in custom-building some of our own Python packaging rules for Bazel.

----

\* soon = 3-6 months

**Comment by gravypod** [comment]
Somewhat related to @thundergolfer 's original post is third party python 2 and python 3 dependencies. Some companies have python 2 and python 3 code and, in those cases, will need to download libraries for these two runtimes. `rules_pip` handles this semi-gracefully and I was forced to use it for a recent project. It allows you to specify which python binary to run to download packages. Will `rules_python` get support for gracefully handling these situations?

**Comment by jmcfallargo** [comment]
I agree with the O.P's request.  We are also trying to evaluate where our time should be spent with development also.  There are certain packages that don't work with like Tensorflow (https://github.com/bazelbuild/rules_python/issues/71) that has been open for almost a year.  A roadmap and guidance from the Bazel team would be very helpful.

**Comment by ali5h** [comment]
check our implementation https://github.com/ali5h/rules_pip/
we use python heavily in production with bazel

**Comment by thundergolfer** [comment]
Due to not getting info on this issue, we've also started investing more in this area, with some of those efforts ending up in https://github.com/dillon-giacoppo/rules_python_external

**Comment by thundergolfer** [comment]
Closing as I'm now a maintainer and about to post an update on the packaging rules 😅.

**Comment by jmcfallargo** [comment]
This is really exciting news!
