### ISSUE TITLE
Enable straightforward use of Python 3 for packaging rules

### ISSUE THREAD

**Issue by brandjon** [bazelbuild/rules_python#249]
Tracking bug for the various dups of this frequently proposed functionality. Will merge in a rebased version of #158, and use that to provide a `pip3_import` rule.

**Comment by zlalanne** [comment]
Thanks for this! Any chance at a 0.0.2 release soon?

**Comment by brandjon** [comment]
Plan is to have one corresponding to the Bazel Federation release for Bazel 2.0. Opened #261 to track.
