### ISSUE TITLE
python_register_toolchains defs.bzl "interpreter" symbol not found in v1.0.0

### ISSUE THREAD

**Issue by mikex-oss** [bazelbuild/rules_python#2494]
# 🐞 bug report

### Affected Rule

 The issue is caused by the rule: python_register_toolchains

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 0.40.0

### Description

 A clear and concise description of the problem...
Our existing Python toolchain registration WORKSPACE setup follows the docs at https://rules-python.readthedocs.io/en/latest/toolchains.html#workspace-toolchain-registration. This code no longer works in the latest rules_python release because the symbol cannot be found.

https://github.com/google/xls/blob/a1f5872de1b6a186c2392dfdf630d31ccef1a1f0/dependency_support/initialize_external.bzl#L22C43-L22C52

## 🔬 Minimal Reproduction

```
# WORKSPACE
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "rules_python",
    sha256 = "4f7e2aa1eb9aa722d96498f5ef514f426c1f55161c3c9ae628c857a7128ceb07",
    strip_prefix = "rules_python-1.0.0",
    url = "https://github.com/bazelbuild/rules_python/releases/download/1.0.0/rules_python-1.0.0.tar.gz",
)

load("@rules_python//python:repositories.bzl", "py_repositories")

py_repositories()

load("@rules_python//python:repositories.bzl", "python_register_toolchains")

python_register_toolchains(
    name = "python_3_11",
    # Available versions are listed in @rules_python//python:versions.bzl.
    # We recommend using the same version your team is already standardized on.
    python_version = "3.11",
)

load("@python_3_11//:defs.bzl", "interpreter")
```

`> bazel fetch --noenable_bzlmod`

## 🔥 Exception or Error

<pre><code>

 load("@python_3_11//:defs.bzl", "interpreter")
Error: file '@project_python//:defs.bzl' does not contain symbol 'interpreter'
</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Ubuntu 22.04 (GCP Docker)
  </code>
</pre>

**Output of `bazel version`:**
<pre>
  <code>
7.4.1
  </code>
</pre>

**Rules_python version:**

<pre>
  <code>
1.0.0
  </code>
</pre>

**Anything else relevant?**

**Comment by aignas** [comment]
See the changelog notes for breaking changes: https://rules-python.readthedocs.io/en/latest/changelog.html#v1-0-0

It seems that our docs are stale. I'll leave this ticket open to update the docs.
