### ISSUE TITLE
Update pip version to > 19.0

### ISSUE THREAD

**Issue by brandjon** [bazelbuild/rules_python#253]
This is to match [tensorflow's requirement](https://www.tensorflow.org/install#download-a-package).

Current pip version is 9.0.3. (Looks like pip recently switched the versioning scheme to use the last two digits of the year.)

**Comment by bshashank** [comment]
Given the desire to move away from using par files (https://github.com/bazelbuild/rules_python/issues/184), are we going to update pip by updating the vendored third_party directory like it was suggested in https://github.com/bazelbuild/rules_python/pull/81?

**Comment by brandjon** [comment]
I'm just intending to bump the version number and confirm it fixes a repro that's been reported with tensorflow. I'd like to eliminate the circular par dependency (#184) but it's not a blocker and not urgent.

**Comment by thundergolfer** [comment]
https://github.com/bazelbuild/rules_python/pull/412 upgraded pip to `21.x.x` for the `pip_install` repo rule, so I think we can now close this issue 🙂.
