### ISSUE TITLE
Upgrade stardoc, switch to markdown syntax in args

### ISSUE THREAD

**Issue by brandjon** [bazelbuild/rules_python#255]
We still use `<code>` syntax in some docstrings instead of markdown backtics, because the latter doesn't render correctly inside argument docstrings. I believe this can be fixed by updating to a newer stardoc and/or switching to the "markdown tables" template.

See also discussion in #251.

**Comment by thundergolfer** [comment]
Addressed by https://github.com/bazelbuild/rules_python/pull/486
