### ISSUE TITLE
Pip packages specified with brackets fail

### ISSUE THREAD

**Issue by timblakely** [bazelbuild/rules_python#26]
`gapic-google-cloud-datastore` depends on  `googleapis-common-protos[grpc]` and `proto-google-cloud-datastore-v1[grpc]`. I believe pip canonically drops these extra bracketed tags, but the `requirement` function attempts to look it up in `_requirements` by the full key which fails.

**Comment by mattmoor** [comment]
Does this fix it for you? https://github.com/bazelbuild/rules_python/pull/18

**Comment by mattmoor** [comment]
Here's the issue tracking "extras" support: https://github.com/bazelbuild/rules_python/issues/12  I'm going to resolve in favor of that.

**Comment by timblakely** [comment]
Thanks, yup, should resolve it.

**Comment by mattmoor** [comment]
There may be other issues with the `google` libraries (there is another open issue), but I'm hoping that at least the first-level issue is resolved by my PR :-/
