### ISSUE TITLE
Please support a built in way to run linters such as mypy.

### ISSUE THREAD

**Issue by jmcfallargo** [bazelbuild/rules_python#265]
Please add the ability to easily run external tools/linters such as Mypy with native support.  I have seen a few complex solutions but it would be nice to have an official way to do this.
There has been an issue open on the Mypy side for about two years: https://github.com/python/mypy/issues/3912

**Comment by thundergolfer** [comment]
I don't think running linters or type-checkers like MyPy should be something `rules_python` should natively support. Right now I can't think of any other `rule_*` that have native support for linters. None of `rules_scala`, `rules_go`, `rules_java`, and `rules_rust` do. 

At the bottom of that thread you link, I've linked to a recently created Bazel+MyPy integration (https://github.com/thundergolfer/bazel-mypy-integration). I started it last week, and while it's not 1.0 yet I intend to get it user-ready so we can integrate it into a monorepo at work. It's based on Aspects, and I don't think is really that complicated. Have you looked at it? Feedback is welcome 🙂

**Comment by thundergolfer** [comment]
Update so say we've recently begun use of https://github.com/thundergolfer/bazel-mypy-integration at work. 

Dropbox has also recently open-sourced on Github a different approach to doing MyPy checks on Python code. 

So while these are not "built-in" ways of supporting MyPy I think they'll satisfy your needs.

**Comment by thundergolfer** [comment]
Closing as this project will for now just focus on the core language rules and packaging rules.
