### ISSUE TITLE
Creating runfiles tree takes forever on Linux

### ISSUE THREAD

**Issue by pvcnt** [bazelbuild/rules_python#280]
I have a small Bazel repository with a few tests rules (15), but all of them are pulling a quite large number of dependencies (think of Airflow). When running `bazel test //...`, the state remains stuck at "Creating runfiles tree bazel-out/k8-fastbuild/my/target/here.runfiles" for every test for a long time.

Interestingly, I do not observe this behaviour on macOS or on Jenkins (running on CentOS), but only on Ubuntu. It takes about 10 minutes to run those 15 tests on Ubuntu, as opposed to about 1 minute on CentOS or macOS (assuming dependencies have been fetched already). Does this problem ring a bell?

**Comment by henryqinshield** [comment]
We are also seeing some of this on our projects running on Ubuntu 18.04...any help would be appreciated.

**Comment by thekyz** [comment]
I know it's an old ticket but: bazel on centos and ubuntu use a different sandboxing strategy. Can you try adding `--strategy TestRunner=processwrapper-sandbox` to your `bazel test` call when running on the slow system?

**Comment by pvcnt** [comment]
I'm not using Ubuntu anymore at the moment, so unfortunately I won't be able to confirm. I will keep this in mind if this happens again, thank you!

**Comment by groodt** [comment]
Closing. If you run into this issue again, please provide version info of rules_python and a minimal reproduction if possible.

**Comment by mvukov** [comment]
I also observe a number of tests for which "Creating runfiles tree" action takes quite some time, 10s of seconds. This typically happens for test targets that have a lot of pip deps, some of them having quite a lot of files (e.g. pytorch). Setup: Bazel 5.2.0, rules_python 0.13, Ubuntu 20.04 OS (a CI machine).

**Comment by taekahn** [comment]
> I know it's an old ticket but: bazel on centos and ubuntu use a different sandboxing strategy. Can you try adding `--strategy TestRunner=processwrapper-sandbox` to your `bazel test` call when running on the slow system?

Did not seem to make a difference. Wait time was still several minutes per action.
