### ISSUE TITLE
Is there any support for running python library module? 

### ISSUE THREAD

**Issue by lriuui0x0** [bazelbuild/rules_python#282]
Any support for running python module `python -m <module_name>`?

**Comment by jonnyyu** [comment]
I have the same question. My project uses relative imports, so I need run it with '-m'

**Comment by thundergolfer** [comment]
`python -m <module_name>` is just finding a module on the PYTHONPATH and executing it's __main__. Python's CLI describes this as "run module as a script".

Bazel's `*_library` and `*_binary` rule type abstractions don't really support this kind of 'runnable module' idea. A `*_library` is a non-executable unit of library code and a `*_binary ` is an executable program. 

So within Bazel, any Python you want to run should become a `py_binary` target.


@jonnyyu If you have a Python project with relative imports, Bazel can support executing that project without the need of `-m`. See the `imports` attribute of the py_binary rule: https://docs.bazel.build/versions/master/be/python.html#py_binary.imports
