### ISSUE TITLE
GET returned 401 Unauthorized for rules_python

### ISSUE THREAD

**Issue by etsangsplk** [bazelbuild/rules_python#287]
Using under macox

I have my .netrc setup for github.com already
```machine github.com 
login username
password password
```
But still getting this. this is my 1st time using bazel, and i have no idea what is happening.
There does not seem to have an option to show what http command is being sent and the operations of bazel is quite opaque. I am sure is just some configurations problem but unsure what that is.

```WARNING: Download from https://github.com/bazelbuild/rules_python/archive/38f86fb55b698c51e8510c807489c9f4e047480e.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 401 Unauthorized
ERROR: An error occurred during the fetch of repository 'rules_python':
   java.io.IOException: Error downloading 
```

**Comment by thundergolfer** [comment]
Is the error you posted the full error? If not, can you post the full error.

**Comment by etsangsplk** [comment]
full error. It turned out it is personal token. github remove login and password for rest request.
