### ISSUE TITLE
python dependency is missing scripts from setup.py after building

### ISSUE THREAD

**Issue by marosmola** [bazelbuild/rules_python#288]
When i install ansible package trough dependencies i am not able to use its scripts from setup.py.
Is this problem with building application or should i somehow load all the scripts manually? 

WORKSPACE
```
pip_import(
   name = "my_deps",
   requirements = "//:requirements.txt",
)
load("@nts_deps//:requirements.bzl", "pip_install")
pip_install()
```
requirements.txt
```
ansible==2.5.5
```

scripts in ansible setup.py -https://github.com/ansible/ansible/blob/5f6e1a70a6f879146b8504244d1b43f2e2059856/setup.py#L275
```
scripts=[
    'bin/ansible',
    'bin/ansible-playbook',
    'bin/ansible-pull',
    'bin/ansible-doc',
    'bin/ansible-galaxy',
    'bin/ansible-console',
    'bin/ansible-connection',
    'bin/ansible-vault',
    'bin/ansible-config',
    'bin/ansible-inventory',
]
```

Error message when i run bazel:
```
Unable to find location of 'ansible-connection'
```

**Comment by thundergolfer** [comment]
This project doesn't support `console_scripts` in installed packages. AFAIK no alternative open-source package rules support it. There's some discussion linked in here https://github.com/dillon-giacoppo/rules_python_external/issues/18
