### ISSUE TITLE
Clarify ownership of rules_python

### ISSUE THREAD

**Issue by brandjon** [bazelbuild/rules_python#291]
Following up on #290, I've added @andyscott and @thundergolfer as maintainers of rules_python. We now need to define the boundaries between community-owned pieces of this repo and pieces owned by the core Bazel team.

+Cc @lberki and @laurentlb on core Bazel, and @pstradomski who is responsible for the wheel packaging rules under //experimental.

This repo currently serves two purposes: pip integration rules written purely in Starlark, and Starlark stubs for the native Python rules. Our intent is that the community take ownership of the pip integration rules (e.g., `python/pip.bzl`, `python/wheel.bzl`, `packaging/...`, `tools/...`) while core Bazel team retains ownership of the stubs (`python/defs.bzl`, subdirectories of `python/`). For repo-global things like the WORKSPACE I think the chance of stepping on each other's toes is low so I'm not worried about explicit ownership delineations there.

Action items are to spell out this division in a little more detail (expand on #290) and add CODEOWNERS. Beyond that, Andy and Jonathan should discuss how they'd like to evolve the packaging rules -- e.g. whether to merge with an existing alternative ruleset, vs preserving the existing API.

**Comment by brandjon** [comment]
One minor note @andyscott and @thundergolfer: When you merge PRs affecting `piptool,py` and `whl.py`, please regenerate the par files under `tools/` yourself as mentioned in [CONTRIBUTING.md](https://github.com/bazelbuild/rules_python/blob/a0fbf98d4e3a232144df4d0d80b577c7a693b570/CONTRIBUTING.md#generated-files)

**Comment by andyscott** [comment]
Sounds good. Thanks for adding me.

I'm currently quite busy but should be able to make time in the next week (or two) to review/discuss.

**Comment by thundergolfer** [comment]
Thanks @brandjon, looking forward to working on this with the community. Also thanks for clarification on ownership, makes sense.

> Beyond that, Andy and Jonathan should discuss how they'd like to evolve the packaging rules -- e.g. whether to merge with an existing alternative ruleset, vs preserving the existing API.

Yeah plenty to discuss here.

**Comment by abergmeier** [comment]
> Following up on #290, I've added @andyscott and @thundergolfer as maintainers of rules_python.

Is there anyone with maintainer access who has time for the role? Looking at the Issues, PRs, Design Documents it seems to me like there is so far nobody visible.

**Comment by thundergolfer** [comment]
Hey @abergmeier, 

The ball started rolling on this ownership change while Andy and I are quite busy, but expect movement soon after we've had time to do some initial orientation. We have a meeting planned for Thursday. 🙂

**Comment by abergmeier** [comment]
> We have a meeting planned for Thursday

Mind if I listen?

**Comment by thundergolfer** [comment]
Much of it will be Andy and I talking about how we'll coordinate. I think it won't be appropriate to have this opened up, but anything relevant to the community will be shared. We haven't talked about how we'll do the sharing, but right now the Slack is the place of most discussion.

**Comment by andyscott** [comment]
It's also our very first meeting, so we'll likely be spending some time to understand each other's perspective and sorting how how we'll work together to support the project!

Practically speaking, in this first call I don't expect to address specific issues/PRs open on the project. Instead, I hope we lay some groundwork for how we'll be maintaining the project going forward.

**Comment by andyscott** [comment]
Jonathon and I just finished our call. We mostly discussed the current state of affairs with rules_python and how we can begin to maintain the rules.

Next week we are meeting again to:
- Draft requests to the rules_python community. These are meant to foster discussion and help shape the future of the rules. We'll be posting these as Github issues.
- Draft a rule governance doc to be committed to the repository. This will show up as a pull request or as an issue with links to a Google doc.

We'll be back again next week with another update.

**Comment by laurentlb** [comment]
I've promoted @andyscott and @thundergolfer to admins so that they can give maintain/write roles to other people. At the same time, I've changed the role of Bazel team (~50 people) from write to triage.

There are probably other changes to do, but I'll let the new owners decide.
