### ISSUE TITLE
Documentation: pip3_import not supported by released version of rules_python

### ISSUE THREAD

**Issue by chrisfenner** [bazelbuild/rules_python#292]
Can the documentation be updated to note near https://github.com/bazelbuild/rules_python#importing-pip-dependencies that the 0.0.1 release doesn't support pip3_import rules?

**Comment by thundergolfer** [comment]
Hmm yes, seems like another release is due. The `README` does say "To depend on a particular unreleased version (not recommended)" but then describes features like `pip3_import` that aren't present in any release.

**Comment by thundergolfer** [comment]
Release `0.0.2` is out now 🙂. `pip3_import` is now supported by latest release. 

Thanks for reporting the issue, will close it now.
