### ISSUE TITLE
Ship a repo rule to fetch a hermetic Python interpreter and generate a py_runtime / toolchain for it

### ISSUE THREAD

**Issue by brandjon** [bazelbuild/rules_python#293]
Tracking issue for the feature request proposed [here](https://github.com/bazelbuild/bazel/issues/4815#issuecomment-464419291).

**Comment by brandjon** [comment]
See also bazelbuild/bazel#8265, which can be reopened in this repo.

**Comment by ddlees** [comment]
@brandjon I've been posting to GH Issues like this w/ a tiny project I put together that might fill the gap here. It should help some people at least while there isn't a native solution in bazel or in these rules. Anyway, I hope you guys have time to take a gander and provide some feedback if you think it's warranted. Cheers!

https://github.com/digital-plumbers-union/rules_pyenv

**Comment by brandjon** [comment]
Thanks for the contribution! I'll leave a decision on the approach for this issue to the new maintainers, @thundergolfer and @andyscott.

**Comment by thundergolfer** [comment]
@f0rmiga let's organize in this issue. 

👀  also say this recent issue comment: https://github.com/bazelbuild/rules_python/issues/42#issuecomment-1001222292

**Comment by f0rmiga** [comment]
@thundergolfer Take a look at https://github.com/bazelbuild/rules_python/pull/618.
