### ISSUE TITLE
Tests for transitions

### ISSUE THREAD

**Issue by abergmeier** [bazelbuild/rules_python#297]
If we ever want to move transitions, we need tests to validate, that implementation is not regressing between Java und Starlark.

**Comment by brandjon** [comment]
I'm not clear exactly what the request is. Is it just to have test coverage to ensure that Python 2 / 3 targets behave as expected? We have coverage for this in the Bazel tests (Java code), and any migration work would have to create corresponding not-in-Bazel tests (either shell integration or Starlark).

Migration of the Python rules to Starlark will be owned by the Bazel Rules subteam. I'm not sure what the prioritization of that is. I don't think we need tracking bugs for the individual items to be ported (at least, not yet).

FYI, it's possible to implement a kind of Python version transition in Starlark code using Starlark-defined transitions, but it's not quite the same as the native one; Starlark-defined transitions mess with the output root by appending a hash of the configuration.

**Comment by brandjon** [comment]
Sorry if it wasn't clear -- the recent transfer of maintainership of this repo refers to the pip-integration part of the rules. The native rules in Bazel, and their stubs here, are still owned by the core Bazel team.
