### ISSUE TITLE
Support environment markers

### ISSUE THREAD

**Issue by drigz** [bazelbuild/rules_python#30]
From [PEP 508](https://www.python.org/dev/peps/pep-0508/#id23):

> Environment markers allow a dependency specification to provide a rule that describes when the dependency should be used.

PEP 508 also describes the syntax of environment markers.

For example, here is subset of the `metadata.json` for google-cloud-core==0.27.0:

```
  "run_requires": [
    {
      "requires": [
        "google-auth (>=0.4.0,<2.0.0dev)",
        "googleapis-common-protos (>=1.3.4)",
        "protobuf (>=3.0.0)",
        "requests (<3.0.0dev,>=2.18.0)",
        "setuptools (>=34.0.0)",
        "six"
      ]
    },
    {
      "environment": "python_version<\"3.2\"",
      "requires": [
        "futures (>=3.0.0)"
      ]
    }
  ],
```

For Python 2.7, rules_python should install the `futures` package.

You can work around this by manually declaring the dependency on `futures` in WORKSPACE and BUILD.

**Comment by duggelz** [comment]
We would need something like a `py_toolchain` target in Bazel so that it actually knows what version of Python it's invoking.  See [py_toolchain draft proposal](https://docs.google.com/document/d/1dQjbbLEJqxUIJWmH5sIZAv-_emnKksDI-VCG1v86dWA/edit#heading=h.i1dkz9bbvubm)
