### ISSUE TITLE
Can there be a simpler project example? 

### ISSUE THREAD

**Issue by oconnore** [bazelbuild/rules_python#301]
I'm trying to copy+paste from the setup instructions to get a working hello world app, and this isn't working for me. 

How does `internal_deps.bzl` relate to the examples in `/examples/hello_world/...`? 

https://github.com/bazelbuild/rules_python/blob/a0fbf98d4e3a232144df4d0d80b577c7a693b570/internal_deps.bzl#L33-L50

Also, where does requirements.bzl come from when there's no `requirements.bzl` file in the whole project? 

https://github.com/bazelbuild/rules_python/blob/a0fbf98d4e3a232144df4d0d80b577c7a693b570/examples/helloworld/BUILD#L15

https://github.com/bazelbuild/rules_python/search?q=requirements.bzl&unscoped_q=requirements.bzl

**Comment by oconnore** [comment]
I was able to get this working, but I'll leave this open since it was rather still rather painful. Here's my hello world:

Project: [hello_world.zip](https://github.com/bazelbuild/rules_python/files/4566968/hello_world.zip)

Workspace:
```
# SNIP *********

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
http_archive(
    name = "rules_python",
    url = "https://github.com/bazelbuild/rules_python/releases/download/0.0.1/rules_python-0.0.1.tar.gz",
    sha256 = "aa96a691d3a8177f3215b14b0edc9641787abaaa30363a080165d06ab65e1161",
)
load("@rules_python//python:repositories.bzl", "py_repositories")
py_repositories()
load("@rules_python//python:pip.bzl", "pip_repositories")
pip_repositories()

# Define Deps
load("@rules_python//python:pip.bzl", "pip_import")
pip_import(
   name = "analytics_dependencies",
   requirements = "//sql_monitor:requirements.txt",
)
# Load Analytics Deps
load("@analytics_dependencies//:requirements.bzl", "pip_install")
pip_install()
```

**Comment by thundergolfer** [comment]
Thanks for the feedback. I haven't tried the example myself, but you'd hope running it was a simple matter of copying the folder out of the repo and running it. I'll check it out.

**Comment by oconnore** [comment]
If Bazel just searches for the next closest workspace file up the file tree, then the examples could perhaps stay in this repository as independent projects from the rule implementation?

**Comment by thundergolfer** [comment]
Yeah we can have a separate `WORKSPACE` inside `examples/` and use a `.bazelignore` in the root to ensure the inner workspace doesn't interfere with the main rules workspace. Basically what's done [here](https://github.com/thundergolfer/bazel-mypy-integration/tree/master/examples).

**Comment by thundergolfer** [comment]
> Also, where does requirements.bzl come from when there's no requirements.bzl file in the whole project?

Didn't realise I could've answered this question. `requirements.bzl` is generated by executing the `pip_import` repository rule. That file will exist inside your [Bazel output directory space](https://docs.bazel.build/versions/master/output_directories.html#layout-diagram)

**Comment by thundergolfer** [comment]
rules_python now provides simpler, self-contained examples 🙂. Eg. https://github.com/bazelbuild/rules_python/tree/bc256eff477eb08045f13bea58213672efb25d4e/examples
