### ISSUE TITLE
Multi-platform solution for python single executables

### ISSUE THREAD

**Issue by sitaktif** [bazelbuild/rules_python#310]
Bazel currently has good support for creating single executable python binary outputs (e.g python zip and previously, par), however these formats don't support producing a single file that is compatible with multiple platforms (e.g. Linux and MacOS) when dependencies include platform-specific dependencies.

Some solutions exist for this problem (e.g. the pex format supports that use case by including all the various wheels in the output file and doing some magic with sys.path at runtime) but no such thing is currently supported by `rules_python`.

It would be great to have a solution to support the multi-platform case for python binaries.

**Comment by njlr** [comment]
Perhaps this should be reopened?

 - Google subpar is now archived
 - Existing PEX rules seem to be abandoned

**Comment by aignas** [comment]
This should be implemented as a separate ruleset if needed, keeping rules_python small and focused.

**Comment by njlr** [comment]
Understood. It looks like [progress is being made](https://github.com/aspect-build/rules_py/pull/324) on PEX for `rules_py`.
