### ISSUE TITLE
Can you clarify why the releases are pre-release.

### ISSUE THREAD

**Issue by aiuto** [bazelbuild/rules_python#314]
Are they pre-release because they will be finalized, or because they are 0.x?
To put it a different way, can I take a dependency on the 0.0.2, wait a few days/weeks, or should I continue to point to git commits?

**Comment by thundergolfer** [comment]
I didn't make the first release pre-release, but I continued with the pre-release marker for `0.0.2` and can try answer your question. 

> or because they are 0.x?

This is the reason I think. This project is subtitled as "experimental" and ships packaging rules which aren't stable or ready for `1.x.x`. 

> To put it a different way, can I take a dependency on the 0.0.2, wait a few days/weeks, or should I continue to point to git commits?

Would need more context on what the trade-offs are. I don't think waiting a few days/weeks will change much, right now the release cadence is infrequent. 

Pinning to git commits works fine, but doesn't bring the meaning of semantic versioning (so you can't easily know if a subsequent commit is a breaking change).

**Comment by aiuto** [comment]
OK. I understand now. I think
- releases are 0.0.x because that is the state of the world. Fine with that
- you stamp it pre-release for historical inertia. But it is really a real release, just at the 0.x level.
- we both do not like pinning to commits. 

That answers the question for me.
