### ISSUE TITLE
cannot import debugpy

### ISSUE THREAD

**Issue by jonnyyu** [bazelbuild/rules_python#322]
I'm trying to use [debugpy](https://github.com/microsoft/debugpy) in my bazel python project. But I found I cannot import debugpy after adding it to requirements. 

Here's a simplified repro case: https://github.com/jonnyyu/debugpy_test

It seems debugpy's package is a bit different from normal package, 

![image](https://user-images.githubusercontent.com/2011471/84227828-fae30180-ab17-11ea-8fa3-02398fd0368c.png)

However, pip installs it correctly.
![image](https://user-images.githubusercontent.com/2011471/84227904-341b7180-ab18-11ea-96f2-6bda67d9bcd8.png)

any idea how to get it working in Bazel? Thanks!

**Comment by thundergolfer** [comment]
@jonnyyu Looks like this package could be 'purelib'. There's existing issue on this project concerning other 'purelib' packages that don't work (eg. tensorflow). 

> any idea how to get it working in Bazel?

https://github.com/dillon-giacoppo/rules_python_external is an alternative packaging solution that has support for purelib/platlib. I'd expect `debugpy` to work using it, but I haven't tested myself. It should be easy to test though, as the project's API is very similar to `rules_python`.

**Comment by jonnyyu** [comment]
@thundergolfer Thanks! I'll try it.

**Comment by thundergolfer** [comment]
@jonnyyu are you able to leave a comment in here as to whether `rules_python_external` solved your problem? It would be useful to confirm.

**Comment by jonnyyu** [comment]
sorry for late reply. yes! `rules_python_external` solves my problem!

**Comment by thundergolfer** [comment]
Thanks. Will now close this issue as duplicated by the other issues concerning this 'purelib' incompatibility.
