### ISSUE TITLE
How to test if all the dependencies are fetched?

### ISSUE THREAD

**Issue by sophieball** [bazelbuild/rules_python#325]
Is there a way to write a script to test if all my dependencies listed in `requirements.txt` are fetched? (Or, is it necessary?)

**Comment by thundergolfer** [comment]
It shouldn't be necessary. That would amount to testing the correctness of a third-party program.

Are you experiencing some issue with the package fetching that motivates such a test?

**Comment by sophieball** [comment]
(Didn't meant to mention this issue in my PR.. I pasted the wrong link there)

I think the motivation is that we didn't want to wait until we run the program to know that some dependencies are missing.
