### ISSUE TITLE
package rules should create wrappers around tool entry_points

### ISSUE THREAD

**Issue by alexeagle** [bazelbuild/rules_python#341]
This feature is inspired by how we handle the ecosystem of tools in rules_nodejs.

For a long time we assumed we needed to write custom rules for each tool in the ecosystem. The last one of these was for the Less CSS preprocessor. Then we realized that since we have Starlark code generating BUILD files to dep on each installed package (via `pip_install` for example, but will apply for poetry or others), we could also generate .bzl files to call tools. Now every tool in npm ecosystem can be called from Bazel (I [wrote more about it](https://dev.to/bazel/layering-in-bazel-for-web-389h) )

For example if I `pip_install` the package `Sphinx==3.1.1` then today I can `load("@my_deps//:requirements.bzl", "requirement")` and dep on `requirement("sphinx")` - but loading sphinx as a dep is not the common way to use it. It's a utility for generating documentation so it should be called as a separate action, without me writing a custom program to drive it.

This is evident from the package metadata
```
% less $HOME/.pyenv/versions/3.6.5/lib/python3.6/site-packages/Sphinx-3.1.1.dist-info/entry_points.txt
[console_scripts]
sphinx-build = sphinx.cmd.build:main
```
 
So users actually want to do something like this:

```
load("@my_deps//sphinx:defs.bzl", "sphinx_build")

sphinx_build(
    name = "docgen",
    srcs = glob(["docs/**"]),
    args = ["-b", "html", "$(@D)"],
    outdir = "html",
)
```

Similarly it should be possible to grab a server from pypi and `bazel run` it, or a testing framework and `bazel test` it. So in rules_nodejs we actually generate three things in the generated `.bzl` for any package that exposes entry points.

**Comment by thundergolfer** [comment]
https://github.com/bazelbuild/rules_python/issues/318
https://github.com/bazelbuild/rules_python/issues/288

also

https://github.com/dillon-giacoppo/rules_python_external/issues/18

**Comment by alexeagle** [comment]
This golden file from one of our tests illustrates the three things:
https://github.com/bazelbuild/rules_nodejs/blob/1.x/internal/npm_install/test/golden/jasmine/index.bzl.golden
yes we always generate them because there's nothing in the metadata of an npm package that tells you whether a binary is meant to produce outputs, be a long-running process, or be a test runner. So we just adapt the behavior based on how the user names/uses the loaded symbol.

**Comment by UebelAndre** [comment]
Would this mean the entry points would be represented by `py_binary` targets? 🙏

**Comment by UebelAndre** [comment]
Anyone have any new thoughts on this one? I feel like it'd solve for a sizable gap in functionality and unlock many workflows.

**Comment by UebelAndre** [comment]
I ended up writing a rule which solves for my specific use case. Hopefully others can find it useful or become inspired to adapt it to something worth merging 😄 

https://github.com/UebelAndre/bazel_pip_entrypoint

**Comment by alexeagle** [comment]
Note, this was solved for the `bazel run` case by #523 which adds a generated `py_binary` for every bin.

We still need the `bazel test` and `bazel build` cases to be contributed, where a py_test and genrule target are generated, respectively.

**Comment by aignas** [comment]
Note, that for using a tool in a `py_test` fashion one could do something similar to:
```starlark
load("@rules_python//python:defs.bzl", "py_test")
load("@rules_python//python/entry_points:py_console_script_binary.bzl", "py_console_script_binary")

py_library(
    name = "extra_tool_deps",
    srcs = glob(["*.py"]),
)

py_console_script_binary(
    name = "tool_test",
    args = ["args to the behave tool"],
    binary_rule = py_test,
    data = glob("extra_files/*"),
    pkg = "@pypi//tool",
    script = "tool",
    deps = [":extra_tool_deps"],
)
```

In my particular case, the `tool` was `behave` and this recipe worked a treat,
however, for something like `py_test` this may be insufficient, because you may
want to add extra integration with how bazel parameters are translated to
`py_test` parameters and `py_console_script_binary` might not have the
sufficient arguments to make it possible. Being able to provide a custom
template to the `py_console_script_binary` would be probably a sufficient
change to accommodate those usecases.

cc: @groodt as we discussed the question:
> Is it possible to do something like this today?

**Comment by groodt** [comment]
Oh nice. I didnt think about using hinary_rule.

**Comment by groodt** [comment]
Closing. [py_console_script_binary](py_console_script_binary) was introduced a while ago now to facilitate the creation of  `console_scripts` with bazel.

**Comment by alexeagle** [comment]
That works okay for run, but not build or test. The feature gap is still here, but it's okay with me if you don't want to add more

**Comment by aignas** [comment]
I think with bazel skylib's run_binary and native_test rules it is possible to cover the cases for bazel build and bazel test when using py_console_script_binary.

Am I missing anything?

Having package specific rules without eager fetching is something tricky to have if the information about the scripts is not present in the lock file, and for now python's ecosystem stores the script information inside the wheel, hence we think its for the best for now to ask the user to use bazel skylib to achieve run, build, test using a specific tool.

**Comment by alexeagle** [comment]
Yes for rules_js we have the same constraint about info in the lock file so we always generate all three symbols for each bin.

**Comment by aignas** [comment]
Could you explain about what you mean about each bin? Is it the case that each npm package provides only a single binary? I am not sure we can assume anything about python wheels here other than download the wheel and inspect the contents.
