### ISSUE TITLE
Project deploys to GH Pages but is 404

### ISSUE THREAD

**Issue by alexeagle** [bazelbuild/rules_python#343]
Something is up with docs publishing?
https://github.com/bazelbuild/rules_python/deployments says that every commit results in publishing a docsite, but

https://bazelbuild.github.io/rules_python/ is a 404

**Comment by thundergolfer** [comment]
Missing `index.html` I think. https://github.com/bazelbuild/rules_python/pull/469 👈

**Comment by alexeagle** [comment]
we turned off GH pages instead
