### ISSUE TITLE
Attribute 'timeout' in 'pip_import' rule not found

### ISSUE THREAD

**Issue by leopetter** [bazelbuild/rules_python#346]
# 🐞 bug report 

### Affected Rule
The issue is caused by the rule: pip_import

### Description
The attribute 'timeout' in the 'pip_import' rule is supposedly non-existent.  

## 🌏  Environment
I use the latest release: rules_python-0.0.2, bazel version 3.4.1 and I am working on macOS Catalina (10.15.5).

## 🔥 Exception or Error
The exact error message is "ERROR: /Users/<...>: //external:common_service_deps: no such attribute 'timeout' in 'pip_import' rule". 
The attribute should be merged with #217 and is available in the current version.

Below is the specified rule in the WORKSPACE file of my project: 
<pre><code>
http_archive(
    name = "rules_python",
    url = "https://github.com/bazelbuild/rules_python/releases/download/0.0.2/rules_python-0.0.2.tar.gz",
    strip_prefix = "rules_python-0.0.2",
    sha256 = "b5668cde8bb6e3515057ef465a35ad712214962f0b3a314e551204266c7be90c",
)

load("@rules_python//python:repositories.bzl", "py_repositories")

py_repositories()

load("@rules_python//python:pip.bzl", "pip_repositories", "pip3_import", "pip_import")

pip_repositories()

pip3_import(
    name = "common_service_deps",
    requirements = "//backend/services:common-requirements.txt",
    timeout = 1200,
)
</code></pre>

Does anyone have the same issue and knows how to fix it?

**Comment by keith** [comment]
Is this your entire WORKSPACE file? If there are any other repos setup above this in your WORKSPACE bazel could silently be pulling in an older version of rules_python, which could lead to this. If that's the case you should be able to fix by moving rules_python's http-archive to the top of your WORKSPACE (we hit this case with some other rules repos conflicting)

**Comment by leopetter** [comment]
It worked, thank you.
