### ISSUE TITLE
piptool and whltool bundle pip 9.0.3, which is so old it breaks modern packages

### ISSUE THREAD

**Issue by crutcher** [bazelbuild/rules_python#355]
# 🐞 bug report

### Affected Rule

`pip_import` (and presumably others) bundle `pip==9.0.3`

### Description

`piptool` bundling such an old version of `pip` breaks some newer packages; and alters which repository that will be scanned, and how.

Specifically, `tensorflow==2.3.0` cannot be installed for python3.

## 🔬 Minimal Reproduction

Here's an example repo constructed to show the problem:
https://github.com/crutcher/bazel-pip-tensorflow-lookup-error

## 🌍  Your Environment

**Operating System:**

<pre>
<code>
  (ve) $ cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.5 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
(ve) $ bazel --version
bazel 3.3.1
  </code>
</pre>

**Rules_python version:**

<pre>
  <code>
Head (see attached workspace)
  </code>
</pre>

**Comment by crutcher** [comment]
I checked the bundled version by downloading and un-packing `piptool`.

**Comment by thundergolfer** [comment]
@crutcher would recommend not using `pip_import` with modern packages and instead using `pip_install` or (the newer but less mature) `pip_parse`.
