### ISSUE TITLE
Possible to refer to default runtime?

### ISSUE THREAD

**Issue by cwaeland** [bazelbuild/rules_python#357]
Hi,

I've been working on creating my own toolchain in order to avoid using the system version of Python 3.  However, my organization still has some internal python 2 targets that are still in use.  Rather than going to the trouble of configuring a runtime for Python 2 I was hoping to simply refer to the default `rules_python` runtime in my `py_runtime_pair`.  Is this possible?

Thanks!

**Comment by thundergolfer** [comment]
It's possible, but not elegant. 

Because a in an in-build `py_runtime` the ...

> "interpreter" means any executable binary or wrapper script that is capable of running a Python script passed on the command line

For Python 2 you can create a non-hermetic executable that looks up the location of the `python2` interpreter and simply delegates to it.

**Comment by thundergolfer** [comment]
👋  @cwaeland can I close this as answered, or should there be further investigation, discussion, or action items?

**Comment by cwaeland** [comment]
@thundergolfer yep this definitely helps! Sorry for not getting back to you.

**Comment by thundergolfer** [comment]
No worries at all. Closing 👍
