### ISSUE TITLE
A pylint rule and an example on how to use the rule

### ISSUE THREAD

**Issue by gae123** [bazelbuild/rules_python#360]
I am trying to figure out how to integrate pylint in my project. I saw [this thread](https://stackoverflow.com/questions/47303847/best-way-to-configure-pylint-with-bazel) in SO but this seems more of a workaround.

**Comment by mfarrugi** [comment]
That thread is the crux of how you would fix this. 

The next step would be to either:
-  implement a macro that automatically create pylint targets, eg. writing a `python_library` macros that also emits the linting targets. 
- implement a rule that takes a py_library as an argument and runs the lints.

Dropbox has an implementation for mypy in the latter style @ https://github.com/dropbox/dbx_build_tools/blob/master/build_tools/py/mypy.bzl#L1-L18

**Comment by thundergolfer** [comment]
Apple has recently open-sourced their approach to linting across Bazel workspaces. There's an example of it in the Selenium codebases

**Their rules:** https://github.com/apple/apple_rules_lint
**An example linter rule:** https://github.com/SeleniumHQ/selenium/blob/9108b707376a29d57b43bb589eec11bda280e025/java/private/spotbugs.bzl#L68
**Configuring that linter:** https://github.com/SeleniumHQ/selenium/blob/trunk/WORKSPACE#L27

**Comment by mfarrugi** [comment]
And for the sake of completeness, an example of the aspect approach is [rules_rust's implementation of clippy]( https://github.com/bazelbuild/rules_rust/blob/afee872f08ed67b53caab2e1d2fefd501dce81f4/rust/private/clippy.bzl#L122-L125)
