### ISSUE TITLE
Python 3: Dependency with cffi-generated interface can't be imported

### ISSUE THREAD

**Issue by hwright** [bazelbuild/rules_python#37]
Using this [sample repository](https://github.com/bazelbuild/rules_python/files/1467459/bcrypt-test.tar.gz):

```
$ bazel test :bcrypt_test 
..........................................................
INFO: Found 1 test target...
FAIL: //:bcrypt_test (see /private/var/tmp/_bazel_hwright/a6f0babcfe493d859400aa369b17eeeb/execroot/foo/bazel-out/darwin_x86_64-py3-fastbuild/testlogs/bcrypt_test/test.log).
INFO: From Testing //:bcrypt_test:
==================== Test output for //:bcrypt_test:
Traceback (most recent call last):
  File "/private/var/tmp/_bazel_hwright/a6f0babcfe493d859400aa369b17eeeb/bazel-sandbox/9102214513008705191/execroot/foo/bazel-out/darwin_x86_64-py3-fastbuild/bin/bcrypt_test.runfiles/foo/bcrypt_test.py", line 4, in <module>
    import bcrypt
  File "/private/var/tmp/_bazel_hwright/a6f0babcfe493d859400aa369b17eeeb/bazel-sandbox/9102214513008705191/execroot/foo/bazel-out/darwin_x86_64-py3-fastbuild/bin/bcrypt_test.runfiles/pypi__bcrypt_3_1_4/bcrypt/__init__.py", line 25, in <module>
    from bcrypt import _bcrypt
ImportError: dlopen(/private/var/tmp/_bazel_hwright/a6f0babcfe493d859400aa369b17eeeb/bazel-sandbox/9102214513008705191/execroot/foo/bazel-out/darwin_x86_64-py3-fastbuild/bin/bcrypt_test.runfiles/pypi__bcrypt_3_1_4/bcrypt/_bcrypt.so, 2): Symbol not found: _PyInt_FromLong
  Referenced from: /private/var/tmp/_bazel_hwright/a6f0babcfe493d859400aa369b17eeeb/bazel-sandbox/9102214513008705191/execroot/foo/bazel-out/darwin_x86_64-py3-fastbuild/bin/bcrypt_test.runfiles/pypi__bcrypt_3_1_4/bcrypt/_bcrypt.so
  Expected in: flat namespace
 in /private/var/tmp/_bazel_hwright/a6f0babcfe493d859400aa369b17eeeb/bazel-sandbox/9102214513008705191/execroot/foo/bazel-out/darwin_x86_64-py3-fastbuild/bin/bcrypt_test.runfiles/pypi__bcrypt_3_1_4/bcrypt/_bcrypt.so
================================================================================
Target //:bcrypt_test up-to-date:
  bazel-bin/bcrypt_test
INFO: Elapsed time: 16.377s, Critical Path: 0.37s
//:bcrypt_test                                                           FAILED in 0.3s
  /private/var/tmp/_bazel_hwright/a6f0babcfe493d859400aa369b17eeeb/execroot/foo/bazel-out/darwin_x86_64-py3-fastbuild/testlogs/bcrypt_test/test.log

Executed 1 out of 1 test: 1 fails locally.
```

I'm not sure if this specific to `bcrypt`, or more general (hence the issue description).  Since this works under python 2, and the module API changed between them, I wonder if this is part of the same underlying problem as #33.  Because we're running the import tooling inside of Bazel under python2, the wrong package gets pulled from pypi, and hence doesn't work with python 3.

If it is the same as #33, feel free to de-dupe (and make of of these a more general "python 3" issue).

**Comment by hwright** [comment]
I've taken a brief look at this, and am recording my thoughts for posterity (and correction).

As stated above, the problem here is that we're running the import tooling under python 2, when we really should be running it under whatever runtime is specified by the `--python_top` flag or whatever other mechanisms Bazel gives for specifying which python interpreter to use.  In this line, we unconditionally use `python` to execute the `pipimport` tooling:
https://github.com/bazelbuild/rules_python/blob/d6fbb0fb2a5c8e318dd4de5104dc41358cefaa90/python/pip.bzl#L27

When I change the `python` in that line to `python3`, everything works as expected with a python 3 runtime, since it is now executing `pip wheel` under a python 3 environment.

The next step is to determine if we can conditionally set the executable string in the above line based upon the user's configuration.  As usual, I'm mostly flailing around in the dark here, and would appreciate whatever pointers folks may have. :)

**Comment by hwright** [comment]
I started working on making the required changes to Bazel itself, but quickly got lost in the weeds. 
 Relevant mailing list thread: https://groups.google.com/d/msg/bazel-dev/48vLC_2VAro/a6pG7wwPAQAJ

**Comment by mattmoor** [comment]
@hwright [Here's](https://github.com/bazelbuild/rules_docker/blob/master/container/pull.bzl#L21-L32) what I'm doing in `rules_docker`, which was born of Windows-compatibility, but enables users to override what we use here.

**Comment by treuherz** [comment]
The problem here seems more general than the title implies. Can we re-title this something more like #59 to make it easier to find?

**Comment by adamcharnock** [comment]
I would love to see a resolution to this. I've tried every workaround I've come across but have yet to find even a temporary solution (disclaimer: I'm new to bazel). Right now the `enum34` package gets installed and breaks my projects build, resulting in:

```
AttributeError: module 'enum' has no attribute 'IntFlag'
```

I've been trying the following as an attempt at a workaround but it seems to have no effect:

```
bazel run --action_env=PATH=/Users/adam/.pyenv/versions/3.6.3/bin //src/python/foo/bar:bar
```

**Comment by darrengarvey** [comment]
FWIW I'm using [this hack/fix](https://github.com/darrengarvey/rules_python/commit/1d5a456b9c3f6b4926e15858596386d7f41e21b1) which does work. Then you pass `--action_env=BAZEL_PYTHON=python3` to bazel and it'll work.

This is the same approach that rules_docker uses, although it is clearly incomplete as `--python_top` should be respected like @hwright was trying to get adopted into bazel.

**Comment by raliste** [comment]
Any updates?

**Comment by tmc** [comment]
This issue makes using bazel today feel premature.

**Comment by tmc** [comment]
@darrengarvey any reason to not open a PR?

**Comment by dgrnbrg** [comment]
I am also forced to use @darrengarvey's fix, because this is a fundamentally critical feature--being able to build CFFI code with python3.

**Comment by alschult-saildrone** [comment]
Hey, any chance this bug is going to get some attention? I'm also forced to use the fix above, which is OK, but causes issues if you switch between py2 and py3 since it will not cause the pips to be re-downloaded.  A true fix for this really is necessary if you want to use the dependency system at all.

**Comment by brandjon** [comment]
It seems there's two issues in this thread:

1. We end up confusing PY2 and PY3 during the evaluation of `pip_import`.

2. There's currently no good way to enforce that the same Python interpreter is used for `pip_import` as is used to run a `py_binary`.

I'm dedupping the first problem against #249 (also #33). For the second problem, I forked #257 to track discussion.
