### ISSUE TITLE
bazel_skylib dependency leaks into distro

### ISSUE THREAD

**Issue by alexeagle** [bazelbuild/rules_python#372]
expanding rules_python-0.1.0.tar.gz we see that /python/pip_install/BUILD has a load statement from `@bazel_skylib`.

Users weren't told to depend on that, nor did our WORKSPACE dependencies install such a thing.
Moreover until the new Bazel external deps story is landed, adding such a dependency is a nasty breaking change for users where they may have a hard time getting the right version of bazel_skylib to satisfy rules_python along with anything else that transitively depends on it.

I suggest we make this a development dependency (like we do in rules_nodejs) so that the `load` statement doesn't appear in our distro and we can continue to have zero dependencies, as (IMO) a core rule should.

**Comment by thundergolfer** [comment]
Nice catch. Agree with your suggestion, which we could ship as `0.1.1`.

**Comment by alexeagle** [comment]
fixed in https://github.com/bazelbuild/rules_python/releases/tag/0.2.0
