### ISSUE TITLE
Import module fail, example : 'google.auth'

### ISSUE THREAD

**Issue by vincent-herlemont** [bazelbuild/rules_python#383]
# 🐞 bug report

### Affected Rule

`py_binary` or `py_test`

### Description

The error append when we use some external module like 'google.auth'

## 🔬 Minimal Reproduction

./WORKSPACE
```
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
http_archive(
    name = "rules_python",
    url = "https://github.com/bazelbuild/rules_python/releases/download/0.1.0/rules_python-0.1.0.tar.gz",
    sha256 = "b6d46438523a3ec0f3cead544190ee13223a52f6a6765a29eae7b7cc24cc83a0",
)

load("@rules_python//python:pip.bzl", "pip_install")
pip_install(
   name = "pip_deps",
   requirements = "//test:requirements.txt",
)
```

./test/BUILD.bazel
```
load("@rules_python//python:defs.bzl", "py_binary")
load("@pip_deps//:requirements.bzl", "requirement")

py_binary(
    name = "test",
    srcs = ["test.py"],
    main = "test.py",
    deps = [
        requirement("google-auth"),
    ],
)
```
./test/requirements.txt
```
google-auth==1.18.0
````

./test/test.py
```
import sys
print(sys.path)
import google.auth
```

## 🔥 Exception or Error

<pre><code>
INFO: Analyzed target //integration_test:test (8 packages loaded, 415 targets configured).
INFO: Found 1 target...
Target //integration_test:test up-to-date:
  bazel-bin/integration_test/test
INFO: Elapsed time: 0.687s, Critical Path: 0.12s
INFO: 4 processes: 4 internal.
INFO: Build completed successfully, 4 total actions
INFO: Build completed successfully, 4 total actions
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
Executing tests from //integration_test:test
-----------------------------------------------------------------------------
[
'/home/vincent/work/pipeline-demo/integration_test', 
'/home/vincent/.cache/bazel/_bazel_vincent/55e31083404cf40043d2810f68eeadac/execroot/pipeline_demo/bazel-out/k8-fastbuild/bin/integration_test/test.runfiles', 
'/home/vincent/.cache/bazel/_bazel_vincent/55e31083404cf40043d2810f68eeadac/execroot/pipeline_demo/bazel-out/k8-fastbuild/bin/integration_test/test.runfiles/pip_deps/pypi__cachetools', 
'/home/vincent/.cache/bazel/_bazel_vincent/55e31083404cf40043d2810f68eeadac/execroot/pipeline_demo/bazel-out/k8-fastbuild/bin/integration_test/test.runfiles/pip_deps/pypi__pyasn1', 
'/home/vincent/.cache/bazel/_bazel_vincent/55e31083404cf40043d2810f68eeadac/execroot/pipeline_demo/bazel-out/k8-fastbuild/bin/integration_test/test.runfiles/pip_deps/pypi__pyasn1_modules', 
'/home/vincent/.cache/bazel/_bazel_vincent/55e31083404cf40043d2810f68eeadac/execroot/pipeline_demo/bazel-out/k8-fastbuild/bin/integration_test/test.runfiles/pip_deps/pypi__rsa', 
'/home/vincent/.cache/bazel/_bazel_vincent/55e31083404cf40043d2810f68eeadac/execroot/pipeline_demo/bazel-out/k8-fastbuild/bin/integration_test/test.runfiles/pip_deps/pypi__setuptools', 
'/home/vincent/.cache/bazel/_bazel_vincent/55e31083404cf40043d2810f68eeadac/execroot/pipeline_demo/bazel-out/k8-fastbuild/bin/integration_test/test.runfiles/pip_deps/pypi__six', 
'/home/vincent/.cache/bazel/_bazel_vincent/55e31083404cf40043d2810f68eeadac/execroot/pipeline_demo/bazel-out/k8-fastbuild/bin/integration_test/test.runfiles/pip_deps/pypi__google_auth', 
'/home/vincent/.cache/bazel/_bazel_vincent/55e31083404cf40043d2810f68eeadac/execroot/pipeline_demo/bazel-out/k8-fastbuild/bin/integration_test/test.runfiles/pipeline_demo', 
'/home/vincent/.cache/bazel/_bazel_vincent/55e31083404cf40043d2810f68eeadac/execroot/pipeline_demo/bazel-out/k8-fastbuild/bin/integration_test/test.runfiles/pip_deps', 
'/home/vincent/.cache/bazel/_bazel_vincent/55e31083404cf40043d2810f68eeadac/execroot/pipeline_demo/bazel-out/k8-fastbuild/bin/integration_test/test.runfiles/bazel_tools', 
'/usr/lib/python38.zip', 
'/usr/lib/python3.8', 
'/usr/lib/python3.8/lib-dynload', 
'/home/vincent/.local/lib/python3.8/site-packages', 
'/usr/lib/python3.8/site-packages'
]
Traceback (most recent call last):
  File "/home/vincent/.cache/bazel/_bazel_vincent/55e31083404cf40043d2810f68eeadac/execroot/pipeline_demo/bazel-out/k8-fastbuild/bin/integration_test/test.runfiles/pipeline_demo/integration_test/test.py", line 5, in <module>
    import google.auth
ModuleNotFoundError: No module named 'google.auth'
</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Linux 
5.9.2-arch1-1 
x86_64
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
bazel 3.7.0
  </code>
</pre>

**Rules_python version:**

<pre>
  <code>
0.1.0
  </code>
</pre>

**Comment by thundergolfer** [comment]
Hey @vincent-herlemont, 

I just tried to reproduce your issue, but couldn't. **Details of my reproduction**

```
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
http_archive(
    name = "rules_python",
    url = "https://github.com/bazelbuild/rules_python/releases/download/0.1.0/rules_python-0.1.0.tar.gz",
    sha256 = "b6d46438523a3ec0f3cead544190ee13223a52f6a6765a29eae7b7cc24cc83a0",
)

load("@rules_python//python:pip.bzl", "pip_install")
pip_install(
   name = "pypi",  # <--- different to yours, but should be inconsequential
   requirements = "//test:requirements.txt",
)
```

```python
BUILD
load("@rules_python//python:defs.bzl", "py_binary", "py_library", "py_test")
load("@pypi//:requirements.bzl", "requirement")

py_binary(
    name = "test",
    srcs = ["test.py"],
    deps = [requirement("google-auth")],
    srcs_version = "PY3",
)
```


```python
# test.py
import google.auth
print("works")
```

```
root@971e1864ab8f:/test_project# USE_BAZEL_VERSION=3.7.0 ./bazelisk-linux-amd64 run //test:test
2020/11/24 04:59:14 Downloading https://releases.bazel.build/3.7.0/release/bazel-3.7.0-linux-x86_64...
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
INFO: Analyzed target //test:test (25 packages loaded, 498 targets configured).
INFO: Found 1 target...
Target //test:test up-to-date:
  bazel-bin/test/test
INFO: Elapsed time: 10.179s, Critical Path: 0.06s
INFO: 3 processes: 3 internal.
INFO: Build completed successfully, 3 total actions
INFO: Build completed successfully, 3 total actions
works
```

**Operating System:** 

I was inside the `l.gcr.io/google/bazel:latest` image on Mac OSX.

```
echo $OSTYPE
linux-gnu
```

(This setup isn't identical)

-----

If you update `test.py` to be: 

```python
import google.auth
import sys

print(sys.path)
```

What does it output? For me, it's: 

```
root@971e1864ab8f:/test_project# USE_BAZEL_VERSION=3.7.0 ./bazelisk-linux-amd64 run //test
Starting local Bazel server and connecting to it...
INFO: Analyzed target //test:test (25 packages loaded, 498 targets configured).
INFO: Found 1 target...
Target //test:test up-to-date:
  bazel-bin/test/test
INFO: Elapsed time: 5.399s, Critical Path: 0.10s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
INFO: Build completed successfully, 1 total action
[
'/test_project/test', 
'/root/.cache/bazel/_bazel_root/64937c0fa78032586a25bdbe661dfdf0/execroot/uni/bazel-out/k8-fastbuild/bin/test/test.runfiles',
 '/root/.cache/bazel/_bazel_root/64937c0fa78032586a25bdbe661dfdf0/execroot/uni/bazel-out/k8-fastbuild/bin/test/test.runfiles/pypi/pypi__cachetools',
'/root/.cache/bazel/_bazel_root/64937c0fa78032586a25bdbe661dfdf0/execroot/uni/bazel-out/k8-fastbuild/bin/test/test.runfiles/pypi/pypi__pyasn1', 
'/root/.cache/bazel/_bazel_root/64937c0fa78032586a25bdbe661dfdf0/execroot/uni/bazel-out/k8-fastbuild/bin/test/test.runfiles/pypi/pypi__pyasn1_modules', 
'/root/.cache/bazel/_bazel_root/64937c0fa78032586a25bdbe661dfdf0/execroot/uni/bazel-out/k8-fastbuild/bin/test/test.runfiles/pypi/pypi__rsa', 
'/root/.cache/bazel/_bazel_root/64937c0fa78032586a25bdbe661dfdf0/execroot/uni/bazel-out/k8-fastbuild/bin/test/test.runfiles/pypi/pypi__setuptools', 
'/root/.cache/bazel/_bazel_root/64937c0fa78032586a25bdbe661dfdf0/execroot/uni/bazel-out/k8-fastbuild/bin/test/test.runfiles/pypi/pypi__six', 
'/root/.cache/bazel/_bazel_root/64937c0fa78032586a25bdbe661dfdf0/execroot/uni/bazel-out/k8-fastbuild/bin/test/test.runfiles/pypi/pypi__google_auth', 
'/root/.cache/bazel/_bazel_root/64937c0fa78032586a25bdbe661dfdf0/execroot/uni/bazel-out/k8-fastbuild/bin/test/test.runfiles/uni', 
'/root/.cache/bazel/_bazel_root/64937c0fa78032586a25bdbe661dfdf0/execroot/uni/bazel-out/k8-fastbuild/bin/test/test.runfiles/pypi', 
'/root/.cache/bazel/_bazel_root/64937c0fa78032586a25bdbe661dfdf0/execroot/uni/bazel-out/k8-fastbuild/bin/test/test.runfiles/bazel_tools', 
'/usr/lib/python35.zip', 
'/usr/lib/python3.5', 
'/usr/lib/python3.5/plat-x86_64-linux-gnu', 
'/usr/lib/python3.5/lib-dynload', 
'/usr/local/lib/python3.5/dist-packages', 
'/usr/lib/python3/dist-packages'
]
```

And in that we can see: 

```
'/root/.cache/bazel/_bazel_root/64937c0fa78032586a25bdbe661dfdf0/execroot/uni/bazel-out/k8-fastbuild/bin/test/test.runfiles/pypi/pypi__google_auth'
```

which is the requisite path entry.

**Comment by vincent-herlemont** [comment]
Hello @thundergolfer, 

It seem because `google-auth` are installed globaly in `l.gcr.io/google/bazel:latest`.
Can you try to remove `requirement("google-auth")` that should works anyway.
Or try to remove `google-auth` globaly in the image by `sudo pip google-auth` for to appear the error.

**Comment by thundergolfer** [comment]
> It seem because google-auth are installed globally ...

Oh boy, thanks.

**Comment by vincent-herlemont** [comment]
```
py_test(
    name = "test",
    srcs = ["test.py"],
    main = "test.py",
)
```

test.py
```
import google.auth
import sys

print(sys.path)
```

```
$> pip list | grep google-auth
google-auth            1.23.0
```

```
INFO: Elapsed time: 0.799s, Critical Path: 0.02s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
INFO: Build completed successfully, 1 total action
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
Executing tests from //integration_test:test
-----------------------------------------------------------------------------
[
'/home/vincent/work/pipeline-demo/integration_test', '/home/vincent/.cache/bazel/_bazel_vincent/55e31083404cf40043d2810f68eeadac/execroot/pipeline_demo/bazel-out/k8-fastbuild/bin/integration_test/test.runfiles', 
'/home/vincent/.cache/bazel/_bazel_vincent/55e31083404cf40043d2810f68eeadac/execroot/pipeline_demo/bazel-out/k8-fastbuild/bin/integration_test/test.runfiles/pipeline_demo', 
'/home/vincent/.cache/bazel/_bazel_vincent/55e31083404cf40043d2810f68eeadac/execroot/pipeline_demo/bazel-out/k8-fastbuild/bin/integration_test/test.runfiles/bazel_tools', 
'/usr/lib/python38.zip',
 '/usr/lib/python3.8', '/usr/lib/python3.8/lib-dynload', 
'/home/vincent/.local/lib/python3.8/site-packages', 
'/usr/lib/python3.8/site-packages'
]
```

**Comment by vincent-herlemont** [comment]
@thundergolfer the global package path is present to `sys.path`, you can see it by this command for `google-auth` :

```
$> pip list -v | grep google-auth
google-auth            1.23.0       /usr/lib/python3.8/site-packages                 pip
```

So if y run the following step : 

BUILD.bazel
```
....
py_test(
    name = "test",
    srcs = ["test.py"],
    main = "test.py",
)
```
test.py
```
import google.auth
import sys

print(sys.path)
```
I can see this output. It works and no google-auth is required in bazel dependencies, python take the global one.
```
$> bazel run test
INFO: Elapsed time: 0.799s, Critical Path: 0.02s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
INFO: Build completed successfully, 1 total action
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
Executing tests from //integration_test:test
-----------------------------------------------------------------------------
[
'/home/vincent/work/pipeline-demo/integration_test', '/home/vincent/.cache/bazel/_bazel_vincent/55e31083404cf40043d2810f68eeadac/execroot/pipeline_demo/bazel-out/k8-fastbuild/bin/integration_test/test.runfiles', 
'/home/vincent/.cache/bazel/_bazel_vincent/55e31083404cf40043d2810f68eeadac/execroot/pipeline_demo/bazel-out/k8-fastbuild/bin/integration_test/test.runfiles/pipeline_demo', 
'/home/vincent/.cache/bazel/_bazel_vincent/55e31083404cf40043d2810f68eeadac/execroot/pipeline_demo/bazel-out/k8-fastbuild/bin/integration_test/test.runfiles/bazel_tools', 
'/usr/lib/python38.zip',
 '/usr/lib/python3.8', '/usr/lib/python3.8/lib-dynload', 
'/home/vincent/.local/lib/python3.8/site-packages', 
'/usr/lib/python3.8/site-packages'
]
```

I'm not a python expert and I don't know why some python libraries are interpreted only if they are installed as global packages. 
That is an big issue for replicability. The `google-auth` version do not depend of the build in this case, and as @thundergolfer notice that can to "fail" silently.

**Comment by thundergolfer** [comment]
> That is an big issue for replicability. 

Yes the default toolchain is not hermetic at all which is a problem. This seems like a separate issue to the issue which prompted this issue's creation, which is an import error when you _were_ listing `google-auth` in your deps:  `deps = [requirement("google-auth")],`

When I tried to reproduce your issue on Linux I couldn't which I why I asked: 

> What does [sys.path] output?

when you _do_ list the `google-auth` package in your `deps`, as it should include an entry like I show in [this thread comment](https://github.com/bazelbuild/rules_python/issues/383#issuecomment-732657391).

**Comment by vincent-herlemont** [comment]
ho you're right @thundergolfer my apologie, here the `sys.path` and you can see `...tegration_test/test.runfiles/pip_deps/pypi__google_auth` and the error `...No module named 'google.auth'`.
I have completed the issue with this trace too.
```
INFO: Analyzed target //integration_test:test (8 packages loaded, 415 targets configured).
INFO: Found 1 target...
Target //integration_test:test up-to-date:
  bazel-bin/integration_test/test
INFO: Elapsed time: 0.687s, Critical Path: 0.12s
INFO: 4 processes: 4 internal.
INFO: Build completed successfully, 4 total actions
INFO: Build completed successfully, 4 total actions
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
Executing tests from //integration_test:test
-----------------------------------------------------------------------------
[
'/home/vincent/work/pipeline-demo/integration_test', 
'/home/vincent/.cache/bazel/_bazel_vincent/55e31083404cf40043d2810f68eeadac/execroot/pipeline_demo/bazel-out/k8-fastbuild/bin/integration_test/test.runfiles', 
'/home/vincent/.cache/bazel/_bazel_vincent/55e31083404cf40043d2810f68eeadac/execroot/pipeline_demo/bazel-out/k8-fastbuild/bin/integration_test/test.runfiles/pip_deps/pypi__cachetools', 
'/home/vincent/.cache/bazel/_bazel_vincent/55e31083404cf40043d2810f68eeadac/execroot/pipeline_demo/bazel-out/k8-fastbuild/bin/integration_test/test.runfiles/pip_deps/pypi__pyasn1', 
'/home/vincent/.cache/bazel/_bazel_vincent/55e31083404cf40043d2810f68eeadac/execroot/pipeline_demo/bazel-out/k8-fastbuild/bin/integration_test/test.runfiles/pip_deps/pypi__pyasn1_modules', 
'/home/vincent/.cache/bazel/_bazel_vincent/55e31083404cf40043d2810f68eeadac/execroot/pipeline_demo/bazel-out/k8-fastbuild/bin/integration_test/test.runfiles/pip_deps/pypi__rsa', 
'/home/vincent/.cache/bazel/_bazel_vincent/55e31083404cf40043d2810f68eeadac/execroot/pipeline_demo/bazel-out/k8-fastbuild/bin/integration_test/test.runfiles/pip_deps/pypi__setuptools', 
'/home/vincent/.cache/bazel/_bazel_vincent/55e31083404cf40043d2810f68eeadac/execroot/pipeline_demo/bazel-out/k8-fastbuild/bin/integration_test/test.runfiles/pip_deps/pypi__six', 
'/home/vincent/.cache/bazel/_bazel_vincent/55e31083404cf40043d2810f68eeadac/execroot/pipeline_demo/bazel-out/k8-fastbuild/bin/integration_test/test.runfiles/pip_deps/pypi__google_auth', 
'/home/vincent/.cache/bazel/_bazel_vincent/55e31083404cf40043d2810f68eeadac/execroot/pipeline_demo/bazel-out/k8-fastbuild/bin/integration_test/test.runfiles/pipeline_demo', 
'/home/vincent/.cache/bazel/_bazel_vincent/55e31083404cf40043d2810f68eeadac/execroot/pipeline_demo/bazel-out/k8-fastbuild/bin/integration_test/test.runfiles/pip_deps', 
'/home/vincent/.cache/bazel/_bazel_vincent/55e31083404cf40043d2810f68eeadac/execroot/pipeline_demo/bazel-out/k8-fastbuild/bin/integration_test/test.runfiles/bazel_tools', 
'/usr/lib/python38.zip', 
'/usr/lib/python3.8', 
'/usr/lib/python3.8/lib-dynload', 
'/home/vincent/.local/lib/python3.8/site-packages', 
'/usr/lib/python3.8/site-packages'
]
Traceback (most recent call last):
  File "/home/vincent/.cache/bazel/_bazel_vincent/55e31083404cf40043d2810f68eeadac/execroot/pipeline_demo/bazel-out/k8-fastbuild/bin/integration_test/test.runfiles/pipeline_demo/integration_test/test.py", line 5, in <module>
    import google.auth
ModuleNotFoundError: No module named 'google.auth'
```

**Comment by thundergolfer** [comment]
Ok so it still fails when the package's root directory is present in `sys.path`. Odd. 

The next thing I'd look at is where Python is searching for `google.auth` and what it's finding or not finding inside `pypi_google_auth/`. You can do this by building the target and then running: 

```

**Comment by lukedirtwalker** [comment]
I had a similar problem. For the python binary didn't find the `google.protobuf` package. This only occurred on CI at first. Once I also installed the `google-auth` package locally I could also reproduce the issue locally. By deleting the `__init__.py` file in the google protobuf dependency I could fix the issue.

See also: https://github.com/protocolbuffers/protobuf/issues/6135#issuecomment-546241914 for more explanation.

**Comment by thundergolfer** [comment]
Without a shareable reproduction it's going to be hard for me to reproduce the bug. I tried setting up a reproduction and got normal behaviour. 

If this is a case of a failure to handle namespace packages it would be good to find it. Tracking the import path searching behaviour of the binary is a good place to look, as detailed here -> https://github.com/bazelbuild/rules_python/issues/383#issuecomment-741489651

**Comment by thundergolfer** [comment]
@vincent-herlemont were you able to resolve the issue on your end?
