### ISSUE TITLE
Add support for building universal wheels in the py_wheel rule.

### ISSUE THREAD

**Issue by awbraunstein** [bazelbuild/rules_python#392]
# 🚀 feature request

### Relevant Rules

This is a feature that should be added to the `py_wheel` rule.

-->

### Description

I'd like the ability to build universal wheels to be added to the `py_wheel` rule. This should be relatively simple since it just requires passing the `--universal` flag when building the wheel.

### Describe the solution you'd like

Add a new value for `python_tag` that is either `universal` or `py2and3` that builds a universal wheel.

### Describe alternatives you've considered

Building two wheels isn't as easy to distribute.

**Comment by pstradomski** [comment]
It's probably best to change versions to be a list.

**Comment by pstradomski** [comment]
Relevant PEPs:
 - https://www.python.org/dev/peps/pep-0427/#file-contents
 - https://www.python.org/dev/peps/pep-0425/#compressed-tag-sets

**Comment by pstradomski** [comment]
It would be best to merge https://github.com/bazelbuild/rules_python/pull/388 first, to avoid conflicts

**Comment by groodt** [comment]
Closing. Universal wheels are no longer relevant because Python 2 is end of life.
