### ISSUE TITLE
Automatically insert __init__.py files when building wheels.

### ISSUE THREAD

**Issue by awbraunstein** [bazelbuild/rules_python#394]
# 🚀 feature request

### Relevant Rules

`py_wheel`

### Description

Bazel doesn't require any `__init__.py` files and adds those automatically. When building a `py_wheel`, it would be useful if `__init__.py` files could be automatically inserted to allow the wheel to be used without significant modification to the bazel repository.

### Describe the solution you'd like

I implemented this by doing this in the `wheelmaker.py` file by tracking what files are added and what directories need `__init__.py` files added that weren't provided. Then at the very end before writing the record, I add all the empty `__init__.py` files to the zip and record.

### Describe alternatives you've considered

My solution above was my workaround.

**Comment by aaliddell** [comment]
The auto addition of init files is intended to be disabled and removed at some point, as it has ended up causing more issues than expected: https://github.com/bazelbuild/bazel/issues/7386

I would suggest either manually making the init files where necessary (as you would in any other python packaging outside Bazel) or should this be added to rules_python that the default be having it disabled.

**Comment by pstradomski** [comment]
I agree that automatic creation of __init__ is causing many problems. Doing
it for wheels would also prevent building namespace wheels.

The simplest workaround is to just create __init__.py files in your
repository.

-- 
Paweł Stradomski

wt., 22 gru 2020, 16:55 użytkownik Adam Liddell <notifications@github.com>
napisał:

**Comment by thundergolfer** [comment]
@awbraunstein this has just recently been marked for closure. Do you perceive a need to keep this open, or are you satisfied that manual `__init__.py` is the best way forward?

**Comment by awbraunstein** [comment]
No, you can keep this closed. I ended up implementing a manual solution.
