### ISSUE TITLE
Nowhere does it say which version of Python this selects

### ISSUE THREAD

**Issue by blais** [bazelbuild/rules_python#399]
The README has lots of information, but not once does it say how to select the version of Python the resulting binaries run, which is central to the output of these rules. This is disconcertingly confusing to an external user.

Please add a paragraph to let us how how the Python binary and libraries are selected, and whether a user's PYTHONPATH will be honored or not, and other relevant basic details.

**Comment by thundergolfer** [comment]
Good point. We can workshop a paragraph in this issue, then submit it as a PR. 

> , and other relevant basic details.

If you have specifics in mind, would be helpful to list then out

Key points identified so far:

* Python binary (ie. interpreter)
* Python library / package platform selection (I presume you platform selection is what you refer to as being "selected")
* `PYTHONPATH` hermeticity

**Comment by blais** [comment]
I have to admit, even with experience from as a developer from within, I'm not familiar enough with what's going on with the Bazel plans to craft it myself. My comment is as much of a question as it is about the doc... 

The experience from outside is really confusing. It's very hard to setup and understand Bazel with the resources out there. For instance, why doesn't this project include the oft-seen file "python_configure.bzl" which sets up a local configuration (e.g. from TensorFlow, and other projects)? And does this replace it?

Answering the questions with a newbie eye will tremendously help the adoption of Bazel (and I'd love to see that).

**Comment by thundergolfer** [comment]
> Bazel plans to craft it myself. My comment is as much of a question as it is about the doc...

Oh I didn't mean for you to have to write it. I'll work on it here just for visibility, and feedback from others (including yourself).

**Comment by thundergolfer** [comment]
> The experience from outside is really confusing. It's very hard to setup and understand Bazel with the resources out there.  ...  Answering the questions with a newbie eye will tremendously help the adoption of Bazel (and I'd love to see that).

Totally agree.

**Comment by hrfuller** [comment]
I agree this is a pain point, just linking this here because its what I used to learn about how to configure the bazel python toolchain. https://github.com/bazelbuild/bazel/blob/master/tools/python/toolchain.bzl

**Comment by thundergolfer** [comment]
The wrapper script will use the `py_runtime_pair` path. It's managing that logic here: https://github.com/bazelbuild/bazel/blob/9d43bdfe3d63fe36a35e8c00df0f5f921d7e56ce/src/main/java/com/google/devtools/build/lib/bazel/rules/python/python_stub_template.txt#L73

We use rules_nixpkgs to do our Python toolchain, so our stub scripts contain this: 

```
PYTHON_BINARY = '/nix/store/gj2s9dc8zlnrblcyls8jnyx315zrbfj8-python3-3.7.9/bin/python'
if IsWindows() and not HasWindowsExecutableExtension(PYTHON_BINARY):
  PYTHON_BINARY = PYTHON_BINARY + '.exe'
```

We means in `FindPythonBinary` (linked above) we hit [this part of the conditional](https://github.com/bazelbuild/bazel/blob/9d43bdfe3d63fe36a35e8c00df0f5f921d7e56ce/src/main/java/com/google/devtools/build/lib/bazel/rules/python/python_stub_template.txt#L79)

**Comment by thundergolfer** [comment]
🚧 Work in progress new README section.

- What to say about the Windows situation? 🤔 
- Why is `py_runtime_pair` documented in the repo, but not in https://docs.bazel.build/versions/master/be/python.html ??
- Need something about how platform-specific packages are installed?

----

### Python Toolchain

The default 'autodetecting' toolchain is `@bazel_tools//tools/python:_autodetecting_py_runtime_pair` which will look for the Python interpreter on the `$PATH`. This is _not_ hermetic, and depending on how the Python interpreter on the `$PATH` is setup, this can leak globally-installed packages into Bazel targets.

To configure a toolchain that refers to an explicitly specific, possibly in-build interpreter, you implement a [py_runtime](https://docs.bazel.build/versions/master/be/python.html#py_runtime) for Python 3, Python 2, or both. 

.... TODO ...
