### ISSUE TITLE
consider renaming "package" from requirements.bzl

### ISSUE THREAD

**Issue by maximermilov** [bazelbuild/rules_python#4]
It's bazel builtin (https://docs.bazel.build/versions/master/be/functions.html#package)

buildozer(https://github.com/bazelbuild/buildtools/tree/master/buildozer) always insert new load statement as first line, which causing conflict if file have package declaration.

**Comment by mattmoor** [comment]
@duggelz Doh!  Suggestions?

**Comment by duggelz** [comment]
It shouldn't be `py_package`, because that should be the name of the rule that creates python packages.  Maybe `py_package_name`?  `py_package_dep`? `py_package_import`?

**Comment by pcj** [comment]
`py_wheel`?

**Comment by mattmoor** [comment]
Not sure "wheel" is well enough known, I hadn't heard of it before @duggelz first brought it up, but that's perhaps my naivette from our packageless mono-repo world.

What about `requirement`?
