### ISSUE TITLE
Add rules_python to mirror.bazel.build

### ISSUE THREAD

**Issue by limdor** [bazelbuild/rules_python#400]
# 🚀 feature request

### Relevant Rules

rules_python

### Description

rules_python release is not available to mirror.bazel.build
From a user point of view it is not clear to me what is the criteria for having rules mirror to the bazel build or not.
In our case having it mirror.bazel.build help in some cases because we have a mechanism to mirror to our internal mirror replica.

### Describe the solution you'd like

I would request if the releases for rules_python could also be added to mirror.bazel.build

### Describe alternatives you've considered

If it is not done it is ok, but a comment saying what is the criteria on going to mirror.bazel.build or not it would be great.

**Comment by thundergolfer** [comment]
👋  @limdor, 

I'm not clear myself on the way to get rules_python mirrored to `mirror.bazel.build`,  or why it isn't already mirrored. Here's an example of a Googler (Deepmind) not being clear of the process: [link](https://github.com/deepmind/lab/issues/139#issuecomment-472831880).

Over email @alexeagle has reached out to @philwo, who works closely with that mirror I think.

**Comment by philwo** [comment]
I can mirror the currently existing releases later today. 👍 

There is currently no real process for uploading files there except pinging me. :/

**Comment by thundergolfer** [comment]
> There is currently no real process for uploading files there except pinging me. :/

No worries. What is the best way to ping you?

**Comment by philwo** [comment]
@thundergolfer Just on GitHub is fine, or you can send me a mail (address is in my profile). :)

**Comment by thundergolfer** [comment]
@limdor I'll resolve this issue, having made the contact with the dev that can do the mirror, and putting a note in #317 about  adding a 'mirror.bazel.build' step into release documentation.

**Comment by philwo** [comment]
All existing rules_python releases have now been uploaded to the mirror.

- https://mirror.bazel.build/github.com/bazelbuild/rules_python/releases/download/0.1.0/rules_python-0.1.0.tar.gz
- https://mirror.bazel.build/github.com/bazelbuild/rules_python/releases/download/0.0.3/rules_python-0.0.3.tar.gz
- https://mirror.bazel.build/github.com/bazelbuild/rules_python/releases/download/0.0.2/rules_python-0.0.2.tar.gz
- https://mirror.bazel.build/github.com/bazelbuild/rules_python/releases/download/0.0.1/rules_python-0.0.1.tar.gz
