### ISSUE TITLE
pip_install on Python 3.8 fails by getting confused over hostname

### ISSUE THREAD

**Issue by larsga** [bazelbuild/rules_python#401]
Bazel 3.6.0 on MacOS, with this `WORKSPACE`:

```
http_archive(
    name = "rules_python",
    sha256 = "b6d46438523a3ec0f3cead544190ee13223a52f6a6765a29eae7b7cc24cc83a0",
    url = "https://github.com/bazelbuild/rules_python/releases/download/0.1.0/rules_python-0.1.0.tar.gz",
)

load("@rules_python//python:pip.bzl", "pip_install")

pip_install(
    name = "probe_dependencies",
    requirements = ":requirements.txt",
)
```

the requirements.txt is unremarkable:

```
python-consul==1.1.0
prometheus-client==0.6.0
requests[security]==2.16.5
grpcio-health-checking==1.21.1
grpcio==1.21.1
grpcio-tools==1.20.1
enum34==1.1.6 # grcp needs this, and older Python 2.7s don't have it
```

When I run it, it goes:

```
bazel test --subcommands //analytics/src/main/python:probe_test
Loading: 0 packages loaded
    currently loading: analytics/src/main/python
    Fetching @probe_dependencies; fetching 21s
```

And there it hangs for a long, long time. Turning off wifi it fails much quicker, and more instructively. The output says:

```
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x11042a6d0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /simple/python-consul/
```

So looks like it's trying to resolve a URL and gets confused into thinking the hostname is `/simple/python-consul/`

The actual command bazel is running when it fails is :

```
'['/usr/local/opt/python@3.8/bin/python3.8', '-m', 'pip', 'wheel', '-r', '/Users/larsga/cvs-co/cx/external/requirements.txt']'
```

If I run this from the command-line (outside of bazel) it works just fine. However, running on the command-line uses the pip version that's included in Python. 

I checked out the rules_python code and made bazel use that instead. By instrumenting it to output debug info I found out that the python 3.8 command above was actually loading `/private/var/tmp/_bazel_larsga/6679bda6eac97b437aa9778cbeae5ac4/external/pypi__pip/pip/__init__.py`. That seems to contain an entire copy of pip, which I decided not to try to debug.

On our Linux build server, with Python 3.7, the install actually works fine, and the tests themselves fail with: `ImportError: cannot import name cygrpc`. That's a separate error I can solve later. The strange thing is that switching from the git-checkout version of rules_python to 0.1.0 suddenly made the build work the same on my laptop as on the build server. Deleting the bazel cache took me back to the original behaviour.

Any advice on how to proceed with this? It's difficult to know where to start to try to pinpoint what's going on.

**Comment by hrfuller** [comment]
What happens if you add `extra_pip_args="--index-url=https://pypi.org/simple/"` to the pip_install rule?

**Comment by larsga** [comment]
The same error, unfortunately:

```WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after 
connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object 
at 0x106011670>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not 
known')': /simple/python-consul/```

The command being run is shown below, so the argument is clearly picked up:

```
'['/usr/local/opt/python@3.8/bin/python3.8', '-m', 'pip', 'wheel', '-r', 
'/Users/larsga/cvs-co/cx/external/requirements.txt', '--index-url=https://pypi.org/simple/']'
```

**Comment by groodt** [comment]
I don't think this is a "hostname" issue at all. That is a red-herring. The issue can be reproduced as follows without Bazel or rules_python.

```
❯ cat requirements.txt
python-consul==1.1.0
prometheus-client==0.6.0
requests[security]==2.16.5
grpcio-health-checking==1.21.1
grpcio==1.21.1
grpcio-tools==1.20.1
enum34==1.1.6 # grcp needs this, and older Python 2.7s don't have it

/tmp/x
❯ python --version
Python 3.8.6

/tmp/x
❯ python -m venv venv

/tmp/x
❯ source venv/bin/activate.fish

/tmp/x
venv ❯ python -m pip install pip==20.3.3 wheel==0.36.1 pkginfo==1.6.1 setuptools==44.1.0
Collecting pip==20.3.3
  Using cached pip-20.3.3-py2.py3-none-any.whl (1.5 MB)
Collecting wheel==0.36.1
  Using cached wheel-0.36.1-py2.py3-none-any.whl (34 kB)
Collecting pkginfo==1.6.1
  Using cached pkginfo-1.6.1-py2.py3-none-any.whl (25 kB)
Collecting setuptools==44.1.0
  Using cached setuptools-44.1.0-py2.py3-none-any.whl (583 kB)
Installing collected packages: pip, wheel, pkginfo, setuptools
  Attempting uninstall: pip
    Found existing installation: pip 20.2.1
    Uninstalling pip-20.2.1:
      Successfully uninstalled pip-20.2.1
  Attempting uninstall: setuptools
    Found existing installation: setuptools 49.2.1
    Uninstalling setuptools-49.2.1:
      Successfully uninstalled setuptools-49.2.1
Successfully installed pip-20.3.3 pkginfo-1.6.1 setuptools-44.1.0 wheel-0.36.1

/tmp/x
venv ❯ python -m pip wheel -r requirements.txt
```

(It goes into an endless loop, occasionally spitting out some fun looking native compiler flags)

```
Building wheels for collected packages: grpcio, grpcio-health-checking, grpcio-tools, prometheus-client
  Building wheel for grpcio (setup.py) ... -
```

How was the `requirements.txt` produced? Was it locked with a recent version of pip-tools? 

If you choose a version of grpcio with a wheel, it seems to work ok. Not sure if this is possible for you?
```
grpcio-health-checking==1.21.1
grpcio==1.34.1
grpcio-tools==1.34.1
```

**Comment by groodt** [comment]
A similar issue on grpcio project? https://github.com/grpc/grpc/issues/24630

**Comment by larsga** [comment]
> How was the requirements.txt produced?

By hand.

> If you choose a version of grpcio with a macos wheel, it seems to work ok.

Yes, using those versions instead worked just fine. Thank you! 👍 

So this is a bug, then. But where? In pip?

**Comment by groodt** [comment]
> By hand.

Pinning dependencies by hand with `==` can be sketchy sometimes as Im sure you're aware. Although, in this case, those do seem to be a very short list of dependencies that probably wouldn't clash transitively.

> So this is a bug, then. But where? In pip?

If I had to guess, either in setuptools or the `setup.py` of `grpcio`. It might have an endless loop inside the sdist when trying to build the native extension.

**Comment by larsga** [comment]
I see. Thanks! It seems this isn't a bazel issue, so I'll close this ticket.

**Comment by thundergolfer** [comment]
Thanks @groodt 🙏
