### ISSUE TITLE
Documentation is inconsistent

### ISSUE THREAD

**Issue by UebelAndre** [bazelbuild/rules_python#406]
# 🐞 bug report

### Description

In trying to use the "experimental"/"modern" rev of this repository in this workspace, I stumbled across some documentation I found to be unclear or incorrect.

- In [Getting Started](https://github.com/bazelbuild/rules_python#getting-started) users are instructed to load and call a deprecated macro `pip_repositories`
- It's unclear how to use dependencies loaded from the non-legacy section on [Importing pip dependencies](https://github.com/bazelbuild/rules_python#importing-pip-dependencies)
- It's also not clear what information is in `./docs` It appears to be legacy information since the [pip documentation](https://github.com/bazelbuild/rules_python/blob/c6e6381723eac2b19cb9c6acedfca2489c008602/docs/pip.md) is missing `pip_install`

I think it'd be awesome if someone with context on the current state of the repository could do a refresh on the documentation here 🙏 .

**Comment by thundergolfer** [comment]
> In Getting Started users are instructed to load and call a deprecated macro pip_repositories

Oh yep thanks for pointing this out. Obsolete info.

> It's unclear how to use dependencies loaded from the non-legacy section

That detail is in [Consuming Pip Dependencies](https://github.com/bazelbuild/rules_python#consuming-pip-dependencies). Do you think that the sections are too separated? 

> It's also not clear what information is in ./docs 

Yeh that folder contained documentation that seemed to be once published to Github pages:

![image](https://user-images.githubusercontent.com/12058921/105985334-71586200-60ef-11eb-9e65-b8cc4e3d59a4.png)

I wasn't around when that Github pages site was even working, if it did ever. We've got to sort out the connection between this repo's documentation and the official Bazel documentation. It should be a separate issue.

**Comment by UebelAndre** [comment]
> That detail is in [Consuming Pip Dependencies](https://github.com/bazelbuild/rules_python#consuming-pip-dependencies). Do you think that the sections are too separated?

No, I just didn't know if that was referring to the legacy way of doing things. I think I was just confused by the layout of the doc





> I wasn't around when that Github pages site was even working, if it did ever. We've got to sort out the connection between this repo's documentation and the official Bazel documentation. It should be a separate issue.

Is there a separate issue for that?

**Comment by UebelAndre** [comment]
I would probably opt to remove the "legacy" documentation. It should be there in the versions people are using, right?

**Comment by thundergolfer** [comment]
@UebelAndre it looks like the main outstanding item is:

> It's unclear how to use dependencies loaded from non-legacy section ...

What action should be taken to close out this issue? Note that the latest README changes are PR'd here: https://github.com/bazelbuild/rules_python/pull/501

**Comment by UebelAndre** [comment]
The "legacy" documentation was removed in https://github.com/bazelbuild/rules_python/pull/582 which now covers all my concerns here. Closing this issue out.
