### ISSUE TITLE
Peer Dependency Support

### ISSUE THREAD

**Issue by ben-ng** [bazelbuild/rules_python#41]
Some packages, like scipy, depend on packages already being installed on your system. In scipy's case, its numpy.

I tried making piptool respect the order of `requirements.txt`, but it wasn't enough, because the scipy wheel won't build unless numpy is already installed.

Maybe we need a `deps` attribute in `pip_import`?

**Comment by mattmoor** [comment]
Hmm, I'm unfamiliar with those specifically, but that sounds like malformed dependencies.

`requirements.txt` expresses top-level deps, but it resolves transitive deps, so if `scipy` hasn't declared a dependency on `numpy` my naive assessment is that it's a bug in `scipy`.

Would it be possible to throw together a little repro that exhibits the problem you are having?

**Comment by ben-ng** [comment]
scipy isn't the only package that's failing this way for us. Python isn't my first language so correct me if I'm wrong: I think it's because popular dependencies like numpy can be rather large, so packages that depend on them don't explicitly declare them.

word2vec and Tensorflow also depend on numpy, for example. Tensorflow just tells people to `apt-get install` it before building with Bazel.

Oddly... I can't reproduce the scipi issue in a new repo. I'll have to figure out what's going on there.

I can [reproduce it with word2vec](https://github.com/ben-ng/rules-python-cross-deps), though.

**Comment by ben-ng** [comment]
Update: I think #32 fixed (or masked) the scipi issue by using the wheel instead.

**Comment by mattmoor** [comment]
Thanks I will TAL.  Perhaps some of these things are pulled in via "extras"?

**Comment by groodt** [comment]
This can be closed. `piptool.py` was removed in https://github.com/bazelbuild/rules_python/pull/582 when the legacy pip_import rule was removed.

Using `pip_install` or `pip_parse` with a transitively-locked `requirements.txt` produced with `compile_pip_requirements` or `pip-tools compile` or `poetry export` or any similar mechanism (ideally using hashes) handles peer / transitive dependencies. From experience at Canva, the dependency between `scipy` and `numpy` is correctly handled.
