### ISSUE TITLE
Running a binary and running test use different Python version

### ISSUE THREAD

**Issue by Topher-the-Geek** [bazelbuild/rules_python#410]
# 🐞 bug report

### Affected Rule

`py_binary` and `py_test`

### Is this a regression?

I do not have prior experience with rules_python to answer the question

### Description

Running a binary uses Python 3.9.0 as setup by `pyenv` in the shell I used to invoke `bazel`. Running the test used Python 3.8.2, which is my system's `python3`.

## 🔬 Minimal Reproduction

File `WORKSPACE`

```
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "rules_python",
    url = "https://github.com/bazelbuild/rules_python/releases/download/0.1.0/rules_python-0.1.0.tar.gz",
    sha256 = "b6d46438523a3ec0f3cead544190ee13223a52f6a6765a29eae7b7cc24cc83a0",
)
```

File `BUILD`:

```
load("@rules_python//python:defs.bzl", "py_binary", "py_test")

py_binary(
    name = "binary",
    srcs = ["test.py"],
    main = "test.py"
)
py_test(
    name = "test",
    srcs = ["test.py"]
)
```

File `test.py`:

```
import sys

if __name__ == '__main__':
    if not sys.version.startswith('3.9.0'):
        raise Exception('Wrong version: ' + sys.version)
    print(sys.version)
```

## 🔥 Exception or Error

`bazel run //:binary` picks up 3.9.0. `bazel test //:test` picks up 3.8.2.

```
$ bazel clean --expunge
INFO: Starting clean.
$
$ bazel run //:binary
Starting local Bazel server and connecting to it...
INFO: Analyzed target //:binary (19 packages loaded, 237 targets configured).
INFO: Found 1 target...
Target //:binary up-to-date:
  bazel-bin/binary
INFO: Elapsed time: 10.880s, Critical Path: 0.04s
INFO: 5 processes: 5 internal.
INFO: Build completed successfully, 5 total actions
INFO: Build completed successfully, 5 total actions
3.9.0 (default, Jan 27 2021, 16:43:56)
[Clang 12.0.0 (clang-1200.0.32.29)]
$
$ bazel test --test_output=errors //:test
INFO: Analyzed target //:test (6 packages loaded, 220 targets configured).
INFO: Found 1 test target...
FAIL: //:test (see /private/var/tmp/_bazel_topher/82d9bd1ee99ac3074fe624aae0dceb5b/execroot/__main__/bazel-out/darwin-fastbuild/testlogs/test/test.log)
INFO: From Testing //:test:
==================== Test output for //:test:
Traceback (most recent call last):
  File "/private/var/tmp/_bazel_topher/82d9bd1ee99ac3074fe624aae0dceb5b/sandbox/darwin-sandbox/1/execroot/__main__/bazel-out/darwin-fastbuild/bin/test.runfiles/__main__/test.py", line 5, in <module>
    raise Exception('Wrong version: ' + sys.version)
Exception: Wrong version: 3.8.2 (default, Dec 21 2020, 15:06:04)
[Clang 12.0.0 (clang-1200.0.32.29)]
================================================================================
Target //:test up-to-date:
  bazel-bin/test
INFO: Elapsed time: 5.613s, Critical Path: 0.50s
INFO: 5 processes: 3 internal, 2 darwin-sandbox.
INFO: Build completed, 1 test FAILED, 5 total actions
//:test                                                                  FAILED in 0.4s
  /private/var/tmp/_bazel_topher/82d9bd1ee99ac3074fe624aae0dceb5b/execroot/__main__/bazel-out/darwin-fastbuild/testlogs/test/test.log

INFO: Build completed, 1 test FAILED, 5 total actions
```

## 🌍  Your Environment

**Operating System:**

```
Mac OS BigSur
Version 11.1
```

**Output of `bazel version`:**

```
bazel 4.0.0-homebrew
```

**Rules_python version:**

```
0.1.0
```

**Anything else relevant?**

```
$ pyenv shell system
$ python3 --version
Python 3.8.2
$
$ pyenv shell 3.9.0
$ python3 --version
Python 3.9.0
```

The problem still exists as of the latest commit:

```
rules_python_version = "8537cea11d867333c07c465d536778c1b7560cde"
http_archive(
    name = "rules_python",
    strip_prefix = "rules_python-{}".format(rules_python_version),
    url = "https://github.com/bazelbuild/rules_python/archive/{}.zip".format(rules_python_version),
)
```

**Comment by Topher-the-Geek** [comment]
In case anyone comes across this looking for a solution in the meantime, it's possible to work around this by setting up a toolchain.

Add the following to `WORKSPACE`

```
register_toolchains("//toolchains:my_py_toolchain")
```

Add the file `toolchains/BUILD` and edit the path to python:

```
load("@rules_python//python:defs.bzl", "py_runtime_pair")

py_runtime(
    name = "my_py_runtime",
    interpreter_path = "<YOUR PYTHON>/bin/python",
    python_version = "PY3"
)

py_runtime_pair(
    name = "my_py_runtime_pair",
    py2_runtime = None,
    py3_runtime = ":my_py_runtime",
)

toolchain(
    name = "my_py_toolchain",
    toolchain = ":my_py_runtime_pair",
    toolchain_type = "@bazel_tools//tools/python:toolchain_type",
)
```

**Comment by Topher-the-Geek** [comment]
I stumbled over a second workaround. Instead of the above, you can just:

```
bazel test --action_env=PYENV_VERSION=<YOUR PYENV VERSION> //:test
```

**Comment by groodt** [comment]
Yes, Python itself is *very* leaky and it's difficult to make it hermetic for Bazel. 

Using a toolchain should be the recommended (perhaps even mandatory) approach, but it might be a bit tricky for beginners just wanting to get started. That's the trade-off. Personally, I think it might be beneficial to require a toolchain, because it would prevent the sorts of puzzles and headscratching investigations like you've had to do. I think it gets complicated because Python is used internally for parts of Bazel and other Bazel rules as well. Unfortunatetly, it's not as easy as it is with the JVM languages that can bring along a hermetic default runtime and only require a toolchain if the default isn't desired.

**Comment by filiplindqvist-tink** [comment]
How is this a resonable solution forcing all developers to have python installed at the same path? 

_Python itself is very leaky_, that maybe so, but why shouldn't `py_test` and `py_binary` work the same? 
 
The `py_test` task should be changed to use the same setup as `py_binary`. 

Running this on my machine with Big Sur I get the following: 

With py_test:
`sys.base_prefix: /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8`

With py_binary:
`sys.base_prefix: /Users/$USER/.pyenv/versions/3.7.11`
