### ISSUE TITLE
Breakage with Bazel@HEAD 

### ISSUE THREAD

**Issue by lberki** [bazelbuild/rules_python#419]
`rules_python` is broken on the continuous integration tests of Bazel @ HEAD:

https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1905#e9759395-101f-4047-b7c9-daa0fc4eb714

This breakage is probably caused by https://github.com/bazelbuild/bazel/commit/00805727b867d33fd922e63ca82b0d9825ad79fe that calls test binaries in external repositories not using their legacy `external/$REPO/$REPO_RELATIVE_PATH` path but the canonical `../$REPO/$REPO_RELATIVE_PATH` one.

I haven't looked into what the mechanism of the breakage is; my guess is that test binaries try to find data files relative to `$0` and that logic needs to be updated

This issue is also available in our `continuous-integration` repository as https://github.com/bazelbuild/continuous-integration/issues/1094 .

**Comment by gyias** [comment]
FYI, I ran a downstream CI with https://github.com/bazelbuild/bazel/commit/00805727b867d33fd922e63ca82b0d9825ad79fe reverted, but they're still broken.

https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1919#e5b31176-6516-4422-876f-7a6d3929fdd8

**Comment by comius** [comment]
Breakage is caused by https://github.com/bazelbuild/bazel/commit/7149f578006a4ad0d51df69830a6986749b34df5, sorry.

**Comment by comius** [comment]
Confirming it is fixed https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1924

**Comment by thundergolfer** [comment]
Thanks @comius
