### ISSUE TITLE
[pip_install] ERROR: File "setup.py" not found. Directory cannot be installed in editable mode

### ISSUE THREAD

**Issue by amirh** [bazelbuild/rules_python#434]
# 🐞 bug report

### Affected Rule

 The issue is caused by the rule: pip_install

### Is this a regression?

 No

### Description

when using `pip_install` for a requirements file that has a `-e` file, pip fails with:
`ERROR: File "setup.py" not found. Directory cannot be installed in editable mode`.

This happens because pip ([executed from here](https://github.com/bazelbuild/rules_python/blob/c37ba2215eccab53ae1da5f827a335281f81b9e1/python/pip_install/extract_wheels/__init__.py#L87)) looks for the `setup.py` file in the CWD which does not have a `setup.py` .

**Anything else relevant?**
https://github.com/bazelbuild/rules_python/pull/433 fixes this issue as it executes pip from the directory that contains `setup.py` (confirmed locally that it solved the problem for me).

**Comment by groodt** [comment]
@amirh Is this now fixed from your perspective since #433 was merged? I'm not sure that bazel can truly support "editable installs" since they would not be hermetic , but at least they should install successfully the first time without error.
