### ISSUE TITLE
Parse pip flags from requirements_lock.txt

### ISSUE THREAD

**Issue by hrfuller** [bazelbuild/rules_python#438]
### Description

As a follow up to #432 and the issue brought up by @skliarpawlo we aren't capturing pip flags that may be passed in the requirements_lock.txt file.

E.g
requirements_lock.txt:
```
--index-url=some.index.com/simple
foo > 0.0.0
bar==1.0.0
...
```
--index-url is ignored, but in `pip_install` it works because the requirements file is passed verbatim to pip there.

### Describe the solution you'd like

Let's use pip to parse those arguments out of the requirements lock and amend the extra_pip_args array with them.

**Comment by srstrickland** [comment]
hi @hrfuller ... did not notice this issue but I ran into the same and opened a PR here: https://github.com/bazelbuild/rules_python/pull/446

**Comment by UebelAndre** [comment]
This feature would be awesome!
