### ISSUE TITLE
pip_parse ignores hashes and is incompatible with custom sources

### ISSUE THREAD

**Issue by titanous** [bazelbuild/rules_python#447]
# 🐞 bug report

### Affected Rule

The issue is caused by the rule: `pip_parse`

### Is this a regression?

No.

### Description

`pip_parse` does not work with custom (URL-based) sources of packages.

## 🔬 Minimal Reproduction

If I have this listed in my `requirements_lock`, the rule will actually install `spacy-transformers` from PyPI with no version specified instead of downloading the archive from github. 

```
https://github.com/explosion/spacy-transformers/archive/015daa34efbf2202b56080954832d029b99f821a.zip#egg=spacy-transformers \
    --hash=sha256:f81470a17f999975b525d265a41d28a417944984774a710387cafeba47e0407
```

Additionally, it looks like the `--hash` is completely ignored for all packages.

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Linux
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
Build label: 4.0.0
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Jan 21 07:33:24 2021 (1611214404)
Build timestamp: 1611214404
Build timestamp as int: 1611214404
  </code>
</pre>

**Rules_python version:** 

16965937f5e1f1ddc888c523323d0db8155241b1

**Comment by ajbouh** [comment]
I ran into this issue as well.

I forked rules_python locally and modified https://github.com/bazelbuild/rules_python/blob/5126cf1bd3d423bbb6aebe14e44546ca2585ea44/python/pip_install/parse_requirements_to_bzl/__init__.py#L24

to be `str(ir.link or ir.req)`.

So overall the method goes from:
```python
def repo_names_and_requirements(install_reqs: List[InstallRequirement], repo_prefix: str) -> List[Tuple[str, str]]:
    return [
        (
            bazel.sanitise_name(ir.name, prefix=repo_prefix),
            str(ir.req)
        )
        for ir in install_reqs
    ]
```

To
```python
def repo_names_and_requirements(install_reqs: List[InstallRequirement], repo_prefix: str) -> List[Tuple[str, str]]:
    return [
        (
            bazel.sanitise_name(ir.name, prefix=repo_prefix),
            str(ir.link or ir.req)
        )
        for ir in install_reqs
    ]

**Comment by hrfuller** [comment]
Thanks for the bug report. @ajbouh Would you open a pull request with that change? It looks reasonable to me.

**Comment by hrfuller** [comment]
@titanous do you have a repro for --hash being ignored? It may be that your --require-hashes flag is not getting propagated correctly due to https://github.com/bazelbuild/rules_python/issues/438
