### ISSUE TITLE
Bazel failing to Install Scipy Module

### ISSUE THREAD

**Issue by stephenjones5543** [bazelbuild/rules_python#465]
# 🐞 bug report
### Affected Rule

 The issue is caused by pip_install

### Is this a regression?

 No

### Description

Running ``` bazel run  //main:main``` at the  project root folder throws error.

## 🔬 Minimal Reproduction
I have tried to setup a tiny repo to replicate this issue, kindly [check it out here. ](https://github.com/stephenjones5543/bazel-test) 

## 🔥 Exception or Error
Please check the [error log output here](https://github.com/stephenjones5543/bazel-test/blob/main/main/output.log)

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
MacOS Big Sur Version 11.1
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
Build label: 4.0.0-homebrew
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Sat Jan 23 02:07:47 2021 (1611367667)
Build timestamp: 1611367667
Build timestamp as int: 1611367667
  </code>
</pre>

**Rules_python version:**

<pre>
  <code>
Using the SHA digest 0ab06a2d6cc5abca83d9c8a21d65630b773a079b
  </code>
</pre>

**Anything else relevant?**

**Comment by person142** [comment]
So you're getting a timeout, which almost surely means that your system is trying to compile SciPy, which takes quite a while (longer than 600s certainly). It looks like you are using SciPy 1.0.0:

https://github.com/stephenjones5543/bazel-test/blob/main/main/requirements.txt#L21

which is quite old and only has wheels for up to Python 3.6:

https://pypi.org/project/scipy/1.0.0/#files

I suspect that using a newer version of SciPy will unblock you.

**Comment by thundergolfer** [comment]
Thanks @person142 👍
