### ISSUE TITLE
pip_install doesn't treat python_version correctly for Python 3.10+

### ISSUE THREAD

**Issue by codeschlosser** [bazelbuild/rules_python#468]
### Description
pip_install doesn't treat python_version correctly for Python 3.10+

## 🔬 Minimal Reproduction
Try installing "asgiref=3.3.4" pip dependency via pip_install with python having version >= 3.10
asgiref's METADATA mentions requirement for typing-extnensions:

`Requires-Dist: typing-extensions ; python_version < "3.8"`

## 🔥 Exception or Error

`BUILD file not found in directory 'pypi__typing_extensions' of external repository @workspace_name.`

## 🌍  Your Environment

**Debian 10**
**bazel 4.0.0**
**Rules_python version: both 2.0 and current master**

## Anything else relevant?
~~It _seems_ like an issue is in [line 53 of wheel.py](https://github.com/bazelbuild/rules_python/blob/master/python/pip_install/extract_wheels/lib/wheel.py#L53) where it should be `or []` instead of `or [""]`, but I don't have a holistic understanding of rules_python, so no PR, just a bug~~

**Comment by thundergolfer** [comment]
> pip_install ignores python_version requriement

Could be that there's a Python version mismatch between what's used at runtime when installing the dependencies and what's used when running the `py_` target. But...

That doesn't match up in my head with the error you provide: 

> `BUILD file not found in directory 'pypi__typing_extensions' of external repository @workspace_name.`

----

If I install that package at your specified version with Python 3.9.2 and `rules_python` 0.2.0 I can successfully run a program using the dependency.

```python
import asgiref.sync

def run():
    print("hello world")
    print(asgiref.sync.__file__)

if __name__ == "__main__":
    run()
```

**Output:**

```
hello world
/private/var/tmp/_bazel_jonathon/d674c99385955331871afd0b7a4cb642/execroot/rules_python_demo/bazel-out/darwin-fastbuild/bin/helloworld/helloworld.runfiles/pypi/pypi__asgiref/asgiref/sync.py
```

----

I think to better debug your issue it would be helpful to get a reproduction.

**Comment by codeschlosser** [comment]
My fault for poor investigation. Fails with Python 3.10, but not with Python 3.9. Anyway, closing until I figure out stable way to reproduce it

**Comment by codeschlosser** [comment]
Yes, this is Python 3.10+ problem. The problem is actually with `setuptools` package. The version that is used by `rules_python` is 44 which doesn't include the [commit](https://github.com/pypa/setuptools/commit/c30aca86261cac34b60e679a1ee430dbc968582c#diff-1257648538b26ebaa2baa20146231d59030efd2818dbb2dd79e12a96160b97deR262) that fixes default python_version variable definition for markers

**Comment by thundergolfer** [comment]
Thanks for that update. I guess this would be sorted by merging https://github.com/bazelbuild/rules_python/pull/422.

**Comment by bweston92** [comment]
Hey @codeschlosser is this issue ok to close now is the problem fixed?

**Comment by codeschlosser** [comment]
Works now, thanks!
