### ISSUE TITLE
Direct dependency `funcsigs` of pip_imported `mock` package not available

### ISSUE THREAD

**Issue by nikhaldi** [bazelbuild/rules_python#49]
A minimal repro needs multiple files (also in the attachment [funcsigs-repro.tar.gz](https://github.com/bazelbuild/rules_python/files/1533133/funcsigs-repro.tar.gz) for convenience):

WORKSPACE:
```
git_repository(
    name = "io_bazel_rules_python",
    remote = "https://github.com/bazelbuild/rules_python.git",
    commit = "346b898e15e75f832b89e5da6a78ee79593237f0"
)

load("@io_bazel_rules_python//python:pip.bzl", "pip_import")
pip_import(
   name = "requirements",
   requirements = "//:requirements.txt",
)

load("@requirements//:requirements.bzl", "pip_install")
pip_install()
```

BUILD:
```
exports_files(["requirements.txt"])

load("@requirements//:requirements.bzl", "requirement")

py_binary(
    name="run",
    srcs=["run.py"],
    deps=[
        requirement('mock'),
    ],
)
```

requirements.txt:
```
mock==2.0.0
```

run.py:
```
import mock
```

Then to reproduce run:

```
$ bazel run //:run
INFO: Found 1 target...
Target //:run up-to-date:
  bazel-bin/run
INFO: Elapsed time: 1.138s, Critical Path: 0.03s

INFO: Running command line: bazel-bin/run
Traceback (most recent call last):
  File "/private/var/tmp/_bazel_nik/5a08842075e4d3de340bcb5074db6110/execroot/__main__/bazel-out/darwin_x86_64-fastbuild/bin/run.runfiles/__main__/run.py", line 1, in <module>
    import mock
  File "/private/var/tmp/_bazel_nik/5a08842075e4d3de340bcb5074db6110/execroot/__main__/bazel-out/darwin_x86_64-fastbuild/bin/run.runfiles/pypi__mock_2_0_0/mock/__init__.py", line 2, in <module>
    import mock.mock as _mock
  File "/private/var/tmp/_bazel_nik/5a08842075e4d3de340bcb5074db6110/execroot/__main__/bazel-out/darwin_x86_64-fastbuild/bin/run.runfiles/pypi__mock_2_0_0/mock/mock.py", line 80, in <module>
    import funcsigs
ImportError: No module named funcsigs
ERROR: Non-zero return code '1' from command: Process exited with status 1.
```

Important: This doesn't reproduce if `funcsigs` is globally installed (which it will be on many Linuxes). So you may have to do the following:

```
$ virtualenv --no-site-packages venv
$ source venv/bin/activate
$ bazel run //:run
...
```

I can reproduce this with bazel 0.7 on OS X Sierra and Ubuntu 16.04. As far as I can tell, the `funcsigs` wheel gets pulled when `requirements.txt` is processed but when the Python dependencies for the build target are put together, it's somehow not included. I can see it's not in `bazel-bin/run.runfiles`, even though the other dependencies (`six` and `pbr`) are.

I did notice that the version specification at https://github.com/testing-cabal/mock/blob/master/requirements.txt#L1 is a bit funky (`funcsigs>=1;python_version<"3.3"`). Maybe it's failing to parse that correctly?

**Comment by nikhaldi** [comment]
Oh wow, after I wrote this I discovered there is a test which explicitly asserts the existence of this bug: https://github.com/bazelbuild/rules_python/blob/master/rules_python/whl_test.py#L63-L64

Not sure what the motivation was here. I guess it this makes sure that things work correctly on Python 3.3+ but it happens to be broken at lower versions.

**Comment by nikhaldi** [comment]
And I now understand that any support the Python version restriction is missing: https://github.com/bazelbuild/rules_python/blob/master/rules_python/whl.py#L89-L93

I'm happy to try to provide a fix, this seems like quite an important feature. Any ideas how to best approach this welcome though. It seems there must be some piece of code maybe in wheel that can interpret the version restrictions.

**Comment by mattmoor** [comment]
Yeah I think there were two main reasons I didn't want to handle this when I originally put this together.
1. Not sure how to determine the intended Python version from Bazel.
1. Didn't want to parse these strings myself.

There is probably a lib somewhere in pip/wheel for the latter, but I still don't know about the former.

@duggelz FYI

**Comment by nikhaldi** [comment]
For 2 the correct answer appears to be `pkg_resources.evaluate_marker()` (https://github.com/pypa/setuptools/blob/b2e99f6731c6ba6fe6bd60f79f2166640f3db21d/pkg_resources/__init__.py#L1449).

The underlying `Marker` parser does allow passing in a customized environment, so we can override the version of the Python interpreter that's executing right now, if need be. But I'm not sure I understand this issue. Is the Python interpreter building a Python target ever expected to be different from the one that will run the built target? I don't see how that would even work.

**Comment by nikhaldi** [comment]
@mattmoor I tested my fix a bunch, as far as I can tell it works.

Can you elaborate on your concerns about the intended Python version? Maybe you are referring to the scenario where you're building packages/binaries (e.g., pars) on one machine that are supposed to be portable to other machines maybe with a different interpreter?

First, I think this only works if you have no dependencies with C extensions. If you are building portable executables you have to very consciously choose dependencies to be pure-Python and you have to make explicit decisions about anything that depends on specific Python versions. I seems if you're doing that you're probably not in conflict with my fix, as you've already made those explicit choices in your requirements file.

**Comment by mattmoor** [comment]
> Is the Python interpreter building a Python target ever expected to be different from the one that will run the built target? I don't see how that would even work.

I don't feel like I'm the right person to make a judgement call on this.  @duggelz is probably significantly better qualified, so I'll defer to his wisdom here.

I will leave this flagged and try to review it next week, apologies for the delay (I was at Kubecon last week).

**Comment by duggelz** [comment]
It's actually common for the tools to run under a different Python version than the result .par file runs under.  Right now, for example, Bazel will often/always run tools under Python2 even when the resulting .par file is intended to run under Python3.  Even when that's fixed, cross compile, remote execution, and iOS/Android scenarios need to be handled somehow.

**Comment by duggelz** [comment]
Medium term, Bazel will be adding Python [toolchains](https://docs.bazel.build/versions/master/toolchains.html).  I'm not sure what the short-term answer is.

**Comment by nikhaldi** [comment]
@duggelz ok, that makes sense.

To make sure I got the ground rules correct, I see essentially two cases:

1. Building a par with pure-Python dependencies only. The result will run on multiple Python versions and platforms as long as the the Python code is portable. Today the actual dependencies used are the same regardless of the Python interpreter used to build but they are somewhat random (environment markers are ignored). After my change, the dependencies used depend on the build interpreter. Both behaviours are not ideal but I think my point stands that if you truly care about portability you anyway carefully choose all your dependencies manually.
2. Building (compiling) a par with C extensions. The result will generally only be compatible with a specific Python version/platform. Today you can do this only by building on the same interpreter/platform that will be running it. In the future there may be cross-compilation options where you'll have to specify a specific target version/platform.

I think it's clear that in the future there will have to be some way to target a specific Python version/platform. Once there is support for that, my change is easily adapted to use that environment when parsing environment markers.

**Comment by hwright** [comment]
> Bazel will often/always run tools under Python2 even when the resulting .par file is intended to run under Python3.

@duggelz I'm unconvinced, given the fact that things like google/containerregistry#42 exist.  If anything, Bazel appears to be a bit schizophrenic about what python version it uses, because sometimes it uses the specified `py_runtime` to run internal tools (as above), but other times it won't (as in #33).

I do agree that getting proper toolchain support would be nice (similar to what Go already uses, iiuc).

**Comment by nikhaldi** [comment]
@duggelz @mattmoor #50 now addresses this in a way I think is reasonable. Any other thoughts?
