### ISSUE TITLE
bazel build failing - pip_deps dying due to SigKill

### ISSUE THREAD

**Issue by raj-trustlab** [bazelbuild/rules_python#491]
I'm using ubuntu/focal64 on vagrant, and trying to get a bazel toolchain working for development.

I did pip3 install -r requirements.txt on my teams repo, and it seems to have successfully installed all the requirements. However I then run `bazel build /path/to/target:run` on some target, and get the following output:

```
... <More Packages Loaded here> ...
Collecting torch==1.7.1
 (Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/vagrant/.cache/bazel/_bazel_vagrant/f9910d98673307a31f928c448bd4acd0/external/rules_python/python/pip_install/extract_wheels/__main__.py", line 5, in <module>
    main()
  File "/home/vagrant/.cache/bazel/_bazel_vagrant/f9910d98673307a31f928c448bd4acd0/external/rules_python/python/pip_install/extract_wheels/__init__.py", line 87, in main
    subprocess.run(pip_args, check=True)
  File "/usr/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/home/vagrant/venv/bin/python3', '-m', 'pip', '--isolated', 'wheel', '-r', '/home/vagrant/tech-backends/requirements.txt']' died with <Signals.SIGKILL: 9>.
)
WARNING: Target pattern parsing failed.
ERROR: no such package '@pip_deps//': rules_python_external failed: Collecting gremlinpython==3.4.6
  Using cached gremlinpython-3.4.6-py2.py3-none-any.whl (61 kB)
Collecting aenum==2.2.3
  Using cached aenum-2.2.3-py3-none-any.whl (40 kB)
... <More Packages Loaded here> ...
```
This same pattern repeats about 4 times (as in has an error in the exact same spot), before finally showing a `FAILED: Build did NOT complete successfully (0 packages loaded)`.

Any ideas on what's going on here? Is there a problem with "torch"? (Since it dies there everytime). Note - I don't think there is an issue with "gremlinpython==3.4.6", I think the "rules_python_external_failed:..." line is missing a newline character.

Follow-up: I ran `python3 -m pip --isolated wheel -r requirements.txt` directly, and it gets killed at
```
Collecting tensorflow_hub==0.8.0
  Using cached tensorflow_hub-0.8.0-py2.py3-none-any.whl (101 kB)
Collecting torch==1.7.1
Killed
```

So I think something is wrong with how pip is installing wheels for torch?

Re-Posted from StackOverflow: https://stackoverflow.com/questions/68027230/bazel-build-failing-pip-deps-dying-due-to-sigkill

**Comment by aaliddell** [comment]
Check your RAM usage during the install. SIGKILL is sent by the out-of-memory killer when you run out of free memory. You’ll generally only see this when installing very big packages, such as Torch or tensorflow. The solution is basically to free up some memory prior to running the install or make the VM bigger.

**Comment by raj-trustlab** [comment]
Hmm, my VM had 4gb. In order to fix it, what I ended up having to do was downgrade my VM to ubuntu/bionic64 (it was on focal64), and switch to python 3.7+ (instead of 3.8+ which was on ubuntu/focal64). Things seem to be working now under the same CPU / Ram configs.

Appreciate the help. If I bump into this again, I'll see if increasing the ram helps.
