### ISSUE TITLE
Rename 'master' branch to 'main'

### ISSUE THREAD

**Issue by thundergolfer** [bazelbuild/rules_python#500]
In line with [bazelbuild/bazel#12200](https://github.com/bazelbuild/bazel/issues/12200) and following the directions at https://github.com/github/renaming. 

https://github.com/github/renaming#renaming-existing-branches shows the process to be well supported by Github.

I will leave this issue up while preliminary discussion is had with other maintainers.

**Comment by alexeagle** [comment]
This sounds fantastic to me!

My only concern is that in my experience not everything from master gets redirected. In particular, what happens to open pull requests when the branch they are targetting changes? Not sure how much of this we can know ahead-of-time but I think it's the right thing to do anyway.

**Comment by thundergolfer** [comment]
> what happens to open pull requests when the branch they are targetting changes? 

Github docs say these get automatically updated, which is great.

**Comment by UebelAndre** [comment]
Pull requests are automatically redirected (assuming you simply renamed the branch). Users will see a similar message when they view their forks.
<img width="537" alt="Screen Shot 2021-02-12 at 8 46 11 AM" src="https://user-images.githubusercontent.com/26427366/124211071-61c7b580-daa1-11eb-9430-10627ca7dd37.png">

**Comment by alexeagle** [comment]
Cool I think that has improved since last time I renamed one

**Comment by UebelAndre** [comment]
Renaming is pretty painless. GitHub raises awareness to the users. Passed that the only thing you need to do is ping someone to update the branch for CI.

**Comment by alexeagle** [comment]
bazel CI *ought* to use whatever is the default branch. but if something is hard-coded over there @fweikert has been very responsive fixing it :)
let's do it

**Comment by thundergolfer** [comment]
Done 👍 

The instructions Github provides to update locally are: 

```
git branch -m master main
git fetch origin
git branch -u origin/main main
```

You should see Github showing the same in a notice on the repo. 👌
