### ISSUE TITLE
it should be possible to use different versions of python in different rules

### ISSUE THREAD

**Issue by symbiont-ji** [bazelbuild/rules_python#506]
# 🚀 feature request

### Relevant Rules

Add a feature to `py_binary`, `py_test`, and possibly `par_binary`.

### Description

 A clear and concise description of the problem or missing capability...

In a large monorepo, there is bound to be python code that requires older versions of python, either for bug-to-bug compatibility or because some package does not yet exist for the newer version. For example, we have some code that will only run with python3.7.2, whereas most of our stuff runs with python3.9.

I know about `py_runtime` and `toolchain`, but that changes the python version for everything.

### Describe the solution you'd like

a `python_executable` parameter in `py_binary`, `par_binary`, and `py_test`

 If you have a solution in mind, please describe it.

### Describe alternatives you've considered

 Have you considered any alternative solutions or workarounds?

**Comment by thundergolfer** [comment]
> I know about py_runtime and toolchain, but that changes the python version for everything.

Bazel has a toolchain resolution process, and it can select between different toolchains given constraints you set on your targets. Have you looked into have 2 toolchains and constraints on `py_*` targets to select between them?

**Comment by symbiont-ji** [comment]
Where is this documented? I don't want to write my own python rules!
