### ISSUE TITLE
Increase min tested Bazel version to 4.0.0

### ISSUE THREAD

**Issue by UebelAndre** [bazelbuild/rules_python#526]
# 🚀 feature request

### Description

 A clear and concise description of the problem or missing capability...

Writing tests and new features for these rules is difficult since there are a few new features (for me, the `env` attribute and `json` module) that are incredibly useful pretty un-fun to work around, making changes take more time than the need to. The min tested version should be bumped to 4.0.0 to enable the use of these features.

### Describe the solution you'd like

 If you have a solution in mind, please describe it.
Update the bazel versions in [.bazelrc](https://github.com/bazelbuild/rules_python/blob/bef2244d295ea5bf979261513b31bf38b941ac28/.bazelversion) and [version.bzl](https://github.com/bazelbuild/rules_python/blob/bef2244d295ea5bf979261513b31bf38b941ac28/version.bzl#L23) to `4.0.0`

### Describe alternatives you've considered

 Have you considered any alternative solutions or workarounds?
Alternatively, it'd be nice to have a well documented way to conditionally use things in newer versions of Bazel. Perhaps `native.bazel_version` could be made available to rules and macros (not just repository rules) (https://github.com/bazelbuild/bazel/issues/8305) but that would likely also require some way to compare versions which I'm only aware of [@bazel_skylib//lib:versions.bzl](https://github.com/bazelbuild/bazel-skylib/blob/1.0.3/docs/versions_doc.md).

**Comment by alexeagle** [comment]
Agreed - it's a breaking change for users, but we made the same in rules_nodejs to reduce support burden. LTS and rolling releases are the only ones I think we need to support.
