### ISSUE TITLE
supporting google_cloud_core[grpc] style package names

### ISSUE THREAD

**Issue by asa** [bazelbuild/rules_python#53]
Trying to pip package google-cloud-logging, which depends on the strangely named  google_cloud_core[grpc] package  causes problems. 
if my py_image target has a layer thats looking for **requirement("google-cloud-logging")**, I get the following:

ubuntu@ubuntu-xenial:/code$ bazel build app:app_image
ERROR: /home/ubuntu/.cache/bazel/_bazel_ubuntu/3a20ab50938efa4ee22db80044ad3a50/external/pypi__google_cloud_logging_1_4_0/BUILD:6:1: Traceback (most recent call last):
	File "/home/ubuntu/.cache/bazel/_bazel_ubuntu/3a20ab50938efa4ee22db80044ad3a50/external/pypi__google_cloud_logging_1_4_0/BUILD", line 6
		py_library(name = "pkg", srcs = glob(["**/*.p..."]), <3 more arguments>)
	File "/home/ubuntu/.cache/bazel/_bazel_ubuntu/3a20ab50938efa4ee22db80044ad3a50/external/pypi__google_cloud_logging_1_4_0/BUILD", line 13, in py_library
		requirement("google-cloud-core[grpc]")
	File "/home/ubuntu/.cache/bazel/_bazel_ubuntu/3a20ab50938efa4ee22db80044ad3a50/external/gcloud_minimal/requirements.bzl", line 290, in requirement
		_requirements[name]
**key "google_cloud_core[grpc]" not found in dictionary**
ERROR: /code/app/BUILD:37:1: no such target '@pypi__google_cloud_logging_1_4_0//:pkg': target 'pkg' not declared in package '' defined by /home/ubuntu/.cache/bazel/_bazel_ubuntu/3a20ab50938efa4ee22db80044ad3a50/external/pypi__google_cloud_logging_1_4_0/BUILD and referenced by '//app:app_image.binary'

Many other pip packages install fine this way, just not the google cloud ones that end up looking for grpc this way, such as **googleapis-common-protos[grpc]**

Any help would be great.

**Comment by mattmoor** [comment]
Does this reproduce against the latest version of `rules_python`?  I expect it should be covered by the support for "extras" which landed relatively recently.

**Comment by asa** [comment]
Ha!  yes, what a difference a few days makes. This works fine in 44711d8ef543f6232aec8445fb5adce9a04767f9    Thanks!
