### ISSUE TITLE
Feature: Pass Analysis Phase In Environments without Python 3.6+ Installed

### ISSUE THREAD

**Issue by gnossen** [bazelbuild/rules_python#542]
# 🚀 feature request

### Relevant Rules

`pip_install`

### Description

When upgrading from `0.0.1` to `0.4.0`, I found a difference in behavior. The [gRPC repo](https://github.com/grpc/grpc) is a monorepo of sorts. It houses codebases in C++, Python, Objective-C, C#, Ruby, and PHP. most of which have Bazel builds and some of which have remote build execution CI jobs.

While each of these languages has a separate CI job with its own build environment (i.e. with different dependencies installed), they still share a `WORKSPACE` file. So any repo rules included in the `WORKSPACE` must still pass the analysis phase regardless of what dependencies may or may not be installed on the system. For example, the Windows C++ RBE image does not have a Python interpreter installed at all and it does not build any Python targets. However, when upgrading to `0.4.0`, I found this job broken during the analysis phase.

Further, our Linux C++ RBE image has Python 3.5 installed. So, the f-strings and type annotations in the repo rules broke the analysis phase there.

### Describe the solution you'd like

I've already implemented this feature in [a patch](https://github.com/grpc/grpc/blob/60028a82a9ec546141ef98e92655cf0dfb35180e/third_party/rules_python.patch) in the gRPC repo, which I am happy to rework and contribute upstream. It works by detecting 1) whether a Python interpreter is installed at all and 2) whether that interpreter meets the minimum requirements assumed by the Python code in `rules_python`. If the answer is "no" to either of these, we replace the output of the `requirement` rule to be an empty `py_library`, i.e. `py_library(name = "empty", srcs=[])`. This has worked for all of the cases where we've seen issues so far.

I would like to know whether the maintainers

1. View this as a valid use case.
2. Find this approach reasonable.
3. Are amenable to me contributing this solution upstream.
4. Know of any constraints I might not have mentioned already.

**Comment by gnossen** [comment]
@phlax @hrfuller Looking for some maintainer engagement on this.

**Comment by thundergolfer** [comment]
@gnossen Have we addressed your concerns, or at least provided good workarounds?
