### ISSUE TITLE
Support pyd creation

### ISSUE THREAD

**Issue by abergmeier-dsfishlabs** [bazelbuild/rules_python#546]
### Description of the problem / feature request / question:

Native Python modules on Windows need to have a `.pyd` extension (or they will not be recognized).
`cc_binary` does not handle correctly if `name` is e.g. `foo.pyd`.
You get error message like:

    ERROR: ... in linkshared attribute of cc_binary rule //foo.pyd: 'linkshared' used in non-shared library.

### If possible, provide a minimal example to reproduce the problem:

    cc_binary(
        name = "foo.pyd",
        linkstatic = 1,
        linkshared = 1,
    )

### Environment info
* Operating System: Windows 10
* Bazel version (output of `bazel info release`): 0.4.4

###  Have you found anything relevant by searching the web? (e.g. GitHub issues, email threads in the [bazel-discuss@googlegroups.com](https://groups.google.com/forum/#!forum/bazel-discuss) archive)
Nope

### Anything else, information or logs or outputs that would be helpful?
So IMO either allow any `name` to be a shared library or perhaps provide a `py_cc_library`, which handles this specially.

**Comment by stellaraccident** [comment]
I'm still seeing patches in OSS projects that work around this in gross ways so i think is still a problem. Please don't close unless if fixed.

**Comment by meteorcloudy** [comment]
/cc @oquenchil Is it OK we just add "pyd" as an extra extension of shared library here: 
https://cs.opensource.google/bazel/bazel/+/master:src/main/java/com/google/devtools/build/lib/rules/cpp/CppFileTypes.java;l=207

**Comment by oquenchil** [comment]
If it works then by all means.

**Comment by meteorcloudy** [comment]
So anyone what's to add pyd support, feel free to send a PR.

**Comment by stellaraccident** [comment]
Such a good would be a a stopgap for this very specific case, but I can't think of any reason why the build tool should be enforcing anything here. If you really wanted this to be first class, you would allow the output name to be set (and be configurable) independently (which is what cmake allows). Even with an additional exception, people wanting to have one rule that generates the .so/.dylib/.pyd can't do that. It's really janky and compares badly to cmake, which supports the flexibility for all of the uses in the wild.

**Comment by Mizux** [comment]
@stellaraccident
technically it's `.so`/`.so`/`.pyd` (yes on macos you must also use `.so` for "native" package :face_exhaling: )
ref:
* https://github.com/python/cpython/blob/8781a041a00b7a202d73bcb47606ea10e56fb1d1/Python/dynload_shlib.c#L46
* https://github.com/python/cpython/blob/8781a041a00b7a202d73bcb47606ea10e56fb1d1/Python/dynload_win.c#L29

@meteorcloudy 
IMHO I would do like rust and its `RUST_RLIB`:
```
 // dynamic library artifact created to be used as python module.
// see https://docs.python.org/3/extending/building.html#building-c-and-c-extensions
  public static final FileType PYTHON_C_EXTENSIONS = FileType.of(".so", ".pyd");
```
then add it here and there..
e.g. https://cs.opensource.google/bazel/bazel/+/master:src/main/java/com/google/devtools/build/lib/rules/python/PyCommon.java;l=327
