### ISSUE TITLE
Issue with the way we declare pypi dependencies

### ISSUE THREAD

**Issue by mouadino** [bazelbuild/rules_python#56]
I have a project with multiple python sub-project, respectively multiple `requirements.txt`, however, there is an issue in the way we layout `whl_library` dependencies which lead to test operations to fail with `no such target '@pypi__setuptools_38_4_0//:certs': target 'certs' not declared in package '' defined by`.

The reason for such failure is b/c the two python subprojects generate the following snippet `requirements.bzl` file:

Project A:
```
if "pypi__setuptools_38_4_0" not in native.existing_rules():
    whl_library(
        name = "pypi__setuptools_38_4_0",
        whl = "@project_a_deps//:setuptools-38.4.0-py2.py3-none-any.whl",
        requirements = "@project_a_deps//:requirements.bzl",
        extras = ["certs","ssl"]
    )
```

Project B:
```
if "pypi__setuptools_38_4_0" not in native.existing_rules():
    whl_library(
        name = "pypi__setuptools_38_4_0",
        whl = "@project_b_deps//:setuptools-38.4.0-py2.py3-none-any.whl",
        requirements = "@project_b_deps//:requirements.bzl",
        extras = ["ssl"]
    )
```
 
While since this open for implicit ordering in `WORKSPACE` file, its possible that `Project B` was first to generate `pypi__setuptools_38_4_0/BUILD` which mean we end up with the following `BUILD` file:

```

package(default_visibility = ["//visibility:public"])

load("@delivery_service_deps//:requirements.bzl", "requirement")

py_library(
    name = "pkg",
    srcs = glob(["**/*.py"]),
    data = glob(["**/*"], exclude=["**/*.py", "**/* *", "BUILD", "WORKSPACE"]),
    # This makes this directory a top-level in the python import
    # search path for anything that depends on this.
    imports = ["."],
    deps = [],
)
py_library(
    name = "ssl",
    deps = [
        ":pkg",
    ],
)
```

As you can see target `certs` is missing in setuptools BUILD hence it explains the failure above.

**Comment by mattmoor** [comment]
I think the only way to solve this would be to separate each extra into it's own separate repository, e.g. `pypi__setuptools_39_4_0__ssl`.

Basically Project B's `.whl` files don't have enough context to generate a single `BUILD` file with all of the possible targets.

As a workaround, you can re-order the calls to `pip_install` so that the broadest version is installed first.  This only works if the one you put first is a superset (in the overlapping deps), and wouldn't work for:
```python
=== A ===
foo[a,b]
bar[c]

=== B ===
foo[a]
bar[c,d]
```

**Comment by mouadino** [comment]
While relaying on order is theoretically feasible, however, I think it's quite an implicit contract from one side, in the other side with dozens of subprojects like in our case such ordering is quite hard to achieve practically.

Currently, our workaround is to generate a concatenation of all requirements.tx files (using some bash scripts that we hook before running Bazel commands) and then pass this to `pip_import`, we also in each subproject use `all_requirements` from this rule (mainly b/c we cannot expect our subprojects owners to maintain `requirement("...")` manually for the time being), the tradeoffs here are:

- We need to make sure all requirements.txt pin dependencies to the same version i.e. you cannot have subproject A depends on `requests==1.0.0` and subprojects B depends on `requests==2.0.0`.
- Using `all_requirements` means having to install unwanted dependencies in some docker images (since we use this later to ship our code).

Both the above tradeoffs are fine and it also solves a second issue with the current API which is that the `pip_install` calls are sequential and doesn't benefit from a pip cache, which means if two subprojects use the same dependency this later will be downloaded twice, this ends up to be quite slow when you have dozens of sub-projects. 

Generating something like `pypi__setuptools_39_4_0__ssl` is one way to go however I am not sure how this will react to dependencies like `setuptools[ssl,certs]` as an example? b/c and correct me if I misunderstood something, but I think from python import side you may end up with two `pypi__setupstools...` one with `ssl` another with `certs` that includes the same code which can lead to imports issues down the road.

Thoughts?

**Comment by duggelz** [comment]
There's actually some ongoing discussion on the Python Packaging mailing list about this problem.  I.e. it's not just a Bazel problem, although we can figure out some Bazel-specific fixes.

https://mail.python.org/pipermail/distutils-sig/2018-January/031910.html

**Comment by groodt** [comment]
@mouadino This is a very old issue using very old versions of rules_python. Things have changed a lot since then and we now encourage a single transitively closed "lockfile" for third_party dependencies. Take a look and see if the updated rules meet your needs. I've added a label to autoclose this issue in any case, since I imagine you have found sufficient workarounds for now or no longer are waiting on this issue.
