### ISSUE TITLE
The python interpreter cannot be found with requirement generated by running pip_install 

### ISSUE THREAD

**Issue by heounsuk** [bazelbuild/rules_python#563]
# 🐞 bug report
### Description
The python interpreter cannot be found with requirement generated by running pip_install 

## 🔬 Minimal Reproduction
The python interpreter cannot be found in the most recent version environment

load("@rules_python//python:defs.bzl", "py_binary")
load("@my_dep//requirements.bzl", "requirement")

BUILD file
<pre><code>
py_binary(
    name = "main",
    srcs = [
        "main.py",
    ],
    deps = [
        requirement("click"),
    ],
)
</code></pre>

WORKSPACE
<pre><code>

workspace(name = "py3_image")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
http_archive(
    name = "rules_python",
    url = "https://github.com/bazelbuild/rules_python/releases/download/0.5.0/rules_python-0.5.0.tar.gz",
    sha256 = "cd6730ed53a002c56ce4e2f396ba3b3be262fd7cb68339f0377a45e8227fe332",
)

load("@rules_python//python:pip.bzl", "pip_install")
pip_install(
    name="my_dep",
    python_interpreter = "python3",
    requirements = "//:requirements.txt",
)

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
http_archive(
    name = "io_bazel_rules_docker",
    sha256 = "1f4e59843b61981a96835dc4ac377ad4da9f8c334ebe5e0bb3f58f80c09735f4",
    strip_prefix = "rules_docker-0.19.0",
    urls = ["https://github.com/bazelbuild/rules_docker/releases/download/v0.19.0/rules_docker-v0.19.0.tar.gz"],
)

load(
    "@io_bazel_rules_docker//repositories:repositories.bzl",
    container_repositories = "repositories",
)
container_repositories()

load("@io_bazel_rules_docker//repositories:deps.bzl", container_deps = "deps")
container_deps()

load(
    "@io_bazel_rules_docker//python3:image.bzl",
    _py_image_repos = "repositories",
)
_py_image_repos()

load(
    "@io_bazel_rules_docker//container:container.bzl",
    "container_pull",
)

container_pull(
    name = "python3.8_image",
    registry = "index.docker.io",
    repository = "python",
    tag = "3.8",
)

</code></pre>

## 🔥 Exception or Error

<pre><code>
INFO: Repository my_dep instantiated at:
  C:/users/heoun/py3_image/WORKSPACE:13:12: in <toplevel>
  C:/users/heoun/_bazel_heoun/o6ry3odc/external/rules_python/python/pip.bzl:96:19: in pip_install
Repository rule pip_repository defined at:
  C:/users/heoun/_bazel_heoun/o6ry3odc/external/rules_python/python/pip_install/pip_repository.bzl:238:33: in <toplevel>
ERROR: An error occurred during the fetch of repository 'my_dep':
   Traceback (most recent call last):
        File "C:/users/heoun/_bazel_heoun/o6ry3odc/external/rules_python/python/pip_install/pip_repository.bzl", line 104, column 
53, in _pip_repository_impl
                python_interpreter = _resolve_python_interpreter(rctx)
        File "C:/users/heoun/_bazel_heoun/o6ry3odc/external/rules_python/python/pip_install/pip_repository.bzl", line 42, column 17, in _resolve_python_interpreter
                fail("python interpreter not found")
Error in fail: python interpreter not found
ERROR: Error fetching repository: Traceback (most recent call last):
        File "C:/users/heoun/_bazel_heoun/o6ry3odc/external/rules_python/python/pip_install/pip_repository.bzl", line 104, column 
53, in _pip_repository_impl
                python_interpreter = _resolve_python_interpreter(rctx)
        File "C:/users/heoun/_bazel_heoun/o6ry3odc/external/rules_python/python/pip_install/pip_repository.bzl", line 42, column 17, in _resolve_python_interpreter
                fail("python interpreter not found")
Error in fail: python interpreter not found
ERROR: Skipping ':main': no such package '@my_dep//requirements.bzl': python interpreter not found
WARNING: Target pattern parsing failed.
ERROR: no such package '@my_dep//requirements.bzl': python interpreter not found
INFO: Elapsed time: 3.284s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
    currently loading:

</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
window 10
  </code>
</pre>

**Output of `bazel version`:**
<pre>
  <code>

$ bazel --version
bazel 4.2.1

install by choco
  </code>
</pre>

**Rules_python version:**

<pre>
  <code>
$ py --version
Python 3.10.0

install by microsoft store
  </code>
</pre>

**Anything else relevant?**
run in vs code bash command console

**Comment by thundergolfer** [comment]
Some early thoughts: 

* Is the `rules_docker` a necessary part of the issue reproduction? If not, it can be removed to make a minimal reproduction.
* Your `rules_python` version is not `py --version`. It's `0.5.0` according to WORKSPACE file
* The repository rule that is failing looks up `python3` on your path. Can you check that `python3` is on your `PATH`? I'm not familiar with Windows, but a quick check would be to just run `python3` in your terminal.

**Comment by Danvil** [comment]
I have the same issue.

Running `python` in the windows terminal works, but running `python3` does not work.

**Comment by Danvil** [comment]
My rather crude workaround is to create a copy of `python.exe` in the python install folder and name it `python3.exe`.

**Comment by thundergolfer** [comment]
By default `pip_install` (and I think `pip_parse`) will just look up `python3` on the PATH. 

```
"python_interpreter": attr.string(default = "python3"),
```

If you don't have `python3` on the PATH the rule won't work. If `python` is python 3 on your system then you can explicitly set `python_interpreter = "python"` for your rule. 

Be aware that this is a bit brittle. You're just looking up python on the PATH and accepting whatever is found. It's better to provide `python_interpreter_target`.

**Comment by hrfuller** [comment]
Closing as answered.

**Comment by kylecordes** [comment]
Possibly helpful for the next person to come along:

While getting up and running, it is probably best to arrange things with your PATH thought that both python and python3 run your preferred version of Python 3.

**Comment by PeterBorisenko** [comment]
Excuse me, but what's the point of using `python3` notation instead of just `python`?
