### ISSUE TITLE
Release '0.5.0' is missing from the bazel build mirror

### ISSUE THREAD

**Issue by martis42** [bazelbuild/rules_python#566]
Release `0.4.0` is available at the bazel build mirror:
https://mirror.bazel.build/github.com/bazelbuild/rules_python/releases/download/0.4.0/rules_python-0.4.0.tar.gz

Please make release `0.5.0` also available at the mirror. The expected URL would be:
https://mirror.bazel.build/github.com/bazelbuild/rules_python/releases/download/0.5.0/rules_python-0.5.0.tar.gz

**Comment by limdor** [comment]
@philwo could you take a look?

**Comment by thundergolfer** [comment]
Yep, correct person has been pinged. Maintainers can't populated the mirror.

**Comment by thundergolfer** [comment]
Just checked that 0.5.0 URL again and no luck. 

@philwo re-ping 🙂

**Comment by philwo** [comment]
Sorry for the delay! Should be available on the mirror now:

```
Operation completed over 1 objects.                                              
Here's your snippet for the WORKSPACE file:

http_archive(
    name = "<NAME>",
    sha256 = "cd6730ed53a002c56ce4e2f396ba3b3be262fd7cb68339f0377a45e8227fe332",
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/rules_python/releases/download/0.5.0/rules_python-0.5.0.tar.gz",
        "https://github.com/bazelbuild/rules_python/releases/download/0.5.0/rules_python-0.5.0.tar.gz",
    ],
)
```
