### ISSUE TITLE
Lost permissions to execute

### ISSUE THREAD

**Issue by jschenxiaoyu** [bazelbuild/rules_python#58]
## Description of the problem
I am using pyspark in my project and want to import pyspark using rules_python.

Here is my requirements.txt:
`py4j==0.10.4`
`pyspark==2.2.0.post0`

After `bazel build`, I found in `~/.cache/bazel/_bazel_xxx/xxxxx/external/pypi__pyspark_2_2_0/pyspark/bin` and all files lost execute permission.

## Environment info

- Operating System
Ubuntu 16.04 LTS

**Comment by duggelz** [comment]
The rules do not currently examine the 'script' metadata attribute and set executable permissions.

**Comment by rotemtam** [comment]
Any update on this?

**Comment by thundergolfer** [comment]
I think this PR addresses this issue? https://github.com/bazelbuild/rules_python/pull/333

**Comment by gmweaver** [comment]
@rotemtam tried the changes I made in #333 with `pyspark` for a current project and the executables were restored successfully. Both `bazel build` and `bazel test` also succeeded, where some of the tests depend on a Spark session.

**Comment by rotemtam** [comment]
Great, looking forward for this to land in https://github.com/bazelbuild/rules_python/ ! 👍

**Comment by thundergolfer** [comment]
Should be fixed by #333
