### ISSUE TITLE
pip_import doesn't respect --python_path

### ISSUE THREAD

**Issue by treuherz** [bazelbuild/rules_python#59]
Presently, if a library on PyPI shows different dependencies when pulled in from Python 3, rules_python will still pull in the Python 2 requirements. For example, grpcio has a cp27 and a cp36 wheel. The metadata.json in the cp27 version depends on enum34, and the cp36 one doesn't. If you're using `bazel build --python_path="python3.6"` then this can mess things up, as enum34 shadows the Python 3 stdlib's enum, but doesn't provide all the same attributes.

I've tracked the cause down to this call:
https://github.com/bazelbuild/rules_python/blob/73a154a181a53ee9e021668918f8a5bfacbf3b43/python/pip.bzl#L26-L32
In line 27, you'll note piptool.par is invoked with just `python`. As far as I can tell, this means piptool queries the cheeseshop with 2.7 as its version, and therefore gets the cp27 wheels.

This has taken me quite a while to figure out, and I'm happy to go the last mile and submit a PR for this, but I'm not sure of the best way to go about it. I can't figure out a way to access the `--python_path` arg from the Skylark script. Next idea was to piptool.par with `par_binary` as part of the `pip_import` process, in the hope that it would set the correct hashbang (i.e. would follow the `--python_path`) for the par, so that the par could be executed directly rather than as an arg to `python`. I assume there's a reason you've set it up to have the par be manually built, though.

**Comment by hwright** [comment]
This looks a lot like #37.

**Comment by treuherz** [comment]
It sure does. Wouldn't have found that one from the title! Closing this.

**Comment by hwright** [comment]
@treuherz Feel free to re-title that one if it would make it easier to find.
