### ISSUE TITLE
Locking tensorflow==2.7.0 with `bazel run //:requirements.update` breaks build

### ISSUE THREAD

**Issue by tanertopal** [bazelbuild/rules_python#603]
# 🐞 bug report

### Affected Rule

 The issue is caused by the rule: 

`load("@rules_python//python/pip_install:requirements.bzl", "compile_pip_requirements")`

### Is this a regression?

Not sure tbh.

### Description

 A clear and concise description of the problem...

## 🔬 Minimal Reproduction

Here is a repository which setups up everything and has a CI job configured which is showing the unexpected behavior:

* Repository: [bazel-rules_python-bug-report](https://github.com/tanertopal/bazel-rules_python-bug-report)
* CI: [Job](https://github.com/tanertopal/bazel-rules_python-bug-report/runs/4790825094)

## 🔥 Exception or Error

```bash
# This will fail
$ ./bazelisk run //:requirements.update
$ ./bazelisk build :server

...
Collecting wrapt==1.13.3
  Using cached wrapt-1.13.3-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (84 kB)
Collecting zipp==3.7.0
  Using cached zipp-3.7.0-py3-none-any.whl (5.3 kB)
Collecting setuptools>=40.3.0
 (ERROR: In --require-hashes mode, all requirements must have their versions pinned with ==. These do not:
    setuptools>=40.3.0 from https://files.pythonhosted.org/packages/eb/53/0dd4c7960579da8be13fa9b2c2591643d37f323e3d79f8bc8b1b6c8e6217/setuptools-60.5.0-py3-none-any.whl#sha256=68eb94073fc486091447fcb0501efd6560a0e5a1839ba249e5ff3c4c93f05f90 (from google-auth==2.3.3->-r /home/tanto/development/tensorflow-io-bazel-test/requirements.lock.txt (line 41))
Traceback (most recent call last):
  File "/home/tanto/.pyenv/versions/3.8.12/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/tanto/.pyenv/versions/3.8.12/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/tanto/.cache/bazel/_bazel_tanto/af96a3edade469226adcfd4a038e828a/external/rules_python/python/pip_install/extract_wheels/__main__.py", line 5, in <module>
    main()
  File "/home/tanto/.cache/bazel/_bazel_tanto/af96a3edade469226adcfd4a038e828a/external/rules_python/python/pip_install/extract_wheels/__init__.py", line 69, in main
    subprocess.run(pip_args, check=True)
  File "/home/tanto/.pyenv/versions/3.8.12/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/home/tanto/.pyenv/versions/3.8.12/bin/python3', '-m', 'pip', '--isolated', 'wheel', '-r', '/home/tanto/development/tensorflow-io-bazel-test/requirements.lock.txt']' returned non-zero exit status 1.
)
INFO: Elapsed time: 17.707s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
    currently loading:
```

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Ubuntu 20.04 in GitHub Actions
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
4.2.2
  </code>
</pre>

**Rules_python version:**

<pre>
  <code>
0.6.0
  </code>
</pre>

**Anything else relevant?**

**Comment by hrfuller** [comment]
Hey @tanertopal, thanks for reporting. It looks like one of the transitive dependencies of tensorflow doesn't have a pin on setuptools so pip_compile is refusing to select a definitive version. This does seem like a bug / non-ideal feature of the tool.

Having said that I can think of a few workaround for you.
1. in your requirements.in.txt pin a specific version of tensorflow.
2. use `extra_pip_args` in your instantiation of pip install to add `--allow-unsafe` as that comment suggests.

**Comment by hrfuller** [comment]
Looking deeper into this `--allow-unsafe` is a [pip-compile arg](https://github.com/jazzband/pip-tools/blob/master/piptools/scripts/compile.py#L161-L173). It looks like it will be flipped to default on in the future so we can preemptively do that in rules_python. I'll put up a PR.

**Comment by hrfuller** [comment]
You can work around this immediately using the extra_args attr of the compile_pip_requirements rule.

```
examples/pip_install/BUILD
72:    extra_args = ["--allow-unsafe"]
```

**Comment by hrfuller** [comment]
Closing as I don't think we should force everyone to opt in.

**Comment by tanertopal** [comment]
> You can work around this immediately using the extra_args attr of the compile_pip_requirements rule.
> 
> ```
> examples/pip_install/BUILD
> 72:    extra_args = ["--allow-unsafe"]
> ```

Thank you! I will try that.
