### ISSUE TITLE
Heads up: `setuptools` contain files with whitespaces in their names

### ISSUE THREAD

**Issue by abravalheri** [bazelbuild/rules_python#617]
Hello, I would like to thank the authors, maintainers and all contributors for making such a cool project 😄 

The reason why I was brought here is that recently we received a issue in the setuptools repository (https://github.com/pypa/setuptools/issues/3072) that seems related to the fact that `bazel` does not support whitespaces in file names, and this might generate problems for people using `rules_python`.

As noted [in of the issue's comment](https://github.com/pypa/setuptools/issues/3072#issuecomment-1028474077), even before the recent changes, `setuptools` already had files containing whitespaces.

My main objective here is just to give you guys a heads up, so you are aware about potential problems that might arise. (I understand that it might be a very complicated problem to solve and that it will take a long time...)

For the time being `setuptools`' lead developer have kindly provided a patch with a workaround, but it is difficult to guarantee that in the future other files containing whitespace in their names will not be added (specially via vendored dependencies).

**Comment by hrfuller** [comment]
Thanks for reaching out @abravalheri. In rules python we ignore files from installed packages that have spaces in them, which is what caused the runtime error with the Lorem file. We are aware of the issue but there ins't much we can do without upstream support for input files with spaces in bazel https://github.com/bazelbuild/bazel/issues/4327

**Comment by mchristen-astranis** [comment]
> Thanks for reaching out @abravalheri. In rules python we ignore files from installed packages that have spaces in them, which is what caused the runtime error with the Lorem file. We are aware of the issue but there ins't much we can do without upstream support for input files with spaces in bazel [bazelbuild/bazel#4327](https://github.com/bazelbuild/bazel/issues/4327)

@hrfuller out of curiosity, where does rules_python ignore files with spaces in them. I'm noticing an issue where there's a directory of an installed package with spaces in it and that is causing a failure.

**Comment by abravalheri** [comment]
Cross referencing https://github.com/pypa/setuptools/issues/4605.

As previously noted the patch was not bulletproof and there was no guarantee that similar problems would not happen again due the limitation in `bazel` itself (it is not really a bug in setuptools codebase).

**Comment by psalaberria002** [comment]
Is there any workaround we can apply to be able to upgrade setuptools?
