### ISSUE TITLE
How to run IPython with bazel dependencies?

### ISSUE THREAD

**Issue by fortuna** [bazelbuild/rules_python#63]
I'd like to run `ipython` or `jupyter notebook` and be able to load my bazel libraries.
How can I do that?

**Comment by duggelz** [comment]
Unfortunately, this is about the hardest use case possible, assuming you need things with extension modules (pure Python is fine).  To set expectations, this won't be directly supported or worked on for quite a while.

**Comment by fortuna** [comment]
I was able to get it working by creating a `notebook.py`with this content:

```python
from notebook import notebookapp
notebookapp.main()
```

And BUILD:
```python
load("@pip_packages//:requirements.bzl", "all_requirements")
 
py_binary(
  name = "notebook",
  srcs = ["notebook.py"],
  deps = all_requirements,
)
```



I had to clean up my workspace then rebuild in a python3 virtualenv (as in https://github.com/bazelbuild/rules_python/issues/64)

**Comment by EricCousineau-TRI** [comment]
I quickly put together a simple, kinda hacky, rendition:
https://github.com/EricCousineau-TRI/repro/tree/52e484e3d68e29bfb8a8e66362c60838161f0dfa/bazel/jupyter_integration

This allows interactively editing the notebook, using some `.runfiles` hackery (which I guess may break in upcoming Bazel version) via the `./run` script (which perhaps could be replaced via `bazel run --direct`?).
You can also run the notebook via `bazel run` and `bazel test`.

**Comment by michael-quinlan** [comment]
I did something similar to @fortuna 

jupyter.py
```
# -*- coding: utf-8 -*-
import re
import sys

from notebook.notebookapp import main

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(main())

```
BUILD

```
load("@notebooks//:requirements.bzl", "requirement")

py_binary(
    name = "jupyter",
    srcs = ["jupyter.py"],
    deps = [
        "//yourlibrary",
        "//yourotherlibrary:foo",
        requirement("notebook"),
    ],
)
```

requirements.txt
```
notebook>=5.6.0
```

Then just bazel run juypter and the browser should open and you can create a new notebook with access to all your dep libraries.

**Comment by tcwalther** [comment]
@duggelz as a year has past since your last comment, what is your opinion today on how far out this is on the roadmap?

**Comment by johnpaulett** [comment]
Similar to the two jupyter solutions, I created a reusable macro for the iPython shell

Macro defined at bazel_helpers/ipython.bzl
```python
load("@ipython_deps//:requirements.bzl", "all_requirements")

def ipython(name, deps, **kwargs):
    native.py_binary(
        name = name,
        srcs = ["//bazel_helpers:shell.py"],
        deps = deps + all_requirements,
        python_version = "PY3",
    )
```

Entrypoint at bazel_helpers/shell.py
```python
from IPython import start_ipython

if __name__ == '__main__':
    start_ipython()
```

Since I put this in a separate package from my code, added a bazel_helpers/BUILD:
```python
exports_files(["shell.py"])
```

bazel_helpers/requirements.txt (using --hash pinning):
```
ipython==7.8.0 \
  --hash=sha256:c4ab005921641e40a68e405e286e7a1fcc464497e14d81b6914b4fd95e5dee9b
# and other dependencies
```

In the BUILD for the package I want the iPython shell (mypkg/BUILD):
```python
load("//bazel_helpers:ipython.bzl", "ipython")

py_library(
    name = "mylib",
    srcs = glob([
        "*.py",
    ]),
    deps = [...],
)

ipython(
    name = "shell",
    deps = [
        ":mylib",
    ],
)
```

Can run via `bazel run //mypkg:shell`

**Comment by EricCousineau-TRI** [comment]
Nice!

To follow up on my prior post, we have put the Jupyter Bazel stuff into Drake master:
https://github.com/RobotLocomotion/drake/blob/master/tools/jupyter/README.md ([permalink](https://github.com/RobotLocomotion/drake/blob/efaeaa202f4ac46bff83de79c3058edd67e79522/tools/jupyter/README.md))
This permits unittesting the notebooks (ensuring code works and that nominal usage of GUI elements doesn't cause errors, etc.).

Granted, this may be noisy for other people, and the current solution in Drake only uses system-provided Jupyter and does not try to use it through Bazel (like John's solution above).

**Comment by dayfine** [comment]
Thanks guys for the starting point. A more recent attempt of mine:
https://github.com/dayfine/xlab/pull/6

Basically my setup allows me to use Google Colab with the local libraries (proto, etc) I build with Bazel

**Comment by thundergolfer** [comment]
@dayfine I think this is a good setup. I tried the same at work and ran well, but we strictly avoid pulling platform-dependent packages and `notebook` uses `appnope==0.1.0` which is OSX-only.

**Comment by groodt** [comment]
I believe this issue should be closed. There are numerous example approaches and macros mentioned that show how to implement this.

**Comment by sheridan-ozette** [comment]
I used @fortuna's method. In addition, add `-- --notebook-dir=/path/to/working/directory/` to your `bazel run` command to start the notebook server in a useful directory, not deep in the runfiles

**Comment by not-william** [comment]
For jupyter notebook 7, one needs to replace `from notebook.notebookapp import main` with `from notebook.app import main`.

Unfortunately I'm then getting errors of the form

```
[W 2024-02-08 11:53:01.777 JupyterNotebookApp] Missing or misshapen translation settings schema:
    HTTP 404: Not Found (Schema not found: [...]/share/jupyter/lab/schemas/@jupyterlab/translation-extension/plugin.json)
```

Has anyone successfully upgraded to notebook 7?

**Comment by ChewyGumball** [comment]
I got this working with the latest `notebook` version (7.2.2). The annoying bit is you need to search the runfiles for the correct directory.

`//notebooks:jupyter.py`
```python
import sys
import os

from python.runfiles import Runfiles

# Find the real location of the jupyterlab __init__.py file. The first argument is
# the exe name, all the other arguments are the files in the jupyterlab package.
# Unfortunately we can't ask bazel for the directory, only the location of all the
# files. We only need one though and will ignore the rest.
jupyterlab_init_file = next(
    x for x in sys.argv if x.endswith("site-packages/jupyterlab/__init__.py")
)

r = Runfiles.Create()
real_location = r.Rlocation(jupyterlab_init_file)

# Set the JUPYTERLAB_DIR because bazel will not set this for us. Without this, the
# server won't be able to find any extensions and will fail.
os.environ["JUPYTERLAB_DIR"] = os.path.dirname(real_location)

# Set the working directory to the bazel workspace root so we start there, instead
# of the runfiles directory.
os.chdir(os.environ["BUILD_WORKSPACE_DIRECTORY"])

# Remove all the jupyterlab file paths because the jupyter server will try to open
# them as notebook files, but they aren't real paths so it will fail.
sys.argv = [sys.argv[0]]

# We have to import the main function here, otherwise our environment manipulation
# above will not apply to it.
from notebook.app import main

sys.exit(main())
```
`//notebooks:jupyter.bzl`
```starlark
load("@pip//:requirements.bzl", "requirement")
load("@rules_python//python:defs.bzl", "py_binary")

def jupyter_server(name, deps = []):
    py_binary(
        name = name,
        main = "//notebooks:jupyter.py",
        srcs = ["//notebooks:jupyter.py"],
        deps = deps + [requirement("notebook"), "@pip//jupyterlab", "@rules_python//python/runfiles"],
        args = ["$(rlocationpaths @pip//jupyterlab)"],
    )
```
`//notebooks:BUILD.bazel`
```starlark
load("//notebooks:jupyter.bzl", "jupyter_server")
load("@pip//:requirements.bzl", "requirement")

jupyter_server(
    name = "jupyter_server",
    deps = [requirement("sympy")],
)
```

then if you run `//notebooks:jupyter_server` it will launch the server. It will complain about some missing files, but they do not appear to be important enough to break anything.

**Comment by mering** [comment]
According to the [documentation](https://jupyterlab.readthedocs.io/en/latest/user/directories.html#jupyterlab-application-directory) it looks for the application directory in `<sys-prefix>/share/jupyter/lab` which is available in the `@pip//jupyterlab:data` target.
