### ISSUE TITLE
py_binary with build_python_zip can run with just the name

### ISSUE THREAD

**Issue by libratiger** [bazelbuild/rules_python#638]
# 🚀 feature request

### Description

 

After we run the `bazel build --build_python_zip //target` , we get the zip file, when we run the file, we need
```
python xxx.zip
```

can we just run as the following

```
./xxx
```

so we can treat the result as just a single binary.

### Describe the solution you'd like

 If you have a solution in mind, please describe it.

### Describe alternatives you've considered

 Have you considered any alternative solutions or workarounds?

**Comment by piotrromanowski** [comment]
Would love it if that were possible. Or if we could execute that zip with the runtime interpreter rather than using the host interpreter. The later might already be possible to do?
