### ISSUE TITLE
Dependencies missing with jupyter

### ISSUE THREAD

**Issue by fortuna** [bazelbuild/rules_python#64]
I created a `jupyter.py` file like this:

````py
from IPython import embed
embed()
````
With BUILD:
````py
load("@pip_packages//:requirements.bzl", "requirement")
py_binary(
    name = "jupyter",
    srcs = ["jupyter.py"],
    data = [
        requirement("jupyter"),
    ],
)
````

When I run

    bazel build --python_path=$(which python3) :jupyter

I get the error
````
$ bazel build :jupyter 
ERROR: /home/fortuna/.cache/bazel/_bazel_fortuna/deb90c3b6b4ea18fe8c1b7e149bb5ceb/external/pypi__jupyter_console_5_2_0/BUILD:15:1: Traceback (most recent call last):
	File "/home/fortuna/.cache/bazel/_bazel_fortuna/deb90c3b6b4ea18fe8c1b7e149bb5ceb/external/pypi__jupyter_console_5_2_0/BUILD", line 15
		py_library(name = "test", deps = [":pkg", req...")])
	File "/home/fortuna/.cache/bazel/_bazel_fortuna/deb90c3b6b4ea18fe8c1b7e149bb5ceb/external/pypi__jupyter_console_5_2_0/BUILD", line 18, in py_library
		requirement("mock")
	File "/home/fortuna/.cache/bazel/_bazel_fortuna/deb90c3b6b4ea18fe8c1b7e149bb5ceb/external/pip_packages/requirements.bzl", line 666, in requirement
		fail(("Could not find pip-provided de...))
Could not find pip-provided dependency: 'mock'
ERROR: /home/fortuna/.cache/bazel/_bazel_fortuna/deb90c3b6b4ea18fe8c1b7e149bb5ceb/external/pypi__jupyter_console_5_2_0/BUILD:6:1: Target '@pypi__jupyter_console_5_2_0//:jupyter_console-5.2.0.dist-info/DESCRIPTION.rst' contains an error and its package is in error and referenced by '@pypi__jupyter_console_5_2_0//:pkg'
...
````

I have `jupyter` in my `requirements.txt` file.

**Comment by dududko** [comment]
@fortuna just read the error message more careful
`Could not find pip-provided dependency: 'mock'`

**Comment by fortuna** [comment]
@dududko I don't depend on `mock` directly.
`jupyter` depends on that transitively.

Isn't `requirement()` supposed to bring the transitive dependencies?

**Comment by duggelz** [comment]
Speculating, `mock` is an external module for Python 2, but a builtin part of Python 3.  Unfortunately, Bazel doesn't always evaluate conditional requirements in the right context.  See #30

**Comment by fortuna** [comment]
It turns out this works if I run `bazel clean --expunge`, then build again **inside a virtualenv** where `python` points to version 3. I think the problem is the fact that `python` is hardcoded in the `pip_import` code, rather than user the version specified in the bazel command.

**Comment by brandjon** [comment]
There's now a `pip3_import` that uses Python 3. Note that Bazel can't use the Python version specified on the command line because it runs pip as part of the WORKSPACE evaluation, before the build flags are known.
