### ISSUE TITLE
How to create a py_library from a generated source tree

### ISSUE THREAD

**Issue by garymm** [bazelbuild/rules_python#652]
I am trying to consume some Python code + C extensions that are produced by CMake.
I'm using [rules_foreign_cc](https://bazelbuild.github.io/rules_foreign_cc/0.7.1/cmake.html) to build the code, and it puts the code into an output directory, but I'm stumped as to how I can turn that into a `py_library`. I tried the below:

* Depend on the `cmake` rule as `srcs`
* Set `imports` to try to point to the directory containing the Python packages

But it doesn't work. When I run the `py_test`, the constructed `PYTHONPATH` doesn't point to the directory containing the python package from the `cmake` rule.

Thanks for any help!

Here's what I've got in my `third_party/BUILD.bazel`:

```bazel
load("@rules_foreign_cc//foreign_cc:defs.bzl", "cmake")
load("@rules_python//python:defs.bzl", "py_library", "py_test")

filegroup(
    name = "torch_mlir_src",
    srcs = glob(["torch-mlir/**"]),
)

cmake(
    name = "torch_mlir",
    ...
    install = False,
    lib_source = ":torch_mlir_src",
    out_data_dirs = ["python_packages"],
    postfix_script = " && ".join([
        "cp -r --dereference tools/torch-mlir/python_packages/torch_mlir $$INSTALLDIR$$/python_packages",
    ]),
    targets = ["tools/torch-mlir/all"],
    working_directory = "external/llvm-project/llvm",
)

# This doesn't seem to work.
py_library(
    name = "torch_mlir_py",
    srcs = [":torch_mlir"],
    imports = ["$(BINDIR)/third_party/torch_mlir/python_packages"],
    srcs_version = "PY3",
)

py_test(
    name = "torch_mlir_annotations_sugar_test",
    srcs = ["torch-mlir/python/test/annotations-sugar.py"],
    main = "torch-mlir/python/test/annotations-sugar.py",
    srcs_version = "PY3",
    deps = [":torch_mlir_py"],
)
```

**Comment by hrfuller** [comment]
I believe the issue is that imports can only be relative to the current package where the library is defined. See https://docs.bazel.build/versions/main/be/python.html#py_library. Changing the import to `torch_mlir/python_packages` may work.

**Comment by garymm** [comment]
@hrfuller thanks. I tried that, but the resulting `PYTHONPATH` points to the test's `runfiles` directory, which doesn't contain the generated `python_packages` directory. So I guess I'm struggling to figure out how to get the generated `python_packages` directory into the runfiles directory. I've tried switching from `srcs = [":torch_mlir"]` to `data = [":torch_mlir"]`, but that didn't make a difference.

**Comment by hrfuller** [comment]
I see. It may be that output file target cannot be referenced by imports. That may be a feature which only applies to input file target. If the generated python sources are in the runfiles tree then they should be importable in the test at some path. Is that the case?

**Comment by jvolkman** [comment]
If you can't get `py_library` to work, you should be able to do this with a custom rule that return `PyInfo` and the correct runfiles.

**Comment by garymm** [comment]
I don't currently need this, so closing. Will re-open if I do. Thanks for the advices.
