### ISSUE TITLE
`Py2` support in toolchains

### ISSUE THREAD

**Issue by phlax** [bazelbuild/rules_python#668]
# 🚀 feature request

`Py2` support for toolchains

### Relevant Rules

`python_register_toolchains`

### Description

While testing out the new toolchains, all works well except for the fact that one of our tests requires a (discontinued with no py3 version) python 2 library.

I checked in `python/versions.bzl` and saw that the only toolchains listed are python3

### Describe the solution you'd like

to be able to specify a py2 toolchain

### Describe alternatives you've considered

omitting the `interpreter` in `pip_install` - currently waiting on CI to see if that worksaround

**Comment by phlax** [comment]
Looking at this further it seems that there is no upstream support for standalone python2

The error that is thrown is `The Python toolchain does not provide a runtime for Python version PY2` - im wondering if there is a way to tell bazel to use the host python for PY2

**Comment by thundergolfer** [comment]
Looking at the linked GH issue, seems you need Python2 toolchain support for the _Envoy_ project. Python 2 is really dead, see https://endoflife.date/python. The latest supported version of Python is 3.7, so the `rules_python` has been for a while comfortable with not supporting Python 2 going forward. 

So `python_register_toolchains` specifically will not get Python 2 support. 

> im wondering if there is a way to tell Bazel to use the host python for PY2

I believe the default Python toolchain, used if no user toolchain is provided and/or matches, will do `which python2` on the host. If you need Python 2 and don't yet have a toolchain configured, I'd expect this is what's being done in Envoy.

As a general recommendation, the benefits of moving off Python 2 are so significant that I'd prioritize migration to avoid needing to do work to provide a Python 2 toolchain.
