### ISSUE TITLE
Reduce dependencies for generated wrapper script.

### ISSUE THREAD

**Issue by adam-azarchs** [bazelbuild/rules_python#673]
# 🚀 feature request

### Relevant Rules

`py_binary`, `py_test`

### Description

For situations like remote execution or executing in a docker container for hermiticity and reproducibility, it's helpful to keep the container image size to an absolute minimum.  The bazel-generated wrapper script, which at least at the moment runs with the system-provided `python3`, imports a bunch of modules which are not present in the `python3-minimal` package in the debian ecosystem.

### Describe the solution you'd like

The imports
```python
import shutil
import tempfile
import zipfile
```
are only required if `IsRunningFromZip` is `True`.  They shouldn't be imported if it isn't.

They're imported by the template [here](
https://github.com/bazelbuild/bazel/blob/763dd0ce6e1644bf895231432f616427a11d385a/src/main/java/com/google/devtools/build/lib/bazel/rules/python/python_stub_template.txt#L23-L26).

The offending imports could be guarded by
```python
if %is_zipfile%:
```
in the template.

### Describe alternatives you've considered

#42 would also solve this problem, mostly.  If you have a lot of unit tests to run then the time it takes to process those often-unnecessary imports can add up.

**Comment by hrfuller** [comment]
The python binary shim template is part of bazelbuild/bazel. Not this repository. I recommend you open an issue in the repo.
