### ISSUE TITLE
entry_point function executed twice

### ISSUE THREAD

**Issue by ewianda** [bazelbuild/rules_python#675]
# 🐞 bug report

### Affected Rule

 
The issue is caused by the rule:      **entry_point**

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description

 A clear and concise description of the problem...
The current implementation of `entry_point` content generation function results in a repeated calling of the entrypoint funciton. 

https://github.com/bazelbuild/rules_python/blob/79cebad7d2a904fe81c229322177fef6a87b7fc1/python/pip_install/extract_wheels/lib/bazel.py#L44-L45

## 🔥 Exception or Error

<pre><code>

</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>

  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>

  </code>
</pre>

**Rules_python version:**

<pre>
  <code>

  </code>
</pre>

**Anything else relevant?**

**Comment by thundergolfer** [comment]
Yep, that's quite blatant. I reviewed it too, 😖 .

**Comment by thundergolfer** [comment]
Thanks for you issue report @ewianda. 

Addressing this issue in https://github.com/bazelbuild/rules_python/pull/696.
