### ISSUE TITLE
extended-length path with forward slash on windows

### ISSUE THREAD

**Issue by dhmemi** [bazelbuild/rules_python#680]
# 🐞 bug report

### Affected Rule

 The issue is caused by the rule: `py_binary`

### Is this a regression?

 No.

### Description

 
I'm using `py_binary` to run sphinx to generate docs, and sphinx will try to open template file with path from `path.join(<package_path>, <template_name>)` at [here](https://github.com/sphinx-doc/sphinx/blob/4221d1a5163d023d80a34bd4a12e9c2a2c648ae3/sphinx/jinja2glue.py#L119), the `<package_path>` is changed into [extended-length path](https://stackoverflow.com/questions/21194530/what-does-mean-when-prepended-to-a-file-path) by rules_python, and the `<template_name>` would contains forward slashes like `partials/_head_css_variables.html` in [furo](https://github.com/pradyunsg/furo/blob/c386171ffad12d069cc179fb5d77c75145f21d22/src/furo/theme/furo/base.html#L68), as a result, the final file path would be like:
```
\\?\C:\Temp\Bazel.runfiles_8zw7lmen\runfiles\requirements\pypi__furo\furo\theme\furo\partials/_head_css_variables.html
```

but [extended-length path](https://stackoverflow.com/questions/21194530/what-does-mean-when-prepended-to-a-file-path) is not support forward slashes. 

what's the better way to fix this bug?

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Windows
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
4.1.0
  </code>
</pre>

**Rules_python version:**

<pre>
  <code>
0.8.0
  </code>
</pre>

**Comment by dhmemi** [comment]
related issue: https://github.com/bazelbuild/bazel/issues/2504

**Comment by thundergolfer** [comment]
Thanks for your issue report. 

> is changed into [extended-length path](https://stackoverflow.com/questions/21194530/what-does-mean-when-prepended-to-a-file-path) by rules_python,

Where in the code do you think this is happening? I must profess ignorance of Windows' extended-length path functionality.

**Comment by dhmemi** [comment]
Sorry，I read the code of rules_python and found that py_binary is just a simple wrapper for the rules in bazel native. So the path might be modified [here](https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/bazel/rules/python/python_stub_template.txt#L32) by bazel:

```starlark
def GetWindowsPathWithUNCPrefix(path):
  """Adds UNC prefix after getting a normalized absolute Windows path.

  No-op for non-Windows platforms or if running under python2.
  """
  path = path.strip()

  # No need to add prefix for non-Windows platforms.
  # And \\?\ doesn't work in python 2 or on mingw
  if not IsWindows() or sys.version_info[0] < 3:
    return path

  # import sysconfig only now to maintain python 2.6 compatibility
  import sysconfig
  if sysconfig.get_platform() == 'mingw':
    return path

  # Lets start the unicode fun
  unicode_prefix = '\\\\?\\'
  if path.startswith(unicode_prefix):
    return path

  # os.path.abspath returns a normalized absolute path
  return unicode_prefix + os.path.abspath(path)
```

 Maybe we should move this issue to bazel repo.
