### ISSUE TITLE
pip_install fails with `error: command '/usr/bin/gcc' failed with exit code 1`

### ISSUE THREAD

**Issue by davians12** [bazelbuild/rules_python#681]
# 🐞 bug report

### Affected Rule

 The issue is caused by the rule: pip_install

### Is this a regression?

 Yes, the previous version in which this bug was not present was: Not a regression

### Description

 pip_install fails for only one requirement `tree-sitter` from `requirements.txt`

## 🔥 Exception or Error

<pre><code>

Failed to build tree-sitter
 (  ERROR: Command errored out with exit status 1:
   command: /home/user/.cache/bazel/_bazel_user/1ced21babfe30b5e39b8b34411e58735/external/python_interpreter/python_bin /home/user/.cache/bazel/_bazel_user/1ced21babfe30b5e39b8b34411e58735/external/pypi__pip/pip/_vendor/pep517/_in_process.py build_wheel /tmp/tmpxxrp34vx
       cwd: /tmp/pip-wheel-hw8ksvfm/tree-sitter
  Complete output (20 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.7
  creating build/lib.linux-x86_64-3.7/tree_sitter
  copying tree_sitter/__init__.py -> build/lib.linux-x86_64-3.7/tree_sitter
  running build_ext
  building 'tree_sitter.binding' extension
  creating build/temp.linux-x86_64-3.7
  creating build/temp.linux-x86_64-3.7/tree_sitter
  creating build/temp.linux-x86_64-3.7/tree_sitter/core
  creating build/temp.linux-x86_64-3.7/tree_sitter/core/lib
  creating build/temp.linux-x86_64-3.7/tree_sitter/core/lib/src
  gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -g0 -fPIC -Itree_sitter/core/lib/include -Itree_sitter/core/lib/src -I/home/user/.cache/bazel/_bazel_user/1ced21babfe30b5e39b8b34411e58735/external/python_interpreter/bazel_install/lib/python3.7/config-3.7m-x86_64-linux-gnu/Include -I/home/user/.cache/bazel/_bazel_user/1ced21babfe30b5e39b8b34411e58735/external/python_interpreter -c tree_sitter/binding.c -o build/temp.linux-x86_64-3.7/tree_sitter/binding.o -std=c99 -Wno-unused-variable
tree_sitter/binding.c:2:10: fatal error: Python.h: No such file or directory
   #include "Python.h"
            ^~~~~~~~~~
  compilation terminated.
  error: command '/usr/bin/gcc' failed with exit code 1
  ----------------------------------------
  ERROR: Failed building wheel for tree-sitter
ERROR: Failed to build one or more wheels
Traceback (most recent call last):
  File "/home/user/.cache/bazel/_bazel_user/1ced21babfe30b5e39b8b34411e58735/external/python_interpreter/bazel_install/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/user/.cache/bazel/_bazel_user/1ced21babfe30b5e39b8b34411e58735/external/python_interpreter/bazel_install/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/user/.cache/bazel/_bazel_user/1ced21babfe30b5e39b8b34411e58735/external/rules_python/python/pip_install/extract_wheels/__main__.py", line 5, in 
    main()
  File "/home/user/.cache/bazel/_bazel_user/1ced21babfe30b5e39b8b34411e58735/external/rules_python/python/pip_install/extract_wheels/__init__.py", line 87, in main
    subprocess.run(pip_args, check=True)
  File "/home/user/.cache/bazel/_bazel_user/1ced21babfe30b5e39b8b34411e58735/external/python_interpreter/bazel_install/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/home/user/.cache/bazel/_bazel_user/1ced21babfe30b5e39b8b34411e58735/external/python_interpreter/python_bin', '-m', 'pip', 'wheel', '-r', '/home/user/natural-cubert/requirements.txt']' returned non-zero exit status 1.
)
</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
   Ubuntu
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
Build label: 4.0.0
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Jan 21 07:33:24 2021 (1611214404)
Build timestamp: 1611214404
  </code>
</pre>

**Rules_python version:**

<pre>
  <code>
0.1.0
  </code>
</pre>

**Anything else relevant?**
The bazel setup used to build and run, not sure what changed.

**Comment by hrfuller** [comment]
I believe the issue lies with the hermetic interpreters which are now used, apparently by default. The installed interpreters pins don't seem have the correct header files present.

**Comment by hrfuller** [comment]
@davians12 I can't repro this exact issue because I develop on macos. Can you put together a repro of the WORKSPACE which create this issue. In particular are you using a custom python interpreter toolchain target or the built in hermetic toolchains?

**Comment by thundergolfer** [comment]
@hrfuller Yep this is totally expected with the python-build-standalone intepreter. 

> pip_install fails for only one requirement `tree-sitter` from `requirements.txt`

It's failed to find a wheel for `tree-sitter` so fell back to compiling it. It appears `tree-sitter` doesn't distribute a Linux wheel. https://pypi.org/project/tree-sitter/#files

**Comment by hrfuller** [comment]
So this issue is basically the linux equivalent of bazelbuild/rules_python#646 but in the integration test I added to that PR I can't repro this failure with linux. To me that implies that the interpreter setup here is slightly different.

**Comment by groodt** [comment]
Coincidentally running into the same issue. The setuptools upgrade was introduced here: https://github.com/bazelbuild/rules_python/pull/661

**Comment by aaliddell** [comment]
Are you running with the new built-in toolchains or a custom Python toolchain?

Rolling back setuptools may be a short-term solution, but that only hides the issue and we should be able to upgrade it freely in the future (particularly as new Python releases come out that could start to have issues with a very old setuptools version). In this particular case for this issue: there's nothing that rules_python can fix (besides maybe updating the demo code I linked), as it's my local custom toolchain layout that was breaking distutils. It just so happens that a fair number of us have adopted and adapted that original demo code, so are seeing similar bugs.

**Comment by groodt** [comment]
My issue is now resolved after upgrading `rules_python` to the latest and upgrading the failing dependency to a `wheel`, rather than relying on the `sdist`. Relying on the `sdist` was fragile to `setuptools` and `distutils` changes as you mention.

I no longer believe I was seeing the same issue, so I think we still need to see a repro from the original poster to be certain (although I do think @aaliddell has the best explanation so far).

**Comment by hrfuller** [comment]
Agreed the @aaliddell bisect makes sense to me.

**Comment by groodt** [comment]
@davians12 Can you confirm whether @aaliddell fix solves your issue?

**Comment by aaliddell** [comment]
A useful closure here could be to update the example python build toolchain [here](https://github.com/bazelbuild/rules_python/blob/main/examples/pip_install/WORKSPACE#L60-L100) to fix the symlink being inside the source tree.

**Comment by garymm** [comment]
For me this was fixed on MacOS by version 0.12.0. From the release notes, I'm guessing fixed by https://github.com/bazelbuild/rules_python/pull/809
