### ISSUE TITLE
py_wheel should produce dist-info/top_level.txt

### ISSUE THREAD

**Issue by alexeagle** [bazelbuild/rules_python#684]
Similar to how `py_wheel` already understands generation of the dist-info/entry_points.txt file.
This is needed to generate wheels which match how other build tools create them.

**Comment by pstradomski** [comment]
Do you think we should try to guess the right contents by looking at the packaged directories and let the user override if we guess wrong, or have the user always provide the list?

**Comment by alexeagle** [comment]
Researching this some more, it seems the `top-level.txt` file is actually a remnant of the egg package format from setuptools, and isn't mentioned in the Wheel spec https://peps.python.org/pep-0427/#the-dist-info-directory.
I see some mentions of it being used by some tooling for knowing which things in a global site-packages to delete when running `pip uninstall` but otherwise I think it's vestigial.

I noticed this issue while porting a legacy build to Bazel - I'll likely close this assuming that file wasn't actually load-bearing for them.

**Comment by alexeagle** [comment]
Interesting https://github.com/pypa/wheel/commit/9ae7f886db930e60133e1e1354c9b5ae0f13f595

I think `bdist_wheel` used to produce dist-info/top-level.txt
