### ISSUE TITLE
Pre build python interpreter on arm/linux "not defined"

### ISSUE THREAD

**Issue by nstng** [bazelbuild/rules_python#687]
# 🐞 bug report

### Affected Rule

The issue is caused by the rule: `python_register_toolchains` and `pip_parse`

### Is this a regression?

Not a regression - a new feature is not working as expected. See https://github.com/bazelbuild/rules_python/pull/669

### Description

Running a `bazel build` using `python_register_toolchains` and `pip_parse` on linux/aarch64 leads to the error below. Tested on AWS image `ubuntu/images/hvm-ssd/ubuntu-focal-20.04-arm64-server-20220404-3ba3581b-86f4-4bf1-a9a5-c2e11fe9408d`.
```
lscpu: Architecture:                    aarch64
uname -r: 5.13.0-1021-aws
```
On a local x86/linux (uname -r: 5.13.0-35-generic) docker setup the build is successful.

## 🔬 Minimal Reproduction

```
WORKSPACE.bazel:

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
http_archive(
    name = "rules_python",
    sha256 = "20ceb9337b2a139884a80e8af4ddb7400baefcf3df46ecaf11c5854d80e4d9bd",
    strip_prefix = "rules_python-main",
    url = "https://github.com/bazelbuild/rules_python/archive/refs/heads/main.zip",
)

load("@rules_python//python:repositories.bzl", "python_register_toolchains")

python_register_toolchains(
    name = "python3_8",
    python_version = "3.8",
)

load("@python3_8//:defs.bzl", "interpreter")
load("@rules_python//python:pip.bzl", "pip_parse")

pip_parse(
    name = "python_deps",
    python_interpreter_target = interpreter,
    requirements_lock = "//:requirements.txt",
)
```

```
BUILD.bazel:

load("@rules_python//python:defs.bzl", "py_binary")
load("@python_deps//:requirements.bzl", "requirement")

py_binary(
  name = "foo",
  srcs = ["foo.py"],
  main = "foo.py",
)
```

```
foo.py:

print("hello world")
```

```
requirtements.txt (empty)
```

## 🔥 Exception or Error

<pre><code>
INFO: Repository python_deps instantiated at:
  /home/ubuntu/test/WORKSPACE.bazel:19:10: in <toplevel>
  /home/ubuntu/.cache/bazel/_bazel_ubuntu/3ff83f08db4c343acc8f94cc156328c9/external/rules_python/python/pip.bzl:211:19: in pip_parse
Repository rule pip_repository defined at:
  /home/ubuntu/.cache/bazel/_bazel_ubuntu/3ff83f08db4c343acc8f94cc156328c9/external/rules_python/python/pip_install/pip_repository.bzl:295:33: in <toplevel>
ERROR: An error occurred during the fetch of repository 'python_deps':
   Traceback (most recent call last):
	File "/home/ubuntu/.cache/bazel/_bazel_ubuntu/3ff83f08db4c343acc8f94cc156328c9/external/rules_python/python/pip_install/pip_repository.bzl", line 123, column 53, in _pip_repository_impl
		python_interpreter = _resolve_python_interpreter(rctx)
	File "/home/ubuntu/.cache/bazel/_bazel_ubuntu/3ff83f08db4c343acc8f94cc156328c9/external/rules_python/python/pip_install/pip_repository.bzl", line 56, column 39, in _resolve_python_interpreter
		python_interpreter = rctx.path(target)
Error in path: Unable to load package for @python3_8_aarch64-unknown-linux-gnu//:bin/python3: The repository '@python3_8_aarch64-unknown-linux-gnu' could not be resolved: Repository '@python3_8_aarch64-unknown-linux-gnu' is not defined
ERROR: /home/ubuntu/test/WORKSPACE.bazel:19:10: fetching pip_repository rule //external:python_deps: Traceback (most recent call last):
	File "/home/ubuntu/.cache/bazel/_bazel_ubuntu/3ff83f08db4c343acc8f94cc156328c9/external/rules_python/python/pip_install/pip_repository.bzl", line 123, column 53, in _pip_repository_impl
		python_interpreter = _resolve_python_interpreter(rctx)
	File "/home/ubuntu/.cache/bazel/_bazel_ubuntu/3ff83f08db4c343acc8f94cc156328c9/external/rules_python/python/pip_install/pip_repository.bzl", line 56, column 39, in _resolve_python_interpreter
		python_interpreter = rctx.path(target)
Error in path: Unable to load package for @python3_8_aarch64-unknown-linux-gnu//:bin/python3: The repository '@python3_8_aarch64-unknown-linux-gnu' could not be resolved: Repository '@python3_8_aarch64-unknown-linux-gnu' is not defined
ERROR: Skipping '//:foo': no such package '@python_deps//': Unable to load package for @python3_8_aarch64-unknown-linux-gnu//:bin/python3: The repository '@python3_8_aarch64-unknown-linux-gnu' could not be resolved: Repository '@python3_8_aarch64-unknown-linux-gnu' is not defined
WARNING: Target pattern parsing failed.
ERROR: no such package '@python_deps//': Unable to load package for @python3_8_aarch64-unknown-linux-gnu//:bin/python3: The repository '@python3_8_aarch64-unknown-linux-gnu' could not be resolved: Repository '@python3_8_aarch64-unknown-linux-gnu' is not defined
INFO: Elapsed time: 0.656s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
See above - relevant to the problem descriptionm.
  </code>
</pre>

**Output of `bazel version`:**
(via bazelisk)
<pre>
  <code>
Bazelisk version: v1.10.0
Build label: 5.1.1
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Fri Apr 8 15:49:48 2022 (1649432988)
Build timestamp: 1649432988
Build timestamp as int: 1649432988
  </code>
</pre>

**Rules_python version:**

<pre>
  <code>
current master at time of this report
  </code>
</pre>

**Anything else relevant?**

**Comment by lazcamus** [comment]
Sadly, there isn't a prebuilt python 3.8 for linux-arm64, so I commented it and moved on: https://github.com/bazelbuild/rules_python/blob/main/python/versions.bzl#L43

It looks like the [latest release](https://github.com/indygreg/python-build-standalone/releases/tag/20220318) continues to have this gap.

Once `python-build-standalone` produces a binary, it'd be trivial to add it to `rules_python`

**Comment by lazcamus** [comment]
It looks like this isn't an oversight, but is instead intentional ["Cross-compiles can't do PGO and require Python 3.9."](https://github.com/indygreg/python-build-standalone/blob/main/.github/workflows/linux.yml#L131)

**Comment by nstng** [comment]
@lazcamus thank you for the detailed answer! I totally missed #L43 when I was taking a look :see_no_evil: - I will close this issue and see if we can upgrade to 3.9.
