### ISSUE TITLE
Unable to load package

### ISSUE THREAD

**Issue by zezuladp** [bazelbuild/rules_python#7]
OSX Bazel 0.5.4 (also 0.5.2)
Constantly getting 
`ERROR: error loading package '': Extension file not found. Unable to load package for '//python:pip.bzl': BUILD file not found on package path.`
after following setup instructions. Won't even get past this part in WORKSPACE
```
git_repository(
    name = "io_bazel_rules_python",
    remote = "https://github.com/bazelbuild/rules_python.git",
    commit = "d6fbb0fb2a5c8e318dd4de5104dc41358cefaa90",
)

# Only needed for PIP support:
load("//python:pip.bzl", "pip_repositories")
```

**Comment by mattmoor** [comment]
Oops, you need `@io_bazel_rules_python` in front of `//python:pip.bzl`
