### ISSUE TITLE
Package .libs not included in BUILD

### ISSUE THREAD

**Issue by lromor** [bazelbuild/rules_python#706]
# 🚀 feature request

### Relevant Rules

pip_parse, requirement

### Description

It looks like some PyPI libraries such as cffi have a `cffi.libs` in their wheel containing specific library versions they are wrapping.
```
BUILD.bazel
cffi
cffi-1.15.0-cp39-cp39-manylinux_2_12_x86_64.manylinux2010_x86_64.whl
cffi-1.15.0.dist-info
_cffi_backend.cpython-39-x86_64-linux-gnu.so
cffi.libs
WORKSPACE
```

What's the recommended approach in this case? 

### Describe the solution you'd like

I'm not experienced enough to know if this <package>.libs folder is a standard location, but it would be nice to include those as well as automatic dependencies of the python library.

### Describe alternatives you've considered

Maybe just exposing the downloaded file and manually create a cc_import could suffice?

**Comment by groodt** [comment]
If Im not mistaken, that is the default location where `auditwheel` will patch and copy relevant libraries on linux.
