### ISSUE TITLE
bazel run //:gazelle doesn't work with imports with format ("from x import y")

### ISSUE THREAD

**Issue by sramirezmartin** [bazelbuild/rules_python#709]
# 🐞 bug report

### Affected Rule

 The issue is caused by the rule: 
<pre><code>
gazelle(
    name = "gazelle",
    data = GAZELLE_PYTHON_RUNTIME_DEPS,
    gazelle = "@rules_python//gazelle:gazelle_python_binary",
)
</code></pre>

### Is this a regression?

Unsure about this.

### Description

When importing a google.cloud modules in the formar `from google.cloud import aiplatform`, we get the following error when running `bazel run //:gazelle`.

<pre><code>
gazelle: ERROR: failed to validate dependencies for target "@toy_build_file_generation_example//subdir1/subdir2": "google.cloud" at line 4 from "subdir1/subdir2/test2.py" is an invalid dependency: possible solutions:
        1. Add it as a dependency in the requirements.txt file.
        2. Instruct Gazelle to resolve to a known dependency using the gazelle:resolve directive.
        3. Ignore it with a comment '# gazelle:ignore google.cloud' in the Python file.

</code></pre>

But when we use the format `import google.cloud.aiplatform as aiplatform`, the command `bazel run //:gazelle` finishes successfully and the BUILD files are updated accordingly. 

## 🔬 Minimal Reproduction

Here is a link to a toy example where the issue can be reproduced: https://github.com/sramirezmartin/gazelle-toy-example

The commands to run are:
<pre><code>
git clone https://github.com/sramirezmartin/gazelle-toy-example.git
cd gazelle-toy-example
pip-compile --generate-hashes --output-file=subdir1/requirements_lock.txt subdir1/requirements.txt
bazel run //subdir1:gazelle_python_manifest.update
bazel run //:gazelle
</code></pre>

## 🔥 Exception or Error

<pre><code>
gazelle: ERROR: failed to validate dependencies for target "@toy_build_file_generation_example//subdir1/subdir2": "google.cloud" at line 4 from "subdir1/subdir2/test2.py" is an invalid dependency: possible solutions:
        1. Add it as a dependency in the requirements.txt file.
        2. Instruct Gazelle to resolve to a known dependency using the gazelle:resolve directive.
        3. Ignore it with a comment '# gazelle:ignore google.cloud' in the Python file.

</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
NAME="Ubuntu"
VERSION="18.04.6 LTS (Bionic Beaver)"
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
Build label: 5.1.1
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Fri Apr 8 15:49:48 2022 (1649432988)
Build timestamp: 1649432988
Build timestamp as int: 1649432988
  </code>
</pre>

**Rules_python version:**

<pre>
  <code>
rules_python-0.8.1
  </code>
</pre>

**Comment by AugustKarlstedt** [comment]
workaround is possible by changing `from google.cloud import aiplatform` to `import google.cloud.aiplatform as aiplatform`

**Comment by domenic-donato** [comment]
We ended up finding that solution, but it only works sometimes. We ended up running into situations where it throws errors about importing `six` which is only imported in the libraries we depend on rather than our source code. So there are more issues with this tool when it comes to correctly parsing import statements.
