### ISSUE TITLE
_test.py files being included in py_library rather than py_test

### ISSUE THREAD

**Issue by domenic-donato** [bazelbuild/rules_python#714]
# 🐞 bug report

### Affected Rule

bazel run //:gazelle

### Is this a regression?

No

### Description

The python gazelle tool does not create a py_test for all `_test.py` files. I think it requires that the test file prefix to be the same as the package. If the prefix is not the same, it adds the _test.py file to a py_library rule.

## 🔬 Minimal Reproduction

Just make a _test.py file whose prefix is not the same as the package it resides in.

**Comment by AugustKarlstedt** [comment]
+1

**Comment by domenic-donato** [comment]
I think this PR is going to fix this: https://github.com/bazelbuild/rules_python/pull/723

**Comment by chrislovecnm** [comment]
That is what we are doing, but it this what we would expect?  I wonder if we should support generating `py_test` declarations when we have `foo_test.py`.  The documentation does not mention `__test__.py` either.

**Comment by chrislovecnm** [comment]
Chatting with @f0rmiga this is working as expected.  And https://github.com/aspect-build/rules_py does have support for adding all _test.py files with a macro.  I wonder if rules_python should support having a flag to pull in _test.py files.  I am going to update the docs to add a bit of clarity

**Comment by chrislovecnm** [comment]
@f0rmiga can you give me a couple of sentences on what is supported?  I know that `__test__.py` is supported, is `foo_test.py` supported?

**Comment by aignas** [comment]
If #999 is not sufficient, please reopen this ticket.
