### ISSUE TITLE
Pipfile support?

### ISSUE THREAD

**Issue by alecbz** [bazelbuild/rules_python#72]
Probably not an immediate priority, but it may be worth considering how/when to support the new ['Pipfile' format](https://github.com/pypa/pipfile) in addition to requirements.txt

**Comment by thedrow** [comment]
[requirementslib ](https://github.com/sarugaku/requirementslib) can help us reuse the same code that imports requirements files since the library can convert Pipfile/Pipfile.lock files into requirements.txt files.

**Comment by thundergolfer** [comment]
Given the presence of Pipenv, Poetry, and pip-tools with their respective `Pipfile[.lock]`, `pyproject.toml`, and `requirements.in` files, the Python packaging ecosystem is not close to having a useful consensus towards Pipenv on which we could justify adding `Pipfile` support.

I will close this issue for now.
