### ISSUE TITLE
Feature request: conda_import rule

### ISSUE THREAD

**Issue by tmandry** [bazelbuild/rules_python#73]
Anaconda is a popular Python distribution for doing data science and ML. Their [conda package manager](https://conda.io/docs/) is central to it and also very popular. It is Python-centric, but not exclusive to Python packages (for example, PhantomJS is included in the conda-forge repo for doing browser integration testing).

conda is a central part of the Python dev process for our organization, so having access to it within bazel would be a big step forward in terms of consolidating our workflow. bazel + conda means instant access to a huge set of analytics and visualization tooling, full integration testing, **AND** hermetic cross-platform builds (otherwise known as "the dream")!

At the same time, I'm not sure whether support would fit in as part of this repository, or whether it belongs elsewhere. So I'd like to begin a conversation of what this support would look like.

**Comment by adeora** [comment]
Is there any timeline on when this might be implemented? +1 that this would be incredibly useful for me

**Comment by conjam** [comment]
Bumping this again... has there been any progress on this? I would be keen on helping out if so, or getting the ball rolling if conda support has been shelved.

**Comment by thundergolfer** [comment]
There's multiple open-source projects that focus on stock `pip` packaging and an OSS project that focuses on `poetry` support. These were created because the core `rule_python` packaging rules don't progress fast enough. I think you'll get progress only once there's a similar effort to start an open-source project for it, like a `rules_conda`.

**Comment by spietras** [comment]
> I think you'll get progress only once there's a similar effort to start an open-source project for it, like a `rules_conda`.

Let's try to make progress then: https://github.com/spietras/rules_conda
