### ISSUE TITLE
windows pytest bug

### ISSUE THREAD

**Issue by ustcsq** [bazelbuild/rules_python#733]
# 🐞 bug report

### Affected Rule

 The issue is caused by the rule: py_test()

## 🔬 Minimal Reproduction

[debug.zip](https://github.com/bazelbuild/rules_python/files/8938713/debug.zip)

## 🔥 Exception or Error

<pre><code>
import os
print(os.getcwd())
</code></pre>

should be C:\Users\MSI-PC\_bazel_MSI-PC\27b2qbns\.....
but be C:\Users\MSI-PC\AppData\Local\Temp\Bazel.runfiles_hhzyym94\runfiles\smartmore_smore_xrack

![企业微信截图_16557117214365](https://user-images.githubusercontent.com/26031983/174553973-8efaeb4e-ebe5-44c6-ba94-832023d7aff6.png)

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
windows 10
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
5.1.0
  </code>
</pre>

**Rules_python version:**

<pre>
  <code>
default
  </code>
</pre>

**Anything else relevant?**

**Comment by groodt** [comment]
Can you describe the error more clearly? Tests are run a temporary "sandbox" location, there shouldn't be any expectation of the CWD. Unless I have misunderstood the bug report?
