### ISSUE TITLE
Support for pip --index-url, --extra-index-url, --find-links

### ISSUE THREAD

**Issue by alecbz** [bazelbuild/rules_python#74]
Atm it doesn't seem possible to fetch wheels from anywhere except the default PyPI index. We have some custom built wheels that we store in a directory and commit with the repository, and want to use those with `--find-links`, not something from PyPI.

**Comment by clintharrison** [comment]
Since the `requirements.txt` file is simply passed along to `pip` to resolve dependencies, you can add these directly in your `requirements.txt`:

```
--index-url https://example.com/simple
--find-links https://example.com/custom

flask==0.12
custom-thing==0.0.1
```

**Comment by Globegitter** [comment]
That does not work for me, I get the error:
```
piptool.par: error: no such option: --no-cache-dir
```

**Comment by qzmfranklin** [comment]
Being able to download from mirrors other than pypi is important for our team too. PyPi is slow from China.

**Comment by amarshat** [comment]
One workaround is to add the `-i https://pypi.someorg.com/simple` in the `requirements.txt`, usually at the top, but it could also be put just above the packages which need to be obtained from a mirror specifically.

**Comment by amarshat** [comment]
(I don't understand why github shows this `amarshat unassigned davidstanke 21 seconds ago`. The only action I did was to comment on this issue.)

**Comment by TheKaur** [comment]
Any update on this?

**Comment by jmcfallargo** [comment]
This is very important to us and the workaround doesn't work because we use a private registry that requires authorization.

**Comment by ali5h** [comment]
we have implemented this feature check it out https://github.com/ali5h/rules_pip

**Comment by caseyduquettesc** [comment]
Another workaround if you already have the extra index url configured in your pip.conf file is to set `PIP_CONFIG_FILE=~/.pip/pip.conf`

**Comment by uhlajs** [comment]
@aignas Can you provide a link to the documentation for the `pip_parse(extra_pip_args)`?

**Comment by hrfuller** [comment]
Doesn't  look to have generated stardoc: https://github.com/bazelbuild/rules_python/blob/main/python/pip_install/pip_repository.bzl#L208

Basically a string list of cli args.e.g how you would pass flags to subprocess.check_call if you were using that to invoke pip.

**Comment by bolbken** [comment]
Any suggestions on how to pass the index url from a pip.conf, environment variable, or similar?  Repository rules seem necessary, but not sure how to pass it in within WORKSPACE file.

**Comment by hrfuller** [comment]
Repository rules execute non hermetically so if the pip version you are using supports it exporting PIP_CONFIG_FILE like is mentioned here: https://github.com/bazelbuild/rules_python/issues/74#issuecomment-842652033 might work.

**Comment by aignas** [comment]
Regarding passing the index, you can pass the index by using:
```starlark
load("@rules_python//python/pip_install:requirements.bzl", "compile_pip_requirements")

# This rule adds a convenient way to update the requirements file.
compile_pip_requirements(
    name = "requirements",
    size = "large",
    extra_args = [
        "--allow-unsafe",
        "--extra-index-url=<my_custom_index>",
        "--no-reuse-hashes",
    ],
    tags = ["manual"],
)
```

Then the index will be stored in the compiled `requirements.txt` file. You can then run `pip_parse` by simply having:
```starlark
load("@rules_python//python:repositories.bzl", "python_register_toolchains")

python_register_toolchains(
    name = "python39",
    python_version = "3.9",
)

load("@python39_resolved_interpreter//:defs.bzl", "interpreter")
load("@rules_python//python:pip.bzl", "pip_parse")

# Code dependencies are installed on demand
pip_parse(
    name = "pip",
    extra_pip_args = [
        "--no-cache-dir",
        "--only-binary",
        ":all:",
    ],
    isolated = True,
    python_interpreter_target = interpreter,
    requirements_lock = "//:requirements.txt",
)
```

**Comment by groodt** [comment]
Are you happy to close this @alecbz ? The solution posted by @aignas should solve the issue. This issue was raised against very old versions of these rules.
