### ISSUE TITLE
Hosted whl files:  RuntimeError: The `requirements_lock` file must be fully pinned.

### ISSUE THREAD

**Issue by anuragkanungo** [bazelbuild/rules_python#742]
Hi, looks like this breaks the ability to specify a hosted whl file in the requirements.in

Having something like this in `requirements.in`
```
https://files.pythonhosted.org/packages/24/93/f5b001dc0f5de84ce049a34ff382032cd9478e1080aa6ac48470fa810577/onnx-1.11.0-cp39-cp39-manylinux_2_12_x86_64.manylinux2010_x86_64.whl
```

generates this in `requirements.lock`
```
onnx @ https://files.pythonhosted.org/packages/24/93/f5b001dc0f5de84ce049a34ff382032cd9478e1080aa6ac48470fa810577/onnx-1.11.0-cp39-cp39-manylinux_2_12_x86_64.manylinux2010_x86_64.whl \
    --hash=sha256:67c6d2654c1c203e5c839a47900b51f588fd0de71bbd497fb193d30a0b3ec1e9
```

which basically then fails with

```
RuntimeError: The `requirements_lock` file must be fully pinned. See `compile_pip_requirements`.
Alternatively, use `pip-tools` or a similar mechanism to produce a pinned lockfile.

The following requirements were not pinned:
onnx@ https://files.pythonhosted.org/packages/24/93/f5b001dc0f5de84ce049a34ff382032cd9478e1080aa6ac48470fa810577/onnx-1.11.0-cp39-cp39-manylinux_2_12_x86_64.manylinux2010_x86_64.whl from https://files.pythonhosted.org/packages/24/93/f5b001dc0f5de84ce049a34ff382032cd9478e1080aa6ac48470fa810577/onnx-1.11.0-cp39-cp39-manylinux_2_12_x86_64.manylinux2010_x86_64.whl
)
```

Seems like the check provided by pip, looks for `==` and `===` but not `@`.
https://github.com/pypa/pip/blob/main/src/pip/_internal/req/req_install.py#L252

Unless, I am missing something, it's breaking backward compatibility.

_Originally posted by @anuragkanungo in https://github.com/bazelbuild/rules_python/issues/732#issuecomment-1173365627_

**Comment by groodt** [comment]
That looks like a [PEP440 direct references](https://peps.python.org/pep-0440/#direct-references). Yes, presumably those will need to be excluded from the check.

> Unless, I am missing something, it's breaking backward compatibility.

The packaging rules are not stable and we mention that in the README as follows:
`The packaging rules (pip_install, etc.) are less stable. We may make breaking changes as they evolve.` 

We do of course strive to keep things working as far as possible :) These rules are certainly not in a place where there won't be breaking changes. This "pinning" change was a included in a version bump to indicate that quite a lot of breaking changes had come through.
