### ISSUE TITLE
add the ability to define multiple environments with pip_parse

### ISSUE THREAD

**Issue by KukumavMozolo** [bazelbuild/rules_python#780]
# 🚀 feature request
add the ability to define multiple environments with pip_parse
### Relevant Rules
```
pip_parse,py_library,py_binary,py_test 
```

### Description

Torch can be installed with or without cuda backend. Depending on the target I would like to be able to specify what torch version I want to use. The problem is that both versions are just called torch. Is there a way to do that?

### Describe the solution you'd like

I tried to use pip parse like so:
```
pip_parse(
    name = "pypi",
...
    requirements_lock = "//:requirements_lock.txt",
)

```
and 
```
pip_parse(
    name = "pypi_cuda",
...
    requirements_lock = "//:requirements_lock_cuda.txt",
)

```
and then in py_library/py_binary
```
py_library(
    name = "lib_with_cuda",
    srcs = ["lib.py"],
    deps = [
        "@pypi_cuda_torch//:pkg",
    ],
)
```
or

```
py_library(
    name = "lib_without_cuda",
    srcs = ["lib.py"],
    deps = [
        "@pypi_torch//:pkg",
    ],
)
```
However, this doesn't work atm since pypi will be overwritten by pypi_cuda.

### Describe alternatives you've considered

 Have you considered any alternative solutions or workarounds?

**Comment by groodt** [comment]
The rules do already support multiple repositories. 

I haven’t seen this issue before, try work around it with an entirely different name for the repositories? Try calling it “foo” or something without a similar prefix and see if that helps.

**Comment by KukumavMozolo** [comment]
Thank you, I will try it out.
