### ISSUE TITLE
Need python3.6 binary

### ISSUE THREAD

**Issue by thepolelion** [bazelbuild/rules_python#800]
# 🚀 python3.6 support

### Description

 A clear and concise description of the problem or missing capability...

not finding 3.6 pre-built binary 

### Describe the solution you'd like

[ If you have a solution in mind, please describe it.]
Want 3.6 here (https://github.com/bazelbuild/rules_python/blob/main/python/versions.bzl#L30)

### Describe alternatives you've considered
building custom interpreter

**Comment by groodt** [comment]
The project we use to source the standalone python interpreters doesn't support 3.6 https://github.com/indygreg/python-build-standalone/issues/8#issuecomment-612543572

Supporting versions below 3.7 isn't technically viable as 3.6 is end of life https://endoflife.date/python
