### ISSUE TITLE
allow specifying test timeout in gazelle_python_manifest

### ISSUE THREAD

**Issue by garymm** [bazelbuild/rules_python#802]
# allow specifying test size in gazelle_python_manifest

### Relevant Rules

gazelle_python_manifest

### Description

gazelle_python_manifest generates an sh_test.
In my case, `bazel test` complains that the specified timeout is too long:
```
WARNING: //:gazelle_python_manifest.test: Test execution time (0.2s excluding execution overhead) outside of range for MODERATE tests. Consider setting timeout="short" or size="small".
```

### Describe the solution you'd like

A `test_timeout` parameter to `gazelle_python_manifest`.

### Describe alternatives you've considered

Just ignoring the warning.

If this is acceptable I could try to contribute the PR.

**Comment by f0rmiga** [comment]
A contribution is welcome! I think we can mark this test small no problem, they are supposed to also execute super fast even on large manifests.

**Comment by garymm** [comment]
@f0rmiga https://github.com/bazelbuild/rules_python/pull/817
