### ISSUE TITLE
Cannot set repo_prefix in pip_parse as the docs describe

### ISSUE THREAD

**Issue by caseyduquettesc** [bazelbuild/rules_python#834]
# 🐞 bug report

### Affected Rule

The issue is caused by the rule: `"@rules_python//python:pip.bzl", "pip_parse"`

### Is this a regression?

Unsure, haven't used this feature before

### Description

Trying to configure the repo prefix for migrating a repo from an old version and the attribute seems to cause a failure
```
got multiple values for parameter 'repo_prefix'
```

## 🔬 Minimal Reproduction

```
load("@rules_python//python:pip.bzl", "pip_parse")

pip_parse(
    name = "py3_deps",
    python_interpreter = "python3",
    requirements_lock = "requirements.txt",
   repo_prefix = "pip_pypi__",
)
```

## 🔥 Exception or Error

<pre><code>
        File "~/.cache/bazel/x86_64/722abed65ca53ba6bf8bdec57319a893/external/rules_python/python/pip.bzl", line 206, column 19, in pip_parse
                pip_repository(
Error in repository_rule: com.google.devtools.build.lib.bazel.repository.starlark.StarlarkRepositoryModule$RepositoryRuleFunction@1e5e65b got multiple values for parameter 'repo_prefix'
</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
MacOS 12.6
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
4.1.0
  </code>
</pre>

**Rules_python version:**

<pre>
  <code>
0.12.0
  </code>
</pre>

**Anything else relevant?**

**Comment by groodt** [comment]
`pip_parse` uses the `name` to determine the repo_prefix attribute.

In your example, if you used a `name` of `py3_deps`, your repo_prefix would be `py3_deps_`.

**Comment by FrankPortman** [comment]
Was hoping to re-open this because I just chased my tail here for a while as well.

@groodt your response makes sense for the observed behavior - however, is this intended? Are the maintainers open to allowing `repo_prefix` to actually be used? The `attrs` of `pip_parse` accept it, however it is ignored and re-set manually per your specification.
