### ISSUE TITLE
py_wheel built with stamping doesn't embed version in METADATA file

### ISSUE THREAD

**Issue by pstradomski** [bazelbuild/rules_python#845]
### Affected Rule

py_wheel

### Is this a regression?

No

### Description

//examples/wheel:minimal_with_py_library_with_stamp generates a wheel with the following metadata

```
Metadata-Version: 2.1
Name: example_minimal_library
Version: 0.1.{BUILD_TIMESTAMP}

UNKNOWN
```

There's a verabatim `{BUILD_TIMESTAMP}` there: the replacement was not applied correctly.

**Comment by ns-ggeorgiev** [comment]
I am hitting the same bug as well. Any way to help with the fix?
