### ISSUE TITLE
Various examples do not have a README

### ISSUE THREAD

**Issue by chrislovecnm** [bazelbuild/rules_python#858]
Add a README.md to the examples/pip_repository_annotations directory

**Comment by chrislovecnm** [comment]
pip_parse does not have one

**Comment by chrislovecnm** [comment]
Bump

**Comment by groodt** [comment]
Closing. Documentation can always be improved. Pull requests are always welcome. If there is a proposal for an overhaul of documentation or the maintainers feel like there is a need to track a specific issue around documentation, then this issue will be re-opened or another created.
