### ISSUE TITLE
compile_pip_requirements does not work when the requirements.in is a result of a rule

### ISSUE THREAD

**Issue by ns-ggeorgiev** [bazelbuild/rules_python#860]
# 🐞 bug report

### Affected Rule

rule compile_pip_requirements

### Is this a regression?

no

### Description

when I provide requirements.in file that is generated from a rule, compile_pip_requirements fails file not found, because it is looking for the file in the workspace, instead of bazel sanbox area.

## 🔬 Minimal Reproduction

```
genrule(
        name = "requirements_in",
        outs = ["requirements.in"],
        cmd = "echo six > \"$@\"",
    )

compile_pip_requirements(
    name = "requirements",
    requirements_in = ":requirements_in",
    requirements_txt = "requirements.txt",
)

```

## 🔥 Exception or Error

<pre><code>

Updating bzl/requirements/requirements.txt
Usage: pip_compile.py [OPTIONS] [SRC_FILES]...
Try 'pip_compile.py -h' for help.

Error: Invalid value for '[SRC_FILES]...': Path 'bzl/requirements/requirements.in' does not exist.

</code></pre>

**Comment by rickeylev** [comment]
I don't think this is possible. If I understand things correctly, repo
rules can't use generated files (
https://github.com/bazelbuild/bazel/issues/4069), and compile pip
requirements has to be a repo rule (because it has to run external commands
to resolve transitive deps and generate external repos)

You might be able to approximate something by using Bazel run to generate
the requirements.in file in your source tree, though.

**Comment by jvolkman** [comment]
Is this fixed by #829?

**Comment by rickeylev** [comment]
Oh, I see. I stand corrected!

**Comment by groodt** [comment]
> Oh, I see. I stand corrected!

Only in a sense. The repository rules for locking dependencies probably need a bit more documentation written around them to list the caveats. There are quite a few problematic areas (relative file paths, non-hermetic, platform specific, coupled to a format that might change and rules don’t control) that I think as maintainers we should have the freedom to change if necessary.

**Comment by ns-ggeorgiev** [comment]
The way I solved the same was just adding 
```
        if not shutil._samefile(requirements_in, os.path.join(os.environ["BUILD_WORKSPACE_DIRECTORY"], requirements_in)):
            requirements_in = os.path.abspath(requirements_in)
```

but https://github.com/bazelbuild/rules_python/pull/829 seems to resolves the issue as well.

I am closing this.
