### ISSUE TITLE
Missing file when the target name and folder name are the same

### ISSUE THREAD

**Issue by njlr** [bazelbuild/rules_python#861]
# 🐞 bug report

### Affected Rule

The issue is caused by the rule: `py_binary`

### Is this a regression?

Unknown

### Description

When trying to run the `py_binary` a file cannot be found:

```bash
AssertionError: Cannot exec() '/home/njlr/.cache/bazel/_bazel_njlr/438423ebbd766c9dca9e0913a8f72928/execroot/__main__/bazel-out/k8-fastbuild/bin/foo/foo.runfiles/__main__/foo/foo/main.py': file not found.
```

## 🔬 Minimal Reproduction

Given this structure:

```
.
├── BUILD.bazel
├── foo
│   ├── BUILD.bazel
│   └── foo
│       └── main.py
├── README.md
└── WORKSPACE

```

`WORKSPACE`

```starlark
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
  name = "rules_python",
  sha256 = "8c8fe44ef0a9afc256d1e75ad5f448bb59b81aba149b8958f02f7b3a98f5d9b4",
  strip_prefix = "rules_python-0.13.0",
  url = "https://github.com/bazelbuild/rules_python/archive/refs/tags/0.13.0.tar.gz",
)
```

`foo/BUILD.bazel`

```starlark
py_binary(
  name = "foo",
  main = "foo/main.py",
  srcs = [
    "foo/main.py",
  ],
)
```

## 🔥 Exception or Error

```
bazel run //foo
Starting local Bazel server and connecting to it...
INFO: Analyzed target //foo:foo (40 packages loaded, 308 targets configured).
INFO: Found 1 target...
WARNING: /home/njlr/Documents/python-repro/foo/BUILD.bazel:1:10: runfiles symlink foo/foo/main.py -> foo/foo/main.py obscured by foo/foo -> bazel-out/k8-fastbuild/bin/foo/foo
Target //foo:foo up-to-date:
  bazel-bin/foo/foo
INFO: Elapsed time: 2.758s, Critical Path: 0.02s
INFO: 5 processes: 5 internal.
INFO: Build completed successfully, 5 total actions
INFO: Build completed successfully, 5 total actions
Traceback (most recent call last):
  File "/home/njlr/.cache/bazel/_bazel_njlr/438423ebbd766c9dca9e0913a8f72928/execroot/__main__/bazel-out/k8-fastbuild/bin/foo/foo", line 392, in <module>
    Main()
  File "/home/njlr/.cache/bazel/_bazel_njlr/438423ebbd766c9dca9e0913a8f72928/execroot/__main__/bazel-out/k8-fastbuild/bin/foo/foo", line 326, in Main
    assert os.path.exists(main_filename), \
AssertionError: Cannot exec() '/home/njlr/.cache/bazel/_bazel_njlr/438423ebbd766c9dca9e0913a8f72928/execroot/__main__/bazel-out/k8-fastbuild/bin/foo/foo.runfiles/__main__/foo/foo/main.py': file not found.
```

## 🌍  Your Environment

**Operating System:**

```bash
$ lsb_release -a

No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04 LTS
Release:	22.04
Codename:	jammy
```

**Output of `bazel version`:**

```bash
bazel version
Build label: 5.3.1
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Mon Sep 19 17:28:49 2022 (1663608529)
Build timestamp: 1663608529
Build timestamp as int: 1663608529
```

**Rules_python version:**

`https://github.com/bazelbuild/rules_python/archive/refs/tags/0.13.0.tar.gz`

**Anything else relevant?**

If you rename the folders it starts working!

```
.
├── BUILD.bazel
├── foo
│   ├── bar
│   │   └── main.py
│   └── BUILD.bazel
├── README.md
└── WORKSPACE
```

**Comment by jvolkman** [comment]
The target `//foo:foo` generates a binary at `foo/foo` (a filled-out instance of the Bazel's Python [stub](https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/bazel/rules/python/python_stub_template.txt) script) which replaces the directory `foo/foo` in the runfiles tree. I'm not sure there's a great solution to this other than a better error message. I'm pretty sure all of the relevant logic lives upstream in https://github.com/bazelbuild/bazel.

**Comment by njlr** [comment]
> The target `//foo:foo` generates a binary at `foo/foo` (a filled-out instance of the Bazel's Python [stub](https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/bazel/rules/python/python_stub_template.txt) script) which replaces the directory `foo/foo` in the runfiles tree. I'm not sure there's a great solution to this other than a better error message. I'm pretty sure all of the relevant logic lives upstream in https://github.com/bazelbuild/bazel.

Thanks @jvolkman 

Yes I eventually figured out this is what was happening! A better error message would definitely have helped.
