### ISSUE TITLE
`ignore_root_user_error` flag not working properly, root user error still is raised

### ISSUE THREAD

**Issue by flynneva** [bazelbuild/rules_python#864]
# 🐞 bug report

### Affected Rule

The issue is caused by the rule: `repositories.bzl:python_register_toolchains`

### Is this a regression?

Not that I know of. I think this flag is relatively new. I've tested versions `0.12.0` and `0.13.0`.
### Description

Right now it errors out if the user is `root`. The flag `ignore_root_user_error` is provided in order to skip this, but setting the flag to `True` does not skip the error as intended.

## 🔬 Minimal Reproduction

1. Checkout branch from:  https://github.com/flynneva/rules_ros/pull/1
2. `cd rules_ros/.github/test_ws/`
3. `sudo bazel build @rules_ros//examples/hello_world`

## 🔥 Exception or Error

<pre><code>
ERROR: An error occurred during the fetch of repository 'python_interpreter_x86_64-unknown-linux-gnu':
   Traceback (most recent call last):
	File "/github/home/.cache/bazel/_bazel_root/cfbc809efc5e12740f6d40f95d4c38a2/external/rules_python/python/repositories.bzl", line 153, column 25, in _python_repository_impl
		fail("The current user is root, please run as non-root when using the hermetic Python interpreter. See https://github.com/bazelbuild/rules_python/pull/713.")
Error in fail: The current user is root, please run as non-root when using the hermetic Python interpreter. See https://github.com/bazelbuild/rules_python/pull/713.

</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
uname -a
Linux workshop 5.14.0-1054-oem #61-Ubuntu SMP Fri Oct 14 13:05:50 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
bazel --version
bazel 5.3.1
  </code>
</pre>

**Rules_python version:**

<pre>
  <code>
RULES_PYTHON_VERSION = "0.13.0"
RULES_PYTHON_SHA = "8c8fe44ef0a9afc256d1e75ad5f448bb59b81aba149b8958f02f7b3a98f5d9b4"
  </code>
</pre>

**Anything else relevant?**

**Comment by printdhruv** [comment]
I saw same issue. what's the fix ?
