### ISSUE TITLE
Support python 3.11

### ISSUE THREAD

**Issue by ph03** [bazelbuild/rules_python#866]
# 🚀 Support python 3.11 toolchain

### Relevant Rules

`python_register_toolchains`

### Description

 A clear and concise description of the problem or missing capability...

Python 3.11 was just released and it would be nice to hook it up in via `rules_python`

### Describe the solution you'd like

Add support for `python_version = "3.11"` in `python_register_toolchains` by enumerating packages in `//python:versions.bzl`.

**Comment by groodt** [comment]
Tracking issue for upstream https://github.com/indygreg/python-build-standalone/issues/141

**Comment by indygreg** [comment]
Just published https://github.com/indygreg/python-build-standalone/releases/tag/20230116. So hopefully this is unblocked now.

**Comment by jvolkman** [comment]
Thank you @indygreg!
