### ISSUE TITLE
Rolling TLS brownouts breaking pip integration

### ISSUE THREAD

**Issue by jkinkead** [bazelbuild/rules_python#87]
I'm seeing mysterious failures that I'm pretty sure are [this issue](https://github.com/pypa/packaging-problems/issues/130): pypi deprecating old TLS support.

The fix is to update to pip 9.0.3. I have a patch for this coming in a PR in a moment.

**Comment by jkinkead** [comment]
@mattmoor / @duggelz - Per one of the comments in the linked issue, this is going to break the pip rules completely starting April 8th (Monday). This should be fixed ASAP.

**Comment by duggelz** [comment]
Pull request merged, thank you.

**Comment by jkinkead** [comment]
Thanks for fixing this quickly!
