### ISSUE TITLE
py_test generate test.xml miss "classname" which cannot pass the junit schema check

### ISSUE THREAD

**Issue by doubler** [bazelbuild/rules_python#882]
# 🐞 bug report

### Affected Rule
load("@rules_python//python:defs.bzl", "py_test")
the `py_test` rule

### Is this a regression?
no

### Description
the `bazel test` output file failed to pass the junit validation

## 🔬 Minimal Reproduction
`bazel test //package:target`
Check the XML reports are located in `bazel-testlogs/package/target/test.xml`
```
<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
  <testsuite name="xxx/smoke_test" tests="1" failures="0" errors="0">
    <testcase name="xxx/smoke_test" status="run" duration="3" time="3"></testcase>
      <system-out>
-----------------------------------------------------------------------------
.
----------------------------------------------------------------------
Ran 9 tests in 0.340s

      </system-out>
    </testsuite>
</testsuites>
```

## 🔥 Exception or Error
miss the `classname` attribute which is required in the [junit schema](https://windyroad.com.au/dl/Open%20Source/JUnit.xsd)
![image](https://user-images.githubusercontent.com/1324660/201317074-e2284011-ea38-42b5-9181-9b105b26a576.png)

## 🌍  Your Environment

**Operating System:**
centos7

**Output of `bazel version`:**

<pre>
  <code>
Build label: 4.2.3
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed Oct 19 08:27:37 2022 (1666168057)
Build timestamp: 1666168057
Build timestamp as int: 1666168057
  </code>
</pre>

**Rules_python version:**

<pre>
  <code>
Python 3.7.11
pytest==6.2.5
  </code>
</pre>

**Anything else relevant?**

**Comment by mattem** [comment]
Confusingly, rules_python doesn't contain the logic to generate the Junit XMLs, that lives in the [bazel server itself](https://cs.opensource.google/bazel/bazel/+/master:tools/test/generate-xml.sh;l=118). Can you open this issue against the main bazel repo? Thanks!
