### ISSUE TITLE
Support for PEP 440 local version identifiers is broken

### ISSUE THREAD

**Issue by vonschultz** [bazelbuild/rules_python#883]
# 🐞 bug report

### Affected Rule

The issue is caused by the rule: `py_wheel`.

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 0.3.0

### Description

Support for [PEP 440 local version identifiers](https://peps.python.org/pep-0440/#local-version-identifiers) is broken. While a version number such as `1.0.0+local` is correctly reflected in the `*.dist-info/METADATA` file, it is not correctly reflected in commands such as `pip list`, `pip show` or `pip freeze`, which show this version number as `1.0.0-local`, with `-` instead of `+`.

## 🔬 Minimal Reproduction

<pre><code>load("@rules_python//python:packaging.bzl", "py_wheel")

py_wheel(
    name = "testwheel",
    distribution = "test",
    version = "1.0.0+local",
    visibility = ["//visibility:public"],
) </code></pre>

and a `WORKSPACE.bazel` file according to [version 0.3.0](https://github.com/bazelbuild/rules_python/releases/tag/0.3.0) (works), [version 0.4.0](https://github.com/bazelbuild/rules_python/releases/tag/0.4.0) (exhibits problem) or [version 0.13.0](https://github.com/bazelbuild/rules_python/releases/tag/0.13.0) (exhibits problem).

Build the wheel, install in a venv, run `pip list`, see the correct version `1.0.0+local` (in case of rules_python 0.3.0) or incorrect version `1.0.0-local` (in newer versions).

## 🔥 Exception or Error

If used with a package index and a `requirements.txt` file, you'll find that the `-` version number raises `pip._vendor.packaging.version.InvalidVersion` or `has inconsistent version` (depending on `pip` version), and the `+` version number produces `Could not find a version that satisfies the requirement`.

Using `pip 22.3.1` (you may need to `pip install --upgrade pip`):
<pre><code>$ pip install test==1.0.0+local -f rules_python-0.13.0/bazel-bin/
Looking in links: rules_python-0.13.0/bazel-bin/
ERROR: Could not find a version that satisfies the requirement test==1.0.0+local (from versions: 1.0.0-local)
ERROR: No matching distribution found for test==1.0.0+local</code></pre>
<pre><code>$ pip install test==1.0.0-local -f rules_python-0.13.0/bazel-bin/
Looking in links: rules_python-0.13.0/bazel-bin/
Processing /home/von/.cache/bazel/_bazel_von/709d76476fbc87d51d99291df73a3511/execroot/__main__/bazel-out/k8-fastbuild/bin/test-1.0.0_local-py3-none-any.whl
Discarding file:///home/von/.cache/bazel/_bazel_von/709d76476fbc87d51d99291df73a3511/execroot/__main__/bazel-out/k8-fastbuild/bin/test-1.0.0_local-py3-none-any.whl: Requested test==1.0.0-local from file:///home/von/.cache/bazel/_bazel_von/709d76476fbc87d51d99291df73a3511/execroot/__main__/bazel-out/k8-fastbuild/bin/test-1.0.0_local-py3-none-any.whl has inconsistent version: expected '1.0.0-local', but metadata has '1.0.0+local'
ERROR: Could not find a version that satisfies the requirement test==1.0.0-local (from versions: 1.0.0-local)
ERROR: No matching distribution found for test==1.0.0-local</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre><code>Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.5 LTS
Release:	20.04
Codename:	focal</code></pre>

**Output of `bazel version`:**

<pre><code>Bazelisk version: v1.9.0
Build label: 5.3.2
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed Oct 19 18:22:12 2022 (1666203732)
Build timestamp: 1666203732
Build timestamp as int: 1666203732</code></pre>

**Rules_python version:**

0.13.0

## 🔍 Anything else relevant?

You may also compare with the corresponding setuptools project:

<pre><code>from setuptools import setup, find_packages

setup(
    name='test',
    version='1.0.0+local',
    packages=find_packages(),
)</code></pre>

This does not exhibit the problem. Analyzing the contents of the `.whl` files seems to indicate that the problem is the name of the `*.dist-info` directory, which in all the working examples uses a `+` in the version number part. The broken versions use `_` instead of `+` in the name of the `*.dist-info` directory, and renaming the `*.dist-info` directory inside the venv to use `+` instead of `_` fixes the bug.

It seems probable to me that the problem was introduced in pull request #518, which was supposed to escape characters in the wheel file name according to [PEP 427](https://peps.python.org/pep-0427/#escaping-and-unicode). That's all fine when it comes to the name of the wheel file itself, but nothing in PEP 427 says to do that to the dist-info directory, and I think doing so causes the observed breakage.

I believe, in other words, that `escape_filename_segment()` should be removed from [tools/wheelmaker.py](https://github.com/bazelbuild/rules_python/blob/main/tools/wheelmaker.py).

**Comment by vonschultz** [comment]
I wrote in the description:
> [...] the problem was introduced in pull request https://github.com/bazelbuild/rules_python/pull/518, which was supposed to escape characters in the wheel file name according to [PEP 427](https://peps.python.org/pep-0427/#escaping-and-unicode). That's all fine when it comes to the name of the wheel file itself, but [...]

Actually, digging a bit deeper, it is **not** all fine when it comes to the name of the wheel file either. [PEP 427](https://peps.python.org/pep-0427/) "is a historical document. The up-to-date, canonical spec, [Binary distribution format](https://packaging.python.org/en/latest/specifications/binary-distribution-format/#binary-distribution-format), is maintained on the [PyPA specs page](https://packaging.python.org/en/latest/specifications/)."

Guess what that says about escaping version numbers?

> Version numbers should be normalised according to [PEP 440](https://peps.python.org/pep-0440/).

https://packaging.python.org/en/latest/specifications/binary-distribution-format/#escaping-and-unicode

So we should never do anything like `escape_filename_segment()` on a version number. Not on the `dist-info` directory, and not on the wheel file name either. But there is a [PEP 440 Normalization](https://peps.python.org/pep-0440/#normalization) procedure to follow instead.

**Comment by hisener** [comment]
Is there any update on this? The [latest version of setuptools](https://setuptools.pypa.io/en/latest/history.html#v66-0-0) also drops the support for PEP 440 non-conforming versions.

Currently, the logic below breaks our wheels with a local version segment (e.g., `1.0.0+ubuntu`) since it replaces `+` with `_`.

https://github.com/bazelbuild/rules_python/blob/aab11ab0736c22585d4c2185c50916b1af48b975/python/packaging.bzl#L99-L115

**Comment by vonschultz** [comment]
The problem exists in two places, as far as I can see. Once in Starlark code, here:
https://github.com/bazelbuild/rules_python/blob/c5f24dd4927a0ce9881792389c84e359a3a7b528/python/private/py_wheel.bzl#L209-L220
Once in Python code, here:
https://github.com/bazelbuild/rules_python/blob/c5f24dd4927a0ce9881792389c84e359a3a7b528/tools/wheelmaker.py#L63-L68
In the Python world, I think I know what the right solution would be.
```python
 import packaging.utils 
 self._distinfo_dir = ( 
     packaging.utils.canonicalize_name(self._name) 
     + "-" 
     + packaging.utils.canonicalize_version(self._version) 
     + ".dist-info/" 
 ) 
```
(See https://packaging.pypa.io/en/stable/utils.html#packaging.utils.canonicalize_version)

However, running `packaging.utils.canonicalize_version()` likely won't be an option in the Starlark world. I don't know if @pstradomski has given this some thought, but maybe we should simply change the interface of `py_wheel` by adding the requirement that `version` needs to be [normalized according to PEP 440](https://peps.python.org/pep-0440/#normalization) already when you invoke `py_wheel` — we won't do it for you. In `wheelmaker.py` we could then check this requirement,
```python
import packaging.utils
if self._version != packaging.utils.canonicalize_version(self._version):
    raise SomeSuitableException(
        "version needs to be normalized according to PEP 440. "
        f"Got {self._version}, expected {packaging.utils.canonicalize_version(self._version)}")
```
The alternative would be to try to re-implement `packaging.utils.canonicalize_version()` as a Starlark function, I suppose.
