### ISSUE TITLE
Intellij plugin can't resolve imports after 0.10+ (x-post)

### ISSUE THREAD

**Issue by caseyduquettesc** [bazelbuild/rules_python#885]
I wanted to loop in some rules_python maintainers to this intellij plugin issue (https://github.com/bazelbuild/intellij/issues/2239) to get their thoughts. Essentially, after rules_python 0.10, the bazel intellij plugin can't resolve imports anymore. [Downgrading](https://github.com/bazelbuild/intellij/issues/2239#issuecomment-1231966928) rules_python to 0.9 seems to fix the issue, which I also confirmed.

Would help a great deal to narrow down which change may have changed the behavior of the bazel plugin, and whether the fix should be on the plugin side or the rules side.

**Comment by groodt** [comment]
Replied https://github.com/bazelbuild/intellij/issues/2239#issuecomment-1379441363
