### ISSUE TITLE
Drop Python 2 support

### ISSUE THREAD

**Issue by rickeylev** [bazelbuild/rules_python#886]
This is the general tracking issue for removing Python 2 support in rules_python.

For the bazel-side of things, see https://github.com/bazelbuild/bazel/issues/15684

Right now, Python 2 support is defacto not present because...
 * `pip_parse` doesn't work with Python 2
 * Many systems don't provide Python 2 anymore
 * Many libraries no longer support Python 2
 * Us maintainers of these rules will ignore requests for it
 * The Starlark rewrite of the native.py_* rules won't support it
 * It has been 2+ years past the Python 2 EOL date.

However, several of our apis still accept e.g. `python_version=PY2` or `src_version=PY2|PY2ONLY`, which technically do allow Python 2. We'll be disabling and breaking those.

If you want to continue to use rules_python with Python 2, then you will need to use an earlier release and/or fork.

TODO list
  * [ ] Fail for `python_version` and `srcs_version` values that are Python 2
  * [ ] For if `py_runtime_pair.py2_runtime` is set
  * [ ] Remove `PYTHON2` make var (see `current_py_toolchain`)

**Comment by pstradomski** [comment]
Note: there are a few `if sys.version` in wheelmaker.py. If we're dropping py2 support, these could be removed to simplify the code.

**Comment by rickeylev** [comment]
posterity/update: the PR is ready to merge and it'll be merged in January after the holidays. We're also going to cut one last release before it is merged.

**Comment by rickeylev** [comment]
Actually, small change of plans: I've merged this in now with https://github.com/bazelbuild/rules_python/pull/887.

If it turns out to be too problematic, we can revert it for now and attempt again after the holidays. In the meantime, we'll find out about any issues sooner rather than later.
