### ISSUE TITLE
Condition `pip_parse` on python version?

### ISSUE THREAD

**Issue by deannagarcia** [bazelbuild/rules_python#898]
# 🐞 bug report

### Affected Rule

The issue is caused by the rule: `pip_parse`

### Is this a regression?

Did this behavior use to work in the previous version? no

### Description

When `requirements.txt` is conditioned on `python_version` and only one matches an error is thrown.

## 🔬 Minimal Reproduction

Using this `requirements.txt`:
```
numpy==1.21.6; python_version < "3.11"
numpy==1.23.5; python_version >= "3.11"
```

and attempt to load `@pip_deps_numpy`

## 🔥 Exception or Error

When compiling with python 3.10 I see:

<pre><code>
ERROR: An error occurred during the fetch of repository 'pip_deps_numpy':
   Traceback (most recent call last):
	File "/workspace/_build/out/external/rules_python/python/pip_install/pip_repository.bzl", line 550, column 13, in _whl_library_impl
		fail("whl_library %s failed: %s (%s)" % (rctx.attr.name, result.stdout, result.stderr))
Error in fail: whl_library pip_deps_numpy failed: Ignoring numpy: markers 'python_version >= "3.11"' don't match your environment
 (Traceback (most recent call last):
  File "/usr/local/bin/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/bin/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/workspace/_build/out/external/rules_python/python/pip_install/extract_wheels/extract_single_wheel.py", line 105, in <module>
    main()
  File "/workspace/_build/out/external/rules_python/python/pip_install/extract_wheels/extract_single_wheel.py", line 92, in main
    whl = next(iter(glob.glob("*.whl")))
StopIteration
)
</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Linux x86
  </code>
</pre>

**Rules_python version:**

<pre>
  <code>
0.14.0
  </code>
</pre>

**Anything else relevant?**

**Comment by groodt** [comment]
`pip_parse` and the approach used in the rules to retrieve external python packages from pypi requires the usage of a fully resolved set of dependencies. See the documentation for [installing third party dependencies](https://github.com/bazelbuild/rules_python#installing-third_party-packages). The reason for this is to avoid non-hermetic builds as much as possible during the execution of the repository rules.

You can obtain something similar to what you want by having your input dependencies defined in a `requirements.in` file and compiling or resolving it into different `requirements.txt` for your different python versions. You can use something like pip-tools or the `compile_pip_requirements` rule to produce these files for you.

You will then need to use 2 different `pip_parse` invocations (and toolchains) to support your desired outcome. Something similar to.

```
# WORKSPACE

load("@rules_python//python:pip.bzl", "pip_parse")
load("@python3_10//:defs.bzl", interpreter_310 = "interpreter")
load("@python3_11//:defs.bzl", interpreter_311 = "interpreter")

pip_parse(
    name = "pypi_310",
    python_interpreter_target = interpreter_310,
    requirements_lock = "requirements_310.txt",
)

pip_parse(
    name = "pypi_311",
    python_interpreter_target = interpreter_311,
    requirements_lock = "requirements_311.txt",
)
```
