### ISSUE TITLE
invalid repository name when using `pip_parse` from module (0.14.0)

### ISSUE THREAD

**Issue by kirschem** [bazelbuild/rules_python#900]
# 🐞 bug report

### Affected Rule

 The issue is caused by the rule: pip_parse / pip module extension

### Is this a regression?

No.

### Description

 A clear and concise description of the problem...
When using pip_parse from the module, it seems like something is wrong with the repository names. Using the example below, the `requirement` macro generates a bad repo name containing two `@`s.

However, when I correct the repo name manually (without using `requirement`), I'm hitting a visibility issue:
```
#BUILD.bazel

py_test(
    name = "a_test",
    srcs = ["a_test.py"],
    deps = ["@rules_python.0.14.0.pip.pip//:pytest_pkg"],
)
```
```
The repository '@rules_python.0.14.0.pip.pip' could not be resolved: Repository '@rules_python.0.14.0.pip.pip' is not visible from repository '@'
```

## 🔬 Minimal Reproduction

```
#MODULE.bazel

bazel_dep(name = "rules_python", version = "0.14.0")
python = use_extension("@rules_python//python:extensions.bzl", "python")
python.toolchain(
    name = "python3_8",
    python_version = "3.8",
)
use_repo(python, "python3_8_toolchains")
register_toolchains(
    "@python3_8_toolchains//:all",
)
pip = use_extension("@rules_python//python:extensions.bzl", "pip")

pip.parse(
    name = "pip",
    requirements_lock = "//:requirements_lock.txt",
)

use_repo(pip, "pip")
```
```
#requirements_lock.txt

#
# This file is autogenerated by pip-compile with python 3.8
# To update, run:
#
#    bazel run //bazel/rules/python:requirements.update
#
attrs==22.1.0 \
    --hash=sha256:29adc2665447e5191d0e7c568fde78b21f9672d344281d0c6e1ab085429b22b6 \
    --hash=sha256:86efa402f67bf2df34f51a335487cf46b1ec130d02b8d39fd248abfd30da551c
    # via pytest
exceptiongroup==1.0.4 \
    --hash=sha256:542adf9dea4055530d6e1279602fa5cb11dab2395fa650b8674eaec35fc4a828 \
    --hash=sha256:bd14967b79cd9bdb54d97323216f8fdf533e278df937aa2a90089e7d6e06e5ec
    # via pytest
iniconfig==1.1.1 \
    --hash=sha256:011e24c64b7f47f6ebd835bb12a743f2fbe9a26d4cecaa7f53bc4f35ee9da8b3 \
    --hash=sha256:bc3af051d7d14b2ee5ef9969666def0cd1a000e121eaea580d4a313df4b37f32
    # via pytest
packaging==21.3 \
    --hash=sha256:dd47c42927d89ab911e606518907cc2d3a1f38bbd026385970643f9c5b8ecfeb \
    --hash=sha256:ef103e05f519cdc783ae24ea4e2e0f508a9c99b2d4969652eed6a2e1ea5bd522
    # via pytest
pluggy==1.0.0 \
    --hash=sha256:4224373bacce55f955a878bf9cfa763c1e360858e330072059e10bad68531159 \
    --hash=sha256:74134bbf457f031a36d68416e1509f34bd5ccc019f0bcc952c7b909d06b37bd3
    # via pytest
pyparsing==3.0.9 \
    --hash=sha256:2b020ecf7d21b687f219b71ecad3631f644a47f01403fa1d1036b0c6416d70fb \
    --hash=sha256:5026bae9a10eeaefb61dab2f09052b9f4307d44aee4eda64b309723d8d206bbc
    # via packaging
pytest==7.2.0 \
    --hash=sha256:892f933d339f068883b6fd5a459f03d85bfcb355e4981e146d2c7616c21fef71 \
    --hash=sha256:c4014eb40e10f11f355ad4e3c2fb2c6c6d1919c73f3b5a433de4708202cade59
    # via -r ./requirements.in
tomli==2.0.1 \
    --hash=sha256:939de3e7a6161af0c887ef91b7d41a53e7c5a1ca976325f429cb46ea9bc30ecc \
    --hash=sha256:de526c12914f0c550d15924c62d72abc48d6fe7364aa87328337a31007fe8a4f
    # via pytest
```

```
#BUILD.bazel

load("@pip//:requirements.bzl", "requirement")


py_test(
    name = "a_test",
    srcs = ["a_test.py"],
    deps = [requirement("pytest")],
)
```

## 🔥 Exception or Error

<pre><code>

invalid label '@@rules_python.0.14.0.pip.pip//:pytest_pkg' in element 0 of attribute 'deps' in 'py_test' rule: invalid repository name '@@rules_python.0.14.0.pip.pip': workspace names may contain only A-Z, a-z, 0-9, '-', '_' and '.'

</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Linux (Ubuntu 20)
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
Build label: 5.3.2
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed Oct 19 18:22:12 2022 (1666203732)
Build timestamp: 1666203732
Build timestamp as int: 1666203732
  </code>
</pre>

**Rules_python version:**

<pre>
  <code>
     0.14.0
  </code>
</pre>

**Anything else relevant?**

**Comment by kirschem** [comment]
@kormide I think you implemented that here: https://github.com/bazelbuild/rules_python/issues/900
I tried to dig into the code a little but could not pinpoint the issue yet. Could you explain the mechanism behind the double `@`?

**Comment by kirschem** [comment]
Ok, it seems like this new label syntax is introduced with Bazel 6: https://docs.google.com/document/d/1N81qfCa8oskCk5LqTW-LNthy6EBrDot7bdUsjz6JFC4/edit#heading=h.5mcn15i0e1ch

This explains the error message. I will try it now with version 6.

**Comment by kormide** [comment]
If you want to have access to a repository created by the bzlmod extension, you have to use `use_repo` to give it a name in your workspace. This is due to strict deps in bzlmod.

>  Still, I wonder if someone was able to run the modules example on their machine?
That example should have a `.bazelversion` pointing to 6, so if you use bazelisk it should run correctly.

**Comment by kirschem** [comment]
After working around this java issue, it is looking good now, thanks! Closing the issue.
