### ISSUE TITLE
two releases for 0.15.0

### ISSUE THREAD

**Issue by gawi** [bazelbuild/rules_python#905]
# 🐞 bug report

### Description

There were 2 different versions of 0.15.0. The checksum has changed during the day but not the version number. 

We picked up the 1st 0.15.0 this morning and updated our WORKSPACE file with the fab7608fc15a2bc2cc42c137a7eff516d51376aa1fd237023f44c7e2b1cac681 checksum to find out later that it has been updated with fda23c37fbacf7579f94d5e8f342d3a831140e9471b770782e83846117dd6596.

## 🔬 Minimal Reproduction

Not relevant.

## 🔥 Exception or Error

<pre><code>
Error in download_and_extract: java.io.IOException: Error downloading [https://github.com/bazelbuild/rules_python/archive/refs/tags/0.15.0.tar.gz] to /home/runner/.cache/bazel/_bazel_runner/ef964960fb460c615b37dff2bce8fda2/external/rules_python/temp12652826977816361866/0.15.0.tar.gz: Checksum was fda23c37fbacf7579f94d5e8f342d3a831140e9471b770782e83846117dd6596 but wanted fab7608fc15a2bc2cc42c137a7eff516d51376aa1fd237023f[44](https://github.com/nuecho/nu-workforce/actions/runs/3577564209/jobs/6016793815#step:5:45)c7e2b1cac681</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
$ uname -a
Linux myhost 5.4.0-132-generic #148-Ubuntu SMP Mon Oct 17 16:02:06 UTC 2022 x86_64 GNU/Linux
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
Bazelisk version: development
Build label: 5.3.2
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed Oct 19 18:22:12 2022 (1666203732)
Build timestamp: 1666203732
Build timestamp as int: 1666203732
  </code>
</pre>

**Rules_python version:**

<pre>
  <code>
0.15.0 (well... one of them)
  </code>
</pre>

**Anything else relevant?**

**Comment by f0rmiga** [comment]
A tag existed but there was no release attached to it. A tag alone cannot be assumed to be a release.

**Comment by alexeagle** [comment]
@gawi do you know how you picked up the first SHA? do you have some automation like renovate that might have picked it up?

**Comment by gawi** [comment]
> @gawi do you know how you picked up the first SHA? do you have some automation like renovate that might have picked it up?

Yes, renovate.
