### ISSUE TITLE
compile_pip_requirements no longer uses predictable paths

### ISSUE THREAD

**Issue by vonschultz** [bazelbuild/rules_python#908]
# 🐞 bug report

### Affected Rule

The issue is caused by the rule: `compile_pip_requirements`

### Is this a regression?

Yes, the previous version in which this bug was not present was: 0.13.0. It is present in 0.15.0. I didn't explicitly check 0.14.0, but I'll actually go one step further: a `git bisect` says the first bad commit is b15e15fb95d584df80339a5f3bdfd253fcdff2dc. (Ping @philsc  and @f0rmiga.)

### Description

As it says in python/pip_install/pip_compile.py: 
 
>    We don't want fully resolved, absolute paths in the generated requirements file.
>    The paths could differ for every invocation. Replace them with a predictable path.

I haven't double checked that that's the right file for this bug report, but the comment describes a desirable outcome that I'm no longer seeing.

## 🔬 Minimal Reproduction

See https://gist.github.com/vonschultz/9e242d1612ec70b1848057cce681e037. I'm using it with `bazelisk run :pip_dependencies.update`. 

## 🔥 Exception or Error

You see the problem in [requirements_common_lock-txt](https://gist.github.com/vonschultz/9e242d1612ec70b1848057cce681e037#file-requirements_common_lock-txt):
<pre><code>    # via -r /tmp/rules_python-tests/9e242d1612ec70b1848057cce681e037/requirements_extra.in</code></pre>

Before b15e15fb95d584df80339a5f3bdfd253fcdff2dc that line reads
<pre><code>    # via -r ./requirements_extra.in</code></pre>
which is the desired behavior.

## 🌍  Your Environment

**Operating System:**

Ubuntu 20.04

**Output of `bazel version`:**

<pre>
  <code>
Bazelisk version: v1.9.0
Build label: 5.3.2
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed Oct 19 18:22:12 2022 (1666203732)
Build timestamp: 1666203732
Build timestamp as int: 1666203732
  </code>
</pre>

**Rules_python version:**

<pre><code>0.15.0</code></pre>

**Comment by f0rmiga** [comment]
I was able to reproduce this and it only seems to happen with the added `-r requirements_extra.in`.

**Comment by philsc** [comment]
Whoops. Sorry about that. Thanks for fixing it @f0rmiga!

**Comment by vonschultz** [comment]
I can confirm that the problem is fixed in the new version, 0.15.1. Many thanks, @f0rmiga.

**Comment by vonschultz** [comment]
The bug is back. Regression caused by fbf8bc10a466c498fc80c6b58c939a87a8d9e929 according to my `git bisect`. Reproducing with Ubuntu 24.04 and Bazel 8.0.1.

**Comment by louisbuchbinder** [comment]
I am seeing this issue with:
bazel version: 8.3.1
rules_python: 1.6.0

result of compile-pip-requirements update lock file has absolute paths in via requirements
```
 # via
    #   -r /private/var/tmp/_bazel_...
```

this fails in the test step with a diff on the file path. If I get around to making a patch I will share back here.
