### ISSUE TITLE
Copyright headers

### ISSUE THREAD

**Issue by chrislovecnm** [bazelbuild/rules_python#916]
This is a housekeeping issue for the repo.  I am noticing that we do not have copyright headers on the code files.  See here: https://github.com/bazelbuild/bazel/blob/master/src/create_embedded_tools.py#L3 for an example of the header I a referring to. The go_fules repo uses the "addlicense" tool to update the headers in the code. 

Is this something we should have in this repo as well?

**Comment by rickeylev** [comment]
I'm guessing the answer is probably "yes". I emailed our licensing people on the off chance the answer is "no"

**Comment by rickeylev** [comment]
I heard back: the answer is yes, they should all have the copyright notice

**Comment by rickeylev** [comment]
After talking with some lawyers, the couple generated files I skipped initially also need to have copyright headers added (just to the checked in file in our repo, the code-generator won't emit a copyright header). Gonna re-open this to address that.

**Comment by chrislovecnm** [comment]
Closing.  We fixed
