### ISSUE TITLE
whl_library ignores purelib / platlib directories

### ISSUE THREAD

**Issue by jkinkead** [bazelbuild/rules_python#92]
The `whl_library` rule does not handle `purelib` and `platlib` directories at all during unpacking.

See [the "Spread" section in PEP 491](https://www.python.org/dev/peps/pep-0491/#installing-a-wheel-distribution-1-0-py32-none-any-whl) for more info.

This is the root cause of issue #71 .

**Comment by jkinkead** [comment]
[A quick-hack implementation of a fix](https://github.com/jkinkead/rules_python/commit/220c1133af2bb5c37f20c87b4c2ccfeee596ecda).

It works in the tensorflow case, but is probably broken in many others.

**Comment by faltad** [comment]
We have exactly the same issue with SQLAlchemy. Tried your branch @jkinkead and it seems to fix the issue (aka bringing the sqlalchemy folder to the root of the package)

**Comment by josh-theorem** [comment]
Just want to bump this fix or get a conversation going for a more general fix. We also had xgboost fail (also reported by someone else in #104), and I can confirm it's caused by this same issue with purelib

**Comment by lshamis** [comment]
Thanks @jkinkead for the fix impl. Is there any fix that doesn't involve rebuilding the par files?
My bazel setup provides a "patch" hook for git repos, s.t. a diff is applied immediately after fetching. This allows us to make small fixes to a repo without requiring a full fork. Unfortunately, it doesn't work for binaries.

**Comment by vmax** [comment]
@jkinkead thank you for the patch! would you be able to submit a PR with it such that it can be reviewed and integrated into upstream?

**Comment by jkinkead** [comment]
I wrote that patch two computers ago, shortly before giving up on using bazel. :)

The patch is a bad hack - I didn't read the PEP to ensure I was following spec, and I recall ignoring most of it. It's still live on my fork if anyone would like to take it over!

**Comment by groodt** [comment]
I believe this issue can be closed. Modern versions of the rules do support purelib and platlib.
