### ISSUE TITLE
rules_python does not respect the `namespace_packages=` argument of setuptools.setup().

### ISSUE THREAD

**Issue by mishas** [bazelbuild/rules_python#93]
(more information here: http://setuptools.readthedocs.io/en/latest/setuptools.html#namespace-packages)

There are packages, that have the same namespace in their name. Trying to use them via rules_python fails on `ImportError: No module named '...'`.

For example, try installing this package: `testing.postgresql`. It has another package `testing.common.database` as its dependency. Now rules_python installs those separately without taking the `namespace_packages=['testing']` argument into account, which creates a situation where during `import testing.postgresql`, the program fails with `ImportError: No module named 'testing.postgresql'`, due to it's stopping the search after finding the first "testing" directory in the path, which belongs to `testing.common.database`.

Possible solution: pushing an __init__.py file declaring a namespace (having the content: `__path__ = __import__("pkgutil").extend_path(__path__, __name__)`) instead of an empty file to folders that should be namespaces.

**Comment by calder** [comment]
Is anyone working on fixing this? This makes it impossible to use [google-auth](https://github.com/GoogleCloudPlatform/google-auth-library-python) and protobuf in the same py_binary.

**Comment by daicoden** [comment]
+1 ran into this issue too.  

I think the suggested `__path__ = __import__("pkgutil").extend_path(__path__, __name__)`, will work - here's the workaround I came up with which might fix your issue @mishas. I can see the proper files on disk, with the`__path__` in place.


```
def _py_namespace_impl(ctx):
    srcs_with_namespace = []
    symlinks = {}
    namespace_directory = ""

    for file in ctx.files.srcs:
        parts = file.path.split(ctx.attr.namespace)
        if len(parts) == 2:
            if namespace_directory == "":
                namespace_directory = parts[0]

            elif namespace_directory != parts[0]:
                fail("The srcs packages are too complex, use multiple py_namespace rules to break it up")

            if parts[1] == "__init__":
                # Don't add it to the srcs_with_namespace, instead we're going to insert our own before
                pass
            else:
                srcs_with_namespace += [file]
                # Eh, can't get this to work... symlinks don't get created :(
                # symlinks[file.path] = file

        else:
            # File not related to namespace
            srcs_with_namespace += [file]
            # symlinks[file.path] = file


    if namespace_directory == "":
        fail("Can't continue, namespace %s not found" % ctx.attr.namespace)

    init_file_with_namespace = ctx.actions.declare_file("%s/%s/__init__.py" % (namespace_directory, ctx.attr.namespace))
    ctx.actions.write(init_file_with_namespace, "__path__ = __import__('pkgutil').extend_path(__path__, __name__)\n")

    # Hack instead of symlinks
    copied_files = []
    for file in srcs_with_namespace:
        newFile = ctx.actions.declare_file(file.path)
        ctx.actions.run_shell(
            arguments = [file.path, newFile.path],
            inputs = [file],
            outputs = [newFile],
            command = "cp $1 $2",
        )
        copied_files += [newFile]

    return DefaultInfo(
        files = depset(copied_files + [init_file_with_namespace]),
        runfiles = ctx.runfiles(
            files=copied_files + [init_file_with_namespace],
            # root_symlinks=symlinks,
        ),
    )

_py_namespace = rule(
    attrs = {
        "srcs": attr.label_list(providers = ["py"]),
        "namespace": attr.string(),
    },
    implementation = _py_namespace_impl,
)

def py_namespace(name, srcs, namespace, imports = ['.']):
    '''
    Adds `__path__ = __import__('pkgutil').extend_path(__path__, __name__)` to the
    init file in the first directory matching namespace
    '''
    _py_namespace(
        name = name + '_namespaced',
        srcs = srcs,
        namespace = namespace
    )

    native.py_library(
        name = name,
        srcs = [':%s_namespaced' % name],
        imports = imports,
    )
```

Unfortunately I'm stuck because of python_protobuf.  Using google protos causes generated code to not include the __path__ change, and it's not as simple as using a similar strategy :(.  Alas I'm out of time to try and fix it, so I'll be installing protobuf with pip on the system for now until this issue can be addressed.  Though, it may need a change in rules_protobuf too... 😢.

**Comment by therc** [comment]
This seems to be a duplicate or, at least, to highly overlap with #14 and #55. The `legacy_create_init` flag with which the latter was closed doesn't really help with the protobuf/google-auth case. You'd assume that using a Google tool with a bunch of Google libraries would just work, but alas...

**Comment by raliste** [comment]
@therc to use protobuf/google apis I created a fork of [googleapiclient](https://github.com/googleapis/google-api-python-client) that simply removes google-auth as a strict dependency from the setup.py. It does work at the expense of using googleapiclient instead of google-cloud packages. The only real benefit of those, at the moment, is gRPC and better idioms, as far as I can see. I think this is the best approach to use python google apis with Bazel at this point in time.

**Comment by ali5h** [comment]
i fixed this issue in https://github.com/ali5h/rules_pip_lock

**Comment by skyl** [comment]
This issue is really blocking our adoption of bazel for Python ...

**Comment by skyl** [comment]
@ali5h I tried your rules and I can't get it to work with a `-e git` requirement. For example:

```
TypeError: Expected a pinned InstallRequirement, got django-mass-edit from git+https://github.com/frnhr/django-mass-edit.git@c424abb7ce43dcb54e822862651821720d52f50b#egg=django-mass-edit (from -r /private/var/tmp/_bazel_i871067/582c43307c634a2c875ee31a5da68b63/external/py/requirements.txt (line 7))
```

```
ERROR: no such package '@py//': pip_import failed:  (Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/private/var/tmp/_bazel_i871067/582c43307c634a2c875ee31a5da68b63/external/com_github_alish_rules_pip_lock/tools/piptool.par/__main__.py", line 184, in <module>
  File "/private/var/tmp/_bazel_i871067/582c43307c634a2c875ee31a5da68b63/external/com_github_alish_rules_pip_lock/tools/piptool.par/__main__.py", line 141, in main
  File "/private/var/tmp/_bazel_i871067/582c43307c634a2c875ee31a5da68b63/external/com_github_alish_rules_pip_lock/tools/piptool.par/__main__.py", line 48, in as_tuple
```

I wonder if you have any ideas about this. Thanks for the contribution though!

**Comment by ali5h** [comment]
@skyl my implementation requires that you pin the version in `requirement.txt`

**Comment by ali5h** [comment]
generate your `requirement.txt` file using `pip-compile`

**Comment by thundergolfer** [comment]
@ali5h 

I'm trying to use your `rules_pip` to fix this kind of issue that I'm experiencing with [`azure-common`](https://pypi.org/project/azure-common/) and `azure-storage-blob` (which both use the `azure` namespace, but it doesn't seem to work. 

If you've fixed this problem, can you elucidate _how_ you've fixed this issue, so that I can poke through your code and rip out a solution for myself 🙂

**Comment by ali5h** [comment]
i just tested it and added them to the tests, it works, did you compile ur req with pip-compile?

**Comment by thundergolfer** [comment]
Yes I did, but I may have done something else wrong. 

Do you mind pointing me at the relevant source code in your project to help me learn about a solution?

**Comment by ali5h** [comment]
fixed the issues, plz use latest release, thanks for the feedback

**Comment by jasonh-logic2020** [comment]
I am using the latest git commit release of rules_python as described in #273, but get the same result: no error from Bazel, but no code loaded from the azure package.

All other libraries load as expected, all versions pinned in requirements.txt.

**Comment by alexeagle** [comment]
rules_python 0.1.0 has been released which upstreams the rules_python_external repo. Please switch from `pip_import` to `pip_install` which doesn't have this issue.
