### ISSUE TITLE
Allow multiple base URLs in python_register_toolchains

### ISSUE THREAD

**Issue by jiawen** [bazelbuild/rules_python#964]
# 🚀 Allow multiple base URLs in python_register_toolchains

### Relevant Rules

`python_register_toolchains`

### Description

Currently, `python_register_toolchains` has a convenient `tool_versions` dictionary argument that the caller customize the mapping between Python versions and URLs from which to retrieve a build. However, the mapping is 1-to-1: a given Python version maps to a **unique** URL.

In my company's deployment, we have a monorepo that runs in multiple "environments" with strict firewalling rules. We are currently using a variant of [thundergolfer's solution](https://thundergolfer.com/bazel/python/2021/06/25/a-basic-python-bazel-toolchain/), passing a **list** of URLs for each Python version. The sha256 hash is the same but points to multiple URLs and `repository_ctx.download_and_extract` works "automatically": it tries to download from the first URL (say corp) and if it fails, tries to download from the next (say, public GitHub).

### Describe the solution you'd like

Change the type of `tool_versions` (or introduce a new attribute) from `str -> url` to `str -> list[url]`.

This is the simplest solution - Bazel will simply download each in turn and is a simple failure mechanism (to handle servers that are down).

### Describe alternatives you've considered

Introducing additional configurability at the `WORKSPACE` level seems too complex. One design could be a different Python "version" for each environment, e.g., `3.9-corp` and `3.9-github`. But this is difficult to manage as both need to be declared in `WORKSPACE` and then pushed down via a `select()` on the `requirements` at each leaf in `BUILD` files.

**Comment by lummax** [comment]
related: https://github.com/bazelbuild/rules_python/pull/973

**Comment by rickeylev** [comment]
Fixed by #1145
