### ISSUE TITLE
Support gazelle plugin when using bzlmod

### ISSUE THREAD

**Issue by aignas** [bazelbuild/rules_python#965]
# 🚀 feature request

Creating this issue to encompass all of the PRs related to this feature, as the single research PR (#961) got a little bit too big for easy review.

### Relevant Rules

`gazelle` Python plugin.

### Description

Currently the `gazelle` plugin does not work if using `bzlmod` with `bazel >= 6.0.0`. This is due to:
* Gazelle and go toolchain is not present in `MODULE.bazel` of `rules_python`, which means that the plugin reference fails.
* The `all_whl_requirements` have labels, that do not work in `bzlmod` due to repository remapping. Hence, the `modules_mapping` rule fails unless we do something about it.
* Gazelle will generate dependency labels in the targets that do not work in `bzlmod` due to repository remapping.

### Describe the solution you'd like

As researched in #961, we can fix these three issues separately:
1. Adding gazelle and go as bzlmod deps.
1. Changing the contents of the `all_whl_requirements` and `all_requirements` based on wether `bzlmod` is used.
1. Have extra declaratives for changing the generated labels to work with bzlmod.
1. Have extra aliases in the `@pip` repo that work with both, `bzlmod` and classic gazelle. This might be similar to #814, however this is not a requirement to make gazelle with `bzlmod` work.

### Describe alternatives you've considered

Rejected alternatives:
* Having a flag in `gazelle_python.yaml` manifest, which would say that we are using `bzlmod`. The manifest should be the same irrespective of whether we are using `bzlmod` or not due to the same reason why we may want to have aliases in `@pip` repo -- because we want to enable a smooth transition to `bzlmod` as described in the [migration guide](https://docs.google.com/document/d/1JtXIVnXyFZ4bmbiBCr5gsTH4-opZAFf5DMMb-54kES0/edit)

**Comment by aignas** [comment]
Some ideas that came from the comment in #970.

Regarding the metadata for gazelle to consume from the `requirements.bzl` file, I see that there are 2 pieces for gazelle to work:
- `modules_mapping` creates a mapping between import names and Python package names. It downloads the `whl` files to get this information, so it depends on the said `whl` targets.
- `gazelle_python.yaml` manifest generation depends on the mapping and a few extra variables, which help it map the Python package name back to the bazel label for the `pkg` target.

Thinking from outside-in, I'd like to use something like below in my BUILD.bazel files:
```starlark
# BUILD.bazel contents
load("@pip//:gazelle.bzl", "gazelle_python_manifest")
load("@gazelle//:def.bzl", "gazelle", "gazelle_binary")
load("@rules_python//gazelle:defs.bzl", "GAZELLE_PYTHON_RUNTIME_DEPS")

# This macro could read the metadata within the '@pip//:gazelle.bzl' which would have the
# following info:
# - The whl library list needed for gazelle.
# - The name of the pip repository.
# - The pip repo naming convention, thus eliminating the need for some of the
#   PRs in the series.
# - The '//:requirements_lock.txt' could be also infered as we pass it to `pip_parse` anyway.
gazelle_python_manifest(
    name = "gazelle_python_manifest",
    extend_exclude_patterns = [
        "(\\tests)+",  # There are many packages on PyPI with tests in their wheels
    ],
)

gazelle_binary(
    name = "gazelle_bin",
    extend_languages = [
        "@rules_python//gazelle",
    ],
)

gazelle(
    name = "gazelle",
    data = GAZELLE_PYTHON_RUNTIME_DEPS,
    binary = ":gazelle_bin",
)
```

I'll play around with the idea of having gazelle macro come from the output of `pip_parse`.

**Comment by aignas** [comment]
Thanks @alexeagle, will change the approach in #968. I was under an impression, that the dependencies will be lazy-fetched anyway, so there is no harm.

**Comment by aignas** [comment]
@alexeagle, #972 moves `gazelle` plugin into a separate workspace, other PRs will add bzlmod to it. Let me know if this is something similar to what you had in mind.

**Comment by aignas** [comment]
It seems that the approach described in one of my first comments should be changed given that there is a tool for easily managing the `use_repo` repositories. So the proposed plan would be to:

1. breaking: Move `gazelle` plugin into a separate WORKSPACE (#972).
2. Add a `MODULE.bazel` file with correct dependencies (#968).
3. Onboard `rules_python` onto [auto_use_repo] tool. https://github.com/bazelbuild/bazel-gazelle/pull/1404 could be a good starting point.
4. Deprecate the current `alias`ed targets which are in the main `pip_parse` repo when using `bzlmod`. People should use `auto_use_repo` to manage the `use_repo(pip, ...)` statement to consume pip repositories, thus making the targets identical between bzlmod and non-bzlmod cases. This can be done in a future release as it is not hindering usage of gazelle from `bzlmod`.
5. Remove the `alias`ed targets which are created in the main pip repo when using `bzlmod`.

The changes in #971, #970, #967, #966 would be not needed if `auto_use_repo` is adopted. Let me know what you think about such new direction.

[auto_use_repo]: https://github.com/fmeum/auto_use_repo

**Comment by alexeagle** [comment]
My understanding is that `auto_use_repo` is still experimental, and only needed in rules_go or similar cases where users typically depend on a package nested within the dependency. For Python, users depend on entire packages, so their MODULE.bazel files do not need `use_repo` lines for every dependency (and they make maintenance of that file harder).

Instead gazelle should load through the `@pip` repository (or whatever the user named it).
