### ISSUE TITLE
Allow py_wheel as dependency for py_binary rule

### ISSUE THREAD

**Issue by BSharp94** [bazelbuild/rules_python#974]
# 🚀 feature request

For one of my py_binary rules I need the generated wheel file from a py_wheel as a dependency. The py_binary rules is used to orchestrate the packaging of AWS Lambdas. The easiest way to include a py_library into a lambda image is to load it using a wheel file. However, when I make a py_wheel rule a dependency of a py_binary, I get the following error:

_in deps attribute of py_binary rule //projects/vision:build: '//projects/library:library_wheel' does not have mandatory providers: 'py' or 'PyInfo'_

### Relevant Rules

Allow adding py_wheel rule into the deps param of a py_binary. 

### Describe alternatives you've considered

Right now, we have the alternative of including the entire library as a dependency and packaging the library as a wheel file within the py_binary script. However, this is a bulky solution. It would be nicer to have the wheel file as a dependency instead.

**Comment by BSharp94** [comment]
Closing this issue. It looks like this is possible by adding a reference to the py_wheel rule in the data attribute. 

_data = ['//projects/library:library_wheel']_

**Comment by jvolkman** [comment]
Adding the wheel as a data dependency isn't going to make it available to `import` in python, if that's what you need.

**Comment by BSharp94** [comment]
> Adding the wheel as a data dependency isn't going to make it available to `import` in python, if that's what you need.

No. We needed the wheel file as a data dependency so that we could copy it to a docker container we are building for AWS Lambda functions. Some of our lambda functions depend on internal packages but are built using custom docker containers. We needed to have the wheel file so that we can add a line to copy and install the package inside the docker container on build.
