### ISSUE TITLE
py_wheel#requires - Substitute/stamp info

### ISSUE THREAD

**Issue by jgsogo** [bazelbuild/rules_python#997]
# 🚀 Support stamping in `requires` and `extra_requires`

### Relevant Rules

`py_wheel`

### Description

On `py_wheel` rule I would like to be able to stamp bazel provided variables:

```py
py_wheel(
    ... 
    requires = [
        "{SOME_DEP_AND_VERSION}",
        "req1~={REQ1_VERSION}",
    ],
    extra_requires = {
        "feature": [
            "opt_req~={OPT_REQ_VERSION}",
        ]
    },
    ...
)
```

Currently no replacement is done on those strings, they are just used as a `string_list`.

### Describe the solution you'd like

The generated wheel should contain the requirement list resulting from the replacement.

**Comment by alexeagle** [comment]
I think #994 is the more general answer to this - if you could provide the `requires` and `extra_requires` as the output of some other rule, then you'd be able to use something like https://docs.aspect.build/rules/aspect_bazel_lib/docs/expand_make_vars/#expand_template to create whatever  you want.

**Comment by jgsogo** [comment]
For sure you know better how to fit these feature requests into the codebase (and I agree #994 is more generic and includes this request). 👍 

Based on my little experience, I find this one quite straightforward to implement, while #994 is a bit harder. I'm fine closing this one, but I'm not sure if I will have the time to give #994 a try in the following days (I'll try, but I cannot promise, my free time is very scarce now)
